Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2018-08, with the labels that each got.

#1168 Automl - minor bug fixes
  language/automl/pom.xml
  language/automl/src/main/java/com/google/cloud/language/samples/ModelApi.java
  language/automl/src/test/java/com/google/cloud/language/samples/DatasetApiIT.java
  translate/automl/pom.xml
  translate/automl/src/main/java/com/google/cloud/translate/automl/DatasetApi.java
  translate/automl/src/test/java/com/google/cloud/translate/automl/PredictionApiIT.java
  vision/automl/pom.xml
Labels: cla: yes

#1169 Create monitoring uptime check config samples.
  monitoring/v3/manage_alerts_sample.sh
  monitoring/v3/pom.xml
  monitoring/v3/src/main/java/com/example/AlertSample.java
  monitoring/v3/src/main/java/com/example/UptimeSample.java
  monitoring/v3/src/test/java/com/example/AlertIT.java
  monitoring/v3/src/test/java/com/example/UptimeIT.java
Labels: cla: yes

#1164 Remove deprecated references to categories and fix paths.
  dlp/README.md
Labels: automerge, cla: yes

#1174 Revert Apache Beam version to unbreak test.
  dataflow/spanner-io/pom.xml
Labels: cla: yes

#1177 Modified publish message command line arg
  pubsub/cloud-client/README.md
Labels: cla: yes

#1180 Add final Monitoring Uptime Check sample (update).
  monitoring/v3/src/main/java/com/example/UptimeSample.java
  monitoring/v3/src/test/java/com/example/UptimeIT.java
Labels: cla: yes

#1182 Vision region tag update
  vision/beta/cloud-client/src/main/java/com/example/vision/Detect.java
  vision/cloud-client/src/main/java/com/example/vision/Detect.java
  vision/product-search/cloud-client/src/main/java/com/example/vision/ImportProductSets.java
  vision/product-search/cloud-client/src/main/java/com/example/vision/ProductInProductSetManagement.java
  vision/product-search/cloud-client/src/main/java/com/example/vision/ProductManagement.java
  vision/product-search/cloud-client/src/main/java/com/example/vision/ProductSearch.java
  vision/product-search/cloud-client/src/main/java/com/example/vision/ProductSetManagement.java
  vision/product-search/cloud-client/src/main/java/com/example/vision/ReferenceImageManagement.java
Labels: cla: yes

#1184 Udpate Beta Vision samples to use beta tags
  vision/beta/cloud-client/src/main/java/com/example/vision/Detect.java
Labels: cla: yes

#1185 [DO_NOT_MERGE] Microphone streaming with a 1 minute duration.
  speech/cloud-client/README.md
  speech/cloud-client/src/main/java/com/example/speech/Recognize.java
Labels: cla: yes

#1179 update region tags
  appengine-java8/requests/src/main/java/com/example/appengine/requests/LoggingServlet.java
  appengine-java8/requests/src/main/java/com/example/appengine/requests/RequestsServlet.java
  appengine/requests/src/main/java/com/example/appengine/requests/LoggingServlet.java
  appengine/requests/src/main/java/com/example/appengine/requests/RequestsServlet.java
  flexible/analytics/src/main/appengine/app.yaml
  flexible/analytics/src/main/java/com/example/analytics/AnalyticsServlet.java
  flexible/cloudsql/pom.xml
  flexible/cloudsql/src/main/java/com/example/cloudsql/CloudSqlServlet.java
  flexible/cloudstorage/src/main/appengine/app.yaml
  flexible/cloudstorage/src/main/java/com/example/cloudstorage/UploadServlet.java
  flexible/datastore/pom.xml
  flexible/datastore/src/main/java/com/example/datastore/DatastoreServlet.java
  flexible/mailgun/pom.xml
  flexible/mailgun/src/main/java/com/example/mailgun/MailgunServlet.java
  flexible/mailjet/pom.xml
  flexible/mailjet/src/main/appengine/app.yaml
  flexible/mailjet/src/main/java/com/example/mailjet/MailjetServlet.java
  flexible/postgres/pom.xml
  flexible/postgres/src/main/java/com/example/postgres/PostgresSqlServlet.java
  flexible/pubsub/pom.xml
  flexible/pubsub/src/main/appengine/app.yaml
  flexible/sendgrid/pom.xml
  flexible/sendgrid/src/main/appengine/app.yaml
  flexible/sendgrid/src/main/java/com/example/sendgrid/SendEmailServlet.java
  flexible/twilio/pom.xml
  flexible/twilio/src/main/appengine/app.yaml
  flexible/twilio/src/main/java/com/example/twilio/ReceiveCallServlet.java
  flexible/twilio/src/main/java/com/example/twilio/ReceiveSmsServlet.java
  flexible/twilio/src/main/java/com/example/twilio/SendSmsServlet.java
Labels: DO NOT MERGE, cla: yes

#1187 Update pom.xml region tags
  memorystore/redis/pom.xml
Labels: cla: yes

#1188 Speech region tag update
  speech/cloud-client/pom.xml
  speech/cloud-client/src/main/java/com/example/speech/Recognize.java
Labels: cla: yes

#1189 Natural Language region tag update
  language/analysis/src/main/java/com/google/cloud/language/samples/Analyze.java
Labels: cla: yes

#1190 TTS region tag update
  texttospeech/beta/src/main/java/com/example/texttospeech/SynthesizeText.java
Labels: cla: yes

#1191 Updates word time offsets region tag
  speech/cloud-client/src/main/java/com/example/speech/Recognize.java
Labels: cla: yes

#1192 NL region tag update
  language/analysis/src/main/java/com/google/cloud/language/samples/Analyze.java
Labels: cla: yes

#1186 added samples for KMS Asymmetric Keys
  kms/pom.xml
  kms/src/main/java/com/example/Asymmetric.java
  kms/src/test/java/com/example/AsymmetricIT.java
Labels: cla: yes

#1193 Update Region Tags
  appengine-java8/analytics/src/main/java/com/example/appengine/analytics/AnalyticsServlet.java
  appengine-java8/appidentity/src/main/java/com/example/appengine/appidentity/IdentityServlet.java
  appengine-java8/appidentity/src/main/java/com/example/appengine/appidentity/SignForAppServlet.java
  appengine-java8/appidentity/src/main/java/com/example/appengine/appidentity/UrlShortener.java
  appengine-java8/bigquery/pom.xml
  appengine-java8/bigquery/src/main/java/com/example/appengine/bigquerylogging/BigQueryRunner.java
  appengine-java8/bigtable/src/main/java/com/example/bigtable/BigtableHelloWorld.java
  appengine-java8/datastore/src/test/java/com/example/appengine/QueriesTest.java
  appengine-java8/endpoints-v2-guice/pom.xml
  appengine-java8/endpoints-v2-guice/src/main/java/com/example/echo/Echo.java
  appengine-java8/endpoints-v2-migration/pom.xml
  appengine/appidentity/src/main/java/com/example/appengine/appidentity/IdentityServlet.java
  appengine/appidentity/src/main/java/com/example/appengine/appidentity/SignForAppServlet.java
  appengine/appidentity/src/main/java/com/example/appengine/appidentity/UrlShortener.java
  flexible/cloudsql/src/main/resources/config.properties
  flexible/helloworld/src/main/appengine/app.yaml
  flexible/helloworld/src/main/java/com/example/flexible/helloworld/HelloServlet.java
  flexible/postgres/src/main/resources/config.properties
Labels: cla: yes

#1195 Adding the Product Search tests.
  vision/product-search/cloud-client/src/main/java/com/example/vision/ProductInProductSetManagement.java
  vision/product-search/cloud-client/src/main/java/com/example/vision/ProductManagement.java
  vision/product-search/cloud-client/src/main/java/com/example/vision/ProductSetManagement.java
  vision/product-search/cloud-client/src/test/java/com/example/vision/ImportProductSetsIT.java
  vision/product-search/cloud-client/src/test/java/com/example/vision/ProductInProductSetManagementIT.java
  vision/product-search/cloud-client/src/test/java/com/example/vision/ProductManagementIT.java
  vision/product-search/cloud-client/src/test/java/com/example/vision/ProductSetManagementIT.java
  vision/product-search/cloud-client/src/test/java/com/example/vision/ReferenceImageManagementIT.java
Labels: cla: yes

#1196 Added the Product Search tests and the src file updates
  vision/product-search/cloud-client/pom.xml
  vision/product-search/cloud-client/src/main/java/com/example/vision/ImportProductSets.java
  vision/product-search/cloud-client/src/main/java/com/example/vision/ProductInProductSetManagement.java
  vision/product-search/cloud-client/src/main/java/com/example/vision/ProductManagement.java
  vision/product-search/cloud-client/src/main/java/com/example/vision/ProductSearch.java
  vision/product-search/cloud-client/src/main/java/com/example/vision/ReferenceImageManagement.java
  vision/product-search/cloud-client/src/test/java/com/example/vision/ImportProductSetsIT.java
  vision/product-search/cloud-client/src/test/java/com/example/vision/ProductInProductSetManagementIT.java
  vision/product-search/cloud-client/src/test/java/com/example/vision/ProductManagementIT.java
  vision/product-search/cloud-client/src/test/java/com/example/vision/ProductSearchIT.java
  vision/product-search/cloud-client/src/test/java/com/example/vision/ProductSetManagementIT.java
Labels: cla: yes

#1198 Update Region Tags
  appengine/analytics/src/main/java/com/example/appengine/analytics/AnalyticsServlet.java
  appengine/helloworld-new-plugins/build.gradle
  appengine/logs/src/main/java/com/example/appengine/logs/LogsServlet.java
  appengine/oauth2/src/main/java/com/example/appengine/HelloServlet.java
  appengine/oauth2/src/main/java/com/example/appengine/Oauth2Filter.java
  appengine/pusher-chat/src/main/java/com/example/appengine/pusher/AuthorizeServlet.java
  appengine/pusher-chat/src/main/java/com/example/appengine/pusher/PusherService.java
  appengine/pusher-chat/src/main/java/com/example/appengine/pusher/SendMessageServlet.java
  flexible/async-rest/src/main/appengine/app.yaml
  flexible/cloud-tasks/pom.xml
  flexible/cloud-tasks/src/main/appengine/app.yaml
  flexible/cron/pom.xml
  flexible/cron/src/main/java/com/example/cron/CronServlet.java
  flexible/disk/src/main/java/com/example/disk/DiskServlet.java
  flexible/errorreporting/pom.xml
  flexible/errorreporting/src/main/appengine/app.yaml
  flexible/extending-runtime/src/main/java/com/example/extendingruntime/FortuneServlet.java
  flexible/gaeinfo/pom.xml
  flexible/gaeinfo/src/main/java/com/example/appengine/flex_compat/GaeInfoServlet.java
  flexible/gaeinfo/src/main/webapp/WEB-INF/appengine-web.xml
  flexible/helloworld/pom.xml
  flexible/sparkjava/pom.xml
Labels: cla: yes

#1199 Update Region Tags
  appengine-java8/twilio/pom.xml
  appengine-java8/twilio/src/main/java/com/example/appengine/twilio/ReceiveCallServlet.java
  appengine-java8/twilio/src/main/java/com/example/appengine/twilio/ReceiveSmsServlet.java
  appengine-java8/twilio/src/main/java/com/example/appengine/twilio/SendSmsServlet.java
  appengine-java8/twilio/src/main/webapp/WEB-INF/appengine-web.xml
  appengine/twilio/pom.xml
  appengine/twilio/src/main/java/com/example/appengine/twilio/ReceiveCallServlet.java
  appengine/twilio/src/main/java/com/example/appengine/twilio/ReceiveSmsServlet.java
  appengine/twilio/src/main/java/com/example/appengine/twilio/SendSmsServlet.java
  appengine/twilio/src/main/webapp/WEB-INF/appengine-web.xml
  flexible/cloudstorage/pom.xml
Labels: cla: yes

#1181 Dialogflow to gcp
  dialogflow/cloud-client/README.md
  dialogflow/cloud-client/pom.xml
  dialogflow/cloud-client/resources/230pm.wav
  dialogflow/cloud-client/resources/RoomReservation.zip
  dialogflow/cloud-client/resources/book_a_room.wav
  dialogflow/cloud-client/resources/half_an_hour.wav
  dialogflow/cloud-client/resources/mountain_view.wav
  dialogflow/cloud-client/resources/today.wav
  dialogflow/cloud-client/resources/two_people.wav
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/ContextManagement.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentAudio.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentKnowledge.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentStream.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentTexts.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentWithModelSelection.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentWithSentimentAnalysis.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentWithTextToSpeechResponse.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DocumentManagement.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/EntityManagement.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/EntityTypeManagement.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/IntentManagement.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/KnowledgeBaseManagement.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/SessionEntityTypeManagement.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/ContextManagementIT.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/CreateDeleteEntityIT.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/DetectIntentAudioIT.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/DetectIntentStreamIT.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/DetectIntentTextsIT.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/DetectIntentWithModelSelectionIT.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/DetectIntentWithSentimentAnalysisIT.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/DetectIntentWithTextToSpeechResponseIT.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/IntentManagementIT.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/KnowledgeBaseManagementIT.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/SessionEntityTypeManagementIT.java
  pom.xml
Labels: cla: yes

#1197 Remove unused dependency region tags and update used region tags
  bigquery/cloud-client/pom.xml
  bigquery/datatransfer/cloud-client/pom.xml
  language/analysis/pom.xml
  language/automl/pom.xml
  pubsub/cloud-client/pom.xml
  texttospeech/beta/pom.xml
  texttospeech/cloud-client/pom.xml
  translate/automl/pom.xml
  translate/cloud-client/pom.xml
  vision/automl/pom.xml
  vision/beta/cloud-client/pom.xml
  vision/cloud-client/pom.xml
  vision/face-detection/pom.xml
  vision/product-search/cloud-client/pom.xml
Labels: cla: yes

#1201 Update Face Detection Tutorial region tags to standard
  vision/face-detection/src/main/java/com/google/cloud/vision/samples/facedetect/FaceDetectApp.java
Labels: cla: yes

#1194 Container Analysis Beta
  container-registry/container-analysis/pom.xml
  container-registry/container-analysis/repo/com/google/cloud/google-cloud-containeranalysis/0.1.1-alpha/google-cloud-containeranalysis-0.1.1-alpha.jar
  container-registry/container-analysis/repo/com/google/cloud/google-cloud-containeranalysis/0.1.1-alpha/google-cloud-containeranalysis-0.1.1-alpha.pom
  container-registry/container-analysis/repo/com/google/cloud/google-cloud-containeranalysis/maven-metadata-local.xml
  container-registry/container-analysis/src/main/java/com/example/containeranalysis/Samples.java
  container-registry/container-analysis/src/test/java/com/example/containeranalysis/SamplesTest.java
  container-registry/container-analysis/src/test/java/com/example/containeranalysis/SamplesTests.java
Labels: cla: yes

#1204 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla: yes
