Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2019-08, with the labels that each got.

#1535 Recreate Test Knowledge Base after it was deleted and update other te…
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/ContextManagementIT.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/DetectIntentStreamIT.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/DetectIntentWithAudioAndModelSelectionIT.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/DetectIntentWithSentimentAndTextToSpeechIT.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/EntityManagementIT.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/IntentManagementIT.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/KnowledgeBaseManagementIT.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/SessionEntityTypeManagementIT.java
Labels: cla: yes

#1534 Make Pub/Sub subscriber example simpler and more idiomatic
  pubsub/cloud-client/src/main/java/com/example/pubsub/SubscriberExample.java
Labels: cla: yes

#1542 Container Analysis exception fix
  container-registry/container-analysis/src/test/java/com/example/containeranalysis/SamplesTest.java
Labels: cla: yes

#1540 Remove references to java7
  appengine-java8/endpoints-v2-migration/build.gradle
  appengine-java8/gaeinfo/pom.xml
  appengine/endpoints-frameworks-v2/backend/build.gradle
  appengine/endpoints-frameworks-v2/guice-example/build.gradle
  appengine/endpoints-frameworks-v2/migration-example/build.gradle
  appengine/gaeinfo/pom.xml
  appengine/helloworld-new-plugins/build.gradle
  appengine/helloworld/pom.xml
  appengine/iap/pom.xml
  appengine/sendgrid/pom.xml
  appengine/sockets/pom.xml
  appengine/static-files/pom.xml
  appengine/taskqueue/defer-samples/pom.xml
  appengine/taskqueue/pull-samples/pom.xml
  compute/cmdline/README.md
  datastore/README.md
  flexible/gaeinfo/pom.xml
Labels: cla: yes

#1543 Only delete dataset created during tests.
  healthcare/v1beta1/src/test/java/snippets/healthcare/DatasetTests.java
  healthcare/v1beta1/src/test/java/snippets/healthcare/DicomStoreTests.java
  healthcare/v1beta1/src/test/java/snippets/healthcare/DicomWebTests.java
  healthcare/v1beta1/src/test/java/snippets/healthcare/FhirResourceTests.java
  healthcare/v1beta1/src/test/java/snippets/healthcare/FhirStoreTests.java
  healthcare/v1beta1/src/test/java/snippets/healthcare/Hl7v2MessageTests.java
  healthcare/v1beta1/src/test/java/snippets/healthcare/Hl7v2StoreTests.java
  healthcare/v1beta1/src/test/java/snippets/healthcare/TestBase.java
Labels: cla: yes

#1500 Update FHIR resource export region tag.
  healthcare/v1beta1/src/main/java/snippets/healthcare/fhir/FhirStoreExport.java
Labels: cla: yes, kokoro:run

#1545 Fix delete FHIR store region tag.
  healthcare/v1beta1/src/main/java/snippets/healthcare/fhir/FhirStoreDelete.java
Labels: cla: yes

#1546 Adds closing includecode block on MQTT snippet
  iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/MqttExample.java
Labels: cla: yes

#1547 Add `fs_update_document_increment` snippet
  firestore/src/main/java/com/example/firestore/snippets/ManageDataSnippets.java
  firestore/src/test/java/com/example/firestore/snippets/ManageDataSnippetsIT.java
Labels: cla: yes

#1541 Pub/Sub: new Pub/Sub DataFlow doc sample
  pubsub/streaming-analytics/README.md
  pubsub/streaming-analytics/pom.xml
  pubsub/streaming-analytics/src/main/java/com/examples/pubsub/streaming/PubSubToGCS.java
Labels: cla: yes

#1530 Add Cloud Vision Sample with Spring Framework
  vision/spring-framework/README.md
  vision/spring-framework/pom.xml
  vision/spring-framework/src/main/java/com/example/vision/Application.java
  vision/spring-framework/src/main/java/com/example/vision/VisionController.java
  vision/spring-framework/src/main/resources/static/index.html
  vision/spring-framework/src/main/resources/templates/result.html
Labels: cla: yes

#1549 Feat: Adds functions_helloworld_background
  functions/snippets/src/main/java/HelloBackground.java
  functions/snippets/src/test/java/SnippetsTests.java
Labels: cla: yes

#1553 Update KnowledgeBaseId and update rouge SA roles
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/KnowledgeBaseManagementIT.java
Labels: cla: yes

#1552 Remove extra dependency from Spring Vision Sample
  vision/spring-framework/pom.xml
Labels: cla: yes

#1555 Remove lesv from assign_issues.
  .kvgbot.yml
Labels: cla: yes

#1556 Java samples for SSML Addresses tutorial
  texttospeech/cloud-client/resources/example.ssml
  texttospeech/cloud-client/resources/example.txt
  texttospeech/cloud-client/resources/expected_example.mp3
  texttospeech/cloud-client/src/main/java/com/example/texttospeech/SsmlAddresses.java
  texttospeech/cloud-client/src/test/java/com/example/texttospeech/SsmlAddressesIT.java
Labels: cla: yes

#1558 Update from kvgbot to Blunderbuss.
  .github/blunderbuss.yml
Labels: automerge, cla: yes

#1554 Change retrieved study output file to use .multipart extension and add Accept headers
  healthcare/v1beta1/src/main/java/snippets/healthcare/dicom/DicomWebRetrieveStudy.java
  healthcare/v1beta1/src/test/java/snippets/healthcare/DicomWebTests.java
Labels: cla: yes

#1568 Add new beta samples for Video Intelligence Streaming with an AutoML …
  video/beta/pom.xml
  video/beta/src/main/java/com/example/video/StreamingAutoMlClassification.java
  video/beta/src/main/java/com/example/video/TextDetection.java
  video/beta/src/main/java/com/example/video/TrackObjects.java
  video/beta/src/test/java/com/example/video/StreamingAutoMlClassificationIT.java
Labels: cla: yes

#1563 asset: add quickstart for Real Time Feed API V1P2Beta1
  asset/cloud-client/pom.xml
  asset/cloud-client/src/main/java/com/example/asset/CreateFeedExample.java
  asset/cloud-client/src/main/java/com/example/asset/DeleteFeedExample.java
  asset/cloud-client/src/main/java/com/example/asset/GetFeedExample.java
  asset/cloud-client/src/main/java/com/example/asset/ListFeedsExample.java
  asset/cloud-client/src/main/java/com/example/asset/UpdateFeedExample.java
  asset/cloud-client/src/test/java/com/example/asset/RealTimeFeed.java
Labels: cla: yes
