Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2019-07, with the labels that each got.

#1499 Container analysis v1
  container-registry/container-analysis/pom.xml
  container-registry/container-analysis/src/main/java/com/example/containeranalysis/CreateNote.java
  container-registry/container-analysis/src/main/java/com/example/containeranalysis/CreateOccurrence.java
  container-registry/container-analysis/src/main/java/com/example/containeranalysis/DeleteNote.java
  container-registry/container-analysis/src/main/java/com/example/containeranalysis/DeleteOccurrence.java
  container-registry/container-analysis/src/main/java/com/example/containeranalysis/GetDiscoveryInfo.java
  container-registry/container-analysis/src/main/java/com/example/containeranalysis/GetNote.java
  container-registry/container-analysis/src/main/java/com/example/containeranalysis/GetOccurrence.java
  container-registry/container-analysis/src/main/java/com/example/containeranalysis/HighVulnerabilitiesForImage.java
  container-registry/container-analysis/src/main/java/com/example/containeranalysis/OccurrencesForImage.java
  container-registry/container-analysis/src/main/java/com/example/containeranalysis/OccurrencesForNote.java
  container-registry/container-analysis/src/main/java/com/example/containeranalysis/PollDiscoveryOccurrenceFinished.java
  container-registry/container-analysis/src/main/java/com/example/containeranalysis/VulnerabilityOccurrencesForImage.java
  container-registry/container-analysis/src/test/java/com/example/containeranalysis/SamplesTest.java
Labels: cla: yes

#1501 Add config for auto-assigning issues and PRs to folks.
  .kvgbot.yml
Labels: cla: yes

#1503 Update CONTRIBUTING, ISSUE_TEMPLATE, and parent README
  .github/ISSUE_TEMPLATE.md
  CONTRIBUTING.md
  README.md
Labels: cla: yes

#1505 ContainerAnalysis: Update topic id
  container-registry/container-analysis/src/main/java/com/example/containeranalysis/Subscriptions.java
  container-registry/container-analysis/src/test/java/com/example/containeranalysis/SamplesTest.java
Labels: cla: yes

#1507 Add flag for UrlFetch
  appengine-java8/urlfetch/src/main/webapp/WEB-INF/appengine-web.xml
Labels: cla: yes

#1498 Add Datatypes examples to Spanner sample.
  spanner/cloud-client/src/main/java/com/example/spanner/SpannerSample.java
  spanner/cloud-client/src/test/java/com/example/spanner/SpannerSampleIT.java
Labels: cla: yes

#1508 Fixing typo in readme
  README.md
Labels: cla: yes

#1509 BigQuery Storage: update sample application to show new API options.
  bigquery/bigquerystorage/pom.xml
  bigquery/bigquerystorage/src/main/java/com/example/bigquerystorage/StorageSample.java
  bigquery/bigquerystorage/src/test/java/com/example/bigquerystorage/QuickstartSampleIT.java
Labels: cla: yes

#1510 BigQuery storage: unnecessary repetition in request builder.
  bigquery/bigquerystorage/src/main/java/com/example/bigquerystorage/StorageSample.java
Labels: cla: yes

#1512 Add back missing break statement
  speech/cloud-client/src/main/java/com/example/speech/Recognize.java
Labels: cla: yes

#1511 Fix listening on port 8080 Warning
  appengine-java11/appengine-simple-jetty-main/src/main/java/com/example/appengine/demo/jettymain/Main.java
  appengine-java11/custom-entrypoint/Main.java
  appengine-java11/http-server/src/main/java/com/example/appengine/Main.java
  appengine-java11/sparkjava-helloworld/src/main/java/com/example/appengine/sparkdemo/Main.java
Labels: cla: yes

#1515 Update README.md
  speech/cloud-client/README.md
Labels: cla: yes

#1521 Add PubSub Tutorial for Cloud Run
  appengine-java11/cloudrun-pubsub/Dockerfile
  appengine-java11/cloudrun-pubsub/README.md
  appengine-java11/cloudrun-pubsub/pom.xml
  appengine-java11/cloudrun-pubsub/src/main/java/com/example/appengine/cloudrunpubsub/Body.java
  appengine-java11/cloudrun-pubsub/src/main/java/com/example/appengine/cloudrunpubsub/CloudrunPubsubApplication.java
  appengine-java11/cloudrun-pubsub/src/main/java/com/example/appengine/cloudrunpubsub/PubsubController.java
  appengine-java11/cloudrun-pubsub/src/test/java/com/example/appengine/cloudrunpubsub/PubsubControllerTests.java
Labels: cla: yes

#1504 Added command line option class + option to pass different lang code as argument
  speech/cloud-client/README.md
  speech/cloud-client/pom.xml
  speech/cloud-client/src/main/java/com/example/speech/InfiniteStreamRecognize.java
  speech/cloud-client/src/main/java/com/example/speech/InfiniteStreamRecognizeOptions.java
Labels: cla: yes

#1516 Creating game servers samples.
  gameservices/v1alpha/pom.xml
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/allocationpolicies/CreateAllocationPolicy.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/allocationpolicies/DeleteAllocationPolicy.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/allocationpolicies/GetAllocationPolicy.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/allocationpolicies/ListAllocationPolicies.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/allocationpolicies/UpdateAllocationPolicy.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/clusters/CreateCluster.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/clusters/DeleteCluster.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/clusters/GetCluster.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/clusters/ListClusters.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/clusters/UpdateCluster.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/deployments/CommitRollout.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/deployments/CreateDeployment.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/deployments/DeleteDeployment.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/deployments/GetDeployment.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/deployments/GetDeploymentTarget.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/deployments/ListDeployments.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/deployments/RevertRollout.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/deployments/SetRolloutTarget.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/deployments/StartRollout.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/deployments/UpdateDeployment.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/realms/CreateRealm.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/realms/DeleteRealm.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/realms/GetRealm.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/realms/ListRealms.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/realms/UpdateRealm.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/scalingpolicies/CreateScalingPolicy.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/scalingpolicies/DeleteScalingPolicy.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/scalingpolicies/GetScalingPolicy.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/scalingpolicies/ListScalingPolicies.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/scalingpolicies/UpdateScalingPolicy.java
  gameservices/v1alpha/src/test/java/com/google/cloud/gameservices/samples/AllocationPolicyTests.java
  gameservices/v1alpha/src/test/java/com/google/cloud/gameservices/samples/ClusterTests.java
  gameservices/v1alpha/src/test/java/com/google/cloud/gameservices/samples/DeploymentTests.java
  gameservices/v1alpha/src/test/java/com/google/cloud/gameservices/samples/GameServicesTestUtil.java
  gameservices/v1alpha/src/test/java/com/google/cloud/gameservices/samples/RealmTests.java
  gameservices/v1alpha/src/test/java/com/google/cloud/gameservices/samples/ScalingPolicyTests.java
Labels: automerge, cla: yes

#1522 forgot to change default val to param
  speech/cloud-client/src/main/java/com/example/speech/InfiniteStreamRecognize.java
Labels: automerge, cla: yes

#1523 Update Firestore Quickstart to use exec:exec
  firestore/README.md
  firestore/pom.xml
Labels: cla: yes

#1526 Saner Jetty native WebSocket usage
  appengine-java8/websocket-jetty/src/main/java/com/example/flexible/websocket/jettynative/EchoServlet.java
  appengine-java8/websocket-jetty/src/main/java/com/example/flexible/websocket/jettynative/SendServlet.java
  appengine-java8/websocket-jetty/src/main/java/com/example/flexible/websocket/jettynative/ServerSocket.java
Labels: cla: yes

#1525 Add Cloud Run directory and ReadMes
  appengine-java11/cloudrun-pubsub/README.md
  run/README.md
  run/pubsub/Dockerfile
  run/pubsub/README.md
  run/pubsub/pom.xml
  run/pubsub/src/main/java/com/example/cloudrun/Body.java
  run/pubsub/src/main/java/com/example/cloudrun/PubSubApplication.java
  run/pubsub/src/main/java/com/example/cloudrun/PubSubController.java
  run/pubsub/src/test/java/com/example/cloudrun/PubSubControllerTests.java
Labels: cla: yes

#1527 Fixes classnames in inline documentation
  iot/api-client/manager/README.md
  iot/api-client/manager/pom.xml
  iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/DeviceRegistryExample.java
  iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/DeviceRegistryExampleOptions.java
  iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/MqttExample.java
  iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/MqttExampleOptions.java
  iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java
Labels: DO NOT MERGE, cla: yes
