Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2020-02, with the labels that each got.

#2047 feat: add cli functionality to dataproc quickstart
  dataproc/pom.xml
  dataproc/src/main/java/Quickstart.java
  dataproc/src/test/java/QuickstartTest.java
Labels: cla: yes

#2052 Update link for Cloud Run HelloWorld
  run/README.md
Labels: cla: yes

#2044 Heathcare API: fix resource path and console output for HL7v2MessageList
  healthcare/v1beta1/src/main/java/snippets/healthcare/hl7v2/messages/HL7v2MessageList.java
Labels: cla: yes

#2050 feat: add functions_firebase_auth
  functions/snippets/pom.xml
  functions/snippets/src/main/java/FirebaseAuth.java
  functions/snippets/src/test/java/SnippetsTests.java
Labels: cla: yes

#2053 translate: use unique gcs folders for batch translate tests
  translate/cloud-client/src/test/java/com/example/translate/BatchTranslateTextTests.java
  translate/cloud-client/src/test/java/com/example/translate/BatchTranslateTextWithGlossaryAndModelTests.java
  translate/cloud-client/src/test/java/com/example/translate/BatchTranslateTextWithGlossaryTests.java
  translate/cloud-client/src/test/java/com/example/translate/BatchTranslateTextWithModelTests.java
Labels: cla: yes

#2057 Undo deleted IAP sample
  appengine-java8/iap/README.md
  appengine-java8/iap/pom.xml
  appengine-java8/iap/src/main/java/com/example/appengine/iap/JwtServlet.java
  appengine-java8/iap/src/main/webapp/WEB-INF/appengine-web.xml
  appengine-java8/iap/src/main/webapp/WEB-INF/web.xml
  iap/README.md
Labels: cla: yes

#2056 Update pom.xml to fix build errors
  appengine-java11/quarkus-helloworld/pom.xml
  appengine-java11/quarkus-helloworld/src/main/resources/META-INF/microprofile-config.properties
  appengine-java11/quarkus-helloworld/src/main/resources/application.properties
Labels: cla: yes

#2059 Update Kokoro java versions
  .kokoro/java11/common.cfg
  .kokoro/java8/common.cfg
  .kokoro/tests/run_tests.sh
  appengine-java11/http-server/pom.xml
  appengine-java8/analytics/README.md
  appengine-java8/analytics/pom.xml
Labels: cla: yes

#2060 Delete old Bigquery samples and link new location.
  bigquery/cloud-client/.gitignore
  bigquery/cloud-client/README.md
  bigquery/cloud-client/pom.xml
  bigquery/cloud-client/src/main/java/com/example/bigquery/AuthSnippets.java
  bigquery/cloud-client/src/main/java/com/example/bigquery/CreateDataset.java
  bigquery/cloud-client/src/main/java/com/example/bigquery/DeleteDataset.java
  bigquery/cloud-client/src/main/java/com/example/bigquery/ListDatasets.java
  bigquery/cloud-client/src/main/java/com/example/bigquery/QuickstartSample.java
  bigquery/cloud-client/src/main/java/com/example/bigquery/SimpleApp.java
  bigquery/cloud-client/src/main/java/com/example/bigquery/UpdateDatasetAccess.java
  bigquery/cloud-client/src/main/java/com/example/bigquery/UpdateDatasetDescription.java
  bigquery/cloud-client/src/main/java/com/example/bigquery/UpdateDatasetExpiration.java
  bigquery/cloud-client/src/test/java/com/example/bigquery/AuthSnippetsIT.java
  bigquery/cloud-client/src/test/java/com/example/bigquery/CreateDatasetIT.java
  bigquery/cloud-client/src/test/java/com/example/bigquery/DeleteDatasetIT.java
  bigquery/cloud-client/src/test/java/com/example/bigquery/ListDatasetsIT.java
  bigquery/cloud-client/src/test/java/com/example/bigquery/QuickstartSampleIT.java
  bigquery/cloud-client/src/test/java/com/example/bigquery/SimpleAppIT.java
  bigquery/cloud-client/src/test/java/com/example/bigquery/UpdateDatasetAccessIT.java
  bigquery/cloud-client/src/test/java/com/example/bigquery/UpdateDatasetDescriptionIT.java
  bigquery/cloud-client/src/test/java/com/example/bigquery/UpdateDatasetExpirationIT.java
Labels: cla: yes

#2014 automl-beta: update samples and move them to master for video
  automl/beta/src/main/java/com/example/automl/BatchPredict.java
  automl/beta/src/main/java/com/example/automl/VideoClassificationCreateDataset.java
  automl/beta/src/main/java/com/example/automl/VideoClassificationCreateModel.java
  automl/beta/src/test/java/com/example/automl/BatchPredictTest.java
  automl/beta/src/test/java/com/example/automl/VideoClassificationCreateDatasetTest.java
  automl/beta/src/test/java/com/example/automl/VideoClassificationCreateModelTest.java
Labels: cla: yes

#2054 Cleanup DLP Metadata and Jobs snippets
  dlp/README.md
  dlp/src/main/java/com/example/dlp/Jobs.java
  dlp/src/main/java/com/example/dlp/Metadata.java
  dlp/src/main/java/dlp/snippets/DeIdentifyWithDateShift.java
  dlp/src/main/java/dlp/snippets/DeIdentifyWithFpe.java
  dlp/src/main/java/dlp/snippets/InfoTypesList.java
  dlp/src/main/java/dlp/snippets/InspectGcsFile.java
  dlp/src/main/java/dlp/snippets/InspectImageFile.java
  dlp/src/main/java/dlp/snippets/InspectString.java
  dlp/src/main/java/dlp/snippets/InspectTextFile.java
  dlp/src/main/java/dlp/snippets/JobsDelete.java
  dlp/src/main/java/dlp/snippets/JobsList.java
  dlp/src/main/java/dlp/snippets/ReIdentifyWithFpe.java
  dlp/src/main/java/dlp/snippets/RedactImageFile.java
  dlp/src/test/java/com/example/dlp/JobsIT.java
  dlp/src/test/java/com/example/dlp/MetadataIT.java
  dlp/src/test/java/dlp/snippets/DeIdentificationTests.java
  dlp/src/test/java/dlp/snippets/InfoTypesTests.java
  dlp/src/test/java/dlp/snippets/JobsTests.java
  dlp/src/test/java/dlp/snippets/RedactTests.java
Labels: cla: yes

#2067 Add helloworld Cloud Run Sample
  run/README.md
  run/helloworld/.dockerignore
  run/helloworld/Dockerfile
  run/helloworld/README.md
  run/helloworld/pom.xml
  run/helloworld/src/main/java/com/example/helloworld/HelloworldApplication.java
  run/helloworld/src/main/resources/application.properties
  run/helloworld/src/test/java/com/example/helloworld/HelloworldApplicationTests.java
Labels: cla: yes

#2066 feat: face and person detection samples
  video/beta/pom.xml
  video/beta/src/main/java/com/example/video/DetectFaces.java
  video/beta/src/main/java/com/example/video/DetectFacesGcs.java
  video/beta/src/main/java/com/example/video/DetectPerson.java
  video/beta/src/main/java/com/example/video/DetectPersonGcs.java
  video/beta/src/test/java/com/example/video/DetectFacesGcsIT.java
  video/beta/src/test/java/com/example/video/DetectFacesIT.java
  video/beta/src/test/java/com/example/video/DetectPersonGcsIT.java
  video/beta/src/test/java/com/example/video/DetectPersonIT.java
Labels: cla: yes

#2062 Cleanup DLP Triggers Snippets
  dlp/src/main/java/com/example/dlp/Triggers.java
  dlp/src/main/java/dlp/snippets/TriggersCreate.java
  dlp/src/main/java/dlp/snippets/TriggersDelete.java
  dlp/src/main/java/dlp/snippets/TriggersList.java
  dlp/src/test/java/com/example/dlp/TriggersIT.java
  dlp/src/test/java/dlp/snippets/TriggersTests.java
Labels: cla: yes

#2065 Cleanup DLP Templates Snippets
  dlp/src/main/java/com/example/dlp/Templates.java
  dlp/src/main/java/dlp/snippets/TemplatesCreate.java
  dlp/src/main/java/dlp/snippets/TemplatesDelete.java
  dlp/src/main/java/dlp/snippets/TemplatesList.java
  dlp/src/test/java/com/example/dlp/TemplatesIT.java
  dlp/src/test/java/dlp/snippets/TemplatesTests.java
Labels: cla: yes

#2071 Remove PR limit.
  renovate.json
Labels: cla: yes

#2063 fix: default to PickFirstLoadBalancerProvider
  spanner/cloud-client/assembly-descriptor.xml
  spanner/cloud-client/pom.xml
  spanner/cloud-client/src/main/resources/META-INF/services/io.grpc.LoadBalancerProvider
Labels: cla: yes

#2033 talent solution: moving published samples into master
  jobs/v4/pom.xml
  jobs/v4/src/main/java/com/example/jobs/JobSearchCreateCompany.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchCreateJob.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchCreateTenant.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchDeleteCompany.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchDeleteJob.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchDeleteTenant.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchGetCompany.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchGetJob.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchGetTenant.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchListCompanies.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchListTenants.java
  jobs/v4/src/test/java/JobSearchCreateCompanyTest.java
  jobs/v4/src/test/java/JobSearchCreateJobTest.java
  jobs/v4/src/test/java/JobSearchCreateTenantTest.java
  jobs/v4/src/test/java/JobSearchDeleteCompanyTest.java
  jobs/v4/src/test/java/JobSearchDeleteJobTest.java
  jobs/v4/src/test/java/JobSearchDeleteTenantTest.java
  jobs/v4/src/test/java/JobSearchGetCompanyTest.java
  jobs/v4/src/test/java/JobSearchGetJobTest.java
  jobs/v4/src/test/java/JobSearchGetTenantTest.java
  jobs/v4/src/test/java/JobSearchListCompaniesTest.java
  jobs/v4/src/test/java/JobSearchListTenantsTest.java
Labels: cla: yes

#2012 Automl beta dataset
  automl/beta/src/main/java/com/example/automl/ExportDataset.java
  automl/beta/src/main/java/com/example/automl/GetDataset.java
  automl/beta/src/test/java/com/example/automl/DeleteDatasetTest.java
  automl/beta/src/test/java/com/example/automl/ExportDatasetTest.java
  automl/beta/src/test/java/com/example/automl/GetDatasetTest.java
  automl/beta/src/test/java/com/example/automl/ImportDatasetTest.java
Labels: cla: yes

#2140 chore: switch to built-in code review assignment
  .github/blunderbuss.yml
Labels: cla: yes, do not merge

#2027 Update Cloud Run Samples to use Jib
  .kokoro/tests/build_cloud_run.sh
  run/README.md
  run/hello-broken/Dockerfile
  run/hello-broken/README.md
  run/hello-broken/pom.xml
  run/image-processing/Dockerfile
  run/image-processing/README.md
  run/image-processing/pom.xml
  run/image-processing/src/main/java/com/example/cloudrun/PubSubApplication.java
  run/logging-manual/Dockerfile
  run/logging-manual/README.md
  run/logging-manual/pom.xml
  run/pubsub/Dockerfile
  run/pubsub/README.md
  run/pubsub/pom.xml
  run/pubsub/src/main/java/com/example/cloudrun/PubSubApplication.java
  run/system-package/.dockerignore
  run/system-package/Dockerfile
  run/system-package/README.md
  run/system-package/pom.xml
Labels: cla: yes, do not merge

#2152 Fix ReadMe Typo
  run/README.md
Labels: cla: yes

#2153 appengine-java8/mailgun: address checkstyle violation
  appengine-java8/mailgun/src/main/java/com/example/appengine/mailgun/MailgunServlet.java
Labels: cla: yes

#2069 Cleanup DLP Risk Analysis snippets
  dlp/README.md
  dlp/src/main/java/com/example/dlp/RiskAnalysis.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisCategoricalStats.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisKAnonymity.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisKMap.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisLDiversity.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisNumericalStats.java
  dlp/src/test/java/dlp/snippets/InspectTests.java
  dlp/src/test/java/dlp/snippets/RiskAnalysisTests.java
Labels: cla: yes

#2083 Fix Checkstyle errors for DLP Snippets and Tests
  dlp/src/main/java/dlp/snippets/DeIdentifyWithDateShift.java
  dlp/src/main/java/dlp/snippets/DeIdentifyWithFpe.java
  dlp/src/main/java/dlp/snippets/DeIdentifyWithMasking.java
  dlp/src/main/java/dlp/snippets/InfoTypesList.java
  dlp/src/main/java/dlp/snippets/JobsDelete.java
  dlp/src/main/java/dlp/snippets/JobsList.java
  dlp/src/main/java/dlp/snippets/ReIdentifyWithFpe.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisKMap.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisLDiversity.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisNumericalStats.java
  dlp/src/main/java/dlp/snippets/TemplatesCreate.java
  dlp/src/main/java/dlp/snippets/TemplatesDelete.java
  dlp/src/main/java/dlp/snippets/TemplatesList.java
  dlp/src/main/java/dlp/snippets/TriggersCreate.java
  dlp/src/main/java/dlp/snippets/TriggersDelete.java
  dlp/src/main/java/dlp/snippets/TriggersList.java
  dlp/src/test/java/dlp/snippets/DeIdentificationTests.java
  dlp/src/test/java/dlp/snippets/InfoTypesTests.java
  dlp/src/test/java/dlp/snippets/InspectTests.java
  dlp/src/test/java/dlp/snippets/JobsTests.java
  dlp/src/test/java/dlp/snippets/QuickstartTests.java
  dlp/src/test/java/dlp/snippets/RedactTests.java
  dlp/src/test/java/dlp/snippets/TemplatesTests.java
  dlp/src/test/java/dlp/snippets/TriggersTests.java
Labels: cla: yes

#2167 For Java 11, skip appengine-java8 & flexible
  .kokoro/tests/run_tests.sh
Labels: cla: yes

#2184 fix: bigquery/bigquerystorage needs a java property set
  bigquery/bigquerystorage/pom.xml
Labels: automerge, cla: yes

#2189 Add "automerge" to RenovateBot actions
  renovate.json
Labels: cla: yes

#2019 Update kms sample to use libraries-bom.
  kms/pom.xml
Labels: cla: yes

#2200 docs: Add SecurityCenter Notification snippets
  securitycenter/pom.xml
  securitycenter/src/main/java/com/google/cloud/examples/securitycenter/snippets/CreateNotificationConfigSnippets.java
  securitycenter/src/main/java/com/google/cloud/examples/securitycenter/snippets/DeleteNotificationConfigSnippets.java
  securitycenter/src/main/java/com/google/cloud/examples/securitycenter/snippets/GetNotificationConfigSnippets.java
  securitycenter/src/main/java/com/google/cloud/examples/securitycenter/snippets/ListNotificationConfigSnippets.java
  securitycenter/src/main/java/com/google/cloud/examples/securitycenter/snippets/NotificationReceiver.java
  securitycenter/src/main/java/com/google/cloud/examples/securitycenter/snippets/UpdateNotificationConfigSnippets.java
  securitycenter/src/test/java/com/google/cloud/examples/securitycenter/snippets/NotificationConfigSnippetTests.java
Labels: cla: yes

#2212 Fix typo in GCF sample region tag
  functions/snippets/src/main/java/com/example/functions/HelloBackground.java
Labels: cla: yes

#2215 Enable buildcop.
  .kokoro/tests/run_tests.sh
Labels: cla: yes

#2137 Fix breaking changes on Data Catalog library update
  datacatalog/cloud-client/build.gradle
  datacatalog/cloud-client/pom.xml
  datacatalog/cloud-client/src/main/java/com/example/datacatalog/CreateEntryGroup.java
  datacatalog/cloud-client/src/main/java/com/example/datacatalog/CreateFilesetEntry.java
  datacatalog/cloud-client/src/main/java/com/example/datacatalog/LookupEntryBigQueryDataset.java
  datacatalog/cloud-client/src/main/java/com/example/datacatalog/LookupEntryBigQueryTable.java
  datacatalog/cloud-client/src/main/java/com/example/datacatalog/LookupEntryPubSubTopic.java
  datacatalog/cloud-client/src/test/java/com/example/datacatalog/CreateEntryTests.java
  datacatalog/quickstart/build.gradle
  datacatalog/quickstart/pom.xml
  datacatalog/quickstart/src/main/java/com/example/datacatalog/CreateFilesetEntry.java
  datacatalog/quickstart/src/test/java/com/example/datacatalog/CreateFilesetEntryTests.java
Labels: automerge, cla: yes

#2136 dialogflow: increase timeout for test
  dialogflow/cloud-client/pom.xml
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DocumentManagement.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/DetectIntentStreamIT.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/KnowledgeBaseManagementIT.java
Labels: cla: yes

#2254 vision: change flaky tests to be more fuzzy
  vision/cloud-client/src/test/java/com/example/vision/DetectIT.java
Labels: cla: yes

#2272 delete gameservices
  gameservices/v1alpha/pom.xml
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/allocationpolicies/CreateAllocationPolicy.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/allocationpolicies/DeleteAllocationPolicy.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/allocationpolicies/GetAllocationPolicy.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/allocationpolicies/ListAllocationPolicies.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/allocationpolicies/UpdateAllocationPolicy.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/clusters/CreateCluster.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/clusters/DeleteCluster.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/clusters/GetCluster.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/clusters/ListClusters.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/clusters/UpdateCluster.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/deployments/CommitRollout.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/deployments/CreateDeployment.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/deployments/DeleteDeployment.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/deployments/GetDeployment.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/deployments/GetDeploymentTarget.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/deployments/ListDeployments.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/deployments/RevertRollout.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/deployments/SetRolloutTarget.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/deployments/StartRollout.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/deployments/UpdateDeployment.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/realms/CreateRealm.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/realms/DeleteRealm.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/realms/GetRealm.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/realms/ListRealms.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/realms/UpdateRealm.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/scalingpolicies/CreateScalingPolicy.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/scalingpolicies/DeleteScalingPolicy.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/scalingpolicies/GetScalingPolicy.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/scalingpolicies/ListScalingPolicies.java
  gameservices/v1alpha/src/main/java/com/google/cloud/gameservices/samples/scalingpolicies/UpdateScalingPolicy.java
  gameservices/v1alpha/src/test/java/com/google/cloud/gameservices/samples/AllocationPolicyTests.java
  gameservices/v1alpha/src/test/java/com/google/cloud/gameservices/samples/ClusterTests.java
  gameservices/v1alpha/src/test/java/com/google/cloud/gameservices/samples/DeploymentTests.java
  gameservices/v1alpha/src/test/java/com/google/cloud/gameservices/samples/GameServicesTestUtil.java
  gameservices/v1alpha/src/test/java/com/google/cloud/gameservices/samples/RealmTests.java
  gameservices/v1alpha/src/test/java/com/google/cloud/gameservices/samples/ScalingPolicyTests.java
Labels: automerge, cla: yes
