Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2020-12, with the labels that each got.

#4282 Add sample for Cloud SQL for SQL Server
  cloud-sql/sqlserver/servlet/README.md
  cloud-sql/sqlserver/servlet/pom.xml
  cloud-sql/sqlserver/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java
  cloud-sql/sqlserver/servlet/src/main/java/com/example/cloudsql/IndexServlet.java
  cloud-sql/sqlserver/servlet/src/main/java/com/example/cloudsql/Vote.java
  cloud-sql/sqlserver/servlet/src/main/webapp/WEB-INF/appengine-web.xml
  cloud-sql/sqlserver/servlet/src/main/webapp/index.jsp
Labels: cla: yes, samples

#4335 chore: fix region tag in Cloud SQL sample
  cloud-sql/sqlserver/servlet/src/main/java/com/example/cloudsql/IndexServlet.java
Labels: cla: yes, samples

#4305 STS check latest transfer operation sample
  storage/storage-transfer/pom.xml
  storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/CheckLatestTransferOperation.java
  storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/RequestChecker.java
  storage/storage-transfer/src/test/java/com/google/cloud/storage/storagetransfer/samples/test/CheckLatestTransferOperationTest.java
  storage/storage-transfer/src/test/java/com/google/cloud/storage/storagetransfer/samples/test/RequestCheckerTest.java
Labels: cla: yes, do not merge, samples

#4350 Limit renovate updates for mssql-jdbc to jre8.
  renovate.json
Labels: cla: yes, samples

#4277 Update README.md
  dataflow/flex-templates/streaming_beam_sql/README.md
Labels: cla: yes, samples

#4352 chore: updates to Cloud SQL samples
  cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java
  cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java
  cloud-sql/sqlserver/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java
Labels: cla: yes, samples

#4353 chore(bigtable_spark): last round of readme updates
  bigtable/spark/README.md
Labels: api: bigtable, cla: yes, samples

#4364 Add allowed list to prevent false positive git secret check.
  .gitallowed
Labels: cla: yes, samples

#4365 Update pom.xml
  iam/api-client/pom.xml
Labels: cla: yes, samples

#4369 Move samples from firebase-appengine-backend to java-docs-samples.
  appengine-java8/firebase-backend/README.md
  appengine-java8/firebase-backend/pom.xml
  appengine-java8/firebase-backend/src/main/java/com/google/cloud/solutions/flexenv/backend/MessageProcessorServlet.java
  appengine-java8/firebase-backend/src/main/java/com/google/cloud/solutions/flexenv/backend/MessagePurger.java
  appengine-java8/firebase-backend/src/main/java/com/google/cloud/solutions/flexenv/common/LogEntry.java
  appengine-java8/firebase-backend/src/main/java/com/google/cloud/solutions/flexenv/common/Message.java
  appengine-java8/firebase-backend/src/main/webapp/WEB-INF/appengine-web.xml
  appengine-java8/firebase-backend/src/main/webapp/WEB-INF/logging.properties
  appengine-java8/firebase-backend/src/main/webapp/WEB-INF/web.xml
Labels: cla: yes, samples

#4397 Update assertNotNull
  appengine-java11/tasks/src/test/java/com/example/task/CreateTaskIT.java
  appengine-java8/tasks/quickstart/src/test/java/com/example/task/CreateTaskIT.java
  cdn/signed-urls/src/test/java/com/google/cdn/SignedUrlsTest.java
  container-registry/container-analysis/src/test/java/com/example/containeranalysis/SamplesTest.java
  healthcare/v1/src/test/java/snippets/healthcare/DatasetTests.java
  healthcare/v1/src/test/java/snippets/healthcare/DicomStoreTests.java
  healthcare/v1/src/test/java/snippets/healthcare/DicomWebTests.java
  healthcare/v1/src/test/java/snippets/healthcare/FhirResourceTests.java
  healthcare/v1/src/test/java/snippets/healthcare/FhirStoreTests.java
  healthcare/v1/src/test/java/snippets/healthcare/Hl7v2MessageTests.java
  healthcare/v1/src/test/java/snippets/healthcare/Hl7v2StoreTests.java
  media/transcoder/src/test/java/com/example/transcoder/CreateJobFromAdHocTest.java
  media/transcoder/src/test/java/com/example/transcoder/CreateJobFromPresetTest.java
  media/transcoder/src/test/java/com/example/transcoder/CreateJobFromTemplateTest.java
  media/transcoder/src/test/java/com/example/transcoder/CreateJobTemplateTest.java
  media/transcoder/src/test/java/com/example/transcoder/DeleteJobTemplateTest.java
  media/transcoder/src/test/java/com/example/transcoder/DeleteJobTest.java
  media/transcoder/src/test/java/com/example/transcoder/GetJobTemplateTest.java
  media/transcoder/src/test/java/com/example/transcoder/GetJobTest.java
  media/transcoder/src/test/java/com/example/transcoder/ListJobTemplateTest.java
  media/transcoder/src/test/java/com/example/transcoder/ListJobsTest.java
  storage/s3-sdk/src/test/java/ListGcsBucketsTest.java
  storage/s3-sdk/src/test/java/ListGcsObjectsTest.java
Labels: cla: yes, samples

#4399 Update README.md
  README.md
Labels: automerge, cla: yes, kokoro:force-run, samples

#4419 chore: remove logging samples from java-docs-samples
  logging/cloud-client/README.md
  logging/cloud-client/pom.xml
  logging/cloud-client/src/main/java/com/example/logging/ListLogs.java
  logging/cloud-client/src/main/java/com/example/logging/QuickstartSample.java
  logging/cloud-client/src/test/java/com/example/logging/LoggingIT.java
  logging/jul/README.md
  logging/jul/pom.xml
  logging/jul/src/main/java/com/example/logging/jul/Quickstart.java
  logging/jul/src/main/java/com/example/logging/jul/enhancers/ExampleEnhancer.java
  logging/jul/src/main/resources/logging.properties
  logging/logback/README.md
  logging/logback/pom.xml
  logging/logback/src/main/java/com/example/logging/logback/Quickstart.java
  logging/logback/src/main/java/com/example/logging/logback/enhancers/ExampleEnhancer.java
  logging/logback/src/main/resources/logback.xml
Labels: api: logging, cla: yes, lang: java, priority: p2, samples, type: docs

#4384 bigtable: spark example
  bigtable/spark/README.md
  bigtable/spark/build.sbt
  bigtable/spark/project/assembly.sbt
  bigtable/spark/project/build.properties
  bigtable/spark/src/main/scala/example/CopyTable.scala
  bigtable/spark/src/main/scala/example/Wordcount.scala
  bigtable/spark/src/test/resources/Romeo-and-Juliet-prologue.txt
  bigtable/spark/src/test/resources/log4j.properties
  bigtable/spark/src/test/scala/example/IntegrationTest.scala
Labels: api: bigtable, cla: yes, samples

#4441 chore(bigtable_spark): deps cleanup
  bigtable/spark/build.sbt
Labels: api: bigtable, cla: yes, samples

#4449 chore(bigtable_spark): rollback scala update and update renovate config
  bigtable/spark/build.sbt
  renovate.json
Labels: api: bigtable, automerge, cla: yes, samples

#4448 Pub/Sub: add --region to command to start dataflow job
  pubsub/streaming-analytics/README.md
Labels: cla: yes, samples

#4478 Update cloud-sql sample apps to deploy to Cloud Run using Jib.
  cloud-sql/mysql/servlet/Dockerfile
  cloud-sql/mysql/servlet/README.md
  cloud-sql/postgres/servlet/README.md
  cloud-sql/sqlserver/servlet/README.md
Labels: cla: yes, samples

#4483 dataflow: simplify enabled APIs list
  dataflow/README.md
Labels: api: dataflow, cla: yes, samples
