Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2020-10, with the labels that each got.

#3866 Pub/Sub: rename input Spring message channel and lint
  pubsub/spring/src/main/java/demo/PubSubApplication.java
Labels: cla: yes

#3885 Fix minor typos
  appengine-java11/appengine-simple-jetty-main/README.md
Labels: automerge, cla: yes, samples

#3887 Remove duplicative (but broken) tests
  flexible/helloworld-springboot/src/test/java/com/example/java/HelloControllerIT.java
Labels: automerge, cla: yes

#3884 Wordcount on Dataproc WORKS! (No more NPEs)
  bigtable/spark/README.md
  bigtable/spark/src/main/scala/example/Wordcount.scala
Labels: cla: yes, samples

#3903 chore(functions/pubsub): use consistent param names
  functions/pubsub/publish-message/src/main/java/functions/PublishMessage.java
  functions/pubsub/publish-message/src/test/java/functions/PublishMessageTest.java
Labels: api: cloudfunctions, cla: yes, samples

#3922 chore: enable snippet-bot
  .github/snippet-bot.yml
Labels: cla: yes

#3695 fix requireEnvVar
  speech/cloud-client/src/test/java/com/example/speech/TranscribeDiarizationIT.java
  vision/cloud-client/src/test/java/com/example/vision/AsyncBatchAnnotateImagesTest.java
Labels: cla: yes, kokoro:run, samples

#3929 Update POM to use smaller Bigtable dependency
  appengine-java8/bigtable/pom.xml
Labels: cla: yes

#3931 Vulnerability notification example
  container-registry/vulnerability-notification-function/.gcloudignore
  container-registry/vulnerability-notification-function/.gitignore
  container-registry/vulnerability-notification-function/README.md
  container-registry/vulnerability-notification-function/cloudops/container-analysis-metrics.yaml
  container-registry/vulnerability-notification-function/cloudops/vulnerability-policy.yaml
  container-registry/vulnerability-notification-function/pom.xml
  container-registry/vulnerability-notification-function/src/main/java/com/example/containeranalysis/OccurrenceNotification.java
  container-registry/vulnerability-notification-function/src/main/java/com/example/containeranalysis/PubSubMessage.java
  container-registry/vulnerability-notification-function/src/main/java/com/example/containeranalysis/VulnerabilityFunction.java
  container-registry/vulnerability-notification-function/src/test/java/com/example/containeranalysis/VulnerabilityFunctionTest.java
Labels: cla: yes

#3957 samples: added retry logic for flaky tests
  video/cloud-client/src/test/java/com/example/video/DetectIT.java
  video/cloud-client/src/test/java/com/example/video/DetectTextTest.java
  video/cloud-client/src/test/java/com/example/video/Retry.java
Labels: cla: yes

#3958 samples: tests refactored
  video/beta/src/test/java/com/example/video/DetectFacesGcsIT.java
  video/beta/src/test/java/com/example/video/DetectFacesIT.java
Labels: automerge, cla: yes

#3717 Sample for Bigtable and Memcached
  bigtable/memorystore/README.md
  bigtable/memorystore/pom.xml
  bigtable/memorystore/src/main/java/Memcached.java
  bigtable/memorystore/src/test/java/MemcachedTest.java
Labels: cla: yes, samples

#3993 samples: added cleanup option
  iot/api-client/end-to-end-example/src/main/java/com/example/cloud/iot/endtoend/CleanUpHelper.java
  iot/api-client/end-to-end-example/src/test/java/com/example/cloud/iot/endtoend/CloudiotPubsubExampleServerTest.java
Labels: automerge, cla: yes

#4012 chore: add observability team to codeowners
  .github/CODEOWNERS
Labels: api: logging, cla: yes, lang: java, priority: p2, samples, type: process

#3784 Add Cloud SQL R2DBC sample
  cloud-sql/r2dbc/README.md
  cloud-sql/r2dbc/pom.xml
  cloud-sql/r2dbc/src/main/appengine/app.yaml
  cloud-sql/r2dbc/src/main/java/com/example/cloudsql/r2dbcsample/CommandLineRunnerSchemaCreator.java
  cloud-sql/r2dbc/src/main/java/com/example/cloudsql/r2dbcsample/MainController.java
  cloud-sql/r2dbc/src/main/java/com/example/cloudsql/r2dbcsample/R2dbcSampleApplication.java
  cloud-sql/r2dbc/src/main/java/com/example/cloudsql/r2dbcsample/Vote.java
  cloud-sql/r2dbc/src/main/java/com/example/cloudsql/r2dbcsample/VoteController.java
  cloud-sql/r2dbc/src/main/java/com/example/cloudsql/r2dbcsample/VoteRepository.java
  cloud-sql/r2dbc/src/main/resources/application.properties
  cloud-sql/r2dbc/src/main/resources/templates/index.html
Labels: cla: yes, samples

#4028 Update blunderbuss to use java-samples-reviewers team
  .github/blunderbuss.yml
Labels: cla: yes

#4037 Bigtable Memcached example fixes/cleanup
  bigtable/memorystore/README.md
  bigtable/memorystore/src/main/java/Memcached.java
  bigtable/memorystore/src/test/java/MemcachedTest.java
Labels: cla: yes

#4038 chore(testing): remove static analysis checks
  .kokoro/static_analysis/common.cfg
  .kokoro/static_analysis/presubmit.cfg
  .kokoro/tests/run_static_analysis.sh
Labels: cla: yes, do not merge

#4048 clean up grammar and spelling
  SAMPLE_FORMAT.md
Labels: cla: yes

#4052 Remove region tag
  eventarc/pubsub/pom.xml
Labels: cla: yes

#4057 chore(functions/ocr): delete unused region tag
  functions/ocr/ocr-save-result/src/main/java/functions/OcrSaveResult.java
Labels: cla: yes

#4051 Update region tags with product name
  appengine-java8/tasks/snippets/src/main/java/com/example/task/CreateQueue.java
  appengine-java8/tasks/snippets/src/main/java/com/example/task/CreateTask.java
  appengine-java8/tasks/snippets/src/main/java/com/example/task/CreateTaskWithName.java
  appengine-java8/tasks/snippets/src/main/java/com/example/task/DeleteQueue.java
  appengine-java8/tasks/snippets/src/main/java/com/example/task/DeleteTask.java
  appengine-java8/tasks/snippets/src/main/java/com/example/task/PauseQueue.java
  appengine-java8/tasks/snippets/src/main/java/com/example/task/PurgeQueue.java
  appengine-java8/tasks/snippets/src/main/java/com/example/task/RetryTask.java
  appengine-java8/tasks/snippets/src/main/java/com/example/task/UpdateQueue.java
Labels: cla: yes

#4062 Fixed description of function
  translate/automl/src/main/java/com/google/cloud/translate/automl/PredictionApi.java
Labels: cla: yes

#4075 chore: added missing exception for iot test
  iot/api-client/end-to-end-example/src/test/java/com/example/cloud/iot/endtoend/CloudiotPubsubExampleServerTest.java
Labels: cla: yes

#4078 chore: update expired keys
  iot/api-client/manager/resources/ec_public.pem
  iot/api-client/manager/resources/rsa_cert.pem
  iot/api-client/manager/resources/rsa_private.pem
  iot/api-client/manager/resources/rsa_private_pkcs8
Labels: cla: yes

#4074 Add FhirResourceUpdate sample.
  healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceUpdate.java
  healthcare/v1/src/test/java/snippets/healthcare/FhirResourceTests.java
Labels: cla: yes, samples

#4082 chores: removing translate samples which already moved to java-translate
  translate/README.md
  translate/automl/README.md
  translate/automl/pom.xml
  translate/automl/resources/input.txt
  translate/automl/src/main/java/com/google/cloud/translate/automl/DatasetApi.java
  translate/automl/src/main/java/com/google/cloud/translate/automl/ModelApi.java
  translate/automl/src/main/java/com/google/cloud/translate/automl/PredictionApi.java
  translate/automl/src/test/java/com/google/cloud/translate/automl/DatasetApiIT.java
  translate/automl/src/test/java/com/google/cloud/translate/automl/ModelApiIT.java
  translate/automl/src/test/java/com/google/cloud/translate/automl/PredictionApiIT.java
  translate/cloud-client/README.md
  translate/cloud-client/pom.xml
  translate/cloud-client/src/main/java/com/example/translate/BatchTranslateText.java
  translate/cloud-client/src/main/java/com/example/translate/BatchTranslateTextWithGlossary.java
  translate/cloud-client/src/main/java/com/example/translate/BatchTranslateTextWithGlossaryAndModel.java
  translate/cloud-client/src/main/java/com/example/translate/BatchTranslateTextWithModel.java
  translate/cloud-client/src/main/java/com/example/translate/CreateGlossary.java
  translate/cloud-client/src/main/java/com/example/translate/DeleteGlossary.java
  translate/cloud-client/src/main/java/com/example/translate/DetectLanguage.java
  translate/cloud-client/src/main/java/com/example/translate/GetGlossary.java
  translate/cloud-client/src/main/java/com/example/translate/GetSupportedLanguages.java
  translate/cloud-client/src/main/java/com/example/translate/GetSupportedLanguagesForTarget.java
  translate/cloud-client/src/main/java/com/example/translate/ListGlossaries.java
  translate/cloud-client/src/main/java/com/example/translate/QuickstartSample.java
  translate/cloud-client/src/main/java/com/example/translate/TranslateText.java
  translate/cloud-client/src/main/java/com/example/translate/TranslateTextWithGlossary.java
  translate/cloud-client/src/main/java/com/example/translate/TranslateTextWithGlossaryAndModel.java
  translate/cloud-client/src/main/java/com/example/translate/TranslateTextWithModel.java
  translate/cloud-client/src/test/java/com/example/translate/BatchTranslateTextTests.java
  translate/cloud-client/src/test/java/com/example/translate/BatchTranslateTextWithGlossaryAndModelTests.java
  translate/cloud-client/src/test/java/com/example/translate/BatchTranslateTextWithGlossaryTests.java
  translate/cloud-client/src/test/java/com/example/translate/BatchTranslateTextWithModelTests.java
  translate/cloud-client/src/test/java/com/example/translate/CreateGlossaryTests.java
  translate/cloud-client/src/test/java/com/example/translate/DeleteGlossaryTests.java
  translate/cloud-client/src/test/java/com/example/translate/DetectLanguageTests.java
  translate/cloud-client/src/test/java/com/example/translate/GetGlossaryTests.java
  translate/cloud-client/src/test/java/com/example/translate/GetSupportedLanguagesForTargetTests.java
  translate/cloud-client/src/test/java/com/example/translate/GetSupportedLanguagesTests.java
  translate/cloud-client/src/test/java/com/example/translate/ListGlossariesTests.java
  translate/cloud-client/src/test/java/com/example/translate/QuickstartSampleIT.java
  translate/cloud-client/src/test/java/com/example/translate/TranslateTextTests.java
  translate/cloud-client/src/test/java/com/example/translate/TranslateTextWithGlossaryAndModelTests.java
  translate/cloud-client/src/test/java/com/example/translate/TranslateTextWithGlossaryTests.java
  translate/cloud-client/src/test/java/com/example/translate/TranslateTextWithModelTests.java
Labels: cla: yes, do not merge, samples
