Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2020-09, with the labels that each got.

#3638 Add Dockerfile for Cloud Run quickstart
  run/helloworld/.dockerignore
  run/helloworld/Dockerfile
Labels: cla: yes

#3650 docs: clean up language
  SAMPLE_FORMAT.md
Labels: cla: yes

#3649 libraries-bom 10.0
  automl/beta/pom.xml
Labels: cla: yes

#3671 translate sample to use libraries-bom 10.0.0
  translate/cloud-client/pom.xml
Labels: cla: yes

#3675 samples: fixed flaky test on getOper sample
  automl/cloud-client/src/main/java/com/example/automl/GetOperationStatus.java
  automl/cloud-client/src/test/java/com/example/automl/GetOperationStatusTest.java
Labels: automerge, cla: yes

#3674 automl/cloud-client/pom.xml to use the GCP Libraries BOM 10.0.0
  automl/cloud-client/README.md
  automl/cloud-client/pom.xml
Labels: cla: yes

#3677 chore(functions/firebase): Add infinite-loop guard + test
  functions/firebase/firestore-reactive/src/main/java/functions/FirebaseFirestoreReactive.java
  functions/firebase/firestore-reactive/src/test/java/functions/FirebaseFirestoreReactiveTest.java
Labels: api: cloudfunctions, cla: yes, samples

#3683 dataflow/flex-templates: update commands to GA
  dataflow/flex-templates/kafka_to_bigquery/Dockerfile
  dataflow/flex-templates/kafka_to_bigquery/README.md
  dataflow/flex-templates/streaming_beam_sql/Dockerfile
  dataflow/flex-templates/streaming_beam_sql/README.md
Labels: cla: yes

#3689 chore(functions/slack): update Slack sample
  functions/slack/pom.xml
  functions/slack/src/main/java/functions/SlackSlashCommand.java
  functions/slack/src/test/java/functions/SlackSlashCommandTest.java
Labels: cla: yes

#3690 chore(functions/slack): add back missing package
  functions/slack/pom.xml
Labels: automerge, cla: yes

#3697 Update Monitoring sample tests
  monitoring/v3/README.md
  monitoring/v3/src/test/java/com/example/AlertIT.java
Labels: cla: yes

#3687 refactored samples
  automl/cloud-client/src/main/java/com/example/automl/BatchPredict.java
  automl/cloud-client/src/main/java/com/example/automl/DeleteDataset.java
  automl/cloud-client/src/main/java/com/example/automl/ExportDataset.java
  automl/cloud-client/src/main/java/com/example/automl/GetDataset.java
  automl/cloud-client/src/main/java/com/example/automl/GetModel.java
  automl/cloud-client/src/main/java/com/example/automl/GetModelEvaluation.java
  automl/cloud-client/src/main/java/com/example/automl/GetOperationStatus.java
  automl/cloud-client/src/main/java/com/example/automl/LanguageEntityExtractionCreateDataset.java
  automl/cloud-client/src/main/java/com/example/automl/LanguageEntityExtractionCreateModel.java
  automl/cloud-client/src/main/java/com/example/automl/LanguageEntityExtractionPredict.java
  automl/cloud-client/src/main/java/com/example/automl/LanguageSentimentAnalysisCreateDataset.java
  automl/cloud-client/src/main/java/com/example/automl/LanguageSentimentAnalysisCreateModel.java
  automl/cloud-client/src/main/java/com/example/automl/LanguageSentimentAnalysisPredict.java
  automl/cloud-client/src/main/java/com/example/automl/LanguageTextClassificationCreateDataset.java
  automl/cloud-client/src/main/java/com/example/automl/LanguageTextClassificationCreateModel.java
  automl/cloud-client/src/main/java/com/example/automl/LanguageTextClassificationPredict.java
  automl/cloud-client/src/main/java/com/example/automl/ListDatasets.java
  automl/cloud-client/src/main/java/com/example/automl/ListModelEvaluations.java
  automl/cloud-client/src/main/java/com/example/automl/ListModels.java
  automl/cloud-client/src/main/java/com/example/automl/ListOperationStatus.java
  automl/cloud-client/src/main/java/com/example/automl/TranslateCreateDataset.java
  automl/cloud-client/src/main/java/com/example/automl/TranslateCreateModel.java
  automl/cloud-client/src/main/java/com/example/automl/TranslatePredict.java
  automl/cloud-client/src/main/java/com/example/automl/VisionClassificationCreateDataset.java
  automl/cloud-client/src/main/java/com/example/automl/VisionClassificationCreateModel.java
  automl/cloud-client/src/main/java/com/example/automl/VisionClassificationPredict.java
  automl/cloud-client/src/main/java/com/example/automl/VisionObjectDetectionCreateDataset.java
  automl/cloud-client/src/main/java/com/example/automl/VisionObjectDetectionCreateModel.java
  automl/cloud-client/src/main/java/com/example/automl/VisionObjectDetectionPredict.java
Labels: automerge, cla: yes, samples

#3710 Pub/Sub: rearrange region tag
  pubsub/spring/pom.xml
Labels: cla: yes

#3713 chore: remove reference to deprecated class
  spanner/jdbc/src/test/java/com/example/spanner/jdbc/JdbcExamplesIT.java
Labels: cla: yes

#3712 fix: explicitly rollback transaction after abort
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/TransactionWithRetryLoopExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/TransactionWithRetryLoopUsingOnlyJdbcExample.java
Labels: cla: yes

#3714 feat: add samples for numeric
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/AutocommitUpdateDataExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/BatchDmlExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/BatchDmlUsingSqlStatementsExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/BufferedWriteExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateTableExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/InsertDataExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/ReadOnlyTransactionExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/ReadWriteTransactionExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/SingleUseReadOnlyExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/SingleUseReadOnlyTimestampBoundExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/TransactionWithRetryLoopExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/TransactionWithRetryLoopUsingOnlyJdbcExample.java
  spanner/jdbc/src/test/java/com/example/spanner/jdbc/JdbcExamplesIT.java
Labels: api: spanner, cla: yes, samples

#3737 All Vertx packages should update together.
  renovate.json
Labels: automerge, cla: yes

#3743 chore: add repo settings config
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes

#3747 Add Dockerfile and fix pom.xml so that the sample builds with Cloud Build
  run/events-storage/Dockerfile
  run/events-storage/pom.xml
Labels: automerge, cla: yes, samples

#3750 Update sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes

#3755 Update sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes

#3752 [IAM] Remove old quickstart, add dependencies
  iam/api-client/README.md
  iam/api-client/pom.xml
  iam/api-client/src/main/java/iam/snippets/Quickstart.java
  iam/api-client/src/main/java/iam/snippets/QuickstartV2.java
  iam/api-client/src/test/java/iam/snippets/QuickstartIT.java
  iam/api-client/src/test/java/iam/snippets/QuickstartTests.java
Labels: cla: yes

#3767 Delete dataset after each test in DatasetTests.
  healthcare/v1/src/test/java/snippets/healthcare/DatasetTests.java
Labels: cla: yes

#3707 samples: add standalone numeric samples for Spanner
  spanner/cloud-client/src/main/java/com/example/spanner/AddNumericColumnSample.java
  spanner/cloud-client/src/main/java/com/example/spanner/QueryWithNumericParameterSample.java
  spanner/cloud-client/src/main/java/com/example/spanner/UpdateNumericDataSample.java
  spanner/cloud-client/src/test/java/com/example/spanner/SpannerStandaloneExamplesIT.java
Labels: api: spanner, cla: yes, samples

#3780 Never update servlet
  renovate.json
Labels: automerge, cla: yes

#3770 Determine pubsub event timestamp correctly in retry-timeout.
  functions/concepts/retry-timeout/src/main/java/functions/RetryTimeout.java
  functions/concepts/retry-timeout/src/test/java/functions/RetryTimeoutTest.java
Labels: cla: yes, samples

#3769 Update static analysis image to include java 8 and 11 runtimes.
  .kokoro/static_analysis/common.cfg
Labels: cla: yes, samples

#3795 gae: lead with gae_ in region tags
  flexible/pubsub/src/main/java/com/example/flexible/pubsub/PubSubPublish.java
  flexible/pubsub/src/main/java/com/example/flexible/pubsub/PubSubPush.java
Labels: cla: yes

#3808 samples: added small reminder for deleted samples
  automl/README.md
Labels: cla: yes, samples

#3804 samples: vision async batch increase timeout len
  vision/beta/cloud-client/src/main/java/com/example/vision/AsyncBatchAnnotateImagesGcs.java
  vision/cloud-client/src/main/java/com/example/vision/Detect.java
Labels: cla: yes, samples

#3806 samples: translate batch lro occasionally hits 4-5 min mark
  translate/cloud-client/src/main/java/com/example/translate/BatchTranslateText.java
  translate/cloud-client/src/main/java/com/example/translate/BatchTranslateTextWithGlossary.java
  translate/cloud-client/src/main/java/com/example/translate/BatchTranslateTextWithGlossaryAndModel.java
  translate/cloud-client/src/main/java/com/example/translate/BatchTranslateTextWithModel.java
Labels: cla: yes, samples

#3487 [WIP] Spark Applications for Cloud Bigtable
  bigtable/spark/README.md
  bigtable/spark/build.sbt
  bigtable/spark/project/assembly.sbt
  bigtable/spark/project/build.properties
  bigtable/spark/src/main/scala/example/CopyTable.scala
  bigtable/spark/src/main/scala/example/Wordcount.scala
  bigtable/spark/src/test/resources/Romeo-and-Juliet-prologue.txt
  bigtable/spark/src/test/resources/log4j.properties
  bigtable/spark/src/test/scala/example/IntegrationTest.scala
Labels: cla: yes, samples

#3837 Remove entrypoint from app.yaml
  appengine-java11/vertx-helloworld/src/main/appengine/app.yaml
Labels: cla: yes

#3840 Fix check style
  appengine-java11/tasks/src/test/java/com/example/task/CreateTaskIT.java
  appengine-java8/bigtable/src/main/java/com/example/bigtable/BigtableHelloWorld.java
  appengine-java8/bigtable/src/main/java/com/example/bigtable/BigtableHelper.java
  appengine-java8/datastore/src/test/java/com/example/appengine/TransactionsTest.java
  appengine-java8/firebase-tictactoe/src/main/java/com/example/appengine/firetactoe/Game.java
  appengine-java8/firebase-tictactoe/src/main/java/com/example/appengine/firetactoe/ObjectifyHelper.java
  appengine-java8/multitenancy/src/main/java/com/example/appengine/Greeting.java
  appengine-java8/multitenancy/src/main/java/com/example/appengine/OfyHelper.java
  appengine-java8/remote-client/src/main/java/com/example/appengine/remote/RemoteApiExample.java
  appengine-java8/search/src/main/java/com/example/appengine/search/Utils.java
  appengine-java8/search/src/test/java/com/example/appengine/search/UtilsTest.java
  appengine-java8/tasks/quickstart/src/test/java/com/example/task/CreateTaskIT.java
  appengine-java8/tasks/snippets/src/test/java/com/example/task/SnippetsIT.java
  cdn/signed-urls/src/main/java/com/google/cdn/SignedUrls.java
  compute/error-reporting/src/main/java/com/example/compute/errorreporting/ExceptionUtil.java
  compute/signed-metadata/src/main/java/com/example/compute/signedmetadata/token/DecodedGoogleJWTWrapper.java
  compute/signed-metadata/src/main/java/com/example/compute/signedmetadata/token/GoogleRSAKeyProvider.java
  flexible/helloworld-springboot/src/test/java/com/example/java/HelloControllerIT.java
  flexible/pubsub/src/main/java/com/example/flexible/pubsub/MessageRepository.java
  functions/slack/src/main/java/functions/SlackSlashCommand.java
  healthcare/v1/src/main/java/snippets/healthcare/hl7v2/messages/HL7v2MessageCreate.java
  healthcare/v1/src/main/java/snippets/healthcare/hl7v2/messages/HL7v2MessageDelete.java
  healthcare/v1/src/main/java/snippets/healthcare/hl7v2/messages/HL7v2MessageGet.java
  healthcare/v1/src/main/java/snippets/healthcare/hl7v2/messages/HL7v2MessageIngest.java
  healthcare/v1/src/main/java/snippets/healthcare/hl7v2/messages/HL7v2MessageList.java
  healthcare/v1/src/main/java/snippets/healthcare/hl7v2/messages/HL7v2MessagePatch.java
  healthcare/v1/src/test/java/snippets/healthcare/Hl7v2MessageTests.java
  jobs/v3/src/main/java/com/google/samples/CustomAttributeSample.java
  kms/src/test/java/kms/SnippetsIT.java
  monitoring/v3/src/main/java/com/example/UptimeSample.java
  secretmanager/src/test/java/secretmanager/QuickstartIT.java
  secretmanager/src/test/java/secretmanager/SnippetsIT.java
  spanner/cloud-client/src/test/java/com/example/spanner/AsyncExamplesIT.java
  spanner/cloud-client/src/test/java/com/example/spanner/SpannerStandaloneExamplesIT.java
  spanner/jdbc/src/test/java/com/example/spanner/jdbc/JdbcExamplesIT.java
  spanner/leaderboard/complete/src/main/java/com/google/codelabs/App.java
  spanner/leaderboard/step6/src/main/java/com/google/codelabs/App.java
  speech/cloud-client/src/main/java/com/example/speech/InfiniteStreamRecognize.java
  tasks/src/test/java/com/example/task/CreateHttpTaskIT.java
  tasks/src/test/java/com/example/task/CreateQueueIT.java
  tasks/src/test/java/com/example/task/DeleteQueueIT.java
  tasks/src/test/java/com/example/task/ListQueuesIT.java
  video/beta/src/test/java/com/example/video/DetectFacesGcsIT.java
  video/beta/src/test/java/com/example/video/DetectFacesIT.java
  video/beta/src/test/java/com/example/video/DetectPersonGcsIT.java
  video/beta/src/test/java/com/example/video/DetectPersonIT.java
  video/cloud-client/src/main/java/com/example/video/Detect.java
  vision/automl/src/test/java/com/google/cloud/vision/samples/automl/ClassificationDeployModelIT.java
Labels: automerge, cla: yes

#3842 Update HelloControllerIT.java
  flexible/helloworld-springboot/src/test/java/com/example/java/HelloControllerIT.java
Labels: cla: yes

#3855 dataflow: update "Open in Cloud Shell" links
  dataflow/README.md
  dataflow/encryption-keys/README.md
  dataflow/flex-templates/README.md
  dataflow/flex-templates/kafka_to_bigquery/README.md
  dataflow/flex-templates/streaming_beam_sql/README.md
  dataflow/templates/README.md
Labels: cla: yes

#3852 fix: skip listBackupOperations test
  spanner/cloud-client/src/test/java/com/example/spanner/SpannerSampleIT.java
Labels: cla: yes

#3853 fix: close Spanner instance after tests
  spanner/cloud-client/src/test/java/com/example/spanner/SpannerSampleIT.java
Labels: automerge, cla: yes

#3846 Eventarc Quickstart Brushup
  eventarc/README.md
  eventarc/audit-storage/Dockerfile
  eventarc/audit-storage/README.md
  eventarc/audit-storage/anthos.md
  eventarc/audit-storage/pom.xml
  eventarc/audit-storage/src/main/java/com/example/cloudrun/Application.java
  eventarc/audit-storage/src/main/java/com/example/cloudrun/EventController.java
  eventarc/audit-storage/src/main/java/com/example/cloudrun/eventpojos/PubSubBody.java
  eventarc/audit-storage/src/main/resources/application.properties
  eventarc/audit-storage/src/test/java/com/example/cloudrun/EventControllerTests.java
  eventarc/pubsub/Dockerfile
  eventarc/pubsub/README.md
  eventarc/pubsub/anthos.md
  eventarc/pubsub/pom.xml
  eventarc/pubsub/src/main/java/com/example/cloudrun/Application.java
  eventarc/pubsub/src/main/java/com/example/cloudrun/EventController.java
  eventarc/pubsub/src/main/java/com/example/cloudrun/eventpojos/PubSubBody.java
  eventarc/pubsub/src/main/resources/application.properties
  eventarc/pubsub/src/test/java/com/example/cloudrun/EventControllerTests.java
Labels: cla: yes, samples

#3830 fix: change return type to List
  spanner/cloud-client/src/main/java/com/example/spanner/AsyncQueryToListAsyncExample.java
Labels: automerge, cla: yes, samples

#3859 docs: add numeric samples for Spanner
  spanner/cloud-client/src/main/java/com/example/spanner/SpannerSample.java
  spanner/cloud-client/src/test/java/com/example/spanner/SpannerSampleIT.java
Labels: cla: yes
