Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2020-06, with the labels that each got.

#3007 Update app.yaml for Java 11
  appengine-java11/appengine-simple-jetty-main/README.md
  appengine-java11/cloudsql/app.yaml
  appengine-java11/gaeinfo/src/main/appengine/app.yaml
  appengine-java11/guestbook-cloud-firestore/src/main/appengine/app.yaml
  appengine-java11/helloworld-servlet/README.md
  appengine-java11/helloworld-servlet/src/main/appengine/app.yaml
  appengine-java11/kotlin-ktor/app.yaml
  appengine-java11/micronaut-helloworld/src/main/appengine/app.yaml
  appengine-java11/oauth2/src/main/appengine/app.yaml
  appengine-java11/quarkus-helloworld/src/main/appengine/app.yaml
  appengine-java11/spanner/src/main/appengine/app.yaml
  appengine-java11/sparkjava-helloworld/src/main/appengine/app.yaml
  appengine-java11/springboot-helloworld/src/main/appengine/app.yaml
Labels: cla: yes

#3008 Fix issues with DLP readme and samples used in it
  dlp/README.md
  dlp/pom.xml
  dlp/src/main/java/dlp/snippets/InfoTypesList.java
  dlp/src/main/java/dlp/snippets/RedactImageFile.java
  dlp/src/test/java/dlp/snippets/RedactTests.java
Labels: automerge, cla: yes

#3010 Move helloworld samples from getting-started-java
  appengine-java8/helloworld/README.md
  appengine-java8/helloworld/build.gradle
  appengine-java8/helloworld/gradle/wrapper/gradle-wrapper.properties
  appengine-java8/helloworld/gradlew
  appengine-java8/helloworld/gradlew.bat
  appengine-java8/helloworld/pom.xml
  appengine-java8/helloworld/settings.gradle
  appengine-java8/helloworld/src/main/java/com/example/appengine/java8/HelloAppEngine.java
  appengine-java8/helloworld/src/main/webapp/WEB-INF/appengine-web.xml
  appengine-java8/helloworld/src/main/webapp/index.jsp
  appengine-java8/helloworld/src/test/java/com/example/appengine/java8/HelloAppEngineTest.java
  appengine-java8/sparkjava-helloworld/.gitignore
  appengine-java8/sparkjava-helloworld/README.md
  appengine-java8/sparkjava-helloworld/pom.xml
  appengine-java8/sparkjava-helloworld/src/main/java/HelloWorld.java
  appengine-java8/sparkjava-helloworld/src/main/webapp/WEB-INF/appengine-web.xml
  appengine-java8/sparkjava-helloworld/src/main/webapp/WEB-INF/logging.properties
  appengine-java8/springboot-helloworld/.gitignore
  appengine-java8/springboot-helloworld/.mvn/wrapper/maven-wrapper.jar
  appengine-java8/springboot-helloworld/.mvn/wrapper/maven-wrapper.properties
  appengine-java8/springboot-helloworld/README.md
  appengine-java8/springboot-helloworld/mvnw
  appengine-java8/springboot-helloworld/mvnw.cmd
  appengine-java8/springboot-helloworld/pom.xml
  appengine-java8/springboot-helloworld/src/main/java/com/example/appengine/demos/springboot/HelloworldController.java
  appengine-java8/springboot-helloworld/src/main/java/com/example/appengine/demos/springboot/ServletInitializer.java
  appengine-java8/springboot-helloworld/src/main/java/com/example/appengine/demos/springboot/SpringBootExampleApplication.java
  appengine-java8/springboot-helloworld/src/main/resources/application.properties
  appengine-java8/springboot-helloworld/src/main/resources/logging.properties
  appengine-java8/springboot-helloworld/src/main/webapp/WEB-INF/appengine-web.xml
  appengine-java8/springboot-helloworld/src/test/java/com/example/appengine/demos/springboot/SpringBootExampleApplicationTests.java
Labels: automerge, cla: yes

#3011 bug: fix importData sample in order to bump libraries-bom version
  vision/automl/pom.xml
  vision/automl/src/main/java/com/google/cloud/vision/samples/automl/DatasetApi.java
  vision/automl/src/test/java/com/google/cloud/vision/samples/automl/DatasetApiIT.java
Labels: automerge, cla: yes

#3012 Add Java code sample for concepts-infotypes
  dlp/src/main/java/dlp/snippets/InspectPhoneNumber.java
  dlp/src/test/java/dlp/snippets/InspectTests.java
Labels: cla: yes

#3017 Create Java code sample for create job
  dlp/src/main/java/dlp/snippets/JobsCreate.java
  dlp/src/test/java/dlp/snippets/JobsTests.java
Labels: automerge, cla: yes

#3019 feat: remove automl beta samples
  automl/beta/pom.xml
  automl/beta/src/main/java/com/example/automl/BatchPredict.java
  automl/beta/src/main/java/com/example/automl/CancelOperation.java
  automl/beta/src/main/java/com/example/automl/DeleteDataset.java
  automl/beta/src/main/java/com/example/automl/DeleteModel.java
  automl/beta/src/main/java/com/example/automl/DeployModel.java
  automl/beta/src/main/java/com/example/automl/GetModel.java
  automl/beta/src/main/java/com/example/automl/GetModelEvaluation.java
  automl/beta/src/main/java/com/example/automl/GetOperationStatus.java
  automl/beta/src/main/java/com/example/automl/ImportDataset.java
  automl/beta/src/main/java/com/example/automl/ListDatasets.java
  automl/beta/src/main/java/com/example/automl/ListModelEvaluations.java
  automl/beta/src/main/java/com/example/automl/ListModels.java
  automl/beta/src/main/java/com/example/automl/SetEndpoint.java
  automl/beta/src/main/java/com/example/automl/TablesBatchPredictBigQuery.java
  automl/beta/src/main/java/com/example/automl/TablesCreateDataset.java
  automl/beta/src/main/java/com/example/automl/TablesCreateModel.java
  automl/beta/src/main/java/com/example/automl/TablesImportDataset.java
  automl/beta/src/main/java/com/example/automl/TablesPredict.java
  automl/beta/src/main/java/com/example/automl/UndeployModel.java
  automl/beta/src/main/java/com/example/automl/VideoClassificationCreateDataset.java
  automl/beta/src/main/java/com/example/automl/VideoClassificationCreateModel.java
  automl/beta/src/main/java/com/example/automl/VideoObjectTrackingCreateDataset.java
  automl/beta/src/main/java/com/example/automl/VideoObjectTrackingCreateModel.java
  automl/beta/src/test/java/com/example/automl/BatchPredictTest.java
  automl/beta/src/test/java/com/example/automl/CancelOperationTest.java
  automl/beta/src/test/java/com/example/automl/DeleteDatasetTest.java
  automl/beta/src/test/java/com/example/automl/DeleteModelTest.java
  automl/beta/src/test/java/com/example/automl/DeployModelTest.java
  automl/beta/src/test/java/com/example/automl/GetModelEvaluationTest.java
  automl/beta/src/test/java/com/example/automl/GetModelTest.java
  automl/beta/src/test/java/com/example/automl/GetOperationStatusTest.java
  automl/beta/src/test/java/com/example/automl/ImportDatasetTest.java
  automl/beta/src/test/java/com/example/automl/ListDatasetsTest.java
  automl/beta/src/test/java/com/example/automl/ListModelEvaluationsTest.java
  automl/beta/src/test/java/com/example/automl/ListModelsTest.java
  automl/beta/src/test/java/com/example/automl/SetEndpointIT.java
  automl/beta/src/test/java/com/example/automl/TablesBatchPredictBigQueryTest.java
  automl/beta/src/test/java/com/example/automl/TablesCreateDatasetTest.java
  automl/beta/src/test/java/com/example/automl/TablesCreateModelTest.java
  automl/beta/src/test/java/com/example/automl/TablesImportDatasetTest.java
  automl/beta/src/test/java/com/example/automl/TablesPredictTest.java
  automl/beta/src/test/java/com/example/automl/UndeployModelTest.java
  automl/beta/src/test/java/com/example/automl/VideoClassificationCreateDatasetTest.java
  automl/beta/src/test/java/com/example/automl/VideoClassificationCreateModelTest.java
  automl/beta/src/test/java/com/example/automl/VideoObjectTrackingCreateDatasetTest.java
  automl/beta/src/test/java/com/example/automl/VideoObjectTrackingCreateModelTest.java
Labels: automerge, cla: yes

#3024 feat: revert "feat: remove automl beta samples"
  automl/beta/pom.xml
  automl/beta/src/main/java/com/example/automl/BatchPredict.java
  automl/beta/src/main/java/com/example/automl/CancelOperation.java
  automl/beta/src/main/java/com/example/automl/DeleteDataset.java
  automl/beta/src/main/java/com/example/automl/DeleteModel.java
  automl/beta/src/main/java/com/example/automl/DeployModel.java
  automl/beta/src/main/java/com/example/automl/GetModel.java
  automl/beta/src/main/java/com/example/automl/GetModelEvaluation.java
  automl/beta/src/main/java/com/example/automl/GetOperationStatus.java
  automl/beta/src/main/java/com/example/automl/ImportDataset.java
  automl/beta/src/main/java/com/example/automl/ListDatasets.java
  automl/beta/src/main/java/com/example/automl/ListModelEvaluations.java
  automl/beta/src/main/java/com/example/automl/ListModels.java
  automl/beta/src/main/java/com/example/automl/SetEndpoint.java
  automl/beta/src/main/java/com/example/automl/TablesBatchPredictBigQuery.java
  automl/beta/src/main/java/com/example/automl/TablesCreateDataset.java
  automl/beta/src/main/java/com/example/automl/TablesCreateModel.java
  automl/beta/src/main/java/com/example/automl/TablesImportDataset.java
  automl/beta/src/main/java/com/example/automl/TablesPredict.java
  automl/beta/src/main/java/com/example/automl/UndeployModel.java
  automl/beta/src/main/java/com/example/automl/VideoClassificationCreateDataset.java
  automl/beta/src/main/java/com/example/automl/VideoClassificationCreateModel.java
  automl/beta/src/main/java/com/example/automl/VideoObjectTrackingCreateDataset.java
  automl/beta/src/main/java/com/example/automl/VideoObjectTrackingCreateModel.java
  automl/beta/src/test/java/com/example/automl/BatchPredictTest.java
  automl/beta/src/test/java/com/example/automl/CancelOperationTest.java
  automl/beta/src/test/java/com/example/automl/DeleteDatasetTest.java
  automl/beta/src/test/java/com/example/automl/DeleteModelTest.java
  automl/beta/src/test/java/com/example/automl/DeployModelTest.java
  automl/beta/src/test/java/com/example/automl/GetModelEvaluationTest.java
  automl/beta/src/test/java/com/example/automl/GetModelTest.java
  automl/beta/src/test/java/com/example/automl/GetOperationStatusTest.java
  automl/beta/src/test/java/com/example/automl/ImportDatasetTest.java
  automl/beta/src/test/java/com/example/automl/ListDatasetsTest.java
  automl/beta/src/test/java/com/example/automl/ListModelEvaluationsTest.java
  automl/beta/src/test/java/com/example/automl/ListModelsTest.java
  automl/beta/src/test/java/com/example/automl/SetEndpointIT.java
  automl/beta/src/test/java/com/example/automl/TablesBatchPredictBigQueryTest.java
  automl/beta/src/test/java/com/example/automl/TablesCreateDatasetTest.java
  automl/beta/src/test/java/com/example/automl/TablesCreateModelTest.java
  automl/beta/src/test/java/com/example/automl/TablesImportDatasetTest.java
  automl/beta/src/test/java/com/example/automl/TablesPredictTest.java
  automl/beta/src/test/java/com/example/automl/UndeployModelTest.java
  automl/beta/src/test/java/com/example/automl/VideoClassificationCreateDatasetTest.java
  automl/beta/src/test/java/com/example/automl/VideoClassificationCreateModelTest.java
  automl/beta/src/test/java/com/example/automl/VideoObjectTrackingCreateDatasetTest.java
  automl/beta/src/test/java/com/example/automl/VideoObjectTrackingCreateModelTest.java
Labels: automerge, cla: yes

#3020 Create Java code sample for omit email address
  dlp/src/main/java/dlp/snippets/InspectStringWithExclusionDict.java
  dlp/src/test/java/dlp/snippets/InspectTests.java
Labels: cla: yes

#3041 healthcare API: add comment clarifying that deleted FHIR resources wi…
  healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceDelete.java
Labels: automerge, cla: yes

#3036 feat: add sample for createInstance
  spanner/cloud-client/src/main/java/com/example/spanner/CreateInstanceExample.java
  spanner/cloud-client/src/test/java/com/example/spanner/SpannerSampleIT.java
Labels: automerge, cla: yes

#3027 Create Java code sample for get jobs
  dlp/src/main/java/dlp/snippets/JobsCreate.java
  dlp/src/main/java/dlp/snippets/JobsGet.java
  dlp/src/test/java/dlp/snippets/JobsTests.java
Labels: cla: yes

#3046 deps: bump libraries-bom version
  automl/cloud-client/pom.xml
Labels: automerge, cla: yes

#3042 Include locations/global in parent field to fix samples
  dlp/src/main/java/dlp/snippets/DeIdentifyWithDateShift.java
  dlp/src/main/java/dlp/snippets/DeIdentifyWithFpe.java
  dlp/src/main/java/dlp/snippets/DeIdentifyWithMasking.java
  dlp/src/main/java/dlp/snippets/InspectBigQueryTable.java
  dlp/src/main/java/dlp/snippets/InspectDatastoreEntity.java
  dlp/src/main/java/dlp/snippets/InspectGcsFile.java
  dlp/src/main/java/dlp/snippets/InspectImageFile.java
  dlp/src/main/java/dlp/snippets/InspectPhoneNumber.java
  dlp/src/main/java/dlp/snippets/InspectString.java
  dlp/src/main/java/dlp/snippets/InspectStringWithExclusionDict.java
  dlp/src/main/java/dlp/snippets/InspectTextFile.java
  dlp/src/main/java/dlp/snippets/JobsCreate.java
  dlp/src/main/java/dlp/snippets/JobsList.java
  dlp/src/main/java/dlp/snippets/QuickStart.java
  dlp/src/main/java/dlp/snippets/ReIdentifyWithFpe.java
  dlp/src/main/java/dlp/snippets/RedactImageFile.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisCategoricalStats.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisKAnonymity.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisKMap.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisLDiversity.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisNumericalStats.java
  dlp/src/main/java/dlp/snippets/TemplatesCreate.java
  dlp/src/main/java/dlp/snippets/TemplatesList.java
  dlp/src/main/java/dlp/snippets/TriggersCreate.java
  dlp/src/main/java/dlp/snippets/TriggersList.java
  dlp/src/test/java/dlp/snippets/JobsTests.java
  dlp/src/test/java/dlp/snippets/TemplatesTests.java
  dlp/src/test/java/dlp/snippets/TriggersTests.java
Labels: automerge, cla: yes

#3047 Fix Firebase Console URL in README
  firestore/README.md
Labels: automerge, cla: yes

#3034 fix: include different ways to delete data in sample
  spanner/cloud-client/src/main/java/com/example/spanner/SpannerSample.java
Labels: cla: yes

#3050 create Java code sample for omit email with specific domain
  dlp/src/main/java/dlp/snippets/InspectStringWithExclusionRegex.java
  dlp/src/test/java/dlp/snippets/InspectTests.java
Labels: automerge, cla: yes

#3054 Create Java code sample for omit finding with substring
  dlp/src/main/java/dlp/snippets/InspectStringWithExclusionDictSubstring.java
  dlp/src/test/java/dlp/snippets/InspectTests.java
Labels: automerge, cla: yes

#3055 Create Java code sample for omit finding with substring using custom detector
  dlp/src/main/java/dlp/snippets/InspectStringCustomExcludingSubstring.java
  dlp/src/test/java/dlp/snippets/InspectTests.java
Labels: cla: yes

#3052 chore: add region tags for Spanner JDBC samples
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/BatchDmlExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateTableExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/InsertDataExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/SingleUseReadOnlyExample.java
Labels: api: spanner, automerge, cla: yes

#3049 Fix DLP inspect tests to fail on timeout
  dlp/src/test/java/dlp/snippets/InspectTests.java
Labels: cla: yes

#3061 fix Gandalf phone number - valid phone numbers cannot start with 1.
  dlp/README.md
Labels: cla: yes

#3060 Make DLP Java samples exception handling consistent
  dlp/src/main/java/dlp/snippets/InspectImageFile.java
  dlp/src/main/java/dlp/snippets/InspectPhoneNumber.java
  dlp/src/main/java/dlp/snippets/InspectString.java
  dlp/src/main/java/dlp/snippets/InspectStringCustomExcludingSubstring.java
  dlp/src/main/java/dlp/snippets/InspectStringWithExclusionDict.java
  dlp/src/main/java/dlp/snippets/InspectStringWithExclusionDictSubstring.java
  dlp/src/main/java/dlp/snippets/InspectStringWithExclusionRegex.java
  dlp/src/main/java/dlp/snippets/InspectTextFile.java
  dlp/src/main/java/dlp/snippets/RedactImageFile.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisCategoricalStats.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisKAnonymity.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisKMap.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisLDiversity.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisNumericalStats.java
  dlp/src/main/java/dlp/snippets/TriggersCreate.java
  dlp/src/main/java/dlp/snippets/TriggersDelete.java
  dlp/src/main/java/dlp/snippets/TriggersList.java
  dlp/src/test/java/dlp/snippets/InspectTests.java
  dlp/src/test/java/dlp/snippets/RedactTests.java
Labels: automerge, cla: yes

#3064 Create Java code sample for omit names that overlap with custom detector
  dlp/src/main/java/dlp/snippets/InspectStringCustomOmitOverlap.java
  dlp/src/test/java/dlp/snippets/InspectTests.java
Labels: automerge, cla: yes

#3065 Create Java code sample for omit names that are also an email
  dlp/src/main/java/dlp/snippets/InspectStringOmitOverlap.java
  dlp/src/test/java/dlp/snippets/InspectTests.java
Labels: cla: yes

#3066 Create Java code sample for omit domain names that are an email
  dlp/src/main/java/dlp/snippets/InspectStringWithoutOverlap.java
  dlp/src/test/java/dlp/snippets/InspectTests.java
Labels: automerge, cla: yes

#3068 Remove error prone from individual pom files.
  appengine-java8/iap/pom.xml
  compute/mailjet/pom.xml
  endpoints/getting-started/clients/pom.xml
  language/analysis/pom.xml
Labels: automerge, cla: yes

#3067 healthcare API: remove unused imports
  healthcare/v1/src/test/java/snippets/healthcare/FhirResourceTests.java
Labels: cla: yes

#3072 Add Java code sample for replacement
  dlp/src/main/java/dlp/snippets/DeIdentifyWithReplacement.java
  dlp/src/test/java/dlp/snippets/DeIdentificationTests.java
Labels: automerge, cla: yes

#3075 Add Java code samples for image redaction
  dlp/src/main/java/dlp/snippets/RedactImageFileAllInfoTypes.java
  dlp/src/main/java/dlp/snippets/RedactImageFileAllText.java
  dlp/src/main/java/dlp/snippets/RedactImageFileColoredInfoTypes.java
  dlp/src/main/java/dlp/snippets/RedactImageFileListedInfoTypes.java
  dlp/src/test/java/dlp/snippets/RedactTests.java
  dlp/src/test/resources/sensitive-data-image.jpg
Labels: cla: yes

#3076 Fix pubsub handling for DLP samples and tests
  dlp/src/main/java/dlp/snippets/InspectBigQueryTable.java
  dlp/src/main/java/dlp/snippets/InspectDatastoreEntity.java
  dlp/src/main/java/dlp/snippets/InspectGcsFile.java
  dlp/src/main/java/dlp/snippets/InspectStringOmitOverlap.java
  dlp/src/main/java/dlp/snippets/InspectStringWithoutOverlap.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisCategoricalStats.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisKAnonymity.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisKMap.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisLDiversity.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisNumericalStats.java
  dlp/src/test/java/dlp/snippets/InspectTests.java
  dlp/src/test/java/dlp/snippets/RiskAnalysisTests.java
Labels: automerge, cla: yes

#3077 Add separate lint and static anaylsis tests for presubmits.
  .kokoro/lint/common.cfg
  .kokoro/lint/presubmit.cfg
  .kokoro/static_analysis/common.cfg
  .kokoro/static_analysis/presubmit.cfg
  .kokoro/tests/run_lint.sh
  .kokoro/tests/run_static_analysis.sh
Labels: cla: yes

#3080 Inspect custom hotword b 156971569
  dlp/src/main/java/dlp/snippets/InspectStringCustomHotword.java
  dlp/src/test/java/dlp/snippets/InspectTests.java
Labels: automerge, cla: yes

#3062 Add Java code sample for table inspection
  dlp/src/main/java/dlp/snippets/InspectTable.java
  dlp/src/test/java/dlp/snippets/InspectTests.java
Labels: automerge, cla: yes

#3084 Fix lint / static analysis checks.
  .kokoro/tests/run_lint.sh
  .kokoro/tests/run_static_analysis.sh
Labels: cla: yes

#3086 Make lint/static checks quieter.
  .kokoro/tests/run_lint.sh
  .kokoro/tests/run_static_analysis.sh
Labels: cla: yes

#3045 Fix java quickstart
  firestore/src/main/java/com/example/firestore/Quickstart.java
  firestore/src/test/java/com/example/firestore/BaseIntegrationTest.java
Labels: cla: yes

#3088 Add Java code samples for image inspection
  dlp/src/main/java/dlp/snippets/InspectImageFileAllInfoTypes.java
  dlp/src/main/java/dlp/snippets/InspectImageFileListedInfoTypes.java
  dlp/src/test/java/dlp/snippets/InspectTests.java
Labels: cla: yes

#3092 Create Java code sample for wordList example
  dlp/src/main/java/dlp/snippets/DeIdentifyWithSimpleWordList.java
  dlp/src/test/java/dlp/snippets/DeIdentificationTests.java
Labels: cla: yes

#3083 chore: splitting sample into single files
  vision/cloud-client/src/main/java/com/example/vision/Detect.java
  vision/cloud-client/src/main/java/com/example/vision/snippets/DetectCropHints.java
  vision/cloud-client/src/main/java/com/example/vision/snippets/DetectCropHintsGcs.java
  vision/cloud-client/src/main/java/com/example/vision/snippets/DetectLandmarks.java
  vision/cloud-client/src/main/java/com/example/vision/snippets/DetectLandmarksGcs.java
  vision/cloud-client/src/main/java/com/example/vision/snippets/DetectLandmarksUrl.java
  vision/cloud-client/src/main/java/com/example/vision/snippets/DetectLogos.java
  vision/cloud-client/src/main/java/com/example/vision/snippets/DetectLogosGcs.java
  vision/cloud-client/src/main/java/com/example/vision/snippets/DetectProperties.java
  vision/cloud-client/src/main/java/com/example/vision/snippets/DetectPropertiesGcs.java
  vision/cloud-client/src/main/java/com/example/vision/snippets/DetectSafeSearch.java
  vision/cloud-client/src/main/java/com/example/vision/snippets/DetectSafeSearchGcs.java
  vision/cloud-client/src/main/java/com/example/vision/snippets/DetectText.java
  vision/cloud-client/src/main/java/com/example/vision/snippets/DetectTextGcs.java
  vision/cloud-client/src/main/java/com/example/vision/snippets/DetectWebDetections.java
  vision/cloud-client/src/main/java/com/example/vision/snippets/DetectWebDetectionsGcs.java
  vision/cloud-client/src/main/java/com/example/vision/snippets/DetectWebEntities.java
  vision/cloud-client/src/main/java/com/example/vision/snippets/DetectWebEntitiesGcs.java
  vision/cloud-client/src/main/java/com/example/vision/snippets/DetectWebEntitiesIncludeGeoResults.java
  vision/cloud-client/src/main/java/com/example/vision/snippets/DetectWebEntitiesIncludeGeoResultsGcs.java
  vision/cloud-client/src/test/java/com/example/vision/DetectCropHintsGcsTest.java
  vision/cloud-client/src/test/java/com/example/vision/DetectCropHintsTest.java
  vision/cloud-client/src/test/java/com/example/vision/DetectIT.java
  vision/cloud-client/src/test/java/com/example/vision/DetectLandmarksGcsTest.java
  vision/cloud-client/src/test/java/com/example/vision/DetectLandmarksTest.java
  vision/cloud-client/src/test/java/com/example/vision/DetectLogosGcsTest.java
  vision/cloud-client/src/test/java/com/example/vision/DetectLogosTest.java
  vision/cloud-client/src/test/java/com/example/vision/DetectPropertiesGcsTest.java
  vision/cloud-client/src/test/java/com/example/vision/DetectPropertiesTest.java
  vision/cloud-client/src/test/java/com/example/vision/DetectSafeSearchGcsTest.java
  vision/cloud-client/src/test/java/com/example/vision/DetectSafeSearchTest.java
  vision/cloud-client/src/test/java/com/example/vision/DetectTextGcsTest.java
  vision/cloud-client/src/test/java/com/example/vision/DetectTextTest.java
  vision/cloud-client/src/test/java/com/example/vision/DetectWebDetectionsGcsTest.java
  vision/cloud-client/src/test/java/com/example/vision/DetectWebDetectionsTest.java
  vision/cloud-client/src/test/java/com/example/vision/DetectWebEntitiesGcsTest.java
  vision/cloud-client/src/test/java/com/example/vision/DetectWebEntitiesIncludeGeoResultsGcsTest.java
  vision/cloud-client/src/test/java/com/example/vision/DetectWebEntitiesIncludeGeoResultsTest.java
  vision/cloud-client/src/test/java/com/example/vision/DetectWebEntitiesTest.java
Labels: api: vision, cla: yes, priority: p2, type: process

#3111 Create Java code sample for custom regex
  dlp/src/main/java/dlp/snippets/InspectWithCustomRegex.java
  dlp/src/test/java/dlp/snippets/InspectTests.java
Labels: automerge, cla: yes, kokoro:run

#3116 Add "compile" goal to static check
  .kokoro/tests/run_static_analysis.sh
  .kokoro/tests/run_tests.sh
Labels: cla: yes

#3093 healthcare API: remove message create from test_Hl7v2MessageList
  healthcare/v1/src/test/java/snippets/healthcare/Hl7v2MessageTests.java
Labels: cla: yes

#3133 Warn us about possible RepoBot failures
  iam/api-client/pom.xml
Labels: automerge, cla: yes

#3132 Formatting consistency pass for DLP Inspect* samples
  dlp/src/main/java/dlp/snippets/InspectBigQueryTable.java
  dlp/src/main/java/dlp/snippets/InspectDatastoreEntity.java
  dlp/src/main/java/dlp/snippets/InspectGcsFile.java
  dlp/src/main/java/dlp/snippets/InspectImageFile.java
  dlp/src/main/java/dlp/snippets/InspectImageFileListedInfoTypes.java
  dlp/src/main/java/dlp/snippets/InspectString.java
  dlp/src/main/java/dlp/snippets/InspectStringCustomExcludingSubstring.java
  dlp/src/main/java/dlp/snippets/InspectStringCustomHotword.java
  dlp/src/main/java/dlp/snippets/InspectStringCustomOmitOverlap.java
  dlp/src/main/java/dlp/snippets/InspectStringMultipleRules.java
  dlp/src/main/java/dlp/snippets/InspectStringOmitOverlap.java
  dlp/src/main/java/dlp/snippets/InspectStringWithExclusionDict.java
  dlp/src/main/java/dlp/snippets/InspectStringWithExclusionDictSubstring.java
  dlp/src/main/java/dlp/snippets/InspectStringWithExclusionRegex.java
  dlp/src/main/java/dlp/snippets/InspectStringWithoutOverlap.java
  dlp/src/main/java/dlp/snippets/InspectTextFile.java
  dlp/src/main/java/dlp/snippets/InspectWithCustomRegex.java
Labels: automerge, cla: yes

#3118 Add Java code samples for fpe
  dlp/src/main/java/dlp/snippets/DeIdentifyTableWithFpe.java
  dlp/src/main/java/dlp/snippets/DeIdentifyTextWithFpe.java
  dlp/src/main/java/dlp/snippets/ReIdentifyTableWithFpe.java
  dlp/src/main/java/dlp/snippets/ReIdentifyTextWithFpe.java
  dlp/src/test/java/dlp/snippets/DeIdentificationTests.java
Labels: cla: yes

#3145 Create Java code sample for custom infotype likelihood
  dlp/src/main/java/dlp/snippets/InspectWithHotwordRules.java
  dlp/src/test/java/dlp/snippets/InspectTests.java
Labels: cla: yes

#2844 automl: remove vision samples no longer on cgc
  vision/automl/src/main/java/com/google/cloud/vision/samples/automl/DatasetApi.java
  vision/automl/src/main/java/com/google/cloud/vision/samples/automl/ModelApi.java
  vision/automl/src/test/java/com/google/cloud/vision/samples/automl/DatasetApiIT.java
  vision/automl/src/test/java/com/google/cloud/vision/samples/automl/ModelApiIT.java
Labels: automerge, cla: yes

#3150 fix-it(Cloud Monitoring Api): Change the quick start documentation.
  monitoring/cloud-client/src/main/java/com/example/monitoring/QuickstartSample.java
Labels: automerge, cla: yes

#3157 Fixes product names and a link reference
  appengine-java8/bigquery/README.md
Labels: cla: yes

#3155 Add Java code samples for replacement with infotype
  dlp/src/main/java/dlp/snippets/DeIdentifyWithInfoType.java
  dlp/src/test/java/dlp/snippets/DeIdentificationTests.java
Labels: cla: yes

#3167 dlp: Update README instructions to remove uberjar info
  dlp/README.md
  dlp/pom.xml
  dlp/src/main/java/dlp/snippets/DeIdentifyTableWithFpe.java
  dlp/src/main/java/dlp/snippets/DeIdentifyTextWithFpe.java
  dlp/src/main/java/dlp/snippets/DeIdentifyWithDateShift.java
  dlp/src/main/java/dlp/snippets/DeIdentifyWithExceptionList.java
  dlp/src/main/java/dlp/snippets/DeIdentifyWithFpe.java
  dlp/src/main/java/dlp/snippets/DeIdentifyWithInfoType.java
  dlp/src/main/java/dlp/snippets/DeIdentifyWithMasking.java
  dlp/src/main/java/dlp/snippets/DeIdentifyWithRedaction.java
  dlp/src/main/java/dlp/snippets/DeIdentifyWithReplacement.java
  dlp/src/main/java/dlp/snippets/DeIdentifyWithSimpleWordList.java
  dlp/src/main/java/dlp/snippets/InspectBigQueryTable.java
  dlp/src/main/java/dlp/snippets/InspectBigQueryTableWithSampling.java
  dlp/src/main/java/dlp/snippets/InspectDatastoreEntity.java
  dlp/src/main/java/dlp/snippets/InspectGcsFile.java
  dlp/src/main/java/dlp/snippets/InspectGcsFileWithSampling.java
  dlp/src/main/java/dlp/snippets/InspectImageFile.java
  dlp/src/main/java/dlp/snippets/InspectPhoneNumber.java
  dlp/src/main/java/dlp/snippets/InspectString.java
  dlp/src/main/java/dlp/snippets/InspectStringCustomExcludingSubstring.java
  dlp/src/main/java/dlp/snippets/InspectStringCustomHotword.java
  dlp/src/main/java/dlp/snippets/InspectStringCustomOmitOverlap.java
  dlp/src/main/java/dlp/snippets/InspectStringMultipleRules.java
  dlp/src/main/java/dlp/snippets/InspectStringOmitOverlap.java
  dlp/src/main/java/dlp/snippets/InspectStringWithExclusionDict.java
  dlp/src/main/java/dlp/snippets/InspectStringWithExclusionDictSubstring.java
  dlp/src/main/java/dlp/snippets/InspectStringWithExclusionRegex.java
  dlp/src/main/java/dlp/snippets/InspectStringWithoutOverlap.java
  dlp/src/main/java/dlp/snippets/InspectTable.java
  dlp/src/main/java/dlp/snippets/InspectTextFile.java
  dlp/src/main/java/dlp/snippets/InspectWithCustomRegex.java
  dlp/src/main/java/dlp/snippets/InspectWithHotwordRules.java
  dlp/src/main/java/dlp/snippets/JobsCreate.java
  dlp/src/main/java/dlp/snippets/JobsDelete.java
  dlp/src/main/java/dlp/snippets/JobsGet.java
  dlp/src/main/java/dlp/snippets/JobsList.java
  dlp/src/main/java/dlp/snippets/ReIdentifyTableWithFpe.java
  dlp/src/main/java/dlp/snippets/ReIdentifyTextWithFpe.java
  dlp/src/main/java/dlp/snippets/ReIdentifyWithFpe.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisCategoricalStats.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisKAnonymity.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisKMap.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisLDiversity.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisNumericalStats.java
  dlp/src/main/java/dlp/snippets/TemplatesCreate.java
  dlp/src/main/java/dlp/snippets/TemplatesDelete.java
  dlp/src/main/java/dlp/snippets/TemplatesList.java
  dlp/src/main/java/dlp/snippets/TriggersCreate.java
  dlp/src/main/java/dlp/snippets/TriggersDelete.java
  dlp/src/main/java/dlp/snippets/TriggersList.java
Labels: automerge, cla: yes

#3166 Clean up some ProjectName uses in DLP
  dlp/src/main/java/dlp/snippets/DeIdentifyWithExceptionList.java
  dlp/src/main/java/dlp/snippets/DeIdentifyWithSimpleWordList.java
  dlp/src/main/java/dlp/snippets/InspectWithCustomRegex.java
  dlp/src/main/java/dlp/snippets/InspectWithHotwordRules.java
Labels: automerge, cla: yes

#3170 Add Java code samples for de-id tabular data
  dlp/src/main/java/dlp/snippets/DeIdentifyTableBucketing.java
  dlp/src/main/java/dlp/snippets/DeIdentifyTableConditionInfoTypes.java
  dlp/src/main/java/dlp/snippets/DeIdentifyTableConditionMasking.java
  dlp/src/main/java/dlp/snippets/DeIdentifyTableInfoTypes.java
  dlp/src/main/java/dlp/snippets/DeIdentifyTableRowSuppress.java
  dlp/src/test/java/dlp/snippets/DeIdentificationTests.java
Labels: cla: yes

#3173 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: automerge, cla: yes

#3175 Clarify infinite retries sample
  functions/concepts/retry-timeout/src/main/java/functions/RetryTimeout.java
Labels: cla: yes

#3177 Pub/Sub: clean up migrated samples and update readme
  pubsub/cloud-client/README.md
  pubsub/cloud-client/pom.xml
  pubsub/cloud-client/src/main/java/com/example/pubsub/CreatePullSubscriptionExample.java
  pubsub/cloud-client/src/main/java/com/example/pubsub/CreateTopicExample.java
  pubsub/cloud-client/src/main/java/com/example/pubsub/PublisherExample.java
  pubsub/cloud-client/src/main/java/com/example/pubsub/SubscriberExample.java
  pubsub/cloud-client/src/test/java/com/example/pubsub/QuickStartIT.java
Labels: cla: yes

#3190 Make pubsub handling consistent across inspect and risk DLP samples
  dlp/src/main/java/dlp/snippets/InspectBigQueryTable.java
  dlp/src/main/java/dlp/snippets/InspectBigQueryTableWithSampling.java
  dlp/src/main/java/dlp/snippets/InspectDatastoreEntity.java
  dlp/src/main/java/dlp/snippets/InspectGcsFile.java
  dlp/src/main/java/dlp/snippets/InspectGcsFileWithSampling.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisCategoricalStats.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisKAnonymity.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisKMap.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisLDiversity.java
  dlp/src/main/java/dlp/snippets/RiskAnalysisNumericalStats.java
Labels: automerge, cla: yes

#3192 Update lint check to use Java 11 image.
  .kokoro/lint/common.cfg
Labels: automerge, cla: yes

#3193 Update GCF samples to Java 11 standards
  functions/concepts/retry-pubsub/src/test/java/functions/RetryPubSubTest.java
  functions/concepts/retry-timeout/src/test/java/functions/RetryTimeoutTest.java
  functions/firebase/auth/src/test/java/functions/FirebaseAuthTest.java
  functions/firebase/firestore-reactive/src/main/java/functions/FirebaseFirestoreReactive.java
  functions/firebase/firestore-reactive/src/test/java/functions/FirebaseFirestoreReactiveTest.java
  functions/firebase/firestore/src/test/java/functions/FirebaseFirestoreTest.java
  functions/firebase/remote-config/src/test/java/functions/FirebaseRemoteConfigTest.java
  functions/firebase/rtdb/src/test/java/functions/FirebaseRtdbTest.java
  functions/helloworld/hello-http/src/test/java/functions/HelloHttpTest.java
  functions/http/parse-content-type/src/test/java/functions/ParseContentTypeTest.java
  functions/imagemagick/src/main/java/functions/ImageMagick.java
  functions/logging/stackdriver-logging/src/test/java/functions/StackdriverLoggingTest.java
  functions/slack/src/test/java/functions/SlackSlashCommandTest.java
Labels: automerge, cla: yes

#3198 Clean up DLP tests
  dlp/pom.xml
  dlp/src/test/java/dlp/snippets/DeIdentificationTests.java
  dlp/src/test/java/dlp/snippets/InfoTypesTests.java
  dlp/src/test/java/dlp/snippets/InspectTests.java
  dlp/src/test/java/dlp/snippets/JobsTests.java
  dlp/src/test/java/dlp/snippets/QuickstartTests.java
  dlp/src/test/java/dlp/snippets/RedactTests.java
  dlp/src/test/java/dlp/snippets/RiskAnalysisTests.java
  dlp/src/test/java/dlp/snippets/TemplatesTests.java
  dlp/src/test/java/dlp/snippets/TestBase.java
  dlp/src/test/java/dlp/snippets/TriggersTests.java
Labels: automerge, cla: yes

#3203 update to BOM 7
  appengine-java11/guestbook-cloud-firestore/pom.xml
Labels: cla: yes

#3186 Remove PowerMock from the Slack GCF sample.
  functions/slack/pom.xml
  functions/slack/src/main/java/functions/SlackSlashCommand.java
  functions/slack/src/test/java/functions/SlackSlashCommandTest.java
Labels: cla: yes

#3148 [bigtable] Update region tags for reads and filters
  bigtable/beam/helloworld/pom.xml
  bigtable/beam/keyviz-art/pom.xml
  bigtable/beam/keyviz-art/src/test/java/KeyVizArtTest.java
  bigtable/cassandra-migration-codelab/pom.xml
  bigtable/cassandra-migration-codelab/src/main/java/CassandraMigrationCodelab.java
  bigtable/cassandra-migration-codelab/src/test/java/CassandraMigrationCodelabTest.java
  bigtable/hbase/snippets/pom.xml
  bigtable/hbase/snippets/src/main/java/com/example/bigtable/Filters.java
  bigtable/hbase/snippets/src/main/java/com/example/bigtable/Reads.java
  bigtable/hbase/snippets/src/main/java/com/example/bigtable/WriteBatch.java
  bigtable/hbase/snippets/src/main/java/com/example/bigtable/WriteConditionally.java
  bigtable/hbase/snippets/src/main/java/com/example/bigtable/WriteIncrement.java
  bigtable/hbase/snippets/src/main/java/com/example/bigtable/WriteSimple.java
  bigtable/snippets/pom.xml
  bigtable/snippets/src/main/java/com/example/bigtable/Filters.java
  bigtable/snippets/src/main/java/com/example/bigtable/Reads.java
  bigtable/snippets/src/test/java/com/example/bigtable/FiltersTest.java
  bigtable/snippets/src/test/java/com/example/bigtable/ReadsTest.java
  bigtable/snippets/src/test/java/com/example/bigtable/WritesTest.java
Labels: cla: yes

#2879 docs: Update Security Command Center UpdateNotificationConfig sample, adding filter to mutable field.
  securitycenter/src/main/java/com/google/cloud/examples/securitycenter/snippets/UpdateNotificationConfigSnippets.java
Labels: cla: yes

#3208 samples: added UUID to prevent concurreny errors
  jobs/v4/src/test/java/JobSearchCreateCompanyTest.java
  jobs/v4/src/test/java/JobSearchCreateTenantTest.java
  jobs/v4/src/test/java/JobSearchDeleteCompanyTest.java
  jobs/v4/src/test/java/JobSearchDeleteTenantTest.java
Labels: cla: yes

#3199 Migrate errorreporting samples to https://github.com/googlepais/java-errorreporting
  errorreporting/README.md
  errorreporting/pom.xml
  errorreporting/src/main/java/com/example/errorreporting/QuickStart.java
  errorreporting/src/test/java/com/example/errorreporting/QuickStartIT.java
Labels: cla: yes, do not merge

#3221 Update README.md
  dlp/README.md
Labels: automerge, cla: yes

#3238 fix region tag
  bigtable/snippets/src/main/java/com/example/bigtable/Reads.java
Labels: automerge, cla: yes

#3239 chore(iap): cleanup spotbugs warnings
  iap/src/main/java/com/example/iap/BuildIapRequest.java
  iap/src/test/java/com/example/iap/BuildAndVerifyIapRequestIT.java
Labels: cla: yes

#2986 refactor: use new verify token functionality from google-auth-library
  iap/pom.xml
  iap/src/main/java/com/example/iap/VerifyIapRequestHeader.java
Labels: cla: yes

#3252 feat(deps): add protobuf-java-util as a direct dep of kms
  kms/pom.xml
Labels: cla: yes

#3255 feat(deps): add protobuf-java-util as a direct dep of secretmanager
  secretmanager/pom.xml
Labels: cla: yes

#3258 feat(deps): add protobuf-java-util as a direct dep of securitycenter
  securitycenter/pom.xml
Labels: cla: yes

#3256 Add Cloud Run Events Samples
  run/README.md
  run/events-pubsub/README.md
  run/events-pubsub/pom.xml
  run/events-pubsub/src/main/java/com/example/cloudrun/Application.java
  run/events-pubsub/src/main/java/com/example/cloudrun/EventController.java
  run/events-pubsub/src/main/java/com/example/cloudrun/eventpojos/PubSubBody.java
  run/events-pubsub/src/test/java/com/example/cloudrun/EventControllerTests.java
  run/events-storage/README.md
  run/events-storage/pom.xml
  run/events-storage/src/main/java/com/example/cloudrun/Application.java
  run/events-storage/src/main/java/com/example/cloudrun/EventController.java
  run/events-storage/src/main/java/com/example/cloudrun/eventpojos/PubSubBody.java
  run/events-storage/src/test/java/com/example/cloudrun/EventControllerTests.java
Labels: automerge, cla: yes

#3259 healthcare API: simplify response for HL7v2MessageList
  healthcare/v1/src/main/java/snippets/healthcare/hl7v2/messages/HL7v2MessageList.java
Labels: automerge, cla: yes

#3262 feat: adding hadoopfs and autoscaling samples
  dataproc/src/main/java/CreateClusterWithAutoscaling.java
  dataproc/src/main/java/SubmitHadoopFsJob.java
  dataproc/src/test/java/CreateClusterWithAutoscalingTest.java
  dataproc/src/test/java/InstantiateInlineWorkflowTemplateTest.java
  dataproc/src/test/java/SubmitHadoopFsJobTest.java
Labels: automerge, cla: yes

#3257 Fix dependency in Cloud Run Readme
  run/pubsub/README.md
Labels: cla: yes

#3266 samples:added docs links to predict samples
  automl/cloud-client/src/main/java/com/example/automl/LanguageEntityExtractionPredict.java
  automl/cloud-client/src/main/java/com/example/automl/LanguageSentimentAnalysisPredict.java
  automl/cloud-client/src/main/java/com/example/automl/LanguageTextClassificationPredict.java
Labels: automerge, cla: yes

#3269 healthcare API: add comment clarifying FHIR update resource
  healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourcePatch.java
Labels: cla: yes

#3284 Add a paragraph on specific exceptions.
  SAMPLE_FORMAT.md
Labels: cla: yes

#3283 samples: refactor dialogflow for 2.1.0
  dialogflow/cloud-client/pom.xml
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentAudio.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentKnowledge.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentStream.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentTexts.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentWithSentimentAnalysis.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentWithTextToSpeechResponse.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DocumentManagement.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/IntentManagement.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/KnowledgeBaseManagement.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/CreateDocumentTest.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/CreateKnowledgeBaseTest.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/DetectIntentKnowledgeTest.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/DetectIntentStreamIT.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/DetectIntentWithAudioTest.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/DetectIntentWithSentimentAndTextToSpeechIT.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/IntentManagementIT.java
Labels: cla: yes
