Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2020-05, with the labels that each got.

#2825 speech: make flaky tests generic
  speech/cloud-client/src/test/java/com/example/speech/RecognizeIT.java
Labels: cla: yes

#2827 Update blunderbuss.yml
  .github/blunderbuss.yml
Labels: automerge, cla: yes

#2828 healthcare API: add DATASET_NAME variable to DatasetPatch.java
  healthcare/v1/src/main/java/snippets/healthcare/datasets/DatasetPatch.java
Labels: cla: yes

#2816 README typo
  bigtable/beam/keyviz-art/README.md
Labels: automerge, cla: yes

#2848 Adding SoDa teams
  .github/CODEOWNERS
Labels: cla: yes

#2847 deps: upgrade beam version to 2.20.0 in bigtable and dataflow samples
  bigtable/beam/keyviz-art/pom.xml
  dataflow/spanner-io/pom.xml
Labels: cla: yes

#2845 functions: shrink example pom sample
  functions/firebase/firestore/pom.xml
  functions/helloworld/helloworld/pom.xml
Labels: cla: yes

#2846 functions: shrink Kotlin example POM
  functions/helloworld/kotlin-helloworld/pom.xml
Labels: cla: yes

#2849 Update CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes

#2853 Remove PowerMock from nearly all samples, in favour of plain Mockito.
  functions/concepts/env-vars/pom.xml
  functions/concepts/env-vars/src/test/java/functions/EnvVarsTest.java
  functions/concepts/execution-count/pom.xml
  functions/concepts/execution-count/src/test/java/functions/ExecutionCountTest.java
  functions/concepts/file-system/pom.xml
  functions/concepts/file-system/src/test/java/functions/FileSystemTest.java
  functions/concepts/lazy-fields/pom.xml
  functions/concepts/lazy-fields/src/test/java/functions/LazyFieldsTest.java
  functions/concepts/retry-pubsub/pom.xml
  functions/concepts/retry-pubsub/src/test/java/functions/RetryPubSubTest.java
  functions/concepts/retry-timeout/pom.xml
  functions/concepts/retry-timeout/src/test/java/functions/RetryTimeoutTest.java
  functions/concepts/scopes/pom.xml
  functions/concepts/scopes/src/test/java/functions/ScopesTest.java
  functions/firebase/firestore-reactive/pom.xml
  functions/firebase/firestore-reactive/src/main/java/functions/FirebaseFirestoreReactive.java
  functions/firebase/firestore-reactive/src/test/java/functions/FirebaseFirestoreReactiveTest.java
  functions/helloworld/groovy-helloworld/pom.xml
  functions/helloworld/groovy-helloworld/src/test/java/functions/GroovyHelloWorldTest.java
  functions/helloworld/hello-http/pom.xml
  functions/helloworld/hello-http/src/test/java/functions/ExampleSystemTest.java
  functions/helloworld/hello-http/src/test/java/functions/HelloHttpTest.java
  functions/helloworld/hello-pubsub/pom.xml
  functions/helloworld/hello-pubsub/src/test/java/functions/HelloPubSubTest.java
  functions/helloworld/helloworld/pom.xml
  functions/helloworld/helloworld/src/test/java/functions/HelloWorldTest.java
  functions/helloworld/kotlin-helloworld/pom.xml
  functions/helloworld/kotlin-helloworld/src/test/java/functions/KotlinHelloWorldTest.java
  functions/helloworld/scala-hello-pubsub/pom.xml
  functions/helloworld/scala-helloworld/pom.xml
  functions/helloworld/scala-helloworld/src/test/java/functions/ScalaHelloWorldTest.java
  functions/http/bearer-token-http/pom.xml
  functions/http/cors-enabled-auth/pom.xml
  functions/http/cors-enabled-auth/src/test/java/functions/CorsEnabledAuthTest.java
  functions/http/cors-enabled/pom.xml
  functions/http/cors-enabled/src/test/java/functions/CorsEnabledTest.java
  functions/http/http-form-data/pom.xml
  functions/http/http-form-data/src/test/java/functions/HttpFormDataTest.java
  functions/http/http-method/pom.xml
  functions/http/http-method/src/test/java/functions/HttpMethodTest.java
  functions/http/parse-content-type/pom.xml
  functions/http/parse-content-type/src/test/java/functions/ParseContentTypeTest.java
  functions/http/send-http-request/pom.xml
  functions/http/send-http-request/src/test/java/functions/SendHttpRequestTest.java
  functions/logging/log-helloworld/pom.xml
  functions/logging/retrieve-logs/pom.xml
  functions/logging/retrieve-logs/src/test/java/functions/RetrieveLogsTest.java
  functions/ocr/ocr-process-image/pom.xml
  functions/ocr/ocr-save-result/pom.xml
  functions/ocr/ocr-translate-text/pom.xml
  functions/ocr/ocr-translate-text/src/test/java/functions/OcrTranslateTextTest.java
  functions/pubsub/publish-message/pom.xml
  functions/pubsub/publish-message/src/test/java/functions/PublishMessageTest.java
  functions/spanner/pom.xml
Labels: cla: yes

#2852 Clear current registry between tests.
  iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java
Labels: cla: yes

#2851 functions: remove extra pom.xml line
  functions/helloworld/helloworld/pom.xml
Labels: cla: yes

#2855 healthcare API: add missing variables, fix incorrect var in fhir/
  healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomStorePatch.java
  healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomWebRetrieveRendered.java
  healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomWebSearchForInstances.java
  healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomWebSearchStudies.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStorePatch.java
Labels: cla: yes

#2856 healthcare API: use dataset path instead of FHIR store path when list…
  healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStoreList.java
Labels: cla: yes

#2864 Clarify comment in scopes sample
  functions/concepts/scopes/src/main/java/functions/Scopes.java
Labels: automerge, cla: yes

#2859 healthcare API: fix FHIR store metadata FHIR_NAME pattern, move file …
  healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStoreGetMetadata.java
  healthcare/v1/src/test/java/snippets/healthcare/FhirResourceTests.java
  healthcare/v1/src/test/java/snippets/healthcare/FhirStoreTests.java
Labels: cla: yes

#2857 healthcare API: fix path for FhirResourceGetHistory and make output d…
  healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceGetHistory.java
  healthcare/v1/src/test/java/snippets/healthcare/FhirResourceTests.java
Labels: cla: yes

#2829 [IAM] Update quickstart samples
  iam/api-client/src/main/java/iam/snippets/AddBinding.java
  iam/api-client/src/main/java/iam/snippets/AddMember.java
  iam/api-client/src/main/java/iam/snippets/CreateServiceAccount.java
  iam/api-client/src/main/java/iam/snippets/CreateServiceAccountKey.java
  iam/api-client/src/main/java/iam/snippets/DeleteServiceAccount.java
  iam/api-client/src/main/java/iam/snippets/DeleteServiceAccountKey.java
  iam/api-client/src/main/java/iam/snippets/DisableServiceAccount.java
  iam/api-client/src/main/java/iam/snippets/EnableServiceAccount.java
  iam/api-client/src/main/java/iam/snippets/GetPolicy.java
  iam/api-client/src/main/java/iam/snippets/GrantableRoles.java
  iam/api-client/src/main/java/iam/snippets/ListServiceAccountKeys.java
  iam/api-client/src/main/java/iam/snippets/ListServiceAccounts.java
  iam/api-client/src/main/java/iam/snippets/Quickstart.java
  iam/api-client/src/main/java/iam/snippets/QuickstartV2.java
  iam/api-client/src/main/java/iam/snippets/RemoveMember.java
  iam/api-client/src/main/java/iam/snippets/RenameServiceAccount.java
  iam/api-client/src/main/java/iam/snippets/SetPolicy.java
  iam/api-client/src/main/java/iam/snippets/TestPermissions.java
  iam/api-client/src/test/java/iam/snippets/AccessTests.java
  iam/api-client/src/test/java/iam/snippets/GrantableRolesIT.java
  iam/api-client/src/test/java/iam/snippets/QuickstartIT.java
  iam/api-client/src/test/java/iam/snippets/QuickstartV2Tests.java
  iam/api-client/src/test/java/iam/snippets/ServiceAccountTests.java
Labels: cla: yes

#2871 [functions/scopes]: use CONSTANT_CASE for variable
  functions/concepts/scopes/src/main/java/functions/Scopes.java
Labels: automerge, cla: yes

#2870 healthcare API: change how HL7v2MessageList processes results, fix er…
  healthcare/v1/src/main/java/snippets/healthcare/datasets/DatasetSetIamPolicy.java
  healthcare/v1/src/main/java/snippets/healthcare/hl7v2/Hl7v2StoreGetIamPolicy.java
  healthcare/v1/src/main/java/snippets/healthcare/hl7v2/messages/HL7v2MessageGet.java
  healthcare/v1/src/main/java/snippets/healthcare/hl7v2/messages/HL7v2MessageList.java
Labels: cla: yes

#2872 samples: fix test
  video/beta/src/main/java/com/example/video/StreamingAutoMlClassification.java
  video/beta/src/test/java/com/example/video/StreamingAutoMlClassificationIT.java
Labels: cla: yes

#2875 healthcare API: fix DICOM_NAME variable
  healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomStoreGetIamPolicy.java
Labels: cla: yes

#2876 healthcare API: add resource types to remaining FHIR resource code
  healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceDelete.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceDeletePurge.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceGet.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceGetPatientEverything.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceListHistory.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourcePatch.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceSearchGet.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceSearchPost.java
  healthcare/v1/src/test/java/snippets/healthcare/FhirResourceTests.java
Labels: cla: yes

#2877 healthcare API: fix input data for ExecuteBundle, fix path name
  healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStoreExecuteBundle.java
Labels: cla: yes, kokoro:run

#2880 feat: add snipped for firestore.query.limittolast()
  firestore/pom.xml
  firestore/src/main/java/com/example/firestore/snippets/QueryDataSnippets.java
  firestore/src/test/java/com/example/firestore/snippets/QueryDataSnippetsIT.java
Labels: cla: yes

#2882 functions: Java log severity is NOT broken :)
  functions/logging/log-helloworld/src/main/java/functions/LogHelloWorld.java
Labels: cla: yes

#2883 GCF example POM: fix mismatched region tag + add new one
  functions/helloworld/helloworld/pom.xml
Labels: cla: yes

#2887 feat(datacatalog): update quickstart to V1
  datacatalog/quickstart/src/main/java/com/example/datacatalog/CreateFilesetEntry.java
  datacatalog/quickstart/src/test/java/com/example/datacatalog/CreateFilesetEntryTests.java
Labels: api: datacatalog, automerge, cla: yes

#2888 Update SAMPLE_FORMAT to use main.
  SAMPLE_FORMAT.md
Labels: cla: yes

#2889 Let's ask folks to follow our guidelines.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: automerge, cla: yes

#2884 fix: firestore projectId is hardcoded in the tests
  .kokoro/tests/run_tests.sh
  firestore/README.md
  firestore/src/test/java/com/example/firestore/BaseIntegrationTest.java
Labels: automerge, cla: yes

#2936 Update build timeouts.
  .kokoro/java11/common.cfg
  .kokoro/java8/common.cfg
Labels: automerge, cla: yes

#2924 Region tag fixes for b/156959476
  functions/helloworld/helloworld/pom.xml
  functions/helloworld/helloworld/src/main/java/functions/HelloWorld.java
Labels: automerge, cla: yes

#2946 Functions: clarify cloudbuild.yaml
  functions/ci_cd/cloudbuild.yaml
Labels: cla: yes

#2953 Make the example a bit more Groovy idiomatic
  functions/helloworld/groovy-hello-pubsub/src/main/groovy/functions/GroovyHelloPubSub.groovy
Labels: cla: yes

#2973 Change video test to not depend on specific inference
  video/cloud-client/src/test/java/com/example/video/QuickstartIT.java
Labels: cla: yes

#2984 Update ExampleSystemTest.java
  functions/helloworld/hello-http/src/test/java/functions/ExampleSystemTest.java
Labels: automerge, cla: yes

#2977 fix: talent solution v4 samples tests
  jobs/v4/pom.xml
  jobs/v4/src/main/java/com/example/jobs/CommuteSearchJobs.java
  jobs/v4/src/main/java/com/example/jobs/CustomRankingSearchJobs.java
  jobs/v4/src/main/java/com/example/jobs/HistogramSearchJobs.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchAutoCompleteJobTitle.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchCreateClientEvent.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchCreateCompany.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchCreateJob.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchCreateJobCustomAttributes.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchCreateTenant.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchDeleteCompany.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchDeleteJob.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchDeleteTenant.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchGetCompany.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchGetJob.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchGetTenant.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchListCompanies.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchListJobs.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchListTenants.java
Labels: cla: yes

#2989 Update READMEs with source deploy functionality
  appengine-java11/README.md
  appengine-java11/http-server/README.md
  appengine-java11/kotlin-ktor/README.md
  appengine-java11/micronaut-helloworld/README.md
  appengine-java11/quarkus-helloworld/README.md
  appengine-java11/sparkjava-helloworld/README.md
  appengine-java11/springboot-helloworld/README.md
  appengine-java11/tasks/README.md
  appengine-java11/vertx-helloworld/README.md
Labels: cla: yes

#2992 chore(deps): upgrade bigtable dep to 1.13.0 and reorganize dependencies
  bigtable/cassandra-migration-codelab/pom.xml
  bigtable/hbase/snippets/pom.xml
  bigtable/pom.xml
  bigtable/snippets/pom.xml
Labels: automerge, cla: yes
