Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2020-08, with the labels that each got.

#3445 docs: add sample for setting timeout and retry settings
  spanner/cloud-client/src/main/java/com/example/spanner/CustomTimeoutAndRetrySettingsExample.java
  spanner/cloud-client/src/test/java/com/example/spanner/SpannerStandaloneExamplesIT.java
Labels: cla: yes

#3460 Setting a default empty string for the function target when unused
  functions/helloworld/helloworld-gradle/build.gradle
Labels: cla: yes

#3463 Function - Helloworld Gradle needs the Gradle wrapper jar
  functions/helloworld/helloworld-gradle/.gitignore
  functions/helloworld/helloworld-gradle/gradle/wrapper/gradle-wrapper.jar
Labels: cla: yes

#3466 Cloud Run hello world - region tags
  run/helloworld/.dockerignore
  run/helloworld/Dockerfile
  run/helloworld/pom.xml
  run/helloworld/src/main/java/com/example/helloworld/HelloworldApplication.java
  run/helloworld/src/main/resources/application.properties
  run/helloworld/src/test/java/com/example/helloworld/HelloworldApplicationTests.java
Labels: cla: yes

#3461 chore: migrate datastore samples to java-datastore repo
  datastore/README.md
  datastore/cloud-client/README.md
  datastore/cloud-client/pom.xml
  datastore/cloud-client/src/main/java/com/example/datastore/QuickstartSample.java
  datastore/cloud-client/src/test/java/com/example/datastore/QuickstartSampleIT.java
  datastore/pom.xml
  datastore/src/main/java/com/google/datastore/snippets/TaskList.java
  datastore/src/test/java/com/google/datastore/snippets/ConceptsTest.java
Labels: cla: yes

#3480 samples: Pub/Sub Spring
  pubsub/spring/README.md
  pubsub/spring/pom.xml
  pubsub/spring/src/main/java/demo/PubSubApplication.java
  pubsub/spring/src/main/resources/application.properties
Labels: cla: yes

#3500 samples: fixed flaky test of logging
  logging/cloud-client/src/test/java/com/example/logging/LoggingIT.java
Labels: cla: yes

#3512 dataflow: removed negative lookahead
  dataflow/flex-templates/streaming_beam_sql/metadata.json
Labels: cla: yes

#3498 chore: migrate firestore samples to java-firestore repo
  firestore/README.md
  firestore/pom.xml
  firestore/src/main/java/com/example/firestore/Quickstart.java
  firestore/src/main/java/com/example/firestore/snippets/ListenDataSnippets.java
  firestore/src/main/java/com/example/firestore/snippets/ManageDataSnippets.java
  firestore/src/main/java/com/example/firestore/snippets/QueryDataSnippets.java
  firestore/src/main/java/com/example/firestore/snippets/References.java
  firestore/src/main/java/com/example/firestore/snippets/RetrieveDataSnippets.java
  firestore/src/main/java/com/example/firestore/snippets/model/City.java
  firestore/src/test/java/com/example/firestore/BaseIntegrationTest.java
  firestore/src/test/java/com/example/firestore/QuickstartIT.java
  firestore/src/test/java/com/example/firestore/snippets/ListenDataSnippetsIT.java
  firestore/src/test/java/com/example/firestore/snippets/ManageDataSnippetsIT.java
  firestore/src/test/java/com/example/firestore/snippets/QueryDataSnippetsIT.java
  firestore/src/test/java/com/example/firestore/snippets/RetrieveDataSnippetsIT.java
Labels: cla: yes

#3464 chore: remove Dialogflow snippets migrated to googleapis/java-dialogflow
  dialogflow/cloud-client/README.md
  dialogflow/cloud-client/pom.xml
  dialogflow/cloud-client/resources/230pm.wav
  dialogflow/cloud-client/resources/RoomReservation.zip
  dialogflow/cloud-client/resources/book_a_room.wav
  dialogflow/cloud-client/resources/half_an_hour.wav
  dialogflow/cloud-client/resources/mountain_view.wav
  dialogflow/cloud-client/resources/today.wav
  dialogflow/cloud-client/resources/two_people.wav
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentAudio.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentKnowledge.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentStream.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentTexts.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentWithSentimentAnalysis.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentWithTextToSpeechResponse.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DocumentManagement.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/IntentManagement.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/KnowledgeBaseManagement.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/CreateDocumentTest.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/CreateKnowledgeBaseTest.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/DetectIntentKnowledgeTest.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/DetectIntentStreamIT.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/DetectIntentWithAudioTest.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/DetectIntentWithSentimentAndTextToSpeechIT.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/IntentManagementIT.java
Labels: automerge, cla: yes

#3527 chore: migrate asset samples to https://github.com/googleapis/java-asset
  asset/cloud-client/pom.xml
  asset/cloud-client/src/main/java/com/example/asset/BatchGetAssetsHistoryExample.java
  asset/cloud-client/src/main/java/com/example/asset/CreateFeedExample.java
  asset/cloud-client/src/main/java/com/example/asset/DeleteFeedExample.java
  asset/cloud-client/src/main/java/com/example/asset/ExportAssetsBigqueryExample.java
  asset/cloud-client/src/main/java/com/example/asset/ExportAssetsExample.java
  asset/cloud-client/src/main/java/com/example/asset/GetFeedExample.java
  asset/cloud-client/src/main/java/com/example/asset/ListAssetsExample.java
  asset/cloud-client/src/main/java/com/example/asset/ListFeedsExample.java
  asset/cloud-client/src/main/java/com/example/asset/SearchAllIamPoliciesExample.java
  asset/cloud-client/src/main/java/com/example/asset/SearchAllResourcesExample.java
  asset/cloud-client/src/main/java/com/example/asset/UpdateFeedExample.java
  asset/cloud-client/src/test/java/com/example/asset/ListAssets.java
  asset/cloud-client/src/test/java/com/example/asset/QuickStartIT.java
  asset/cloud-client/src/test/java/com/example/asset/RealTimeFeed.java
  asset/cloud-client/src/test/java/com/example/asset/Search.java
Labels: cla: yes

#3524 chore: remove datalabeling samples migrated to https://github.com/googleapis/java-datalabeling
  datalabeling/beta/cloud-client/README.md
  datalabeling/beta/cloud-client/pom.xml
  datalabeling/beta/cloud-client/src/main/java/com/example/datalabeling/CreateAnnotationSpecSet.java
  datalabeling/beta/cloud-client/src/main/java/com/example/datalabeling/CreateDataset.java
  datalabeling/beta/cloud-client/src/main/java/com/example/datalabeling/CreateInstruction.java
  datalabeling/beta/cloud-client/src/main/java/com/example/datalabeling/ExportData.java
  datalabeling/beta/cloud-client/src/main/java/com/example/datalabeling/ImportData.java
  datalabeling/beta/cloud-client/src/main/java/com/example/datalabeling/LabelImage.java
  datalabeling/beta/cloud-client/src/main/java/com/example/datalabeling/LabelText.java
  datalabeling/beta/cloud-client/src/main/java/com/example/datalabeling/LabelVideo.java
  datalabeling/beta/cloud-client/src/test/java/com/example/datalabeling/CreateAnnotationSpecSetIT.java
  datalabeling/beta/cloud-client/src/test/java/com/example/datalabeling/CreateDatasetIT.java
  datalabeling/beta/cloud-client/src/test/java/com/example/datalabeling/CreateInstructionIT.java
  datalabeling/beta/cloud-client/src/test/java/com/example/datalabeling/ImportDataIT.java
  datalabeling/beta/cloud-client/src/test/java/com/example/datalabeling/LabelImageIT.java
  datalabeling/beta/cloud-client/src/test/java/com/example/datalabeling/LabelTextIT.java
  datalabeling/beta/cloud-client/src/test/java/com/example/datalabeling/LabelVideoIT.java
Labels: cla: yes

#3525 chore: remove dataproc samples migrated to https://github.com/googleapis/java-dataproc
  dataproc/pom.xml
  dataproc/src/main/java/CreateCluster.java
  dataproc/src/main/java/CreateClusterWithAutoscaling.java
  dataproc/src/main/java/InstantiateInlineWorkflowTemplate.java
  dataproc/src/main/java/Quickstart.java
  dataproc/src/main/java/SubmitHadoopFsJob.java
  dataproc/src/test/java/CreateClusterTest.java
  dataproc/src/test/java/CreateClusterWithAutoscalingTest.java
  dataproc/src/test/java/InstantiateInlineWorkflowTemplateTest.java
  dataproc/src/test/java/QuickstartTest.java
  dataproc/src/test/java/SubmitHadoopFsJobTest.java
Labels: cla: yes

#3523 chore: migrate datacatalog samples to https://github.com/googleapis/java-datacatalog
  datacatalog/cloud-client/README.md
  datacatalog/cloud-client/build.gradle
  datacatalog/cloud-client/pom.xml
  datacatalog/cloud-client/src/main/java/com/example/datacatalog/CreateEntryGroup.java
  datacatalog/cloud-client/src/main/java/com/example/datacatalog/CreateFilesetEntry.java
  datacatalog/cloud-client/src/main/java/com/example/datacatalog/LookupEntryBigQueryDataset.java
  datacatalog/cloud-client/src/main/java/com/example/datacatalog/LookupEntryBigQueryTable.java
  datacatalog/cloud-client/src/main/java/com/example/datacatalog/LookupEntryPubSubTopic.java
  datacatalog/cloud-client/src/test/java/com/example/datacatalog/CreateEntryTests.java
  datacatalog/cloud-client/src/test/java/com/example/datacatalog/LookupEntryTests.java
Labels: cla: yes

#3530 chore: migrate recommender samples to https://github.com/googleapis/java-recommender
  recommender/beta/cloud-client/README.md
  recommender/beta/cloud-client/pom.xml
  recommender/beta/cloud-client/src/main/java/com/example/recommender/ListRecommendations.java
  recommender/beta/cloud-client/src/test/java/com/example/recommender/ListRecommendationsTest.java
Labels: cla: yes

#3543 chore: migrate securitycenter samples to https://github.com/googleapis/java-securitycenter
  securitycenter/pom.xml
  securitycenter/src/main/java/com/google/cloud/examples/securitycenter/snippets/CreateNotificationConfigSnippets.java
  securitycenter/src/main/java/com/google/cloud/examples/securitycenter/snippets/DeleteNotificationConfigSnippets.java
  securitycenter/src/main/java/com/google/cloud/examples/securitycenter/snippets/GetNotificationConfigSnippets.java
  securitycenter/src/main/java/com/google/cloud/examples/securitycenter/snippets/ListNotificationConfigSnippets.java
  securitycenter/src/main/java/com/google/cloud/examples/securitycenter/snippets/NotificationReceiver.java
  securitycenter/src/main/java/com/google/cloud/examples/securitycenter/snippets/UpdateNotificationConfigSnippets.java
  securitycenter/src/test/java/com/google/cloud/examples/securitycenter/snippets/NotificationConfigSnippetTests.java
Labels: cla: yes

#3542 deps: added temp fix for auth
  monitoring/cloud-client/pom.xml
  monitoring/v3/pom.xml
Labels: cla: yes

#3549 refactor(run): use the Cloud Run authentication sample for Cloud Functions
  run/authentication/src/main/java/com/example/cloudrun/Authentication.java
Labels: cla: yes

#3553 fix: only run test if restore succeeded
  spanner/cloud-client/pom.xml
  spanner/cloud-client/src/test/java/com/example/spanner/SpannerSampleIT.java
Labels: cla: yes

#3556 chore: remove bigtable samples migrated to https://github.com/googleapis/java-bigtable
  bigtable/pom.xml
  bigtable/snippets/pom.xml
  bigtable/snippets/src/main/java/com/example/bigtable/Filters.java
  bigtable/snippets/src/main/java/com/example/bigtable/Reads.java
  bigtable/snippets/src/main/java/com/example/bigtable/WriteBatch.java
  bigtable/snippets/src/main/java/com/example/bigtable/WriteConditionally.java
  bigtable/snippets/src/main/java/com/example/bigtable/WriteIncrement.java
  bigtable/snippets/src/main/java/com/example/bigtable/WriteSimple.java
  bigtable/snippets/src/test/java/com/example/bigtable/FiltersTest.java
  bigtable/snippets/src/test/java/com/example/bigtable/ReadsTest.java
  bigtable/snippets/src/test/java/com/example/bigtable/WritesTest.java
  bigtable/src/main/java/com/m/examples/bigtable/HelloWorld.java
  bigtable/src/main/java/com/m/examples/bigtable/InstanceAdminExample.java
  bigtable/src/main/java/com/m/examples/bigtable/Quickstart.java
  bigtable/src/main/java/com/m/examples/bigtable/TableAdminExample.java
  bigtable/src/test/java/com/m/examples/bigtable/HelloWorldTest.java
  bigtable/src/test/java/com/m/examples/bigtable/InstanceAdminExampleTest.java
  bigtable/src/test/java/com/m/examples/bigtable/QuickstartTest.java
  bigtable/src/test/java/com/m/examples/bigtable/TableAdminExampleTest.java
Labels: cla: yes

#3562 fix(cloud-sql): Updated sample to include full JDBC url in comments.
  cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java
  cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java
Labels: cla: yes

#3580 samples: fixed flaky test automl
  automl/beta/src/main/java/com/example/automl/ListModels.java
Labels: automerge, cla: yes

#3473 chore(functions): remove redundant logging sample
  functions/logging/retrieve-logs/pom.xml
  functions/logging/retrieve-logs/src/main/java/functions/RetrieveLogs.java
  functions/logging/retrieve-logs/src/test/java/functions/RetrieveLogsTest.java
Labels: automerge, cla: yes

#3599 dataflow: have consistent metadata names in camelCase
  dataflow/flex-templates/kafka_to_bigquery/metadata.json
  dataflow/flex-templates/streaming_beam_sql/metadata.json
  dataflow/templates/WordCount_metadata
Labels: cla: yes

#3602 Specify member type
  iam/api-client/src/main/java/iam/snippets/QuickstartV2.java
Labels: cla: yes

#3610 Add UUID for IAM tests
  iam/api-client/src/main/java/iam/snippets/CreateServiceAccount.java
  iam/api-client/src/main/java/iam/snippets/CreateServiceAccountKey.java
  iam/api-client/src/main/java/iam/snippets/DeleteServiceAccount.java
  iam/api-client/src/main/java/iam/snippets/DeleteServiceAccountKey.java
  iam/api-client/src/main/java/iam/snippets/DisableServiceAccount.java
  iam/api-client/src/main/java/iam/snippets/EnableServiceAccount.java
  iam/api-client/src/main/java/iam/snippets/ListServiceAccountKeys.java
  iam/api-client/src/main/java/iam/snippets/RenameServiceAccount.java
  iam/api-client/src/test/java/iam/snippets/ServiceAccountTests.java
Labels: automerge, cla: yes

#3612 healthcare API: increase sleep time for hl7v2MessageList
  healthcare/v1/src/test/java/snippets/healthcare/Hl7v2MessageTests.java
Labels: cla: yes

#3611 samples (test): fixed the flaky test
  vision/cloud-client/src/main/java/com/example/vision/snippets/DetectLandmarksUrl.java
  vision/cloud-client/src/test/java/com/example/vision/DetectLandmarksGcsTest.java
Labels: cla: yes

#3618 Update region tags
  run/helloworld/pom.xml
  run/helloworld/src/main/java/com/example/helloworld/HelloworldApplication.java
  run/helloworld/src/main/resources/application.properties
Labels: cla: yes

#3632 Add region tag for Quickstart dependencies
  iam/api-client/pom.xml
Labels: cla: yes

#3628 samples: refactor automl beta test for importDataset
  automl/beta/src/test/java/com/example/automl/ImportDatasetTest.java
Labels: cla: yes, samples
