Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2020-04, with the labels that each got.

#2282 Corrected local execution cmd-line
  appengine-java11/helloworld-servlet/README.md
Labels: automerge, cla: yes

#2547 small changes test and added sleep time between search func
  jobs/v3/src/main/java/com/google/samples/FeaturedJobsSearchSample.java
  jobs/v3/src/test/java/SampleTests.java
Labels: cla: yes

#2520 [GCF] Add ImageMagick samples
  functions/snippets/pom.xml
  functions/snippets/src/main/java/com/example/functions/ImageMagick.java
  functions/snippets/src/test/java/com/example/functions/ImageMagickTests.java
Labels: cla: yes

#2550 video: update .mp4 file used in test
  video/beta/src/test/java/com/example/video/DetectIT.java
  video/cloud-client/src/test/java/com/example/video/DetectIT.java
Labels: automerge, cla: yes

#2554 Add HTTP bearer token sample
  functions/snippets/src/main/java/com/example/functions/BearerTokenHttp.java
Labels: automerge, cla: yes

#2558 [Container Analysis] simplified pubsub test
  container-registry/container-analysis/src/test/java/com/example/containeranalysis/SamplesTest.java
Labels: cla: yes

#2557 [Cloud Run] Auth Snippet
  .kokoro/tests/build_cloud_run.sh
  run/authentication/README.md
  run/authentication/pom.xml
  run/authentication/src/main/java/com/example/cloudrun/Authentication.java
  run/authentication/src/test/java/com/example/cloudrun/AuthenticationTest.java
Labels: automerge, cla: yes

#2552 Add functions/ocr sample
  functions/snippets/pom.xml
  functions/snippets/src/main/java/com/example/functions/OcrProcessImage.java
  functions/snippets/src/main/java/com/example/functions/OcrSaveResult.java
  functions/snippets/src/main/java/com/example/functions/OcrTranslateApiMessage.java
  functions/snippets/src/main/java/com/example/functions/OcrTranslateText.java
  functions/snippets/src/test/java/com/example/functions/OcrTests.java
Labels: automerge, cla: yes

#2575 docs: Fix securitycenter tests
  securitycenter/src/test/java/com/google/cloud/examples/securitycenter/snippets/NotificationConfigSnippetTests.java
Labels: cla: yes

#2576 Add AfterClass method to cleanup DLP Triggers and Templates
  dlp/src/main/java/dlp/snippets/TriggersList.java
  dlp/src/test/java/dlp/snippets/TemplatesTests.java
  dlp/src/test/java/dlp/snippets/TriggersTests.java
Labels: cla: yes

#2582 Add missing functions_ocr_setup tag to sample
  functions/snippets/src/main/java/com/example/functions/OcrProcessImage.java
Labels: automerge, cla: yes

#2604 Update Data Catalog samples to client library V1
  datacatalog/cloud-client/src/main/java/com/example/datacatalog/CreateEntryGroup.java
  datacatalog/cloud-client/src/main/java/com/example/datacatalog/CreateFilesetEntry.java
  datacatalog/cloud-client/src/main/java/com/example/datacatalog/LookupEntryBigQueryDataset.java
  datacatalog/cloud-client/src/main/java/com/example/datacatalog/LookupEntryBigQueryTable.java
  datacatalog/cloud-client/src/main/java/com/example/datacatalog/LookupEntryPubSubTopic.java
  datacatalog/cloud-client/src/test/java/com/example/datacatalog/CreateEntryTests.java
Labels: automerge, cla: yes

#2602 dialogflow: delete samples that are not in docs
  dialogflow/cloud-client/README.md
  dialogflow/cloud-client/pom.xml
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/ContextManagement.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentKnowledge.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentTexts.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentWithModelSelection.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentWithSentimentAnalysis.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentWithTextToSpeechResponse.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/DocumentManagement.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/EntityManagement.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/EntityTypeManagement.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/KnowledgeBaseManagement.java
  dialogflow/cloud-client/src/main/java/com/example/dialogflow/SessionEntityTypeManagement.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/ContextManagementIT.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/CreateDocumentTest.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/CreateKnowledgeBaseTest.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/DetectIntentKnowledgeTest.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/DetectIntentWithAudioTest.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/EntityManagementIT.java
  dialogflow/cloud-client/src/test/java/com/example/dialogflow/SessionEntityTypeManagementIT.java
Labels: cla: yes

#2625 Jetty should update together
  renovate.json
Labels: automerge, cla: yes

#2626 Fix incorrect region tag on + move HTTP methods sample
  functions/snippets/helloworld/src/test/java/com/example/functions/helloworld/HelloWorldSnippetsTest.java
  functions/snippets/http/src/main/java/com/example/functions/http/HttpMethod.java
  functions/snippets/http/src/test/java/com/example/functions/http/HttpTests.java
Labels: cla: yes

#2615 GCF CI/CD: add cloudbuild.yaml
  functions/snippets/ci_cd/cloudbuild.yaml
Labels: automerge, cla: yes

#2629 GCF: Add HTTP unit test sample
  functions/snippets/helloworld/src/test/java/com/example/functions/helloworld/HelloHttpTest.java
Labels: cla: yes

#2559 docs: add additional samples for Spanner JDBC
  spanner/jdbc/pom.xml
  spanner/jdbc/src/main/java/com/example/spanner/JdbcSample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/AbortBatchExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/AutocommitUpdateDataExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/BatchDdlExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/BatchDdlUsingSqlStatementsExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/BatchDmlExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/BatchDmlUsingSqlStatementsExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/BufferedWriteExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/ConnectionWithQueryOptionsExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateConnectionExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateConnectionWithCredentialsExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateConnectionWithCustomHostExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateConnectionWithDataSourceExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateConnectionWithDefaultProjectIdExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateConnectionWithPropertiesExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateConnectionWithUrlPropertiesExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateTableExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/GetCommitTimestampExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/GetReadTimestampExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/InsertDataExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/PartitionedDmlExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/ReadOnlyTransactionExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/ReadWriteTransactionExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/SetQueryOptionsExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/SingleUseReadOnlyExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/SingleUseReadOnlyTimestampBoundExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/TransactionWithRetryLoopExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/TransactionWithRetryLoopUsingOnlyJdbcExample.java
  spanner/jdbc/src/test/java/com/example/spanner/JdbcSampleIT.java
  spanner/jdbc/src/test/java/com/example/spanner/jdbc/JdbcExamplesIT.java
Labels: api: spanner, cla: yes

#2614 GCF: add Java Pub/Sub samples
  functions/pubsub/pom.xml
  functions/pubsub/src/main/java/com/example/functions/pubsub/PublishMessage.java
  functions/pubsub/src/main/java/com/example/functions/pubsub/SubscribeToTopic.java
  functions/pubsub/src/main/java/com/example/functions/pubsub/eventpojos/PubSubMessage.java
  functions/pubsub/src/test/java/com/example/functions/pubsub/PubsubTest.java
Labels: cla: yes

#2634 jobs-v4: api update
  jobs/v4/src/main/java/com/example/jobs/CommuteSearchJobs.java
  jobs/v4/src/main/java/com/example/jobs/CustomRankingSearchJobs.java
  jobs/v4/src/main/java/com/example/jobs/HistogramSearchJobs.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchAutoCompleteJobTitle.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchCreateClientEvent.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchCreateCompany.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchCreateJob.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchCreateJobCustomAttributes.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchDeleteCompany.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchDeleteJob.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchGetCompany.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchGetJob.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchListCompanies.java
  jobs/v4/src/main/java/com/example/jobs/JobSearchListJobs.java
Labels: cla: yes

#2637 Change how package names should be chosen.
  SAMPLE_FORMAT.md
Labels: automerge, cla: yes

#2664 GCF file split (munge): imagemagick
  functions/imagemagick/pom.xml
  functions/imagemagick/src/main/java/com/example/functions/imagemagick/eventpojos/PubSubMessage.java
  functions/imagemagick/src/main/java/functions/ImageMagick.java
  functions/imagemagick/src/main/java/functions/eventpojos/GcsEvent.java
  functions/imagemagick/src/test/java/functions/ImageMagickTest.java
  functions/imagemagick/src/test/java/functions/eventpojos/MockContext.java
Labels: cla: yes

#2662 GCF file split (munge): Slack
  functions/slack/pom.xml
  functions/slack/src/main/java/functions/SlackSlashCommand.java
  functions/slack/src/test/java/functions/SlackSlashCommandTest.java
Labels: cla: yes

#2665 GCF file split: logging
  functions/logging/log-hello-world/pom.xml
  functions/logging/log-hello-world/src/main/java/functions/LogHelloWorld.java
  functions/logging/retrieve-logs/pom.xml
  functions/logging/retrieve-logs/src/main/java/functions/RetrieveLogs.java
  functions/logging/retrieve-logs/src/test/java/functions/RetrieveLogsTest.java
  functions/logging/stackdriver-logging/pom.xml
  functions/logging/stackdriver-logging/src/main/java/functions/StackdriverLogging.java
  functions/logging/stackdriver-logging/src/main/java/functions/eventpojos/PubSubMessage.java
  functions/logging/stackdriver-logging/src/test/java/functions/StackdriverLoggingTest.java
Labels: automerge, cla: yes

#2668 Fix flaky tests
  automl/beta/src/test/java/com/example/automl/BatchPredictTest.java
  monitoring/v3/manage_alerts_sample.sh
  monitoring/v3/src/test/java/com/example/AlertIT.java
Labels: cla: yes

#2669 Fix monitor test
  monitoring/v3/src/test/java/com/example/AlertIT.java
Labels: cla: yes

#2667 GCF file split: helloworld + add jvm-langs (for non-Java samples)
  functions/helloworld/hello-background/pom.xml
  functions/helloworld/hello-background/src/main/java/functions/HelloBackground.java
  functions/helloworld/hello-background/src/test/java/functions/HelloBackgroundTest.java
  functions/helloworld/hello-error/pom.xml
  functions/helloworld/hello-error/src/main/java/functions/HelloError.java
  functions/helloworld/hello-gcs-generic/pom.xml
  functions/helloworld/hello-gcs-generic/src/main/java/functions/HelloGcsGeneric.java
  functions/helloworld/hello-gcs-generic/src/main/java/functions/eventpojos/GcsEvent.java
  functions/helloworld/hello-gcs-generic/src/test/java/functions/HelloGcsGenericTest.java
  functions/helloworld/hello-gcs-generic/src/test/java/functions/eventpojos/MockContext.java
  functions/helloworld/hello-gcs/pom.xml
  functions/helloworld/hello-gcs/src/main/java/functions/HelloGcs.java
  functions/helloworld/hello-gcs/src/main/java/functions/eventpojos/GcsEvent.java
  functions/helloworld/hello-gcs/src/test/java/functions/HelloGcsTest.java
  functions/helloworld/hello-gcs/src/test/java/functions/eventpojos/MockContext.java
  functions/helloworld/hello-http/pom.xml
  functions/helloworld/hello-http/src/main/java/functions/HelloHttp.java
  functions/helloworld/hello-http/src/test/java/functions/HelloHttpTest.java
  functions/helloworld/hello-pub-sub/pom.xml
  functions/helloworld/hello-pub-sub/src/main/java/functions/HelloPubSub.java
  functions/helloworld/hello-pub-sub/src/main/java/functions/eventpojos/PubSubMessage.java
  functions/helloworld/hello-pub-sub/src/test/java/functions/HelloPubSubTest.java
  functions/helloworld/hello-world/pom.xml
  functions/helloworld/hello-world/src/main/java/functions/HelloWorld.java
  functions/helloworld/hello-world/src/test/java/functions/HelloWorldTest.java
  functions/jvm-langs/groovy-hello-background/pom.xml
  functions/jvm-langs/groovy-hello-background/src/main/groovy/functions/GroovyHelloBackground.groovy
  functions/jvm-langs/groovy-hello-background/src/test/java/functions/GroovyHelloBackgroundTest.java
  functions/jvm-langs/groovy-hello-background/src/test/java/functions/eventpojos/MockContext.java
  functions/jvm-langs/groovy-hello-world/pom.xml
  functions/jvm-langs/groovy-hello-world/src/main/groovy/functions/GroovyHelloWorld.groovy
  functions/jvm-langs/groovy-hello-world/src/test/java/functions/GroovyHelloWorldTest.java
  functions/jvm-langs/kotlin-hello-background/pom.xml
  functions/jvm-langs/kotlin-hello-background/src/main/kotlin/functions/KotlinHelloBackground.kt
  functions/jvm-langs/kotlin-hello-background/src/test/java/functions/KotlinHelloBackgroundTest.java
  functions/jvm-langs/kotlin-hello-background/src/test/java/functions/eventpojos/MockContext.java
  functions/jvm-langs/kotlin-hello-world/pom.xml
  functions/jvm-langs/kotlin-hello-world/src/main/kotlin/functions/KotlinHelloWorld.kt
  functions/jvm-langs/kotlin-hello-world/src/test/java/functions/KotlinHelloWorldTest.java
  functions/jvm-langs/scala-hello-background/pom.xml
  functions/jvm-langs/scala-hello-background/src/main/scala/functions/ScalaHelloBackground.scala
  functions/jvm-langs/scala-hello-background/src/test/java/functions/ScalaHelloBackgroundTest.java
  functions/jvm-langs/scala-hello-background/src/test/java/functions/eventpojos/MockContext.java
  functions/jvm-langs/scala-hello-world/pom.xml
  functions/jvm-langs/scala-hello-world/src/main/scala/functions/ScalaHelloWorld.scala
  functions/jvm-langs/scala-hello-world/src/test/java/functions/ScalaHelloWorldTest.java
Labels: automerge, cla: yes

#2673 Remove old GAE to Cloud SQL samples and point to new ones instead.
  appengine-java8/cloudsql-postgres/README.md
  appengine-java8/cloudsql-postgres/pom.xml
  appengine-java8/cloudsql-postgres/src/main/java/com/example/appengine/postgresql/PostgreSqlServlet.java
  appengine-java8/cloudsql-postgres/src/main/webapp/WEB-INF/appengine-web.xml
  appengine-java8/cloudsql-postgres/src/main/webapp/WEB-INF/web.xml
  appengine-java8/cloudsql/README.md
  appengine-java8/cloudsql/pom.xml
  appengine-java8/cloudsql/src/main/java/com/example/appengine/cloudsql/CloudSqlServlet.java
  appengine-java8/cloudsql/src/main/webapp/WEB-INF/appengine-web.xml
  appengine-java8/cloudsql/src/main/webapp/WEB-INF/web.xml
Labels: cla: yes

#2642 healthcare API: update datasets/ samples from v1beta1 to v1
  healthcare/v1/pom.xml
  healthcare/v1/src/main/java/snippets/healthcare/datasets/DatasetCreate.java
  healthcare/v1/src/main/java/snippets/healthcare/datasets/DatasetDeIdentify.java
  healthcare/v1/src/main/java/snippets/healthcare/datasets/DatasetDelete.java
  healthcare/v1/src/main/java/snippets/healthcare/datasets/DatasetGet.java
  healthcare/v1/src/main/java/snippets/healthcare/datasets/DatasetGetIamPolicy.java
  healthcare/v1/src/main/java/snippets/healthcare/datasets/DatasetList.java
  healthcare/v1/src/main/java/snippets/healthcare/datasets/DatasetPatch.java
  healthcare/v1/src/main/java/snippets/healthcare/datasets/DatasetSetIamPolicy.java
  healthcare/v1/src/test/java/snippets/healthcare/DatasetTests.java
Labels: cla: yes

#2675 Remove ignore for 2 healthcare FHIR Resource tests.
  healthcare/v1beta1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceConditionalPatch.java
  healthcare/v1beta1/src/test/java/snippets/healthcare/FhirResourceTests.java
Labels: cla: yes

#2676 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .kokoro/tests/run_tests.sh
  SAMPLE_FORMAT.md
Labels: automerge, cla: yes

#2674 healthcare API: update fhir/ samples from v1beta1 to v1
  healthcare/v1/pom.xml
  healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStoreCreate.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStoreDelete.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStoreExecuteBundle.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStoreExport.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStoreGet.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStoreGetIamPolicy.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStoreImport.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStoreList.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStorePatch.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStoreSetIamPolicy.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceCreate.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceDelete.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceDeletePurge.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceGet.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceGetHistory.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceGetMetadata.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceGetPatientEverything.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceListHistory.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourcePatch.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceSearchGet.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceSearchPost.java
  healthcare/v1/src/test/java/snippets/healthcare/FhirResourceTests.java
  healthcare/v1/src/test/java/snippets/healthcare/FhirStoreTests.java
Labels: cla: yes

#2677 [Cloud Run] Markdown sample
  .kokoro/tests/build_cloud_run.sh
  run/markdown-preview/README.md
  run/markdown-preview/editor/pom.xml
  run/markdown-preview/editor/src/main/java/com/example/cloudrun/Data.java
  run/markdown-preview/editor/src/main/java/com/example/cloudrun/EditorApplication.java
  run/markdown-preview/editor/src/main/java/com/example/cloudrun/EditorController.java
  run/markdown-preview/editor/src/main/java/com/example/cloudrun/RenderController.java
  run/markdown-preview/editor/src/main/resources/application.properties
  run/markdown-preview/editor/src/main/resources/templates/index.html
  run/markdown-preview/editor/src/main/resources/templates/markdown.md
  run/markdown-preview/editor/src/test/java/com/example/cloudrun/EditorControllerTests.java
  run/markdown-preview/editor/src/test/java/com/example/cloudrun/RenderControllerTests.java
  run/markdown-preview/renderer/pom.xml
  run/markdown-preview/renderer/src/main/java/com/example/cloudrun/MarkdownController.java
  run/markdown-preview/renderer/src/main/java/com/example/cloudrun/RendererApplication.java
  run/markdown-preview/renderer/src/main/resources/application.properties
  run/markdown-preview/renderer/src/test/java/com/example/cloudrun/RendererApplicationTests.java
Labels: automerge, cla: yes

#2680 GCF pub/sub: add missing private keyword to Pub/Sub samples
  functions/pubsub/src/main/java/com/example/functions/pubsub/eventpojos/PubSubMessage.java
Labels: automerge, cla: yes

#2678 Update cloudsql/ samples to address spotbugs issues.
  cloud-sql/mysql/servlet/pom.xml
  cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java
  cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/IndexServlet.java
  cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/Vote.java
  cloud-sql/postgres/servlet/pom.xml
  cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java
  cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/IndexServlet.java
  cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/Vote.java
  cloud-sql/postgres/servlet/src/main/webapp/WEB-INF/appengine-web.xml
  cloud-sql/postgres/servlet/src/main/webapp/index.jsp
Labels: cla: yes

#2686 Example POM: add region tags
  functions/firebase/firestore/pom.xml
Labels: cla: yes

#2646 Fixes some lint errors.
  iot/api-client/manager/pom.xml
  iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/DeviceRegistryExample.java
  iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/DeviceRegistryExampleOptions.java
  iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/HttpExample.java
  iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/HttpExampleOptions.java
  iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/MqttExample.java
  iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/MqttExampleOptions.java
  iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/RetryHttpInitializerWrapper.java
  iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java
Labels: cla: yes

#2689 Move jvm-langs samples to helloworld directory
  functions/helloworld/groovy-hello-background/pom.xml
  functions/helloworld/groovy-hello-background/src/main/groovy/functions/GroovyHelloBackground.groovy
  functions/helloworld/groovy-hello-background/src/test/java/functions/GroovyHelloBackgroundTest.java
  functions/helloworld/groovy-hello-background/src/test/java/functions/eventpojos/MockContext.java
  functions/helloworld/groovy-hello-world/pom.xml
  functions/helloworld/groovy-hello-world/src/main/groovy/functions/GroovyHelloWorld.groovy
  functions/helloworld/groovy-hello-world/src/test/java/functions/GroovyHelloWorldTest.java
  functions/helloworld/kotlin-hello-background/pom.xml
  functions/helloworld/kotlin-hello-background/src/main/kotlin/functions/KotlinHelloBackground.kt
  functions/helloworld/kotlin-hello-background/src/test/java/functions/KotlinHelloBackgroundTest.java
  functions/helloworld/kotlin-hello-background/src/test/java/functions/eventpojos/MockContext.java
  functions/helloworld/kotlin-hello-world/pom.xml
  functions/helloworld/kotlin-hello-world/src/main/kotlin/functions/KotlinHelloWorld.kt
  functions/helloworld/kotlin-hello-world/src/test/java/functions/KotlinHelloWorldTest.java
  functions/helloworld/scala-hello-background/pom.xml
  functions/helloworld/scala-hello-background/src/main/scala/functions/ScalaHelloBackground.scala
  functions/helloworld/scala-hello-background/src/test/java/functions/ScalaHelloBackgroundTest.java
  functions/helloworld/scala-hello-background/src/test/java/functions/eventpojos/MockContext.java
  functions/helloworld/scala-hello-world/pom.xml
  functions/helloworld/scala-hello-world/src/main/scala/functions/ScalaHelloWorld.scala
  functions/helloworld/scala-hello-world/src/test/java/functions/ScalaHelloWorldTest.java
Labels: cla: yes

#2663 GCF file split: pub/sub
  functions/pubsub/publish-message/pom.xml
  functions/pubsub/publish-message/src/main/java/functions/PublishMessage.java
  functions/pubsub/publish-message/src/main/java/functions/eventpojos/PubSubMessage.java
  functions/pubsub/publish-message/src/test/java/functions/PublishMessageTest.java
  functions/pubsub/subscribe-to-topic/pom.xml
  functions/pubsub/subscribe-to-topic/src/main/java/functions/SubscribeToTopic.java
  functions/pubsub/subscribe-to-topic/src/main/java/functions/eventpojos/PubSubMessage.java
  functions/pubsub/subscribe-to-topic/src/test/java/functions/SubscribeToTopicTest.java
Labels: automerge, cla: yes

#2693 Remove extra helloworld samples
  functions/helloworld/src/main/groovy/com/example/functions/helloworld/GroovyHelloBackground.groovy
  functions/helloworld/src/main/groovy/com/example/functions/helloworld/GroovyHelloWorld.groovy
  functions/helloworld/src/main/java/com/example/functions/helloworld/HelloBackground.java
  functions/helloworld/src/main/java/com/example/functions/helloworld/HelloError.java
  functions/helloworld/src/main/java/com/example/functions/helloworld/HelloGcs.java
  functions/helloworld/src/main/java/com/example/functions/helloworld/HelloGcsGeneric.java
  functions/helloworld/src/main/java/com/example/functions/helloworld/HelloHttp.java
  functions/helloworld/src/main/java/com/example/functions/helloworld/HelloPubSub.java
  functions/helloworld/src/main/java/com/example/functions/helloworld/HelloWorld.java
  functions/helloworld/src/main/java/com/example/functions/helloworld/eventpojos/GcsEvent.java
  functions/helloworld/src/main/java/com/example/functions/helloworld/eventpojos/PubSubMessage.java
  functions/helloworld/src/main/kotlin/com/example/functions/helloworld/KotlinHelloBackground.kt
  functions/helloworld/src/main/kotlin/com/example/functions/helloworld/KotlinHelloWorld.kt
  functions/helloworld/src/main/scala/com/example/functions/helloworld/ScalaHelloBackground.scala
  functions/helloworld/src/main/scala/com/example/functions/helloworld/ScalaHelloWorld.scala
  functions/helloworld/src/test/java/com/example/functions/helloworld/GroovyTest.java
  functions/helloworld/src/test/java/com/example/functions/helloworld/HelloGcsTest.java
  functions/helloworld/src/test/java/com/example/functions/helloworld/HelloHttpTest.java
  functions/helloworld/src/test/java/com/example/functions/helloworld/HelloPubSubTest.java
  functions/helloworld/src/test/java/com/example/functions/helloworld/HelloWorldSnippetsTest.java
  functions/helloworld/src/test/java/com/example/functions/helloworld/KotlinTest.java
  functions/helloworld/src/test/java/com/example/functions/helloworld/ScalaTest.java
  functions/helloworld/src/test/java/com/example/functions/helloworld/eventpojos/MockContext.java
Labels: cla: yes

#2697 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: automerge, cla: yes

#2688 GCF: add multipart sample
  functions/http/http-form-data/pom.xml
  functions/http/http-form-data/src/main/java/functions/HttpFormData.java
  functions/http/http-form-data/src/test/java/functions/HttpFormDataTest.java
  functions/http/http-form-data/src/test/java/functions/MockHttpPart.java
Labels: automerge, cla: yes

#2696 GCF file split: OCR
  functions/ocr/ocr-process-image/pom.xml
  functions/ocr/ocr-process-image/src/main/java/functions/OcrProcessImage.java
  functions/ocr/ocr-process-image/src/main/java/functions/OcrTranslateApiMessage.java
  functions/ocr/ocr-process-image/src/main/java/functions/eventpojos/GcsEvent.java
  functions/ocr/ocr-process-image/src/main/java/functions/eventpojos/PubSubMessage.java
  functions/ocr/ocr-process-image/src/test/java/functions/OcrProcessImageTest.java
  functions/ocr/ocr-save-result/pom.xml
  functions/ocr/ocr-save-result/src/main/java/functions/OcrSaveResult.java
  functions/ocr/ocr-save-result/src/main/java/functions/OcrTranslateApiMessage.java
  functions/ocr/ocr-save-result/src/main/java/functions/eventpojos/PubSubMessage.java
  functions/ocr/ocr-save-result/src/test/java/functions/OcrSaveResultTest.java
  functions/ocr/ocr-translate-text/pom.xml
  functions/ocr/ocr-translate-text/src/main/java/functions/OcrTranslateApiMessage.java
  functions/ocr/ocr-translate-text/src/main/java/functions/OcrTranslateText.java
  functions/ocr/ocr-translate-text/src/main/java/functions/eventpojos/PubSubMessage.java
  functions/ocr/ocr-translate-text/src/test/java/functions/OcrTranslateTextTest.java
Labels: automerge, cla: yes

#2692 healthcare API: update remaining dicom/ and hl7v2/ files from v1beta1 to v1
  healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomStoreCreate.java
  healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomStoreDelete.java
  healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomStoreExport.java
  healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomStoreGet.java
  healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomStoreGetIamPolicy.java
  healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomStoreImport.java
  healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomStoreList.java
  healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomStorePatch.java
  healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomStoreSetIamPolicy.java
  healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomWebDeleteStudy.java
  healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomWebRetrieveInstance.java
  healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomWebRetrieveRendered.java
  healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomWebRetrieveStudy.java
  healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomWebSearchForInstances.java
  healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomWebSearchStudies.java
  healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomWebStoreInstance.java
  healthcare/v1/src/main/java/snippets/healthcare/hl7v2/Hl7v2StoreCreate.java
  healthcare/v1/src/main/java/snippets/healthcare/hl7v2/Hl7v2StoreDelete.java
  healthcare/v1/src/main/java/snippets/healthcare/hl7v2/Hl7v2StoreGet.java
  healthcare/v1/src/main/java/snippets/healthcare/hl7v2/Hl7v2StoreGetIamPolicy.java
  healthcare/v1/src/main/java/snippets/healthcare/hl7v2/Hl7v2StoreList.java
  healthcare/v1/src/main/java/snippets/healthcare/hl7v2/Hl7v2StorePatch.java
  healthcare/v1/src/main/java/snippets/healthcare/hl7v2/Hl7v2StoreSetIamPolicy.java
  healthcare/v1/src/main/java/snippets/healthcare/hl7v2/messages/HL7v2MessageCreate.java
  healthcare/v1/src/main/java/snippets/healthcare/hl7v2/messages/HL7v2MessageDelete.java
  healthcare/v1/src/main/java/snippets/healthcare/hl7v2/messages/HL7v2MessageGet.java
  healthcare/v1/src/main/java/snippets/healthcare/hl7v2/messages/HL7v2MessageIngest.java
  healthcare/v1/src/main/java/snippets/healthcare/hl7v2/messages/HL7v2MessageList.java
  healthcare/v1/src/main/java/snippets/healthcare/hl7v2/messages/HL7v2MessagePatch.java
  healthcare/v1/src/test/java/snippets/healthcare/DicomStoreTests.java
  healthcare/v1/src/test/java/snippets/healthcare/DicomWebTests.java
  healthcare/v1/src/test/java/snippets/healthcare/Hl7v2MessageTests.java
  healthcare/v1/src/test/java/snippets/healthcare/Hl7v2StoreTests.java
  healthcare/v1/src/test/resources/hl7v2-sample-ingest.txt
  healthcare/v1/src/test/resources/jpeg_text.dcm
Labels: cla: yes

#2698 Remove signatures from UberJAR for Beam SQL
  dataflow/flex-templates/streaming_beam_sql/pom.xml
Labels: cla: yes

#2713 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla: yes

#2714 fix flaky tests of jobs v4
  jobs/v4/src/test/java/JobSearchGetJobTest.java
Labels: automerge, cla: yes

#2281 add export to bq feature
  asset/cloud-client/pom.xml
  asset/cloud-client/src/main/java/com/example/asset/ExportAssetsBigqueryExample.java
  asset/cloud-client/src/test/java/com/example/asset/QuickStartIT.java
Labels: cla: yes

#2720 Add functions_java_example_pom region tag
  functions/firebase/firestore-reactive/pom.xml
Labels: cla: yes

#2722 CTS: [v4] converting hardcoded IDs into ENV vars
  .kokoro/tests/run_tests.sh
  jobs/v4/src/test/java/CommuteSearchJobsTest.java
  jobs/v4/src/test/java/CustomRankingSearchJobsTest.java
  jobs/v4/src/test/java/HistogramSearchJobsTest.java
  jobs/v4/src/test/java/JobSearchAutoCompleteJobTitleTest.java
  jobs/v4/src/test/java/JobSearchCreateCompanyTest.java
  jobs/v4/src/test/java/JobSearchCreateJobTest.java
  jobs/v4/src/test/java/JobSearchCreateJobWithCustomAttrTest.java
  jobs/v4/src/test/java/JobSearchDeleteCompanyTest.java
  jobs/v4/src/test/java/JobSearchDeleteJobTest.java
  jobs/v4/src/test/java/JobSearchGetCompanyTest.java
  jobs/v4/src/test/java/JobSearchGetJobTest.java
  jobs/v4/src/test/java/JobSearchGetTenantTest.java
  jobs/v4/src/test/java/JobSearchListCompaniesTest.java
  jobs/v4/src/test/java/JobSearchListJobsTest.java
Labels: cla: yes

#2716 Update QuickStartIT.java
  asset/cloud-client/src/test/java/com/example/asset/QuickStartIT.java
Labels: automerge, cla: yes

#2727 fix: use libraries-bom
  spanner/cloud-client/pom.xml
Labels: cla: yes

#2721 Wait for Jobs tasks execution before printing.
  jobs/v3/src/main/java/com/google/samples/CommuteSearchSample.java
  jobs/v3/src/main/java/com/google/samples/CustomAttributeSample.java
  jobs/v3/src/main/java/com/google/samples/EmailAlertSearchSample.java
  jobs/v3/src/main/java/com/google/samples/FeaturedJobsSearchSample.java
  jobs/v3/src/main/java/com/google/samples/GeneralSearchSample.java
  jobs/v3/src/main/java/com/google/samples/HistogramSample.java
  jobs/v3/src/main/java/com/google/samples/LocationSearchSample.java
Labels: cla: yes

#2737 Reduce wait on CommuteSearchSample to 1 second from 5.
  jobs/v3/src/main/java/com/google/samples/CommuteSearchSample.java
Labels: cla: yes

#2739 bigtable: upgrade beam version to 2.20.0
  bigtable/beam/helloworld/pom.xml
Labels: cla: yes

#2743 Let users ask us to merge their PR's
  .github/PULL_REQUEST_TEMPLATE.md
Labels: automerge, cla: yes

#2744 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: automerge, cla: yes

#2738 healthcare API: fix typo in message name
  healthcare/v1/src/main/java/snippets/healthcare/hl7v2/messages/HL7v2MessageGet.java
Labels: cla: yes

#2699 Update and add new KMS samples
  kms/README.md
  kms/pom.xml
  kms/src/main/java/com/example/Asymmetric.java
  kms/src/main/java/com/example/CryptFile.java
  kms/src/main/java/com/example/CryptFileCommands.java
  kms/src/main/java/com/example/SnippetCommands.java
  kms/src/main/java/com/example/Snippets.java
  kms/src/main/java/kms/CreateKeyAsymmetricDecrypt.java
  kms/src/main/java/kms/CreateKeyAsymmetricSign.java
  kms/src/main/java/kms/CreateKeyHsm.java
  kms/src/main/java/kms/CreateKeyLabels.java
  kms/src/main/java/kms/CreateKeyRing.java
  kms/src/main/java/kms/CreateKeyRotationSchedule.java
  kms/src/main/java/kms/CreateKeySymmetricEncryptDecrypt.java
  kms/src/main/java/kms/CreateKeyVersion.java
  kms/src/main/java/kms/DecryptAsymmetric.java
  kms/src/main/java/kms/DecryptSymmetric.java
  kms/src/main/java/kms/DestroyKeyVersion.java
  kms/src/main/java/kms/DisableKeyVersion.java
  kms/src/main/java/kms/EnableKeyVersion.java
  kms/src/main/java/kms/EncryptAsymmetric.java
  kms/src/main/java/kms/EncryptSymmetric.java
  kms/src/main/java/kms/GetKeyLabels.java
  kms/src/main/java/kms/GetPublicKey.java
  kms/src/main/java/kms/IamAddMember.java
  kms/src/main/java/kms/IamGetPolicy.java
  kms/src/main/java/kms/IamRemoveMember.java
  kms/src/main/java/kms/Quickstart.java
  kms/src/main/java/kms/RestoreKeyVersion.java
  kms/src/main/java/kms/SignAsymmetric.java
  kms/src/main/java/kms/UpdateKeyAddRotation.java
  kms/src/main/java/kms/UpdateKeyRemoveLabels.java
  kms/src/main/java/kms/UpdateKeySetPrimary.java
  kms/src/main/java/kms/UpdateKeyUpdateLabels.java
  kms/src/main/java/kms/VerifyAsymmetricEc.java
  kms/src/main/java/kms/VerifyAsymmetricRsa.java
  kms/src/test/java/com/example/AsymmetricIT.java
  kms/src/test/java/com/example/CryptFileIT.java
  kms/src/test/java/com/example/QuickstartIT.java
  kms/src/test/java/com/example/SnippetsIT.java
  kms/src/test/java/kms/SnippetsIT.java
Labels: cla: yes, do not merge

#2750 [Container Analysis] effective severity
  container-registry/container-analysis/src/main/java/com/example/containeranalysis/HighVulnerabilitiesForImage.java
  container-registry/container-analysis/src/test/java/com/example/containeranalysis/SamplesTest.java
Labels: cla: yes

#2691 GCF: add http system/integration test sample
  .kokoro/tests/run_tests.sh
  functions/helloworld/hello-http/pom.xml
  functions/helloworld/hello-http/src/test/java/functions/ExampleIntegrationTest.java
  functions/helloworld/hello-http/src/test/java/functions/ExampleSystemTest.java
Labels: cla: yes

#2765 Simplify the `http-form-data` sample and use Java 11 features.
  functions/http/http-form-data/pom.xml
  functions/http/http-form-data/src/main/java/functions/HttpFormData.java
  functions/http/http-form-data/src/test/java/functions/HttpFormDataTest.java
  functions/http/http-form-data/src/test/java/functions/MockHttpPart.java
Labels: cla: yes

#2774 Update renovate.json
  renovate.json
Labels: automerge, cla: yes

#2776 Add connection pooling comment + region tag
  functions/http/send-http-request/src/main/java/functions/SendHttpRequest.java
Labels: automerge, cla: yes

#2726 Add pubsub tests
  functions/helloworld/hello-pub-sub/pom.xml
  functions/helloworld/hello-pub-sub/src/main/java/functions/HelloPubSub.java
  functions/helloworld/hello-pub-sub/src/test/java/functions/ExampleIntegrationTest.java
  functions/helloworld/hello-pub-sub/src/test/java/functions/ExampleSystemTest.java
Labels: cla: yes

#2775 GCF: add storage system tests
  functions/helloworld/hello-gcs/pom.xml
  functions/helloworld/hello-gcs/src/test/java/functions/ExampleIntegrationTest.java
  functions/helloworld/hello-gcs/src/test/java/functions/ExampleSystemTest.java
  functions/helloworld/hello-gcs/src/test/java/functions/HelloGcsTest.java
Labels: automerge, cla: yes

#2734 sample: add Spanner sample for Cloud Functions
  functions/spanner/pom.xml
  functions/spanner/src/main/java/functions/HelloSpanner.java
  functions/spanner/src/test/java/functions/HelloSpannerTest.java
Labels: cla: yes

#2717 Update Secret Manager samples to be canonical
  secretmanager/pom.xml
  secretmanager/src/main/java/secretmanager/AccessSecretVersion.java
  secretmanager/src/main/java/secretmanager/AddSecretVersion.java
  secretmanager/src/main/java/secretmanager/CreateSecret.java
  secretmanager/src/main/java/secretmanager/DeleteSecret.java
  secretmanager/src/main/java/secretmanager/DestroySecretVersion.java
  secretmanager/src/main/java/secretmanager/DisableSecretVersion.java
  secretmanager/src/main/java/secretmanager/EnableSecretVersion.java
  secretmanager/src/main/java/secretmanager/GetSecret.java
  secretmanager/src/main/java/secretmanager/GetSecretVersion.java
  secretmanager/src/main/java/secretmanager/IamGrantAccess.java
  secretmanager/src/main/java/secretmanager/IamRevokeAccess.java
  secretmanager/src/main/java/secretmanager/ListSecretVersions.java
  secretmanager/src/main/java/secretmanager/ListSecrets.java
  secretmanager/src/main/java/secretmanager/Quickstart.java
  secretmanager/src/main/java/secretmanager/UpdateSecret.java
  secretmanager/src/test/java/secretmanager/QuickstartIT.java
  secretmanager/src/test/java/secretmanager/SnippetsIT.java
Labels: cla: yes

#2782 deps: use libraries bom for dependencies
  spanner/cloud-client/pom.xml
  spanner/jdbc/pom.xml
  spanner/leaderboard/complete/pom.xml
  spanner/leaderboard/step4/pom.xml
  spanner/leaderboard/step5/pom.xml
  spanner/leaderboard/step6/pom.xml
Labels: cla: yes

#2785 Create stale.yml
  .github/stale.yml
Labels: automerge

#2768 automl cleanup of unused samples
  language/automl/src/main/java/com/google/cloud/language/samples/DatasetApi.java
  language/automl/src/main/java/com/google/cloud/language/samples/ModelApi.java
  language/automl/src/main/java/com/google/cloud/language/samples/PredictionApi.java
  language/automl/src/test/java/com/google/cloud/language/samples/DatasetApiIT.java
  language/automl/src/test/java/com/google/cloud/language/samples/ModelApiIT.java
  language/automl/src/test/java/com/google/cloud/language/samples/PredictionApiIT.java
Labels: automerge, cla: yes

#2786 deps: use libraries bom for spanner on appengine
  appengine-java11/spanner/pom.xml
  appengine-java8/spanner/pom.xml
Labels: cla: yes

#2719 automl: explictly update timeoutes due to default library changes
  automl/beta/pom.xml
  automl/beta/src/main/java/com/example/automl/ImportDataset.java
  automl/beta/src/test/java/com/example/automl/ImportDatasetTest.java
  automl/beta/src/test/java/com/example/automl/TablesImportDatasetTest.java
  automl/cloud-client/pom.xml
  automl/cloud-client/src/main/java/com/example/automl/ImportDataset.java
  automl/cloud-client/src/test/java/com/example/automl/ImportDatasetTest.java
Labels: cla: yes

#2798 Remove dashes from pubsub and helloworld dir names
  functions/concepts/retry-pubsub/pom.xml
  functions/concepts/retry-pubsub/src/main/java/functions/RetryPubSub.java
  functions/concepts/retry-pubsub/src/main/java/functions/eventpojos/PubSubMessage.java
  functions/concepts/retry-pubsub/src/test/java/functions/RetryPubSubTest.java
  functions/helloworld/groovy-helloworld/pom.xml
  functions/helloworld/groovy-helloworld/src/main/groovy/functions/GroovyHelloWorld.groovy
  functions/helloworld/groovy-helloworld/src/test/java/functions/GroovyHelloWorldTest.java
  functions/helloworld/hello-pubsub/pom.xml
  functions/helloworld/hello-pubsub/src/main/java/functions/HelloPubSub.java
  functions/helloworld/hello-pubsub/src/main/java/functions/eventpojos/PubSubMessage.java
  functions/helloworld/hello-pubsub/src/test/java/functions/ExampleIntegrationTest.java
  functions/helloworld/hello-pubsub/src/test/java/functions/ExampleSystemTest.java
  functions/helloworld/hello-pubsub/src/test/java/functions/HelloPubSubTest.java
  functions/helloworld/helloworld/pom.xml
  functions/helloworld/helloworld/src/main/java/functions/HelloWorld.java
  functions/helloworld/helloworld/src/test/java/functions/HelloWorldTest.java
  functions/helloworld/kotlin-helloworld/pom.xml
  functions/helloworld/kotlin-helloworld/src/main/kotlin/functions/KotlinHelloWorld.kt
  functions/helloworld/kotlin-helloworld/src/test/java/functions/KotlinHelloWorldTest.java
  functions/helloworld/scala-helloworld/pom.xml
  functions/helloworld/scala-helloworld/src/main/scala/functions/ScalaHelloWorld.scala
  functions/helloworld/scala-helloworld/src/test/java/functions/ScalaHelloWorldTest.java
  functions/logging/log-helloworld/pom.xml
  functions/logging/log-helloworld/src/main/java/functions/LogHelloWorld.java
Labels: cla: yes

#2800 Fix region tags
  functions/helloworld/groovy-helloworld/pom.xml
  functions/helloworld/groovy-helloworld/src/main/groovy/functions/GroovyHelloWorld.groovy
  functions/helloworld/kotlin-helloworld/pom.xml
  functions/helloworld/scala-helloworld/pom.xml
Labels: automerge, cla: yes

#2808 Use a PrintWriter to make printf available.
  functions/concepts/file-system/src/main/java/functions/FileSystem.java
Labels: cla: yes

#2799 automl: delete old folder
  language/automl/README.md
  language/automl/pom.xml
  language/automl/resources/input.txt
Labels: cla: yes

#2810 Wrap BufferedWriter in PrintWriter to simplify some code.
  functions/concepts/lazy-fields/src/main/java/functions/LazyFields.java
  functions/concepts/scopes/src/main/java/functions/Scopes.java
  functions/helloworld/hello-http/src/main/java/functions/HelloHttp.java
  functions/http/parse-content-type/src/main/java/functions/ParseContentType.java
  functions/http/send-http-request/src/main/java/functions/SendHttpRequest.java
  functions/logging/retrieve-logs/src/main/java/functions/RetrieveLogs.java
  functions/spanner/src/main/java/functions/HelloSpanner.java
Labels: cla: yes

#2814 Background function: add return statement
  functions/helloworld/hello-pubsub/src/main/java/functions/HelloPubSub.java
Labels: cla: yes
