Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2020-07, with the labels that each got.

#3286 samples: increased wait time for undeployed model prediction
  vision/automl/src/test/java/com/google/cloud/vision/samples/automl/PredictionApiIT.java
Labels: cla: yes

#3300 chore(blunderbuss): Remove kurtisvg@ from issues/prs while OOO
  .github/blunderbuss.yml
Labels: cla: yes

#2868 Update Auth sample to use Google Library
  run/authentication/README.md
  run/authentication/pom.xml
  run/authentication/src/main/java/com/example/cloudrun/Authentication.java
  run/authentication/src/test/java/com/example/cloudrun/AuthenticationTest.java
Labels: cla: yes

#3316 Use correct java flag for Language API readme
  language/cloud-client/README.md
Labels: cla: yes

#3333 healthcare API: fix flaky test
  healthcare/v1/src/main/java/snippets/healthcare/hl7v2/messages/HL7v2MessageList.java
  healthcare/v1/src/test/java/snippets/healthcare/Hl7v2MessageTests.java
Labels: cla: yes

#3331 Added Events for Cloud Run for Anthos samples. Fixes #3330
  run/README.md
  run/events-pubsub/anthos.md
  run/events-storage/anthos.md
Labels: cla: yes

#3332 Fixed validation regular expressions
  dataflow/flex-templates/streaming_beam_sql/Dockerfile
  dataflow/flex-templates/streaming_beam_sql/README.md
  dataflow/flex-templates/streaming_beam_sql/metadata.json
  dataflow/flex-templates/streaming_beam_sql/pom.xml
  dataflow/flex-templates/streaming_beam_sql/src/main/java/org/apache/beam/samples/StreamingBeamSql.java
Labels: cla: yes

#3363 Remove the NEW_BUILD hack for building without tests.
  functions/concepts/env-vars/pom.xml
  functions/concepts/execution-count/pom.xml
  functions/concepts/file-system/pom.xml
  functions/concepts/lazy-fields/pom.xml
  functions/concepts/retry-pubsub/pom.xml
  functions/concepts/retry-timeout/pom.xml
  functions/concepts/scopes/pom.xml
  functions/firebase/auth/pom.xml
  functions/firebase/firestore-reactive/pom.xml
  functions/firebase/firestore/pom.xml
  functions/firebase/remote-config/pom.xml
  functions/firebase/rtdb/pom.xml
  functions/helloworld/groovy-hello-pubsub/pom.xml
  functions/helloworld/groovy-helloworld/pom.xml
  functions/helloworld/hello-error/pom.xml
  functions/helloworld/hello-gcs-generic/pom.xml
  functions/helloworld/hello-gcs/pom.xml
  functions/helloworld/hello-http/pom.xml
  functions/helloworld/hello-pubsub/pom.xml
  functions/helloworld/helloworld/pom.xml
  functions/helloworld/kotlin-hello-pubsub/pom.xml
  functions/helloworld/kotlin-helloworld/pom.xml
  functions/helloworld/scala-hello-pubsub/pom.xml
  functions/helloworld/scala-helloworld/pom.xml
  functions/http/bearer-token-http/pom.xml
  functions/http/cors-enabled-auth/pom.xml
  functions/http/cors-enabled/pom.xml
  functions/http/http-form-data/pom.xml
  functions/http/http-method/pom.xml
  functions/http/parse-content-type/pom.xml
  functions/http/send-http-request/pom.xml
  functions/imagemagick/pom.xml
  functions/logging/log-helloworld/pom.xml
  functions/logging/retrieve-logs/pom.xml
  functions/logging/stackdriver-logging/pom.xml
  functions/ocr/ocr-process-image/pom.xml
  functions/ocr/ocr-save-result/pom.xml
  functions/ocr/ocr-translate-text/pom.xml
  functions/pubsub/publish-message/pom.xml
  functions/pubsub/subscribe-to-topic/pom.xml
  functions/slack/pom.xml
  functions/spanner/pom.xml
Labels: cla: yes

#3362 Add a simple example of a function built using Gradle.
  functions/helloworld/hello-http-gradle/build.gradle
  functions/helloworld/hello-http-gradle/gradle/wrapper/gradle-wrapper.jar
  functions/helloworld/hello-http-gradle/gradle/wrapper/gradle-wrapper.properties
  functions/helloworld/hello-http-gradle/gradlew
  functions/helloworld/hello-http-gradle/gradlew.bat
  functions/helloworld/hello-http-gradle/settings.gradle
  functions/helloworld/hello-http-gradle/src/main/java/functions/HelloHttp.java
  functions/helloworld/hello-http-gradle/src/test/java/functions/HelloHttpTest.java
Labels: cla: yes

#3370 functions: add after-timeout sample
  functions/concepts/after-timeout/pom.xml
  functions/concepts/after-timeout/src/main/java/functions/AfterTimeout.java
Labels: cla: yes

#3368 functions: remove redundant GCS sample
  functions/helloworld/hello-gcs-generic/pom.xml
  functions/helloworld/hello-gcs-generic/src/main/java/functions/HelloGcsGeneric.java
  functions/helloworld/hello-gcs-generic/src/main/java/functions/eventpojos/GcsEvent.java
  functions/helloworld/hello-gcs-generic/src/test/java/functions/HelloGcsGenericTest.java
  functions/helloworld/hello-gcs-generic/src/test/java/functions/eventpojos/MockContext.java
  functions/helloworld/hello-gcs/src/main/java/functions/HelloGcs.java
  functions/helloworld/hello-gcs/src/test/java/functions/ExampleIntegrationTest.java
  functions/helloworld/hello-gcs/src/test/java/functions/ExampleSystemTest.java
  functions/helloworld/hello-gcs/src/test/java/functions/HelloGcsTest.java
Labels: cla: yes, do not merge

#3393 samples: fixed automl cancel operation bug
  automl/beta/src/test/java/com/example/automl/CancelOperationTest.java
Labels: cla: yes

#3401 Fix minimum Maven version errors
  appengine-java8/bigtable/pom.xml
  appengine-java8/endpoints-v2-backend/pom.xml
  appengine-java8/endpoints-v2-guice/pom.xml
  appengine-java8/endpoints-v2-migration/pom.xml
  appengine-java8/springboot-helloworld/pom.xml
Labels: automerge, cla: yes

#3402 remove unused parameter
  logging/cloud-client/pom.xml
  logging/cloud-client/src/main/java/com/example/logging/ListLogs.java
  logging/cloud-client/src/test/java/com/example/logging/LoggingIT.java
Labels: automerge, cla: yes

#3410 Adjust region tags for Gradle functions sample.
  functions/helloworld/hello-http-gradle/build.gradle
  functions/helloworld/hello-http-gradle/src/main/java/functions/HelloHttp.java
Labels: cla: yes

#3412 chore(functions): fix gradle formatting issue
  functions/helloworld/hello-http-gradle/build.gradle
Labels: automerge, cla: yes

#3418 Helloworld with Gradle
  .gitignore
  functions/helloworld/helloworld-gradle/build.gradle
  functions/helloworld/helloworld-gradle/gradle/wrapper/gradle-wrapper.properties
  functions/helloworld/helloworld-gradle/gradlew
  functions/helloworld/helloworld-gradle/gradlew.bat
  functions/helloworld/helloworld-gradle/src/main/java/functions/HelloWorld.java
  functions/helloworld/helloworld-gradle/src/test/java/functions/HelloWorldTest.java
Labels: cla: yes

#3432 Update renovate.json for Apache Beam packages
  renovate.json
Labels: cla: yes

#3429 docs: add samples for async api
  spanner/cloud-client/pom.xml
  spanner/cloud-client/src/main/java/com/example/spanner/AsyncDmlExample.java
  spanner/cloud-client/src/main/java/com/example/spanner/AsyncQueryExample.java
  spanner/cloud-client/src/main/java/com/example/spanner/AsyncQueryToListAsyncExample.java
  spanner/cloud-client/src/main/java/com/example/spanner/AsyncReadExample.java
  spanner/cloud-client/src/main/java/com/example/spanner/AsyncReadOnlyTransactionExample.java
  spanner/cloud-client/src/main/java/com/example/spanner/AsyncReadRowExample.java
  spanner/cloud-client/src/main/java/com/example/spanner/AsyncReadUsingIndexExample.java
  spanner/cloud-client/src/main/java/com/example/spanner/AsyncRunnerExample.java
  spanner/cloud-client/src/main/java/com/example/spanner/AsyncTransactionManagerExample.java
  spanner/cloud-client/src/test/java/com/example/spanner/AsyncExamplesIT.java
Labels: api: spanner, cla: yes

#3440 Fix lint errors
  dataflow/encryption-keys/pom.xml
  dataflow/encryption-keys/src/main/java/com/example/dataflow/cmek/BigQueryKmsKey.java
  dataflow/flex-templates/kafka_to_bigquery/pom.xml
  dataflow/flex-templates/kafka_to_bigquery/src/main/java/org/apache/beam/samples/KafkaToBigQuery.java
  dataflow/templates/pom.xml
  dataflow/templates/src/main/java/com/example/dataflow/templates/WordCount.java
Labels: automerge, cla: yes

#3441 Pub/Sub: add shared-config and fix lint
  pubsub/streaming-analytics/README.md
  pubsub/streaming-analytics/pom.xml
  pubsub/streaming-analytics/src/main/java/com/examples/pubsub/streaming/PubSubToGcs.java
Labels: cla: yes

#3443 Update token creation for Cloud Run Markdown sample
  run/markdown-preview/editor/pom.xml
  run/markdown-preview/editor/src/main/java/com/example/cloudrun/RenderController.java
Labels: cla: yes

#3408 Add sample code for Cloud Assets Inventory ListAssets v1p5beta1 APIs.
  asset/cloud-client/src/main/java/com/example/asset/ListAssetsExample.java
  asset/cloud-client/src/test/java/com/example/asset/ListAssets.java
Labels: cla: yes, do not merge

#3438 samples: fix flaky video stream and text Detection tests
  video/beta/src/main/java/com/example/video/StreamingAutoMlClassification.java
  video/beta/src/main/java/com/example/video/TextDetection.java
  video/beta/src/test/java/com/example/video/DetectIT.java
  video/beta/src/test/java/com/example/video/StreamingAutoMlClassificationIT.java
Labels: cla: yes
