Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2020-03, with the labels that each got.

#2286 fix: flaky tests in speech
  speech/beta/src/test/java/com/example/speech/RecognizeIT.java
Labels: cla: yes

#2159 automl: move beta samples from branch to master
  automl/beta/pom.xml
  automl/beta/src/main/java/com/example/automl/DeployModel.java
  automl/beta/src/main/java/com/example/automl/ListDatasets.java
  automl/beta/src/main/java/com/example/automl/ListModelEvaluations.java
  automl/beta/src/main/java/com/example/automl/TablesBatchPredictBigQuery.java
  automl/beta/src/main/java/com/example/automl/TablesCreateDataset.java
  automl/beta/src/main/java/com/example/automl/TablesCreateModel.java
  automl/beta/src/main/java/com/example/automl/TablesImportDataset.java
  automl/beta/src/main/java/com/example/automl/TablesPredict.java
  automl/beta/src/main/java/com/example/automl/UndeployModel.java
  automl/beta/src/test/java/com/example/automl/DeployModelTest.java
  automl/beta/src/test/java/com/example/automl/ListModelEvaluationsTest.java
  automl/beta/src/test/java/com/example/automl/TablesBatchPredictBigQueryTest.java
  automl/beta/src/test/java/com/example/automl/TablesCreateDatasetTest.java
  automl/beta/src/test/java/com/example/automl/TablesCreateModelTest.java
  automl/beta/src/test/java/com/example/automl/TablesImportDatasetTest.java
  automl/beta/src/test/java/com/example/automl/TablesPredictTest.java
  automl/beta/src/test/java/com/example/automl/UndeployModelTest.java
Labels: cla: yes

#2298 vision: move samples out of branch
  vision/cloud-client/resources/kafka.pdf
  vision/cloud-client/src/main/java/com/example/vision/BatchAnnotateFiles.java
  vision/cloud-client/src/main/java/com/example/vision/BatchAnnotateFilesGcs.java
  vision/cloud-client/src/test/java/com/example/vision/BatchAnnotateFilesGcsTest.java
  vision/cloud-client/src/test/java/com/example/vision/BatchAnnotateFilesTest.java
Labels: cla: yes

#2299 [Cloud Run] Add jib plugin to hello world
  run/helloworld/pom.xml
Labels: cla: yes

#2297 vision: move samples out of branch and add clarifying comments
  vision/cloud-client/src/main/java/com/example/vision/AsyncBatchAnnotateImages.java
  vision/cloud-client/src/test/java/com/example/vision/AsyncBatchAnnotateImagesTest.java
Labels: automerge, cla: yes

#2301 automl: move video object tracking samples out of branch
  automl/beta/src/main/java/com/example/automl/GetModelEvaluation.java
  automl/beta/src/main/java/com/example/automl/ListDatasets.java
  automl/beta/src/main/java/com/example/automl/VideoObjectTrackingCreateDataset.java
  automl/beta/src/main/java/com/example/automl/VideoObjectTrackingCreateModel.java
  automl/beta/src/test/java/com/example/automl/VideoObjectTrackingCreateDatasetTest.java
  automl/beta/src/test/java/com/example/automl/VideoObjectTrackingCreateModelTest.java
Labels: automerge, cla: yes

#2300 video: move samples out of branch
  video/beta/src/main/java/com/example/video/DetectLogo.java
  video/beta/src/main/java/com/example/video/DetectLogoGcs.java
  video/beta/src/test/java/com/example/video/DetectLogoGcsTest.java
  video/beta/src/test/java/com/example/video/DetectLogoTest.java
Labels: automerge, cla: yes

#2312 fix: region tag
  vision/cloud-client/src/main/java/com/example/vision/BatchAnnotateFilesGcs.java
Labels: automerge, cla: yes

#2290 Revert "chore: switch to built-in code review assignment"
  .github/blunderbuss.yml
Labels: cla: yes, do not merge

#2315 chore: update bigquerystorage example to use V1 bindings
  bigquery/bigquerystorage/pom.xml
  bigquery/bigquerystorage/src/main/java/com/example/bigquerystorage/StorageArrowSample.java
  bigquery/bigquerystorage/src/main/java/com/example/bigquerystorage/StorageSample.java
Labels: automerge, cla: yes

#2310 Updated SecretManager version v1beta1->v1
  secretmanager/src/main/java/com/example/AccessSecretVersion.java
  secretmanager/src/main/java/com/example/AddSecretVersion.java
  secretmanager/src/main/java/com/example/CreateSecret.java
  secretmanager/src/main/java/com/example/DeleteSecret.java
  secretmanager/src/main/java/com/example/DestroySecretVersion.java
  secretmanager/src/main/java/com/example/DisableSecretVersion.java
  secretmanager/src/main/java/com/example/EnableSecretVersion.java
  secretmanager/src/main/java/com/example/GetSecret.java
  secretmanager/src/main/java/com/example/GetSecretVersion.java
  secretmanager/src/main/java/com/example/IamGrantAccess.java
  secretmanager/src/main/java/com/example/IamRevokeAccess.java
  secretmanager/src/main/java/com/example/ListSecretVersions.java
  secretmanager/src/main/java/com/example/ListSecrets.java
  secretmanager/src/main/java/com/example/Quickstart.java
  secretmanager/src/main/java/com/example/UpdateSecret.java
  secretmanager/src/test/java/com/example/QuickstartIT.java
  secretmanager/src/test/java/com/example/SnippetsIT.java
Labels: automerge, cla: yes

#2324 speech: move samples out of branch
  speech/beta/src/main/java/com/example/speech/SpeechAdaptation.java
  speech/beta/src/test/java/com/example/speech/SpeechAdaptationTest.java
Labels: automerge, cla: yes

#2325 automl: move samples out of branch
  automl/beta/src/main/java/com/example/automl/GetOperationStatus.java
  automl/beta/src/test/java/com/example/automl/GetOperationStatusTest.java
Labels: automerge, cla: yes

#2350 Update renovate to use new "rebaseWhen" flag.
  renovate.json
Labels: cla: yes

#2359 Fix flaky DLP inspect tests
  dlp/src/main/java/dlp/snippets/InspectBigQueryTable.java
  dlp/src/main/java/dlp/snippets/InspectDatastoreEntity.java
  dlp/src/main/java/dlp/snippets/InspectGcsFile.java
Labels: cla: yes

#2377 automl: update error check due to changes
  automl/beta/src/test/java/com/example/automl/BatchPredictTest.java
  automl/cloud-client/src/test/java/com/example/automl/BatchPredictTest.java
Labels: cla: yes

#2378 vision: update product search tests
  vision/product-search/cloud-client/src/test/java/com/example/vision/ProductSetManagementIT.java
  vision/product-search/cloud-client/src/test/java/vision/snippets/ProductInProductSetManagementTests.java
  vision/product-search/cloud-client/src/test/java/vision/snippets/ProductManagementTests.java
Labels: cla: yes

#2376 video: fix flaky tests
  video/beta/src/test/java/com/example/video/DetectFacesGcsIT.java
  video/beta/src/test/java/com/example/video/DetectFacesIT.java
  video/beta/src/test/java/com/example/video/DetectPersonGcsIT.java
  video/beta/src/test/java/com/example/video/DetectPersonIT.java
Labels: automerge, cla: yes

#2389 docs: Update securitycenter samples to v1
  securitycenter/src/main/java/com/google/cloud/examples/securitycenter/snippets/CreateNotificationConfigSnippets.java
  securitycenter/src/main/java/com/google/cloud/examples/securitycenter/snippets/DeleteNotificationConfigSnippets.java
  securitycenter/src/main/java/com/google/cloud/examples/securitycenter/snippets/GetNotificationConfigSnippets.java
  securitycenter/src/main/java/com/google/cloud/examples/securitycenter/snippets/ListNotificationConfigSnippets.java
  securitycenter/src/main/java/com/google/cloud/examples/securitycenter/snippets/NotificationReceiver.java
  securitycenter/src/main/java/com/google/cloud/examples/securitycenter/snippets/UpdateNotificationConfigSnippets.java
Labels: cla: yes

#2411 fix: SampleTests: customAttributeSampleTest
  jobs/v3/src/test/java/SampleTests.java
Labels: cla: yes

#2415 fix: Upgrade Spanner samples to OpenCensus 0.25.0
  spanner/cloud-client/pom.xml
Labels: automerge, cla: yes

#2421 Re-add dzlier to blunderbuss
  .github/blunderbuss.yml
Labels: automerge, cla: yes

#2425 Fix recommender dependency update.
  recommender/beta/cloud-client/pom.xml
Labels: cla: yes

#2427 Remove references to deprecated class CryptoKeyName.
  kms/src/main/java/com/example/CryptFile.java
  kms/src/main/java/com/example/Snippets.java
Labels: cla: yes

#2435 Let's let OpenCensus update together...
  renovate.json
Labels: automerge, cla: yes

#2444 Correct path to task queues sample.
  appengine-java8/taskqueues-push/src/main/java/com/example/appengine/taskqueue/push/Enqueue.java
Labels: cla: yes

#2448 Correct error message for unset GOOGLE_CLOUD_PROJECT.
  spanner/cloud-client/src/main/java/com/example/spanner/SpannerSample.java
Labels: cla: yes

#2442 Maven GAE plugin config updates
  cloud-sql/mysql/servlet/README.md
  cloud-sql/mysql/servlet/pom.xml
  cloud-sql/postgres/servlet/README.md
  cloud-sql/postgres/servlet/pom.xml
  memorystore/redis/pom.xml
  storage/cloud-client/pom.xml
  storage/json-api/pom.xml
  storage/s3-sdk/pom.xml
  storage/s3-sdk/src/main/java/ListGcsBuckets.java
  storage/s3-sdk/src/main/java/ListGcsObjects.java
  storage/s3-sdk/src/test/java/ListGcsBucketsTest.java
  storage/s3-sdk/src/test/java/ListGcsObjectsTest.java
  storage/storage-transfer/pom.xml
  storage/xml-api/cmdline-sample/pom.xml
  storage/xml-api/cmdline-sample/src/main/java/StorageSample.java
  storage/xml-api/serviceaccount-appengine-sample/README.md
  storage/xml-api/serviceaccount-appengine-sample/pom.xml
  storage/xml-api/serviceaccount-appengine-sample/src/main/java/com/google/api/client/sample/storage/appengine/serviceaccount/StorageSample.java
  unittests/pom.xml
Labels: automerge, cla: yes

#2441 Update Maven config GAE 11
  appengine-java11/appengine-simple-jetty-main/pom.xml
  appengine-java11/cloudsql/README.md
  appengine-java11/cloudsql/pom.xml
  appengine-java11/gaeinfo/README.md
  appengine-java11/gaeinfo/pom.xml
  appengine-java11/guestbook-cloud-firestore/README.md
  appengine-java11/guestbook-cloud-firestore/pom.xml
  appengine-java11/helloworld-servlet/README.md
  appengine-java11/helloworld-servlet/pom.xml
  appengine-java11/http-server/README.md
  appengine-java11/http-server/pom.xml
  appengine-java11/kotlin-ktor/README.md
  appengine-java11/kotlin-ktor/pom.xml
  appengine-java11/micronaut-helloworld/README.md
  appengine-java11/micronaut-helloworld/pom.xml
  appengine-java11/oauth2/README.md
  appengine-java11/oauth2/pom.xml
  appengine-java11/quarkus-helloworld/README.md
  appengine-java11/quarkus-helloworld/pom.xml
  appengine-java11/spanner/README.md
  appengine-java11/spanner/pom.xml
  appengine-java11/sparkjava-helloworld/README.md
  appengine-java11/sparkjava-helloworld/pom.xml
  appengine-java11/springboot-helloworld/README.md
  appengine-java11/springboot-helloworld/pom.xml
  appengine-java11/tasks-handler/pom.xml
  appengine-java11/tasks/README.md
  appengine-java11/tasks/pom.xml
  appengine-java11/vertx-helloworld/README.md
  appengine-java11/vertx-helloworld/pom.xml
Labels: automerge, cla: yes

#2447 Fix Flaky DLP tests
  dlp/src/test/java/dlp/snippets/InspectTests.java
Labels: cla: yes

#2394 GCF: Add Slack sample + clean up imports
  .kokoro/tests/run_tests.sh
  functions/snippets/.gcloudignore
  functions/snippets/pom.xml
  functions/snippets/src/main/java/com/example/functions/SlackSlashCommand.java
  functions/snippets/src/test/java/com/example/functions/SlackSlashCommandTest.java
  functions/snippets/src/test/java/com/example/functions/SnippetsTests.java
Labels: cla: yes

#2422 functions/logging: add stdout/stderr + ignored logs severity note
  functions/snippets/src/main/java/com/example/functions/LogHelloWorld.java
  functions/snippets/src/test/java/com/example/functions/SnippetsTests.java
Labels: automerge, cla: yes

#2475 vision: makes tests more generic
  vision/cloud-client/src/test/java/com/example/vision/DetectIT.java
Labels: automerge, cla: yes

#2373 dataflow/flex-templates: Add Streaming BeamSQL and Kafka-to-BigQuery samples
  dataflow/README.md
  dataflow/flex-templates/README.md
  dataflow/flex-templates/kafka_to_bigquery/.gcloudignore
  dataflow/flex-templates/kafka_to_bigquery/Dockerfile
  dataflow/flex-templates/kafka_to_bigquery/README.md
  dataflow/flex-templates/kafka_to_bigquery/kafka/Dockerfile
  dataflow/flex-templates/kafka_to_bigquery/kafka/create-topic.sh
  dataflow/flex-templates/kafka_to_bigquery/kafka/start-kafka.sh
  dataflow/flex-templates/kafka_to_bigquery/metadata.json
  dataflow/flex-templates/kafka_to_bigquery/pom.xml
  dataflow/flex-templates/kafka_to_bigquery/src/main/java/org/apache/beam/samples/KafkaToBigQuery.java
  dataflow/flex-templates/streaming_beam_sql/.gcloudignore
  dataflow/flex-templates/streaming_beam_sql/Dockerfile
  dataflow/flex-templates/streaming_beam_sql/README.md
  dataflow/flex-templates/streaming_beam_sql/metadata.json
  dataflow/flex-templates/streaming_beam_sql/pom.xml
  dataflow/flex-templates/streaming_beam_sql/src/main/java/org/apache/beam/samples/StreamingBeamSQL.java
  dataflow/templates/README.md
Labels: cla: yes

#2393 Adding GA samples for Logo detection
  video/cloud-client/src/main/java/com/example/video/LogoDetection.java
  video/cloud-client/src/main/java/com/example/video/LogoDetectionGcs.java
  video/cloud-client/src/test/java/com/example/video/DetectIT.java
  video/cloud-client/src/test/java/com/example/video/DetectLogoGcsTest.java
  video/cloud-client/src/test/java/com/example/video/DetectLogoTest.java
Labels: automerge, cla: yes

#2360 feat: dataproc instantiate inline workflow sample
  dataproc/src/main/java/InstantiateInlineWorkflowTemplate.java
  dataproc/src/test/java/InstantiateInlineWorkflowTemplateTest.java
Labels: cla: yes

#2445 Update GAE Maven Plugin for GAE Flex
  flexible/README.md
  flexible/analytics/pom.xml
  flexible/async-rest/README.md
  flexible/async-rest/pom.xml
  flexible/async-rest/src/main/java/com/google/appengine/demos/asyncrest/SerialRestServlet.java
  flexible/cloudsql/README.md
  flexible/cloudsql/pom.xml
  flexible/cloudsql/src/main/java/com/example/cloudsql/CloudSqlServlet.java
  flexible/cloudstorage/README.md
  flexible/cloudstorage/pom.xml
  flexible/cloudstorage/src/main/java/com/example/cloudstorage/UploadServlet.java
  flexible/cron/README.md
  flexible/cron/pom.xml
  flexible/cron/src/main/java/com/example/cron/CronServlet.java
  flexible/datastore/pom.xml
  flexible/datastore/src/main/java/com/example/datastore/DatastoreServlet.java
  flexible/disk/pom.xml
  flexible/disk/src/main/java/com/example/disk/DiskServlet.java
  flexible/errorreporting/README.md
  flexible/errorreporting/pom.xml
  flexible/errorreporting/src/main/java/com/example/flexible/errorreporting/ErrorReportingExample.java
  flexible/extending-runtime/pom.xml
  flexible/extending-runtime/src/main/java/com/example/extendingruntime/FortuneServlet.java
  flexible/gaeinfo/README.md
  flexible/gaeinfo/pom.xml
  flexible/gaeinfo/src/main/java/com/example/appengine/flex_compat/GaeInfoServlet.java
  flexible/helloworld-springboot/pom.xml
  flexible/helloworld/README.md
  flexible/helloworld/pom.xml
  flexible/helloworld/src/main/java/com/example/flexible/helloworld/HelloServlet.java
  flexible/mailgun/README.md
  flexible/mailgun/pom.xml
  flexible/mailgun/src/main/java/com/example/mailgun/MailgunServlet.java
  flexible/mailjet/README.md
  flexible/mailjet/pom.xml
  flexible/memcache/pom.xml
  flexible/postgres/README.md
  flexible/postgres/pom.xml
  flexible/postgres/src/main/java/com/example/postgres/PostgresSqlServlet.java
  flexible/pubsub/README.md
  flexible/pubsub/pom.xml
  flexible/sendgrid/pom.xml
  flexible/sendgrid/src/main/java/com/example/sendgrid/SendEmailServlet.java
  flexible/sparkjava/README.md
  flexible/sparkjava/jenkins.sh
  flexible/sparkjava/pom.xml
  flexible/static-files/pom.xml
  flexible/twilio/pom.xml
Labels: automerge, cla: yes

#2413 GCF: retries samples
  functions/snippets/src/main/java/com/example/functions/InfiniteRetryPubSub.java
  functions/snippets/src/main/java/com/example/functions/RetryPubSub.java
  functions/snippets/src/test/java/com/example/functions/SnippetsTests.java
Labels: automerge, cla: yes

#2323 feat: add QueryOptions to Spanner samples
  spanner/cloud-client/pom.xml
  spanner/cloud-client/src/main/java/com/example/spanner/SpannerSample.java
  spanner/cloud-client/src/test/java/com/example/spanner/SpannerSampleIT.java
Labels: api: spanner, automerge, cla: yes

#2486 GCF Slack: add javadoc + region tags
  functions/snippets/src/main/java/com/example/functions/SlackSlashCommand.java
Labels: automerge, cla: yes

#2485 Add GCF JVM language samples (Kotlin/Scala/Groovy)
  functions/snippets/pom.xml
  functions/snippets/src/main/groovy/com/example/functions/GroovyHelloBackground.groovy
  functions/snippets/src/main/groovy/com/example/functions/GroovyHelloWorld.groovy
  functions/snippets/src/main/java/com/example/functions/ScalaHelloBackground.scala
  functions/snippets/src/main/java/com/example/functions/ScalaHelloWorld.scala
  functions/snippets/src/main/kotlin/com/example/functions/KotlinHelloBackground.kt
  functions/snippets/src/main/kotlin/com/example/functions/KotlinHelloWorld.kt
  functions/snippets/src/test/java/com/example/functions/GroovyTests.java
  functions/snippets/src/test/java/com/example/functions/HelloGcsTest.java
  functions/snippets/src/test/java/com/example/functions/KotlinTests.java
  functions/snippets/src/test/java/com/example/functions/MockContext.java
  functions/snippets/src/test/java/com/example/functions/ScalaTests.java
Labels: automerge, cla: yes

#2347 feat: add QueryOptions samples for JDBC
  spanner/jdbc/README.md
  spanner/jdbc/pom.xml
  spanner/jdbc/src/main/java/com/example/spanner/JdbcSample.java
  spanner/jdbc/src/test/java/com/example/spanner/JdbcSampleIT.java
Labels: api: spanner, cla: yes

#2500 Revert "Update Bigtable+Beam hello world examples and move them into java-docs-samples"
  bigtable/beam/helloworld/pom.xml
  bigtable/beam/helloworld/src/main/java/HelloWorldRead.java
  bigtable/beam/helloworld/src/main/java/HelloWorldWrite.java
  bigtable/beam/helloworld/src/test/java/HelloWorldTest.java
Labels: cla: yes

#2502 docs: update tests that are failing or not cleaning up resources
  translate/cloud-client/src/main/java/com/example/translate/BatchTranslateText.java
  translate/cloud-client/src/main/java/com/example/translate/BatchTranslateTextWithGlossary.java
  translate/cloud-client/src/main/java/com/example/translate/BatchTranslateTextWithGlossaryAndModel.java
  translate/cloud-client/src/main/java/com/example/translate/BatchTranslateTextWithModel.java
  vision/automl/src/test/java/com/google/cloud/vision/samples/automl/PredictionApiIT.java
  vision/beta/cloud-client/src/test/java/com/example/vision/DetectIT.java
Labels: cla: yes

#2503 Update Bigtable+Beam hello world examples and move them into java-docs-samples
  bigtable/beam/helloworld/pom.xml
  bigtable/beam/helloworld/src/main/java/HelloWorldRead.java
  bigtable/beam/helloworld/src/main/java/HelloWorldWrite.java
  bigtable/beam/helloworld/src/test/java/HelloWorldTest.java
Labels: automerge, cla: yes

#2504 Update Guidelines
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  SAMPLE_FORMAT.md
Labels: automerge, cla: yes

#2512 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla: yes

#2514 Fix 2 URL's
  SAMPLE_FORMAT.md
Labels: automerge, cla: yes

#2487 feat: add backups samples
  spanner/cloud-client/src/main/java/com/example/spanner/SpannerSample.java
  spanner/cloud-client/src/test/java/com/example/spanner/SpannerSampleIT.java
Labels: automerge, cla: yes

#2525 Move Websocket Samples to flexible folder
  flexible/websocket-jetty/README.md
  flexible/websocket-jetty/pom.xml
  flexible/websocket-jetty/src/main/appengine/app.yaml
  flexible/websocket-jetty/src/main/java/com/example/flexible/websocket/jettynative/ClientSocket.java
  flexible/websocket-jetty/src/main/java/com/example/flexible/websocket/jettynative/EchoServlet.java
  flexible/websocket-jetty/src/main/java/com/example/flexible/websocket/jettynative/SendServlet.java
  flexible/websocket-jetty/src/main/java/com/example/flexible/websocket/jettynative/ServerSocket.java
  flexible/websocket-jetty/src/main/webapp/WEB-INF/jetty-web.xml
  flexible/websocket-jetty/src/main/webapp/index.jsp
  flexible/websocket-jetty/src/main/webapp/js_client.jsp
  flexible/websocket-jsr356/README.md
  flexible/websocket-jsr356/pom.xml
  flexible/websocket-jsr356/src/main/appengine/app.yaml
  flexible/websocket-jsr356/src/main/java/com/example/flexible/websocket/jsr356/ClientSocket.java
  flexible/websocket-jsr356/src/main/java/com/example/flexible/websocket/jsr356/SendServlet.java
  flexible/websocket-jsr356/src/main/java/com/example/flexible/websocket/jsr356/ServerSocket.java
  flexible/websocket-jsr356/src/main/webapp/index.jsp
  flexible/websocket-jsr356/src/main/webapp/js_client.jsp
Labels: cla: yes

#2529 Use consistent region tag across all JVM samples
  functions/snippets/src/main/groovy/com/example/functions/GroovyHelloBackground.groovy
  functions/snippets/src/main/kotlin/com/example/functions/KotlinHelloBackground.kt
  functions/snippets/src/main/kotlin/com/example/functions/KotlinHelloWorld.kt
Labels: automerge, cla: yes

#2528 Micronaut sample updates
  appengine-java11/micronaut-helloworld/pom.xml
Labels: automerge, cla: yes

#2531 Add missing helloworld samples + delete excess logging code
  functions/snippets/src/main/java/com/example/functions/GcsEvent.java
  functions/snippets/src/main/java/com/example/functions/HelloError.java
  functions/snippets/src/main/java/com/example/functions/HelloGcsGeneric.java
  functions/snippets/src/main/java/com/example/functions/HelloMethod.java
  functions/snippets/src/test/java/com/example/functions/SnippetsTests.java
Labels: cla: yes

#2530 Update springboot flexible app
  flexible/helloworld-springboot/pom.xml
Labels: automerge, cla: yes

#2532 fix: changed template tag
  dataproc/src/main/java/InstantiateInlineWorkflowTemplate.java
Labels: cla: yes

#2542 upgrade protobuf-gradle-plugin to 0.8.8
  endpoints/getting-started-grpc/api/build.gradle
Labels: cla: yes

#2543 Create build.gradle
  build.gradle
Labels: automerge, cla: yes
