Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2020-11, with the labels that each got.

#4119 chore: remove call to deprecated method
  functions/spanner/src/test/java/functions/HelloSpannerTest.java
Labels: cla: yes

#4127 chore: added UIID to prevent concurrency error
  iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java
Labels: automerge, cla: yes

#4134 chore(bigtable): spark deps cleanup and readme updates
  bigtable/spark/README.md
  bigtable/spark/build.sbt
Labels: api: bigtable, cla: yes

#3406 Cloud Run + Cloud Endpoints
  run/endpoints-v2-backend/README.md
  run/endpoints-v2-backend/openapi-run.yaml
  run/endpoints-v2-backend/pom.xml
  run/endpoints-v2-backend/src/main/java/com/example/endpoints/EndpointsApplication.java
  run/endpoints-v2-backend/src/main/java/com/example/endpoints/controllers/RepeatController.java
  run/endpoints-v2-backend/src/main/resources/application.yml
  run/endpoints-v2-backend/src/test/java/com/example/controllers/RepeatControllerIT.java
  run/endpoints-v2-backend/src/test/java/com/example/controllers/RepeatControllerTest.java
Labels: automerge, cla: yes, samples

#4180 Update README.md
  README.md
Labels: automerge, cla: yes

#4181 New region tags for Cloud Run
  run/authentication/src/main/java/com/example/cloudrun/Authentication.java
  run/hello-broken/pom.xml
  run/hello-broken/src/main/java/com/example/cloudrun/App.java
  run/helloworld/Dockerfile
  run/helloworld/pom.xml
  run/helloworld/src/main/java/com/example/helloworld/HelloworldApplication.java
  run/helloworld/src/main/resources/application.properties
  run/image-processing/Dockerfile
  run/image-processing/pom.xml
  run/image-processing/src/main/java/com/example/cloudrun/ImageMagick.java
  run/image-processing/src/main/java/com/example/cloudrun/PubSubController.java
  run/logging-manual/pom.xml
  run/logging-manual/src/main/java/com/example/cloudrun/App.java
  run/logging-manual/src/main/resources/logback.xml
  run/markdown-preview/editor/src/main/java/com/example/cloudrun/RenderController.java
  run/pubsub/pom.xml
  run/pubsub/src/main/java/com/example/cloudrun/PubSubApplication.java
  run/pubsub/src/main/java/com/example/cloudrun/PubSubController.java
  run/system-package/Dockerfile
  run/system-package/pom.xml
  run/system-package/src/main/java/com/example/cloudrun/App.java
Labels: cla: yes

#4178 test: auto-throttle admin requests
  spanner/cloud-client/src/main/java/com/example/spanner/SpannerSample.java
  spanner/cloud-client/src/test/java/com/example/spanner/AsyncExamplesIT.java
  spanner/cloud-client/src/test/java/com/example/spanner/SpannerSampleIT.java
  spanner/cloud-client/src/test/java/com/example/spanner/SpannerStandaloneExamplesIT.java
Labels: cla: yes

#4192 samples(functions): Add "specify function" tag
  functions/helloworld/helloworld-gradle/build.gradle
  functions/helloworld/helloworld/pom.xml
Labels: api: cloudfunctions, automerge, cla: yes

#4193 chore: add blunderbuss config for logging
  .github/blunderbuss.yml
Labels: cla: yes

#4133 test: delete stale test databases
  spanner/cloud-client/src/test/java/com/example/spanner/SpannerSampleIT.java
  spanner/cloud-client/src/test/java/com/example/spanner/SpannerStandaloneExamplesIT.java
Labels: cla: yes

#4196 Update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#4197 feat: use LazySpannerInitializer instead of DCL
  functions/spanner/src/main/java/functions/HelloSpanner.java
Labels: cla: yes

#4202 Example: Replace wrong PostgreSQL mention in comment
  cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java
Labels: cla: yes

#4208 update Cloud Run region tags
  functions/concepts/lazy-fields/src/main/java/functions/LazyFields.java
  functions/concepts/scopes/src/main/java/functions/Scopes.java
  run/image-processing/pom.xml
Labels: automerge, cla: yes

#4262 test(bigtable_spark): update integration test, update deps and readme
  bigtable/spark/README.md
  bigtable/spark/build.sbt
  bigtable/spark/src/test/scala/example/IntegrationTest.scala
Labels: api: bigtable, cla: yes, samples

#4283 healthcare API: add ascending order to DICOMweb tests
  healthcare/v1/src/test/java/snippets/healthcare/DicomWebTests.java
Labels: cla: yes, samples

#4286 feat(kms): add integrity verification to samples of crypto operations
  kms/pom.xml
  kms/src/main/java/kms/DecryptAsymmetric.java
  kms/src/main/java/kms/DecryptSymmetric.java
  kms/src/main/java/kms/EncryptSymmetric.java
  kms/src/main/java/kms/GetPublicKey.java
  kms/src/main/java/kms/SignAsymmetric.java
Labels: api: cloudkms, cla: yes, samples
