Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2021-07, with the labels that each got.

#5511 feat: update sample to use Secret Manager integration
  run/idp-sql/README.md
  run/idp-sql/pom.xml
  run/idp-sql/postcreate.sh
  run/idp-sql/src/main/java/com/example/cloudrun/IdpSqlApplication.java
  run/idp-sql/src/test/java/com/example/cloudrun/VoteControllerTests.java
Labels: cla: yes, samples

#5534 feat: update README with Secret Manager
  cloud-sql/mysql/servlet/README.md
  cloud-sql/postgres/servlet/README.md
  cloud-sql/r2dbc/README.md
  cloud-sql/sqlserver/servlet/README.md
Labels: cla: yes, samples

#5561 Added "union" to accepted types in the avro schema
  dataflow/transforms/src/main/java/com/example/AvroToCsv.java
Labels: cla: yes, samples

#5437 OpenCensus Cloud Spanner integration samples
  spanner/opencensus/README.md
  spanner/opencensus/pom.xml
  spanner/opencensus/src/main/java/com/example/spanner/opencensus/CaptureGrpcMetric.java
  spanner/opencensus/src/main/java/com/example/spanner/opencensus/CaptureQueryStatsMetric.java
  spanner/opencensus/src/test/java/com/example/spanner/opencensus/CaptureGrpcMetricIT.java
  spanner/opencensus/src/test/java/com/example/spanner/opencensus/CaptureQueryStatsMetricIT.java
Labels: cla: yes, samples

#5600 OpenCensus Cloud Spanner: capture GFE metric sample
  spanner/opencensus/README.md
  spanner/opencensus/src/main/java/com/example/spanner/opencensus/CaptureGfeMetric.java
  spanner/opencensus/src/test/java/com/example/spanner/opencensus/CaptureGfeMetricIT.java
Labels: automerge, cla: yes, samples

#5612 fix(run/markdown-preview): full width input form
  run/markdown-preview/editor/src/main/resources/templates/index.html
Labels: api: run, cla: yes, samples

#5613 fix: modified code to reflect 1.3.0-alpha changes
  compute/cloud-client/pom.xml
  compute/cloud-client/src/main/java/compute/CreateInstance.java
  compute/cloud-client/src/main/java/compute/DeleteInstance.java
Labels: api: compute, cla: yes, samples

#5622 chore: update dependencyDashboard labels
  renovate.json
Labels: automerge, cla: yes, samples

#5641 Debug flaky test
  unittests/src/test/java/com/google/appengine/samples/DeferredTaskTest.java
Labels: cla: yes, samples

#5645 chore: auto-approve.yml
  .github/CODEOWNERS
  .github/auto-approve.yml
Labels: cla: yes, samples

#5649 chore: debug test by extending timeout
  unittests/src/test/java/com/google/appengine/samples/DeferredTaskTest.java
Labels: cla: yes, samples

#5697 fix: extend timeout
  unittests/src/test/java/com/google/appengine/samples/DeferredTaskTest.java
Labels: cla: yes, samples

#5695 Compute pagination samples
  compute/cloud-client/src/main/java/compute/CreateInstance.java
  compute/cloud-client/src/main/java/compute/ListAllInstances.java
  compute/cloud-client/src/main/java/compute/ListImages.java
  compute/cloud-client/src/test/java/compute/SnippetsIT.java
Labels: api: compute, cla: yes, samples

#5702 fix: extend timeout for flaky test
  unittests/src/test/java/com/google/appengine/samples/DeferredTaskTest.java
Labels: cla: yes, samples

#5720 build: update auto-approve to conform with new validation schema
  .github/auto-approve.yml
Labels: cla: yes, samples
