Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2021-12, with the labels that each got.

#6444 chore: appengine sample to have GCLOUD_CONFIG explanation
  appengine-java11/springboot-helloworld/README.md
  appengine-java11/springboot-helloworld/pom.xml
  appengine-java8/springboot-helloworld/pom.xml
Labels: cla: yes, samples

#6446 Pub/Sub: update Spring tutorial with test + other nits
  pubsub/spring/README.md
  pubsub/spring/pom.xml
  pubsub/spring/src/main/java/demo/PubSubApplication.java
  pubsub/spring/src/test/java/demo/PubSubApplicationIT.java
Labels: cla: yes, samples

#6472 feat(transcoder): add sample and test for concatenating input videos
  media/transcoder/src/main/java/com/example/transcoder/CreateJobWithConcatenatedInputs.java
  media/transcoder/src/test/java/com/example/transcoder/CreateJobWithConcatenatedInputsTest.java
  media/transcoder/src/test/java/com/example/transcoder/testdata/ForBiggerEscapes.mp4
  media/transcoder/src/test/java/com/example/transcoder/testdata/ForBiggerJoyrides.mp4
Labels: samples, api: transcoder

#6578 fix(transcoder): use duration instead of float for args
  media/transcoder/src/main/java/com/example/transcoder/CreateJobWithConcatenatedInputs.java
  media/transcoder/src/test/java/com/example/transcoder/CreateJobWithConcatenatedInputsTest.java
Labels: automerge, samples, api: transcoder

#6579 chore(dataflow): delete {unused, insecure} sample
  dataflow/transforms/README.md
  dataflow/transforms/example_files/input.avro
  dataflow/transforms/example_files/input.csv
  dataflow/transforms/example_files/user.avsc
  dataflow/transforms/pom.xml
  dataflow/transforms/src/main/java/com/example/AvroToCsv.java
  dataflow/transforms/src/main/java/com/example/CsvToAvro.java
  dataflow/transforms/src/main/java/com/example/SampleOptions.java
  dataflow/transforms/src/main/resources/log4j.properties
  dataflow/transforms/src/test/java/com/example/AvroToCsvTest.java
  dataflow/transforms/src/test/java/com/example/CsvToAvroTest.java
Labels: api: dataflow, samples

#6584 chore(deps): update beam to 2.34.0 for pub/sub and dataflow
  dataflow/templates/pom.xml
  pubsub/streaming-analytics/pom.xml
  pubsublite/streaming-analytics/pom.xml
Labels: samples

#6587 dataflow: use log4j 2.15 to patch security bug
  dataflow/encryption-keys/pom.xml
  dataflow/flex-templates/kafka_to_bigquery/pom.xml
  dataflow/flex-templates/streaming_beam_sql/pom.xml
  dataflow/spanner-io/pom.xml
  dataflow/templates/pom.xml
Labels: api: dataflow, samples

#6588 dataflow: update imports and upgrade log4j version
  dataflow/encryption-keys/pom.xml
  dataflow/flex-templates/kafka_to_bigquery/pom.xml
  dataflow/flex-templates/kafka_to_bigquery/src/main/java/org/apache/beam/samples/KafkaToBigQuery.java
  dataflow/flex-templates/streaming_beam_sql/pom.xml
  dataflow/flex-templates/streaming_beam_sql/src/main/java/org/apache/beam/samples/StreamingBeamSql.java
  dataflow/spanner-io/pom.xml
  dataflow/spanner-io/src/main/java/com/example/dataflow/SpannerWrite.java
  dataflow/spanner-io/src/test/java/com/example/dataflow/SpannerGroupWriteIT.java
  dataflow/spanner-io/src/test/java/com/example/dataflow/SpannerReadIT.java
  dataflow/spanner-io/src/test/java/com/example/dataflow/SpannerWriteIT.java
  dataflow/templates/pom.xml
Labels: api: dataflow, samples

#6589 deps(bigtable): update beam and bigtable-hbase versions
  bigtable/beam/bulk-data-generator/pom.xml
  bigtable/beam/helloworld/pom.xml
  bigtable/beam/keyviz-art/pom.xml
  bigtable/hbase/snippets/pom.xml
Labels: automerge, api: bigtable, samples

#6590 deps: update bigtable-hbase to 1.26.1
  appengine-java8/bigtable/pom.xml
  bigtable/beam/bulk-data-generator/pom.xml
  bigtable/beam/helloworld/pom.xml
  bigtable/beam/keyviz-art/pom.xml
  bigtable/hbase/snippets/pom.xml
Labels: samples

#6593 deps(bigtable): upgrade bigtable-hbase-2.x-hadoop to 1.26.1
  bigtable/spark/build.sbt
Labels: api: bigtable, samples

#6596 deps: upgrade jdbc to 2.5.6 for hibernate samples
  spanner/hibernate/pom.xml
Labels: samples

#6595 deps: bump spanner dependencies
  spanner/jdbc/pom.xml
Labels: samples

#6594 deps: update to 0.30.0 in opencensus samples
  spanner/opencensus/pom.xml
Labels: samples

#6586 feat: add gradle build scripts to pubsub and pubsublite tutorials for beam
  pubsub/streaming-analytics/README.md
  pubsub/streaming-analytics/build.gradle
  pubsub/streaming-analytics/pom.xml
  pubsublite/streaming-analytics/README.md
  pubsublite/streaming-analytics/build.gradle
  pubsublite/streaming-analytics/pom.xml
Labels: api: pubsub, samples, api: pubsublite

#6597 dataflow: update log4j to 2.17.0
  dataflow/encryption-keys/pom.xml
  dataflow/flex-templates/kafka_to_bigquery/pom.xml
  dataflow/flex-templates/streaming_beam_sql/pom.xml
  dataflow/spanner-io/pom.xml
  dataflow/templates/pom.xml
Labels: api: dataflow, samples, automerge: exact

#6598 chore: add more pubsub and pubsublite codeowners
  .github/CODEOWNERS
Labels: samples

#6585 feat: add gradle build script to pubsub/spring tutorial
  pubsub/spring/README.md
  pubsub/spring/build.gradle
  pubsub/spring/pom.xml
Labels: api: pubsub, samples

#6592 chore: auto-assign issues to new Spanner owner
  .github/blunderbuss.yml
Labels: api: spanner, samples

#6372 docs: Bigtable Load generator tool
  bigtable/beam/workload-generator/README.md
  bigtable/beam/workload-generator/metadata.json
  bigtable/beam/workload-generator/pom.xml
  bigtable/beam/workload-generator/src/main/java/bigtable/WorkloadGenerator.java
  bigtable/beam/workload-generator/src/test/java/bigtable/WorkloadGeneratorTest.java
Labels: cla: yes, samples

#6581 docs(compute-samples): refactored samples and tests to adopt full-lro and enums as strings
  .kokoro/tests/run_tests.sh
  compute/cloud-client/pom.xml
  compute/cloud-client/src/main/java/compute/CreateEncryptedInstance.java
  compute/cloud-client/src/main/java/compute/CreateFirewallRule.java
  compute/cloud-client/src/main/java/compute/CreateInstance.java
  compute/cloud-client/src/main/java/compute/CreateInstancesAdvanced.java
  compute/cloud-client/src/main/java/compute/DeleteFirewallRule.java
  compute/cloud-client/src/main/java/compute/DeleteInstance.java
  compute/cloud-client/src/main/java/compute/ListAllInstances.java
  compute/cloud-client/src/main/java/compute/ListImages.java
  compute/cloud-client/src/main/java/compute/ListInstance.java
  compute/cloud-client/src/main/java/compute/PatchFirewallRule.java
  compute/cloud-client/src/main/java/compute/ResetInstance.java
  compute/cloud-client/src/main/java/compute/SetUsageExportBucket.java
  compute/cloud-client/src/main/java/compute/StartEncryptedInstance.java
  compute/cloud-client/src/main/java/compute/StartInstance.java
  compute/cloud-client/src/main/java/compute/StopInstance.java
  compute/cloud-client/src/main/java/compute/WaitForOperation.java
  compute/cloud-client/src/test/java/compute/SnippetsIT.java
Labels: samples

#6599 dataflow: avoid importing log4j at all
  dataflow/encryption-keys/pom.xml
  dataflow/flex-templates/kafka_to_bigquery/pom.xml
  dataflow/flex-templates/kafka_to_bigquery/src/main/java/org/apache/beam/samples/KafkaToBigQuery.java
  dataflow/flex-templates/streaming_beam_sql/pom.xml
  dataflow/flex-templates/streaming_beam_sql/src/main/java/org/apache/beam/samples/StreamingBeamSql.java
  dataflow/spanner-io/pom.xml
  dataflow/spanner-io/src/main/java/com/example/dataflow/SpannerWrite.java
  dataflow/templates/pom.xml
Labels: api: dataflow, samples

#6600 Update Spring Boot dependencies to 2.5.8
  eventarc/generic/pom.xml
  eventarc/pubsub/pom.xml
  flexible/helloworld-springboot/pom.xml
  pubsub/spring/pom.xml
  run/helloworld/pom.xml
  run/image-processing/pom.xml
  run/markdown-preview/editor/pom.xml
  spanner/r2dbc/pom.xml
Labels: samples

#6602 Upgrade Spring Cloud GCP and remaining Spring Boot versions
  pubsub/spring/pom.xml
  run/idp-sql/pom.xml
  run/image-processing/pom.xml
  spanner/spring-data/pom.xml
Labels: samples

#6552 docs(compute-samples): added samples and tests for: GCE instance from…
  compute/cloud-client/src/main/java/compute/CreateInstance.java
  compute/cloud-client/src/main/java/compute/CreateInstanceFromTemplate.java
  compute/cloud-client/src/main/java/compute/CreateInstanceFromTemplateWithOverrides.java
  compute/cloud-client/src/main/java/compute/CreateInstanceTemplate.java
  compute/cloud-client/src/main/java/compute/DeleteInstanceTemplate.java
  compute/cloud-client/src/main/java/compute/GetInstanceTemplate.java
  compute/cloud-client/src/main/java/compute/ListInstanceTemplates.java
  compute/cloud-client/src/test/java/compute/InstanceTemplatesIT.java
  compute/cloud-client/src/test/java/compute/SnippetsIT.java
Labels: samples
