Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2021-01, with the labels that each got.

#4535 fix: correcting region tags for Hbase filter and read snippets
  bigtable/hbase/snippets/src/main/java/com/example/bigtable/Filters.java
  bigtable/hbase/snippets/src/main/java/com/example/bigtable/Reads.java
Labels: cla: yes, samples

#4524 chore(functions): delete unused region tag
  functions/helloworld/hello-pubsub/src/main/java/functions/HelloPubSub.java
Labels: api: cloudfunctions, cla: yes, samples

#4495 Add tests for Cloud SQL samples
  .kokoro/tests/run_tests.sh
  cloud-sql/mysql/servlet/pom.xml
  cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/IndexServlet.java
  cloud-sql/mysql/servlet/src/test/java/com/TestIndexServletMysql.java
  cloud-sql/postgres/servlet/pom.xml
  cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java
  cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/IndexServlet.java
  cloud-sql/postgres/servlet/src/test/java/com/TestIndexServletPostgres.java
  cloud-sql/sqlserver/servlet/pom.xml
  cloud-sql/sqlserver/servlet/src/main/java/com/example/cloudsql/IndexServlet.java
  cloud-sql/sqlserver/servlet/src/test/java/com/TestIndexServletSqlServer.java
Labels: cla: yes, samples

#4496 [Cloud Run] Identity platform sample
  .kokoro/tests/build_cloud_run.sh
  run/idp-sql/README.md
  run/idp-sql/app.json
  run/idp-sql/pom.xml
  run/idp-sql/postcreate.sh
  run/idp-sql/postgres-secrets.json
  run/idp-sql/setup.sh
  run/idp-sql/src/main/java/com/example/cloudrun/IdpSqlApplication.java
  run/idp-sql/src/main/java/com/example/cloudrun/Vote.java
  run/idp-sql/src/main/java/com/example/cloudrun/VoteController.java
  run/idp-sql/src/main/resources/application.properties
  run/idp-sql/src/main/resources/logback-spring.xml
  run/idp-sql/src/main/resources/schema.sql
  run/idp-sql/src/main/resources/static/config.js
  run/idp-sql/src/main/resources/static/firebase.js
  run/idp-sql/src/main/resources/templates/index.html
  run/idp-sql/src/test/java/com/example/cloudrun/VoteControllerTests.java
  run/idp-sql/src/test/resources/application.properties
Labels: cla: yes, samples

#4549 chore(functions): use correct Gradle argument names
  functions/helloworld/helloworld-gradle/build.gradle
Labels: api: cloudfunctions, cla: yes, samples

#4545 Make scripts executable
  run/idp-sql/postcreate.sh
  run/idp-sql/setup.sh
Labels: cla: yes, samples

#4539 chore(functions): use proper Java test naming
  functions/helloworld/hello-gcs/src/test/java/functions/ExampleIT.java
  functions/helloworld/hello-gcs/src/test/java/functions/ExampleSystemIT.java
  functions/helloworld/hello-http/src/test/java/functions/ExampleIT.java
  functions/helloworld/hello-http/src/test/java/functions/ExampleSystemIT.java
  functions/helloworld/hello-pubsub/src/test/java/functions/ExampleIT.java
  functions/helloworld/hello-pubsub/src/test/java/functions/ExampleSystemIT.java
Labels: api: cloudfunctions, cla: yes, samples

#4580 chore(deps): update spring boot to v2.3.8.RELEASE
  pubsub/spring/pom.xml
Labels: cla: yes, samples

#4551 Use spring-boot-starter-data-r2dbc and version manage as little dependencies as possible
  cloud-sql/r2dbc/pom.xml
Labels: cla: yes, samples

#4583 chore: updated keys that will expire in 1000 days
  iot/api-client/manager/resources/rsa_cert.pem
  iot/api-client/manager/resources/rsa_private.pem
  iot/api-client/manager/resources/rsa_private_pkcs8
Labels: cla: yes, samples

#4582 Add iot team as code owner
  .github/CODEOWNERS
Labels: cla: yes, samples

#4568 chore(GAE flex): remove 3rd-party email API samples
  flexible/mailgun/README.md
  flexible/mailgun/pom.xml
  flexible/mailgun/src/main/appengine/app.yaml
  flexible/mailgun/src/main/java/com/example/mailgun/MailgunServlet.java
  flexible/mailgun/src/main/resources/example-attachment.txt
  flexible/mailgun/src/main/webapp/index.html
  flexible/mailjet/README.md
  flexible/mailjet/pom.xml
  flexible/mailjet/src/main/appengine/app.yaml
  flexible/mailjet/src/main/java/com/example/mailjet/MailjetServlet.java
  flexible/mailjet/src/main/webapp/WEB-INF/lib/client-3.1.1-jar-with-dependencies.jar
  flexible/mailjet/src/main/webapp/index.html
  flexible/sendgrid/README.md
  flexible/sendgrid/pom.xml
  flexible/sendgrid/src/main/appengine/app.yaml
  flexible/sendgrid/src/main/java/com/example/sendgrid/SendEmailServlet.java
Labels: automerge, cla: yes, samples

#4585 Update SAMPLE_FORMAT.md
  SAMPLE_FORMAT.md
Labels: automerge, cla: yes, samples

#4542 standardize region tag to match other languages
  iam/api-client/src/main/java/iam/snippets/AddBinding.java
Labels: cla: yes, samples

#4592 Revert "chore(deps): update dependency org.springframework.boot:spring-boot-dependencies to v2.4.2"
  pubsub/spring/pom.xml
Labels: cla: yes, samples

#4596 Fixtags
  iam/api-client/src/main/java/iam/snippets/AddBinding.java
Labels: automerge, cla: yes, samples

#4610 buildcop => flakybot
  .github/stale.yml
  .kokoro/tests/run_tests.sh
Labels: cla: yes, samples

#4613 build: migrate to flakybot
  .kokoro/tests/run_tests.sh
Labels: cla: yes, samples

#4615 fix: region tag open and close
  pubsub/spring/pom.xml
Labels: cla: yes, samples
