Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2021-03, with the labels that each got.

#4831 deps: update bigtable to 1.21.0
  bigtable/cassandra-migration-codelab/pom.xml
  bigtable/hbase/snippets/pom.xml
  bigtable/memorystore/pom.xml
Labels: cla: yes, samples

#4821 feat: add Cloud SQL samples for Client-side Encryption
  cloud-sql/mysql/client-side-encryption/README.md
  cloud-sql/mysql/client-side-encryption/example.envrc
  cloud-sql/mysql/client-side-encryption/pom.xml
  cloud-sql/mysql/client-side-encryption/src/main/java/cloudsql/tink/CloudKmsEnvelopeAead.java
  cloud-sql/mysql/client-side-encryption/src/main/java/cloudsql/tink/CloudSqlConnectionPool.java
  cloud-sql/mysql/client-side-encryption/src/main/java/cloudsql/tink/EncryptAndInsertData.java
  cloud-sql/mysql/client-side-encryption/src/main/java/cloudsql/tink/QueryAndDecryptData.java
  cloud-sql/mysql/client-side-encryption/src/test/java/cloudsql/tink/EncryptInsertDataIT.java
  cloud-sql/mysql/client-side-encryption/src/test/java/cloudsql/tink/QueryDecryptDataIT.java
Labels: cla: yes, samples

#4833 Fix table of contents
  SAMPLE_FORMAT.md
Labels: cla: yes, samples

#4830 deps: update bigtable to 1.21.0
  bigtable/scheduled-backups/pom.xml
Labels: cla: yes, samples

#4838 fix: replace deprecated envelope encryption method in Tink sample
  cloud-sql/mysql/client-side-encryption/src/main/java/cloudsql/tink/CloudKmsEnvelopeAead.java
Labels: cla: yes, samples

#4839 chore: delete eventarc anthos files
  eventarc/audit-storage/anthos.md
  eventarc/pubsub/anthos.md
Labels: automerge, cla: yes, samples

#4845 restore transfer service initializer samples with proper region tags
  storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/CreateTransferClient.java
  storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/RetryHttpInitializerWrapper.java
  storage/storage-transfer/src/test/java/com/google/cloud/storage/storagetransfer/samples/test/CheckLatestTransferOperationTest.java
  storage/storage-transfer/src/test/java/com/google/cloud/storage/storagetransfer/samples/test/CheckTransferJobTest.java
Labels: cla: yes, samples

#4847 fix: add missing dependency
  iot/api-client/end-to-end-example/pom.xml
Labels: cla: yes, kokoro:force-run, samples

#4849 fix(deps): fix scalaVersion and pin jackson-module-scala
  bigtable/spark/build.sbt
  renovate.json
Labels: automerge, cla: yes, samples

#4864 fix: add missing dependencies
  iot/api-client/end-to-end-example/pom.xml
  iot/api-client/manager/pom.xml
Labels: cla: yes, samples

#4870 chore(bigtable_spark): make print statement less verbose
  bigtable/spark/src/main/scala/example/CopyTable.scala
Labels: api: bigtable, cla: yes, samples

#4878 feat: add spritesheet samples and tests
  media/transcoder/src/main/java/com/example/transcoder/CreateJobWithPeriodicImagesSpritesheet.java
  media/transcoder/src/main/java/com/example/transcoder/CreateJobWithSetNumberImagesSpritesheet.java
  media/transcoder/src/test/java/com/example/transcoder/CreateJobWithPeriodicImagesSpritesheetTest.java
  media/transcoder/src/test/java/com/example/transcoder/CreateJobWithSetNumberImagesSpritesheetTest.java
Labels: automerge, cla: yes, samples

#4866 Update spark sample path
  bigtable/spark/README.md
Labels: automerge, cla: yes, samples

#4889 [Run] add region tags and change secret name
  .kokoro/tests/build_cloud_run.sh
  run/idp-sql/README.md
  run/idp-sql/postcreate.sh
  run/idp-sql/src/main/java/com/example/cloudrun/IdpSqlApplication.java
  run/idp-sql/src/main/java/com/example/cloudrun/VoteController.java
  run/idp-sql/src/main/resources/static/config.js
Labels: cla: yes, samples

#4901 Correct comments on associated data.
  cloud-sql/mysql/client-side-encryption/src/main/java/cloudsql/tink/EncryptAndInsertData.java
  cloud-sql/mysql/client-side-encryption/src/main/java/cloudsql/tink/QueryAndDecryptData.java
  cloud-sql/postgres/client-side-encryption/src/main/java/cloudsql/tink/EncryptAndInsertData.java
  cloud-sql/postgres/client-side-encryption/src/main/java/cloudsql/tink/QueryAndDecryptData.java
  cloud-sql/sqlserver/client-side-encryption/src/main/java/cloudsql/tink/EncryptAndInsertData.java
  cloud-sql/sqlserver/client-side-encryption/src/main/java/cloudsql/tink/QueryAndDecryptData.java
Labels: automerge, cla: yes, samples

#4910 samples(bigtable): update second spark home
  bigtable/spark/README.md
Labels: api: bigtable, cla: yes, samples

#4600 Sample for configuring Bigtable connection pool
  bigtable/hbase/snippets/src/main/java/com/example/bigtable/ConfigureConnectionPool.java
  bigtable/hbase/snippets/src/test/java/com/example/bigtable/ConfigureConnectionPoolTest.java
Labels: cla: yes, samples

#4932 Save & Restore out / err
  SAMPLE_FORMAT.md
Labels: automerge, cla: yes, samples

#4933 docs: quick change of region tag for a Bigtable sample
  bigtable/hbase/snippets/src/main/java/com/example/bigtable/ConfigureConnectionPool.java
Labels: cla: yes, samples

#4938 chore(eventarc): update region tags
  eventarc/audit-storage/Dockerfile
  eventarc/audit-storage/src/main/java/com/example/cloudrun/Application.java
  eventarc/audit-storage/src/main/java/com/example/cloudrun/EventController.java
Labels: api: eventarc, automerge, cla: yes, samples

#4955 chore: clean up migrated BigQuery samples and update related README.md
  bigquery/README.md
  bigquery/bigquerystorage/README.md
  bigquery/cloud-client/README.md
  bigquery/datatransfer/README.md
  bigquery/rest/README.md
  bigquery/rest/pom.xml
  bigquery/rest/src/main/java/com/example/bigquery/LabelsSample.java
  bigquery/rest/src/test/java/com/example/bigquery/Constants.java
  bigquery/rest/src/test/java/com/example/bigquery/LabelsSampleIT.java
Labels: automerge, cla: yes, samples

#4869 chore(functions): remove custom Pub/Sub POJOs
  functions/concepts/retry-pubsub/pom.xml
  functions/concepts/retry-pubsub/src/main/java/functions/RetryPubSub.java
  functions/concepts/retry-pubsub/src/main/java/functions/eventpojos/PubSubMessage.java
  functions/concepts/retry-pubsub/src/test/java/functions/RetryPubSubTest.java
  functions/concepts/retry-timeout/pom.xml
  functions/concepts/retry-timeout/src/main/java/functions/RetryTimeout.java
  functions/concepts/retry-timeout/src/main/java/functions/eventpojos/PubSubMessage.java
  functions/concepts/retry-timeout/src/test/java/functions/RetryTimeoutTest.java
  functions/helloworld/groovy-hello-pubsub/pom.xml
  functions/helloworld/groovy-hello-pubsub/src/main/groovy/functions/GroovyHelloPubSub.groovy
  functions/helloworld/groovy-hello-pubsub/src/main/groovy/functions/eventpojos/PubSubMessage.groovy
  functions/helloworld/groovy-hello-pubsub/src/test/java/functions/GroovyHelloPubSubTest.java
  functions/helloworld/hello-gcs/pom.xml
  functions/helloworld/hello-gcs/src/test/java/functions/HelloGcsTest.java
  functions/helloworld/hello-pubsub/pom.xml
  functions/helloworld/hello-pubsub/src/main/java/functions/HelloPubSub.java
  functions/helloworld/hello-pubsub/src/main/java/functions/eventpojos/PubSubMessage.java
  functions/helloworld/hello-pubsub/src/test/java/functions/HelloPubSubTest.java
  functions/helloworld/kotlin-hello-pubsub/pom.xml
  functions/helloworld/kotlin-hello-pubsub/src/main/kotlin/functions/KotlinHelloBackground.kt
  functions/helloworld/kotlin-hello-pubsub/src/main/kotlin/functions/eventpojos/PubSubMessage.kt
  functions/helloworld/kotlin-hello-pubsub/src/test/java/functions/KotlinHelloPubSubTest.java
  functions/helloworld/scala-hello-pubsub/pom.xml
  functions/helloworld/scala-hello-pubsub/src/main/scala/functions/ScalaHelloPubSub.scala
  functions/helloworld/scala-hello-pubsub/src/main/scala/functions/eventpojos/PubSubMessage.scala
  functions/helloworld/scala-hello-pubsub/src/test/java/functions/ScalaHelloPubSubTest.java
  functions/imagemagick/pom.xml
  functions/imagemagick/src/main/java/functions/ImageMagick.java
  functions/logging/stackdriver-logging/pom.xml
  functions/logging/stackdriver-logging/src/main/java/functions/StackdriverLogging.java
  functions/logging/stackdriver-logging/src/main/java/functions/eventpojos/PubSubMessage.java
  functions/logging/stackdriver-logging/src/test/java/functions/StackdriverLoggingTest.java
  functions/ocr/ocr-process-image/pom.xml
  functions/ocr/ocr-process-image/src/main/java/functions/eventpojos/PubSubMessage.java
  functions/ocr/ocr-process-image/src/test/java/functions/OcrProcessImageTest.java
  functions/ocr/ocr-save-result/pom.xml
  functions/ocr/ocr-save-result/src/main/java/functions/OcrSaveResult.java
  functions/ocr/ocr-save-result/src/main/java/functions/eventpojos/PubSubMessage.java
  functions/ocr/ocr-save-result/src/test/java/functions/OcrSaveResultTest.java
  functions/ocr/ocr-translate-text/pom.xml
  functions/ocr/ocr-translate-text/src/main/java/functions/OcrTranslateText.java
  functions/ocr/ocr-translate-text/src/main/java/functions/eventpojos/PubSubMessage.java
  functions/ocr/ocr-translate-text/src/test/java/functions/OcrTranslateTextTest.java
  functions/pubsub/publish-message/src/main/java/functions/PublishMessage.java
  functions/pubsub/publish-message/src/main/java/functions/eventpojos/PubSubMessage.java
  functions/pubsub/subscribe-to-topic/pom.xml
  functions/pubsub/subscribe-to-topic/src/main/java/functions/SubscribeToTopic.java
  functions/pubsub/subscribe-to-topic/src/main/java/functions/eventpojos/PubSubMessage.java
  functions/pubsub/subscribe-to-topic/src/test/java/functions/SubscribeToTopicTest.java
Labels: api: cloudfunctions, cla: yes, samples

#4962 healthcare API: add missing com.google.http-client dependency
  healthcare/v1/pom.xml
Labels: automerge, cla: yes, samples
