Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2021-05, with the labels that each got.

#5167 Update scheduled_backups.sh
  bigtable/scheduled-backups/scripts/scheduled_backups.sh
Labels: cla: yes, samples

#5177 docs: Replace -Dproj to -Dproject_id in all example commands.
  iot/api-client/manager/README.md
  iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/DeviceRegistryExample.java
Labels: cla: yes, samples

#5187 Update common.cfg
  .kokoro/java11/common.cfg
Labels: automerge, cla: yes, samples

#5189 Set up application to be packaged as an uber-jar via application.properties
  appengine-java11/quarkus-helloworld/src/main/resources/application.properties
Labels: automerge, cla: yes, samples

#5197 Update common.cfg
  .kokoro/java11/common.cfg
Labels: automerge, cla: yes, samples

#5198 Update run_tests.sh
  .kokoro/tests/run_tests.sh
Labels: automerge, cla: yes, samples

#5226 Fix broken link in SAMPLE_FORMAT.md
  SAMPLE_FORMAT.md
Labels: cla: yes, samples

#5240 run tests concurrently and with timeouts
  .kokoro/java11/common.cfg
  .kokoro/java11/continuous.cfg
  .kokoro/java11/presubmit.cfg
  .kokoro/java8/common.cfg
  .kokoro/java8/continuous.cfg
  .kokoro/java8/presubmit.cfg
  .kokoro/tests/run_diff_only.sh
  .kokoro/tests/run_lint.sh
  .kokoro/tests/run_test_java.sh
  .kokoro/tests/run_tests.sh
Labels: cla: yes, samples

#5249 Update SAMPLE_FORMAT.md
  SAMPLE_FORMAT.md
Labels: cla: yes, samples

#5254 Update renovate.json
  renovate.json
Labels: cla: yes, samples

#5258 chore: escape the escape character in renovate.json
  renovate.json
Labels: cla: yes, samples

#5260 chore(renovate): add required match section to package rules
  renovate.json
Labels: cla: yes, samples

#5263 chore(spanner): remove samples that have moved to the client library
  spanner/cloud-client/README.md
  spanner/cloud-client/assembly-descriptor.xml
  spanner/cloud-client/pom.xml
  spanner/cloud-client/src/main/java/com/example/spanner/AddNumericColumnSample.java
  spanner/cloud-client/src/main/java/com/example/spanner/AsyncDmlExample.java
  spanner/cloud-client/src/main/java/com/example/spanner/AsyncQueryExample.java
  spanner/cloud-client/src/main/java/com/example/spanner/AsyncQueryToListAsyncExample.java
  spanner/cloud-client/src/main/java/com/example/spanner/AsyncReadExample.java
  spanner/cloud-client/src/main/java/com/example/spanner/AsyncReadOnlyTransactionExample.java
  spanner/cloud-client/src/main/java/com/example/spanner/AsyncReadRowExample.java
  spanner/cloud-client/src/main/java/com/example/spanner/AsyncReadUsingIndexExample.java
  spanner/cloud-client/src/main/java/com/example/spanner/AsyncRunnerExample.java
  spanner/cloud-client/src/main/java/com/example/spanner/AsyncTransactionManagerExample.java
  spanner/cloud-client/src/main/java/com/example/spanner/BatchSample.java
  spanner/cloud-client/src/main/java/com/example/spanner/CreateInstanceExample.java
  spanner/cloud-client/src/main/java/com/example/spanner/CustomTimeoutAndRetrySettingsExample.java
  spanner/cloud-client/src/main/java/com/example/spanner/QueryWithNumericParameterSample.java
  spanner/cloud-client/src/main/java/com/example/spanner/QuickstartSample.java
  spanner/cloud-client/src/main/java/com/example/spanner/SpannerSample.java
  spanner/cloud-client/src/main/java/com/example/spanner/TracingSample.java
  spanner/cloud-client/src/main/java/com/example/spanner/UpdateNumericDataSample.java
  spanner/cloud-client/src/main/resources/META-INF/services/io.grpc.LoadBalancerProvider
  spanner/cloud-client/src/test/java/com/example/spanner/AsyncExamplesIT.java
  spanner/cloud-client/src/test/java/com/example/spanner/QuickstartSampleIT.java
  spanner/cloud-client/src/test/java/com/example/spanner/SpannerSampleIT.java
  spanner/cloud-client/src/test/java/com/example/spanner/SpannerStandaloneExamplesIT.java
Labels: api: spanner, cla: yes, samples

#5305 chore(functions): fix flaky tests + update dir property
  functions/helloworld/hello-gcs/src/test/java/functions/ExampleIT.java
  functions/helloworld/hello-http/src/test/java/functions/ExampleIT.java
  functions/helloworld/hello-pubsub/src/test/java/functions/ExampleIT.java
Labels: api: cloudfunctions, cla: yes, samples

#5313 Update CODEOWNERS / Blunderbuss for SoDA
  .github/CODEOWNERS
  .github/blunderbuss.yml
Labels: cla: yes, samples
