Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2021-09, with the labels that each got.

#5908 chore(functions/logging): exclude trace code from sample
  run/logging-manual/src/main/java/com/example/cloudrun/App.java
Labels: cla: yes, api: cloudfunctions, samples

#5923 Fix minor typo
  endpoints/getting-started/clients/src/main/java/com/example/app/GoogleJwtClient.java
Labels: cla: yes, samples

#5972 Add GCFv2 Storage sample
  functions/v2/helloworld/hello-gcs/pom.xml
  functions/v2/helloworld/hello-gcs/src/main/java/functions/HelloGcs.java
  functions/v2/helloworld/hello-gcs/src/main/java/functions/eventpojos/GcsEvent.java
  functions/v2/helloworld/hello-gcs/src/test/java/functions/HelloGcsTest.java
Labels: cla: yes, automerge, samples

#5980 Minor updates for GCF sample
  functions/v2/helloworld/hello-gcs/src/main/java/functions/HelloGcs.java
  functions/v2/helloworld/hello-gcs/src/test/java/functions/HelloGcsTest.java
Labels: cla: yes, samples

#5986 docs(samples): updating LRO wrappers and included operations wait blocking call
  compute/cloud-client/pom.xml
  compute/cloud-client/src/main/java/compute/CreateInstance.java
  compute/cloud-client/src/main/java/compute/DeleteInstance.java
  compute/cloud-client/src/main/java/compute/SetUsageExportBucket.java
  compute/cloud-client/src/main/java/compute/WaitForOperation.java
  compute/cloud-client/src/test/java/compute/SnippetsIT.java
Labels: cla: yes, samples

#5973 fix: update workflows quickstart to use env vars for config
  workflows/cloud-client/src/main/java/com/example/workflows/WorkflowsQuickstart.java
Labels: cla: yes, automerge, samples

#5995 Gapic firewall samples
  compute/cloud-client/src/main/java/compute/CreateFirewallRule.java
  compute/cloud-client/src/main/java/compute/DeleteFirewallRule.java
  compute/cloud-client/src/main/java/compute/GetFirewallRule.java
  compute/cloud-client/src/main/java/compute/ListFirewallRules.java
  compute/cloud-client/src/main/java/compute/ListImages.java
  compute/cloud-client/src/main/java/compute/PatchFirewallRule.java
  compute/cloud-client/src/test/java/compute/SnippetsIT.java
Labels: cla: yes, samples

#5312 feat: update sample to use beam-side lite io
  pubsublite/streaming-analytics/pom.xml
  pubsublite/streaming-analytics/src/main/java/examples/PubsubliteToGcs.java
  pubsublite/streaming-analytics/src/test/java/PubsubliteToGcsIT.java
Labels: cla: yes, type: feature request, priority: p2, samples, api: pubsublite

#5971 Update GCFv2 PubSub sample
  functions/v2/pubsub/subscribe-to-topic/pom.xml
  functions/v2/pubsub/subscribe-to-topic/src/main/java/functions/SubscribeToTopic.java
  functions/v2/pubsub/subscribe-to-topic/src/test/java/functions/SubscribeToTopicTest.java
Labels: cla: yes, samples

#5883 feat: JSON samples for Spanner JDBC
  spanner/jdbc/pom.xml
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/JsonCreateTableExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/JsonInsertDataExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/JsonQueryDataExample.java
  spanner/jdbc/src/test/java/com/example/spanner/jdbc/JdbcExamplesIT.java
Labels: cla: yes, samples

#6008 fix: update deprecated image
  run/image-processing/Dockerfile
  run/system-package/Dockerfile
Labels: cla: yes, samples

#6022 fix: correct typo in README.md
  appengine-java11/springboot-helloworld/README.md
Labels: cla: yes, samples, automerge: exact

#6056 chore: add sleep to Bigtable MemcachedTest to fix flakiness
  bigtable/memorystore/src/test/java/MemcachedTest.java
Labels: cla: yes, samples

#6062 Add Cloud Run sample
  .kokoro/tests/run_tests.sh
  run/filesystem/.dockerignore
  run/filesystem/Dockerfile
  run/filesystem/pom.xml
  run/filesystem/run.sh
  run/filesystem/src/main/java/com/example/filesystem/FilesystemApplication.java
  run/filesystem/src/main/resources/application.properties
  run/filesystem/src/test/java/com/example/filesystem/FilesystemApplicationIT.java
  run/filesystem/src/test/java/com/example/filesystem/FilesystemApplicationTests.java
Labels: cla: yes, samples

#6064 docs(iam-samples): added samples and tests for enabling and disabling…
  iam/api-client/src/main/java/iam/snippets/DisableServiceAccountKey.java
  iam/api-client/src/main/java/iam/snippets/EnableServiceAccountKey.java
  iam/api-client/src/test/java/iam/snippets/ServiceAccountTests.java
Labels: cla: yes, api: iam, samples

#6053 docs(compute): samples for instance operations
  compute/cloud-client/src/main/java/compute/CreateEncryptedInstance.java
  compute/cloud-client/src/main/java/compute/ResetInstance.java
  compute/cloud-client/src/main/java/compute/StartEncryptedInstance.java
  compute/cloud-client/src/main/java/compute/StartInstance.java
  compute/cloud-client/src/main/java/compute/StopInstance.java
  compute/cloud-client/src/test/java/compute/SnippetsIT.java
Labels: cla: yes, api: compute, samples
