Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2021-06, with the labels that each got.

#5262 Add a Cloud Spanner with Spring Data R2DBC sample app
  spanner/r2dbc/README.md
  spanner/r2dbc/pom.xml
  spanner/r2dbc/src/main/java/com/example/spanner/r2dbc/Name.java
  spanner/r2dbc/src/main/java/com/example/spanner/r2dbc/R2dbcSampleApplication.java
  spanner/r2dbc/src/main/java/com/example/spanner/r2dbc/WebController.java
  spanner/r2dbc/src/main/resources/application.properties
  spanner/r2dbc/src/main/resources/static/index.html
  spanner/r2dbc/src/test/java/com/example/spanner/r2dbc/R2dbcSampleApplicationIT.java
Labels: cla: yes, samples

#5336 Delete storage/json-api directory
  storage/json-api/README.md
  storage/json-api/pom.xml
  storage/json-api/src/main/java/CustomerSuppliedEncryptionKeysSamples.java
  storage/json-api/src/main/java/StorageFactory.java
  storage/json-api/src/main/java/StorageSample.java
  storage/json-api/src/main/java/StorageUtils.java
  storage/json-api/src/test/java/StorageSampleTest.java
Labels: cla: yes, samples

#5365 chore(storage): move storage/s3-sdk into a package
  storage/s3-sdk/src/main/java/storage/s3sdk/ListGcsBuckets.java
  storage/s3-sdk/src/main/java/storage/s3sdk/ListGcsObjects.java
  storage/s3-sdk/src/test/java/storage/s3sdk/ListGcsBucketsTest.java
  storage/s3-sdk/src/test/java/storage/s3sdk/ListGcsObjectsTest.java
Labels: api: storage, cla: yes, samples

#5357 test: Fixed registry cleanup.
  iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java
Labels: cla: yes, samples

#5366 chore(storage): delete old storage/s3-sdk samples
  storage/s3-sdk/src/main/java/ListGcsBuckets.java
  storage/s3-sdk/src/main/java/ListGcsObjects.java
  storage/s3-sdk/src/test/java/ListGcsBucketsTest.java
  storage/s3-sdk/src/test/java/ListGcsObjectsTest.java
Labels: api: storage, cla: yes, samples

#5364 fix: test timeouts due to large sleep times
  media/transcoder/src/test/java/com/example/transcoder/CreateJobFromAdHocTest.java
  media/transcoder/src/test/java/com/example/transcoder/CreateJobFromPresetTest.java
  media/transcoder/src/test/java/com/example/transcoder/CreateJobFromTemplateTest.java
  media/transcoder/src/test/java/com/example/transcoder/CreateJobWithAnimatedOverlayTest.java
  media/transcoder/src/test/java/com/example/transcoder/CreateJobWithPeriodicImagesSpritesheetTest.java
  media/transcoder/src/test/java/com/example/transcoder/CreateJobWithSetNumberImagesSpritesheetTest.java
  media/transcoder/src/test/java/com/example/transcoder/CreateJobWithStaticOverlayTest.java
Labels: cla: yes, samples

#5373 fix: address feedback
  media/transcoder/src/test/java/com/example/transcoder/CreateJobFromAdHocTest.java
  media/transcoder/src/test/java/com/example/transcoder/CreateJobFromPresetTest.java
  media/transcoder/src/test/java/com/example/transcoder/CreateJobFromTemplateTest.java
  media/transcoder/src/test/java/com/example/transcoder/CreateJobWithAnimatedOverlayTest.java
  media/transcoder/src/test/java/com/example/transcoder/CreateJobWithPeriodicImagesSpritesheetTest.java
  media/transcoder/src/test/java/com/example/transcoder/CreateJobWithSetNumberImagesSpritesheetTest.java
  media/transcoder/src/test/java/com/example/transcoder/CreateJobWithStaticOverlayTest.java
Labels: cla: yes, samples

#5253 Google cloud client compute samples
  compute/cloud-client/pom.xml
  compute/cloud-client/src/main/java/compute/CreateInstance.java
  compute/cloud-client/src/main/java/compute/DeleteInstance.java
  compute/cloud-client/src/main/java/compute/ListAllInstances.java
  compute/cloud-client/src/main/java/compute/ListInstance.java
  compute/cloud-client/src/test/java/compute/SnippetsIT.java
Labels: api: compute, cla: yes, samples

#5345 chore(functions): increase retry counts for flaky tests
  functions/helloworld/hello-gcs/pom.xml
  functions/helloworld/hello-gcs/src/test/java/functions/ExampleIT.java
  functions/helloworld/hello-http/pom.xml
  functions/helloworld/hello-http/src/test/java/functions/ExampleIT.java
  functions/helloworld/hello-pubsub/pom.xml
  functions/helloworld/hello-pubsub/src/test/java/functions/ExampleIT.java
Labels: api: cloudfunctions, cla: yes, samples

#5385 test(storage): fix S3 SDK tests
  .kokoro/tests/run_tests.sh
  storage/s3-sdk/README.md
  storage/s3-sdk/pom.xml
  storage/s3-sdk/src/test/java/storage/s3sdk/ListGcsBucketsTest.java
  storage/s3-sdk/src/test/java/storage/s3sdk/ListGcsObjectsTest.java
  storage/s3-sdk/src/test/java/storage/s3sdk/TestHmacKeyRule.java
Labels: api: storage, cla: yes, samples

#5306 Add Load Csv Data Example to JDBC examples
  spanner/jdbc/pom.xml
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/LoadCsvExample.java
  spanner/jdbc/src/test/java/com/example/spanner/jdbc/JdbcExamplesIT.java
  spanner/jdbc/src/test/resources/singers.csv
Labels: cla: yes, samples

#5388 chore(functions): improve emulator debugging code
  functions/helloworld/hello-gcs/src/test/java/functions/ExampleIT.java
  functions/helloworld/hello-http/src/test/java/functions/ExampleIT.java
  functions/helloworld/hello-pubsub/src/test/java/functions/ExampleIT.java
Labels: api: cloudfunctions, cla: yes, samples

#5407 Update README.md
  appengine-java11/micronaut-helloworld/README.md
Labels: automerge, cla: yes, samples

#5447 chore: only use release version of spring-boot-dependencies
  renovate.json
Labels: cla: yes, samples

#5421 Google cloud client compute samples
  compute/cloud-client/pom.xml
  compute/cloud-client/src/main/java/compute/CreateInstance.java
  compute/cloud-client/src/main/java/compute/DeleteInstance.java
  compute/cloud-client/src/main/java/compute/ListAllInstances.java
  compute/cloud-client/src/main/java/compute/ListInstance.java
  compute/cloud-client/src/main/java/compute/SetUsageExportBucket.java
  compute/cloud-client/src/test/java/compute/SnippetsIT.java
Labels: api: compute, cla: yes, samples

#5454 fix: update Dockerfile to use JRE
  run/helloworld/Dockerfile
  run/image-processing/Dockerfile
  run/system-package/Dockerfile
Labels: automerge, cla: yes, samples

#5455 fix: Update sample with best practices
  run/image-processing/src/main/java/com/example/cloudrun/PubSubController.java
Labels: cla: yes, samples

#5456 chore(ci): bump btlr version
  .kokoro/tests/run_tests.sh
Labels: automerge, cla: yes, samples

#5457 docs: fix connection pool size for samples
  bigtable/hbase/snippets/src/main/java/com/example/bigtable/ConfigureConnectionPool.java
  bigtable/hbase/snippets/src/test/java/com/example/bigtable/ConfigureConnectionPoolTest.java
Labels: cla: yes, samples

#5508 fix(pubsub): update to the latest released version
  pubsub/spring/pom.xml
Labels: api: pubsub, cla: yes, samples

#5505 Update compute java sample
  compute/cmdline/src/main/java/ComputeEngineSample.java
Labels: cla: yes, samples

#5510 docs: fix command line args in Pub/Sub streaming sample
  pubsub/streaming-analytics/README.md
Labels: cla: yes, samples

#5517 docs: updated comments in getUsageExportBucket
  compute/cloud-client/src/main/java/compute/SetUsageExportBucket.java
Labels: api: compute, cla: yes, samples
