Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2021-08, with the labels that each got.

#5725 Update Cloud Run mvn command in Cloud SQL sample READMEs to address build error.
  cloud-sql/mysql/servlet/README.md
  cloud-sql/postgres/servlet/README.md
  cloud-sql/r2dbc/README.md
  cloud-sql/sqlserver/servlet/README.md
Labels: automerge, cla: yes, samples

#5726 docs: removed outdated comment
  iam/api-client/pom.xml
Labels: cla: yes, samples

#5730 Fix appengine8-helloworld sample app
  appengine-java8/helloworld/build.gradle
  appengine-java8/helloworld/gradle/wrapper/gradle-wrapper.jar
Labels: cla: yes, samples

#5729 healthcare API: update Pub/Sub URI and fix FhirResourceDeletePurge formatting/test
  healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomStorePatch.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStorePatch.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceDeletePurge.java
  healthcare/v1/src/main/java/snippets/healthcare/hl7v2/Hl7v2StorePatch.java
  healthcare/v1/src/test/java/snippets/healthcare/FhirResourceTests.java
Labels: cla: yes, samples

#5634 docs: Bigtable data generator
  bigtable/beam/bulk-data-generator/README.md
  bigtable/beam/bulk-data-generator/pom.xml
  bigtable/beam/bulk-data-generator/src/main/java/bigtable/BulkWrite.java
  bigtable/beam/bulk-data-generator/src/test/java/bigtable/BulkWriteTest.java
Labels: cla: yes, samples

#5763 Add test dependencies to pom.xml
  appengine-java11/cloudsql/README.md
  appengine-java11/cloudsql/pom.xml
Labels: cla: yes, samples

#5771 fix(compute): modified LRO wrappers
  compute/cloud-client/src/main/java/compute/CreateInstance.java
  compute/cloud-client/src/main/java/compute/DeleteInstance.java
  compute/cloud-client/src/main/java/compute/SetUsageExportBucket.java
  compute/cloud-client/src/main/java/compute/WaitForOperation.java
  compute/cloud-client/src/test/java/compute/SnippetsIT.java
Labels: cla: yes, api: compute, samples

#5784 feat: update Transcoder API samples to v1
  media/transcoder/src/main/java/com/example/transcoder/CreateJobFromAdHoc.java
  media/transcoder/src/main/java/com/example/transcoder/CreateJobFromPreset.java
  media/transcoder/src/main/java/com/example/transcoder/CreateJobFromTemplate.java
  media/transcoder/src/main/java/com/example/transcoder/CreateJobTemplate.java
  media/transcoder/src/main/java/com/example/transcoder/CreateJobWithAnimatedOverlay.java
  media/transcoder/src/main/java/com/example/transcoder/CreateJobWithPeriodicImagesSpritesheet.java
  media/transcoder/src/main/java/com/example/transcoder/CreateJobWithSetNumberImagesSpritesheet.java
  media/transcoder/src/main/java/com/example/transcoder/CreateJobWithStaticOverlay.java
  media/transcoder/src/main/java/com/example/transcoder/DeleteJob.java
  media/transcoder/src/main/java/com/example/transcoder/DeleteJobTemplate.java
  media/transcoder/src/main/java/com/example/transcoder/GetJob.java
  media/transcoder/src/main/java/com/example/transcoder/GetJobState.java
  media/transcoder/src/main/java/com/example/transcoder/GetJobTemplate.java
  media/transcoder/src/main/java/com/example/transcoder/ListJobTemplates.java
  media/transcoder/src/main/java/com/example/transcoder/ListJobs.java
  media/transcoder/src/test/java/com/example/transcoder/CreateJobFromTemplateTest.java
  media/transcoder/src/test/java/com/example/transcoder/CreateJobTemplateTest.java
  media/transcoder/src/test/java/com/example/transcoder/DeleteJobTemplateTest.java
  media/transcoder/src/test/java/com/example/transcoder/GetJobTemplateTest.java
  media/transcoder/src/test/java/com/example/transcoder/ListJobTemplateTest.java
Labels: cla: yes, samples

#5747 New sample for GCFv2
  functions/v2/pubsub/subscribe-to-topic/pom.xml
  functions/v2/pubsub/subscribe-to-topic/src/main/java/functions/SubscribeToTopic.java
  functions/v2/pubsub/subscribe-to-topic/src/main/java/functions/eventpojos/PubSubBody.java
  functions/v2/pubsub/subscribe-to-topic/src/test/java/functions/SubscribeToTopicTest.java
Labels: cla: yes, automerge, samples

#5807 docs: remove unused region tag
  bigtable/beam/bulk-data-generator/pom.xml
Labels: cla: yes, samples

#5806 Add documentation tags to R2DBC sample's connection string
  spanner/r2dbc/src/main/resources/application.properties
Labels: cla: yes, samples

#5817 Update CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes, automerge, samples

#5803 feat: adds downscoping with Credential Access Boundaries samples
  auth/README.md
  auth/pom.xml
  auth/src/main/java/com/google/cloud/auth/samples/DownscopingExample.java
  auth/src/test/java/com/google/cloud/auth/samples/DownscopingExampleIT.java
Labels: cla: yes, samples

#5821 Add workflows sample
  workflows/cloud-client/README.md
  workflows/cloud-client/pom.xml
  workflows/cloud-client/src/main/java/com/example/workflows/WorkflowsQuickstart.java
  workflows/cloud-client/src/test/java/com/example/workflows/WorkflowsQuickstartTest.java
  workflows/cloud-client/src/test/java/com/example/workflows/resources/source.yaml
Labels: cla: yes, automerge, samples

#5833 Update CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes, automerge, samples

#5855 Update sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes, automerge, samples

#5856 Revert "Update sync-repo-settings.yaml"
  .github/sync-repo-settings.yaml
Labels: cla: yes, samples
