Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2021-11, with the labels that each got.

#6341 chore: remove unnecessary warning suppressions
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/AbortBatchExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/AutocommitUpdateDataExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/BatchDdlExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/BatchDdlUsingSqlStatementsExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/BatchDmlExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/BatchDmlUsingSqlStatementsExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/ConnectionWithQueryOptionsExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateConnectionExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateConnectionWithCredentialsExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateConnectionWithCustomHostExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateConnectionWithDataSourceExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateConnectionWithDefaultProjectIdExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateConnectionWithPropertiesExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateConnectionWithUrlPropertiesExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateTableExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/GetCommitTimestampExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/GetReadTimestampExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/InsertDataExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/PartitionedDmlExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/ReadOnlyTransactionExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/ReadWriteTransactionExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/SetQueryOptionsExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/SingleUseReadOnlyExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/SingleUseReadOnlyTimestampBoundExample.java
Labels: cla: yes, samples

#6365 Update Cloud SQL sample apps with Kubernetes Engine yaml files.
  cloud-sql/mysql/servlet/deployment.yaml
  cloud-sql/mysql/servlet/service-account.yaml
  cloud-sql/mysql/servlet/service.yaml
  cloud-sql/postgres/servlet/deployment.yaml
  cloud-sql/postgres/servlet/servcie-account.yaml
  cloud-sql/postgres/servlet/service.yaml
Labels: cla: yes, samples

#6380 fix(bigtable): add retry logic to MemecachedTest
  bigtable/memorystore/src/test/java/MemcachedTest.java
Labels: cla: yes, api: bigtable, samples

#6314 Docs: Bigtable + Dataflow hello world cleanups
  bigtable/beam/helloworld/README.md
  bigtable/beam/helloworld/pom.xml
  bigtable/beam/helloworld/src/main/java/HelloWorldRead.java
  bigtable/beam/helloworld/src/main/java/HelloWorldWrite.java
  bigtable/beam/helloworld/src/test/java/HelloWorldTest.java
Labels: cla: yes, samples

#6360 Samples compute create instances
  compute/cloud-client/src/main/java/compute/CreateInstancesAdvanced.java
  compute/cloud-client/src/test/java/compute/SnippetsIT.java
Labels: cla: yes, samples

#6402 Update Cloud SQL sample app yaml files with comments for Kubernetes service accounts.
  cloud-sql/mysql/servlet/deployment.yaml
  cloud-sql/mysql/servlet/service-account.yaml
  cloud-sql/postgres/servlet/deployment.yaml
  cloud-sql/postgres/servlet/service-account.yaml
Labels: cla: yes, samples

#6400 feat: add GCFv2 CAL sample
  functions/v2/cloudevent/log-cloudevent/pom.xml
  functions/v2/cloudevent/log-cloudevent/src/main/java/functions/LogCloudEvent.java
  functions/v2/cloudevent/log-cloudevent/src/test/java/functions/LogCloudEventTest.java
Labels: cla: yes, samples

#6392 feat(run): add Cloud Run Jobs sample
  run/jobs/README.md
  run/jobs/pom.xml
  run/jobs/src/main/java/com/example/JobsExample.java
  run/jobs/src/test/java/com/example/JobsExampleTests.java
Labels: cla: yes, api: run, samples

#6424 Update GCFv2 cloudevent
  functions/v2/cloudevent/log-cloudevent/src/main/java/functions/LogCloudEvent.java
  functions/v2/cloudevent/log-cloudevent/src/test/java/functions/LogCloudEventTest.java
Labels: cla: yes, automerge, samples

#6432 Add GCF Compute sample
  functions/v2/label-compute-instance/pom.xml
  functions/v2/label-compute-instance/src/main/java/functions/AutoLabelInstance.java
  functions/v2/label-compute-instance/src/test/java/functions/AutoLabelInstanceTest.java
Labels: cla: yes, automerge, samples

#6434 restructure gcf/v2 directory
  functions/v2/hello-gcs/pom.xml
  functions/v2/hello-gcs/src/main/java/functions/HelloGcs.java
  functions/v2/hello-gcs/src/main/java/functions/eventpojos/GcsEvent.java
  functions/v2/hello-gcs/src/test/java/functions/HelloGcsTest.java
  functions/v2/log-cloudevent/pom.xml
  functions/v2/log-cloudevent/src/main/java/functions/LogCloudEvent.java
  functions/v2/log-cloudevent/src/test/java/functions/LogCloudEventTest.java
  functions/v2/pubsub/pom.xml
  functions/v2/pubsub/src/main/java/functions/SubscribeToTopic.java
  functions/v2/pubsub/src/main/java/functions/eventpojos/PubSubBody.java
  functions/v2/pubsub/src/test/java/functions/SubscribeToTopicTest.java
Labels: cla: yes, samples
