Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2022-11, with the labels that each got.

#7364 feat: migrate code from googleapis/java-batch
  batch/snippets/pom.xml
  batch/snippets/src/main/java/CreateWithContainerNoMounting.java
  batch/snippets/src/main/java/CreateWithScriptNoMounting.java
  batch/snippets/src/main/java/DeleteJob.java
  batch/snippets/src/main/java/GetJob.java
  batch/snippets/src/main/java/ListJobs.java
  batch/snippets/src/test/java/BatchBasicIT.java
Labels: samples

#7385 docs(compute-samples): add samples for image creation and deletion
  compute/cloud-client/src/main/java/compute/windows/osimage/CreateImage.java
  compute/cloud-client/src/main/java/compute/windows/osimage/DeleteImage.java
  compute/cloud-client/src/test/java/compute/windows/osimage/WindowsOsImageIT.java
Labels: samples

#7356 feat: migrate code from googleapis/java-mediatranslation
  mediatranslation/generated/com/google/cloud/mediatranslation/v1beta1/speechtranslationserviceclient/create/SyncCreateSetCredentialsProvider.java
  mediatranslation/generated/com/google/cloud/mediatranslation/v1beta1/speechtranslationserviceclient/create/SyncCreateSetCredentialsProvider1.java
  mediatranslation/generated/com/google/cloud/mediatranslation/v1beta1/speechtranslationserviceclient/create/SyncCreateSetEndpoint.java
  mediatranslation/generated/com/google/cloud/mediatranslation/v1beta1/speechtranslationserviceclient/streamingtranslatespeech/AsyncStreamingTranslateSpeech.java
  mediatranslation/generated/com/google/cloud/mediatranslation/v1beta1/speechtranslationservicesettings/streamingtranslatespeech/SyncStreamingTranslateSpeech.java
  mediatranslation/generated/com/google/cloud/mediatranslation/v1beta1/stub/speechtranslationservicestubsettings/streamingtranslatespeech/SyncStreamingTranslateSpeech.java
Labels: samples

#7402 migrate code from googleapis/java-talent
  talent/snippets/pom.xml
  talent/snippets/src/main/java/com/example/jobs/CommuteSearchJobs.java
  talent/snippets/src/main/java/com/example/jobs/CustomRankingSearchJobs.java
  talent/snippets/src/main/java/com/example/jobs/HistogramSearchJobs.java
  talent/snippets/src/main/java/com/example/jobs/JobSearchAutoCompleteJobTitle.java
  talent/snippets/src/main/java/com/example/jobs/JobSearchCreateClientEvent.java
  talent/snippets/src/main/java/com/example/jobs/JobSearchCreateCompany.java
  talent/snippets/src/main/java/com/example/jobs/JobSearchCreateJob.java
  talent/snippets/src/main/java/com/example/jobs/JobSearchCreateJobCustomAttributes.java
  talent/snippets/src/main/java/com/example/jobs/JobSearchCreateTenant.java
  talent/snippets/src/main/java/com/example/jobs/JobSearchDeleteCompany.java
  talent/snippets/src/main/java/com/example/jobs/JobSearchDeleteJob.java
  talent/snippets/src/main/java/com/example/jobs/JobSearchDeleteTenant.java
  talent/snippets/src/main/java/com/example/jobs/JobSearchGetCompany.java
  talent/snippets/src/main/java/com/example/jobs/JobSearchGetJob.java
  talent/snippets/src/main/java/com/example/jobs/JobSearchGetTenant.java
  talent/snippets/src/main/java/com/example/jobs/JobSearchListCompanies.java
  talent/snippets/src/main/java/com/example/jobs/JobSearchListJobs.java
  talent/snippets/src/main/java/com/example/jobs/JobSearchListTenants.java
  talent/snippets/src/test/java/CommuteSearchJobsTest.java
  talent/snippets/src/test/java/CustomRankingSearchJobsTest.java
  talent/snippets/src/test/java/HistogramSearchJobsTest.java
  talent/snippets/src/test/java/JobSearchAutoCompleteJobTitleTest.java
  talent/snippets/src/test/java/JobSearchCreateCompanyTest.java
  talent/snippets/src/test/java/JobSearchCreateJobTest.java
  talent/snippets/src/test/java/JobSearchCreateJobWithCustomAttrTest.java
  talent/snippets/src/test/java/JobSearchCreateTenantTest.java
  talent/snippets/src/test/java/JobSearchDeleteCompanyTest.java
  talent/snippets/src/test/java/JobSearchDeleteJobTest.java
  talent/snippets/src/test/java/JobSearchDeleteTenantTest.java
  talent/snippets/src/test/java/JobSearchGetCompanyTest.java
  talent/snippets/src/test/java/JobSearchGetJobTest.java
  talent/snippets/src/test/java/JobSearchGetTenantTest.java
  talent/snippets/src/test/java/JobSearchListCompaniesTest.java
  talent/snippets/src/test/java/JobSearchListJobsTest.java
  talent/snippets/src/test/java/JobSearchListTenantsTest.java
Labels: samples

#7404 Java monitoring migration
  monitoring/v3/pom.xml
  monitoring/v3/src/main/java/com/example/monitoring/AlertSample.java
  monitoring/v3/src/main/java/com/example/monitoring/CreateAlertPolicy.java
  monitoring/v3/src/main/java/com/example/monitoring/CreateMetricDescriptor.java
  monitoring/v3/src/main/java/com/example/monitoring/CreateTimeSeries.java
  monitoring/v3/src/main/java/com/example/monitoring/DeleteAlertPolicy.java
  monitoring/v3/src/main/java/com/example/monitoring/DeleteMetricDescriptor.java
  monitoring/v3/src/main/java/com/example/monitoring/DeleteNotificationChannel.java
  monitoring/v3/src/main/java/com/example/monitoring/EnableDisableAlertPolicy.java
  monitoring/v3/src/main/java/com/example/monitoring/GetAlertPolicy.java
  monitoring/v3/src/main/java/com/example/monitoring/GetMonitoredResource.java
  monitoring/v3/src/main/java/com/example/monitoring/ListAlertPolicy.java
  monitoring/v3/src/main/java/com/example/monitoring/ListMetricDescriptor.java
  monitoring/v3/src/main/java/com/example/monitoring/ListTimeSeries.java
  monitoring/v3/src/main/java/com/example/monitoring/MonitoredResourcesList.java
  monitoring/v3/src/main/java/com/example/monitoring/QuickstartSample.java
  monitoring/v3/src/main/java/com/example/monitoring/TimeSeriesHeadersList.java
  monitoring/v3/src/main/java/com/example/monitoring/UpdateAlertPolicy.java
  monitoring/v3/src/main/java/com/example/monitoring/UptimeSample.java
  monitoring/v3/src/test/java/com/example/monitoring/AlertIT.java
  monitoring/v3/src/test/java/com/example/monitoring/CreateAlertPolicyIT.java
  monitoring/v3/src/test/java/com/example/monitoring/CreateMetricDescriptorIT.java
  monitoring/v3/src/test/java/com/example/monitoring/DeleteAlertPolicyIT.java
  monitoring/v3/src/test/java/com/example/monitoring/DeleteMetricDescriptorIT.java
  monitoring/v3/src/test/java/com/example/monitoring/DeleteNotificationChannelIT.java
  monitoring/v3/src/test/java/com/example/monitoring/EnableDisableAlertPolicyIT.java
  monitoring/v3/src/test/java/com/example/monitoring/GetAlertPolicyIT.java
  monitoring/v3/src/test/java/com/example/monitoring/GetMonitoredResourceIT.java
  monitoring/v3/src/test/java/com/example/monitoring/ListAlertPolicyIT.java
  monitoring/v3/src/test/java/com/example/monitoring/ListMetricDescriptorIT.java
  monitoring/v3/src/test/java/com/example/monitoring/ListMonitoredResourcesIT.java
  monitoring/v3/src/test/java/com/example/monitoring/QuickstartSampleIT.java
  monitoring/v3/src/test/java/com/example/monitoring/TimeSeriesIT.java
  monitoring/v3/src/test/java/com/example/monitoring/UpdateAlertPolicyIT.java
  monitoring/v3/src/test/java/com/example/monitoring/UptimeIT.java
Labels: samples

#7409 migrate code from googleapis/java-optimization
  optimization/snippets/pom.xml
  optimization/snippets/resources/sync_request.textproto
  optimization/snippets/src/main/java/com/example/optimizationai/AsyncApi.java
  optimization/snippets/src/main/java/com/example/optimizationai/GetOperation.java
  optimization/snippets/src/main/java/com/example/optimizationai/SyncApi.java
  optimization/snippets/src/main/java/com/example/optimizationai/SyncApiWithLongTimeout.java
  optimization/snippets/src/test/java/com/example/optimizationai/AsyncApiTest.java
  optimization/snippets/src/test/java/com/example/optimizationai/GetOperationTest.java
  optimization/snippets/src/test/java/com/example/optimizationai/SyncApiTest.java
  optimization/snippets/src/test/java/com/example/optimizationai/SyncApiWithLongTimeoutTest.java
Labels: samples

#7411 samples: migrate code from googleapis/java-contact-center-insights
  contact-center-insights/pom.xml
  contact-center-insights/src/main/java/com/example/contactcenterinsights/CreateAnalysis.java
  contact-center-insights/src/main/java/com/example/contactcenterinsights/CreateConversation.java
  contact-center-insights/src/main/java/com/example/contactcenterinsights/CreateConversationWithTtl.java
  contact-center-insights/src/main/java/com/example/contactcenterinsights/CreateIssueModel.java
  contact-center-insights/src/main/java/com/example/contactcenterinsights/CreatePhraseMatcherAllOf.java
  contact-center-insights/src/main/java/com/example/contactcenterinsights/CreatePhraseMatcherAnyOf.java
  contact-center-insights/src/main/java/com/example/contactcenterinsights/EnablePubSubNotifications.java
  contact-center-insights/src/main/java/com/example/contactcenterinsights/ExportToBigquery.java
  contact-center-insights/src/main/java/com/example/contactcenterinsights/GetOperation.java
  contact-center-insights/src/main/java/com/example/contactcenterinsights/SetProjectTtl.java
  contact-center-insights/src/test/java/com/example/contactcenterinsights/CreateAnalysisIT.java
  contact-center-insights/src/test/java/com/example/contactcenterinsights/CreateConversationIT.java
  contact-center-insights/src/test/java/com/example/contactcenterinsights/CreateConversationWithTtlIT.java
  contact-center-insights/src/test/java/com/example/contactcenterinsights/CreateIssueModelIT.java
  contact-center-insights/src/test/java/com/example/contactcenterinsights/CreatePhraseMatcherAllOfIT.java
  contact-center-insights/src/test/java/com/example/contactcenterinsights/CreatePhraseMatcherAnyOfIT.java
  contact-center-insights/src/test/java/com/example/contactcenterinsights/EnablePubSubNotificationsIT.java
  contact-center-insights/src/test/java/com/example/contactcenterinsights/ExportToBigqueryIT.java
  contact-center-insights/src/test/java/com/example/contactcenterinsights/GetOperationIT.java
  contact-center-insights/src/test/java/com/example/contactcenterinsights/SetProjectTtlIT.java
Labels: samples

#7415 migrate code from googleapis/java-webrisk
  webrisk/pom.xml
  webrisk/src/main/java/webrisk/SearchUriExample.java
  webrisk/src/main/java/webrisk/SubmitUriExample.java
  webrisk/src/test/java/webrisk/SearchUriExampleTest.java
  webrisk/src/test/java/webrisk/SubmitUriExampleTest.java
Labels: samples

#7416 chore: updated pom for samples migration
  webrisk/pom.xml
Labels: samples

#7407 migrate code from googleapis/java-dataproc
  dataproc/pom.xml
  dataproc/src/main/java/CreateCluster.java
  dataproc/src/main/java/CreateClusterWithAutoscaling.java
  dataproc/src/main/java/InstantiateInlineWorkflowTemplate.java
  dataproc/src/main/java/Quickstart.java
  dataproc/src/main/java/SubmitHadoopFsJob.java
  dataproc/src/main/java/SubmitJob.java
  dataproc/src/test/java/CreateClusterTest.java
  dataproc/src/test/java/CreateClusterWithAutoscalingTest.java
  dataproc/src/test/java/InstantiateInlineWorkflowTemplateTest.java
  dataproc/src/test/java/QuickstartTest.java
  dataproc/src/test/java/SubmitHadoopFsJobTest.java
  dataproc/src/test/java/SubmitJobTest.java
Labels: samples

#7426 chore: remove conflicting README
  vision/spring-framework/README.md
Labels: automerge, samples

#7423 migrate code from googleapis/java-texttospeech
  texttospeech/snippets/pom.xml
  texttospeech/snippets/resources/example.ssml
  texttospeech/snippets/resources/example.txt
  texttospeech/snippets/resources/expected_example.mp3
  texttospeech/snippets/resources/hello.ssml
  texttospeech/snippets/resources/hello.txt
  texttospeech/snippets/src/main/java/com/example/texttospeech/ListAllSupportedVoices.java
  texttospeech/snippets/src/main/java/com/example/texttospeech/ListAllSupportedVoicesBeta.java
  texttospeech/snippets/src/main/java/com/example/texttospeech/QuickstartSample.java
  texttospeech/snippets/src/main/java/com/example/texttospeech/QuickstartSampleBeta.java
  texttospeech/snippets/src/main/java/com/example/texttospeech/SsmlAddresses.java
  texttospeech/snippets/src/main/java/com/example/texttospeech/SynthesizeFile.java
  texttospeech/snippets/src/main/java/com/example/texttospeech/SynthesizeFileBeta.java
  texttospeech/snippets/src/main/java/com/example/texttospeech/SynthesizeText.java
  texttospeech/snippets/src/main/java/com/example/texttospeech/SynthesizeTextBeta.java
  texttospeech/snippets/src/test/java/com/example/texttospeech/ListAllSupportedVoicesBetaIT.java
  texttospeech/snippets/src/test/java/com/example/texttospeech/ListAllSupportedVoicesIT.java
  texttospeech/snippets/src/test/java/com/example/texttospeech/SsmlAddressesIT.java
  texttospeech/snippets/src/test/java/com/example/texttospeech/SynthesizeFileBetaIT.java
  texttospeech/snippets/src/test/java/com/example/texttospeech/SynthesizeFileIT.java
  texttospeech/snippets/src/test/java/com/example/texttospeech/SynthesizeTextBetaIT.java
  texttospeech/snippets/src/test/java/com/example/texttospeech/SynthesizeTextIT.java
Labels: samples

#7427 samples: migrate code from googleapis/java-document-ai
  document-ai/pom.xml
  document-ai/resources/document_quality_poor.pdf
  document-ai/resources/handwritten_form.pdf
  document-ai/resources/invoice.pdf
  document-ai/resources/multi_document.pdf
  document-ai/resources/us_driver_license.pdf
  document-ai/src/main/java/documentai/v1/BatchProcessDocument.java
  document-ai/src/main/java/documentai/v1/ProcessDocument.java
  document-ai/src/main/java/documentai/v1/QuickStart.java
  document-ai/src/main/java/documentai/v1beta3/ProcessFormDocument.java
  document-ai/src/main/java/documentai/v1beta3/ProcessOcrDocument.java
  document-ai/src/main/java/documentai/v1beta3/ProcessQualityDocument.java
  document-ai/src/main/java/documentai/v1beta3/ProcessSpecializedDocument.java
  document-ai/src/main/java/documentai/v1beta3/ProcessSplitterDocument.java
  document-ai/src/test/java/documentai/v1/BatchProcessDocumentTest.java
  document-ai/src/test/java/documentai/v1/ProcessDocumentTest.java
  document-ai/src/test/java/documentai/v1/QuickStartTest.java
  document-ai/src/test/java/documentai/v1beta3/ProcessFormDocumentTest.java
  document-ai/src/test/java/documentai/v1beta3/ProcessOcrDocumentTest.java
  document-ai/src/test/java/documentai/v1beta3/ProcessQualityDocumentTest.java
  document-ai/src/test/java/documentai/v1beta3/ProcessSpecializedDocumentTest.java
  document-ai/src/test/java/documentai/v1beta3/ProcessSplitterDocumentTest.java
Labels: samples

#7430 fix: bump spark version in readme
  bigtable/spark/README.md
Labels: samples

#7442 chore(jobs): add normalized region tags with product prefix
  jobs/v3/src/main/java/com/google/samples/GeneralSearchSample.java
Labels: api: jobs, samples

#7412 migrate code from googleapis/java-datacatalog
  datacatalog/snippets/pom.xml
  datacatalog/snippets/src/main/java/com/example/datacatalog/CreateCustomEntry.java
  datacatalog/snippets/src/main/java/com/example/datacatalog/CreateEntry.java
  datacatalog/snippets/src/main/java/com/example/datacatalog/CreateEntryGroup.java
  datacatalog/snippets/src/main/java/com/example/datacatalog/CreateFilesetEntry.java
  datacatalog/snippets/src/main/java/com/example/datacatalog/CreateTagTemplate.java
  datacatalog/snippets/src/main/java/com/example/datacatalog/DeleteEntry.java
  datacatalog/snippets/src/main/java/com/example/datacatalog/DeleteEntryGroup.java
  datacatalog/snippets/src/main/java/com/example/datacatalog/DeleteTagTemplate.java
  datacatalog/snippets/src/main/java/com/example/datacatalog/GetEntry.java
  datacatalog/snippets/src/main/java/com/example/datacatalog/GetEntryGroup.java
  datacatalog/snippets/src/main/java/com/example/datacatalog/GetTagTemplate.java
  datacatalog/snippets/src/main/java/com/example/datacatalog/GrantTagTemplateUserRole.java
  datacatalog/snippets/src/main/java/com/example/datacatalog/ListEntries.java
  datacatalog/snippets/src/main/java/com/example/datacatalog/ListEntryGroups.java
  datacatalog/snippets/src/main/java/com/example/datacatalog/LookupEntryBigQueryDataset.java
  datacatalog/snippets/src/main/java/com/example/datacatalog/LookupEntryBigQueryTable.java
  datacatalog/snippets/src/main/java/com/example/datacatalog/LookupEntryPubSubTopic.java
  datacatalog/snippets/src/main/java/com/example/datacatalog/Quickstart.java
  datacatalog/snippets/src/main/java/com/example/datacatalog/SearchAssets.java
  datacatalog/snippets/src/main/java/com/example/datacatalog/UpdateEntry.java
  datacatalog/snippets/src/main/java/com/example/datacatalog/UpdateEntryGroup.java
  datacatalog/snippets/src/main/java/com/example/datacatalog/UpdateTagTemplate.java
  datacatalog/snippets/src/test/java/com/example/datacatalog/CreateCustomEntryIT.java
  datacatalog/snippets/src/test/java/com/example/datacatalog/CreateEntryGroupIT.java
  datacatalog/snippets/src/test/java/com/example/datacatalog/CreateEntryIT.java
  datacatalog/snippets/src/test/java/com/example/datacatalog/CreateEntryTests.java
  datacatalog/snippets/src/test/java/com/example/datacatalog/CreateFilesetEntryIT.java
  datacatalog/snippets/src/test/java/com/example/datacatalog/CreateTagTemplateIT.java
  datacatalog/snippets/src/test/java/com/example/datacatalog/DeleteEntryGroupIT.java
  datacatalog/snippets/src/test/java/com/example/datacatalog/DeleteEntryIT.java
  datacatalog/snippets/src/test/java/com/example/datacatalog/DeleteTagTemplateIT.java
  datacatalog/snippets/src/test/java/com/example/datacatalog/GetEntryGroupIT.java
  datacatalog/snippets/src/test/java/com/example/datacatalog/GetEntryIT.java
  datacatalog/snippets/src/test/java/com/example/datacatalog/GetTagTemplateIT.java
  datacatalog/snippets/src/test/java/com/example/datacatalog/GrantTagTemplateUserRoleIT.java
  datacatalog/snippets/src/test/java/com/example/datacatalog/ListEntriesIT.java
  datacatalog/snippets/src/test/java/com/example/datacatalog/ListEntryGroupsIT.java
  datacatalog/snippets/src/test/java/com/example/datacatalog/LookupEntryTests.java
  datacatalog/snippets/src/test/java/com/example/datacatalog/QuickstartIT.java
  datacatalog/snippets/src/test/java/com/example/datacatalog/SearchAssetsIT.java
  datacatalog/snippets/src/test/java/com/example/datacatalog/UpdateEntryGroupIT.java
  datacatalog/snippets/src/test/java/com/example/datacatalog/UpdateEntryIT.java
  datacatalog/snippets/src/test/java/com/example/datacatalog/UpdateTagTemplateIT.java
Labels: samples

#7459 chore(functions): switch back to Pub/Sub POJOs
  functions/concepts/retry-pubsub/pom.xml
  functions/concepts/retry-pubsub/src/main/java/functions/RetryPubSub.java
  functions/concepts/retry-pubsub/src/main/java/functions/eventpojos/PubsubMessage.java
  functions/concepts/retry-pubsub/src/test/java/functions/RetryPubSubTest.java
  functions/concepts/retry-timeout/pom.xml
  functions/concepts/retry-timeout/src/main/java/functions/RetryTimeout.java
  functions/concepts/retry-timeout/src/main/java/functions/eventpojos/PubsubMessage.java
  functions/concepts/retry-timeout/src/test/java/functions/RetryTimeoutTest.java
  functions/helloworld/groovy-hello-pubsub/pom.xml
  functions/helloworld/groovy-hello-pubsub/src/main/groovy/functions/GroovyHelloPubSub.groovy
  functions/helloworld/groovy-hello-pubsub/src/main/groovy/functions/eventpojos/PubsubMessage.groovy
  functions/helloworld/groovy-hello-pubsub/src/test/java/functions/GroovyHelloPubSubTest.java
  functions/helloworld/hello-gcs/pom.xml
  functions/helloworld/hello-pubsub/pom.xml
  functions/helloworld/hello-pubsub/src/main/java/functions/HelloPubSub.java
  functions/helloworld/hello-pubsub/src/main/java/functions/eventpojos/PubsubMessage.java
  functions/helloworld/hello-pubsub/src/test/java/functions/HelloPubSubTest.java
  functions/helloworld/kotlin-hello-pubsub/pom.xml
  functions/helloworld/kotlin-hello-pubsub/src/main/kotlin/functions/KotlinHelloBackground.kt
  functions/helloworld/kotlin-hello-pubsub/src/main/kotlin/functions/eventpojos/PubsubMessage.kt
  functions/helloworld/kotlin-hello-pubsub/src/test/java/functions/KotlinHelloPubSubTest.java
  functions/helloworld/scala-hello-pubsub/pom.xml
  functions/helloworld/scala-hello-pubsub/src/main/scala/functions/ScalaHelloPubSub.scala
  functions/helloworld/scala-hello-pubsub/src/main/scala/functions/eventpojos/PubSubMessage.scala
  functions/helloworld/scala-hello-pubsub/src/test/java/functions/ScalaHelloPubSubTest.java
  functions/imagemagick/pom.xml
  functions/logging/stackdriver-logging/pom.xml
  functions/logging/stackdriver-logging/src/main/java/functions/StackdriverLogging.java
  functions/logging/stackdriver-logging/src/main/java/functions/eventpojos/PubsubMessage.java
  functions/logging/stackdriver-logging/src/test/java/functions/StackdriverLoggingTest.java
  functions/ocr/ocr-process-image/pom.xml
  functions/ocr/ocr-process-image/src/main/java/functions/eventpojos/PubsubMessage.java
  functions/ocr/ocr-save-result/pom.xml
  functions/ocr/ocr-save-result/src/main/java/functions/OcrSaveResult.java
  functions/ocr/ocr-save-result/src/main/java/functions/eventpojos/PubsubMessage.java
  functions/ocr/ocr-save-result/src/test/java/functions/OcrSaveResultTest.java
  functions/ocr/ocr-translate-text/pom.xml
  functions/ocr/ocr-translate-text/src/main/java/functions/OcrTranslateText.java
  functions/ocr/ocr-translate-text/src/main/java/functions/eventpojos/Message.java
  functions/ocr/ocr-translate-text/src/test/java/functions/OcrTranslateTextTest.java
  functions/pubsub/publish-message/src/main/java/functions/PublishMessage.java
  functions/pubsub/publish-message/src/main/java/functions/eventpojos/PubsubMessage.java
  functions/pubsub/subscribe-to-topic/pom.xml
  functions/pubsub/subscribe-to-topic/src/main/java/functions/SubscribeToTopic.java
  functions/pubsub/subscribe-to-topic/src/main/java/functions/eventpojos/PubsubMessage.java
  functions/pubsub/subscribe-to-topic/src/test/java/functions/SubscribeToTopicTest.java
  functions/v2/pubsub/src/main/java/functions/eventpojos/PubSubBody.java
Labels: api: cloudfunctions, samples

#7457 chore: remove obsolete region tags
  jobs/v3/src/main/java/com/google/samples/GeneralSearchSample.java
Labels: samples
