Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2022-02, with the labels that each got.

#6696 Update Cloud SQL for SQL Server sample app with Kubernetes Engine yaml files.
  cloud-sql/sqlserver/servlet/deployment.yaml
  cloud-sql/sqlserver/servlet/service-account.yaml
  cloud-sql/sqlserver/servlet/service.yaml
Labels: samples

#6702 fix(functions/v2): Fix typo
  functions/v2/log-cloudevent/src/main/java/functions/LogCloudEvent.java
  functions/v2/log-cloudevent/src/test/java/functions/LogCloudEventTest.java
Labels: api: cloudfunctions, samples

#6698 samples: Update Bigtable workload generator to have a timer
  bigtable/beam/workload-generator/README.md
  bigtable/beam/workload-generator/src/main/java/bigtable/WorkloadGenerator.java
  bigtable/beam/workload-generator/src/test/java/bigtable/WorkloadGeneratorTest.java
Labels: samples

#6634 docs: fix Bigtable workload generator (df delete)
  bigtable/beam/workload-generator/README.md
Labels: samples

#6708 Fix typo in comment from singple to single.
  appengine-java8/pubsub/src/main/java/com/example/appengine/pubsub/PubSubAuthenticatedPush.java
Labels: samples, automerge: exact

#6710 bigtable: migrate to jackson-databind
  bigtable/scheduled-backups/pom.xml
  bigtable/scheduled-backups/src/main/java/com/example/cloud/bigtable/scheduledbackups/CreateBackup.java
Labels: api: bigtable, samples

#6715 samples(pubsublite): document edge case to PubsubliteToGcs
  pubsublite/streaming-analytics/src/main/java/examples/PubsubliteToGcs.java
Labels: samples

#6712 docs(compute-samples): init samples and test for delete protection
  compute/cloud-client/src/main/java/compute/deleteprotection/CreateInstanceDeleteProtection.java
  compute/cloud-client/src/main/java/compute/deleteprotection/GetDeleteProtection.java
  compute/cloud-client/src/main/java/compute/deleteprotection/SetDeleteProtection.java
  compute/cloud-client/src/test/java/compute/InstanceTemplatesIT.java
  compute/cloud-client/src/test/java/compute/SnippetsIT.java
  compute/cloud-client/src/test/java/compute/Util.java
  compute/cloud-client/src/test/java/compute/deleteprotection/DeleteProtectionIT.java
Labels: cla: yes, api: compute, samples

#6707 build: fix sbt assembly rules to properly generate a jar for bigtable > 2.0.0-alpha
  bigtable/spark/build.sbt
Labels: automerge, samples

#6716 docs(compute-samples): fix comment
  compute/cloud-client/src/main/java/compute/ResetInstance.java
Labels: samples

#6717 healthcare API: update FhirResourceSearchGet to use CloudHealthcareClient
  healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceSearchGet.java
  healthcare/v1/src/test/java/snippets/healthcare/FhirResourceTests.java
Labels: samples

#6771 Revert "chore(deps): update hbaseversion for org.apache.hbase to v2.4.9"
  bigtable/spark/build.sbt
Labels: samples

#6719 chore: update GCF v2 Sample
  functions/v2/pubsub/src/main/java/functions/SubscribeToTopic.java
  functions/v2/pubsub/src/test/java/functions/SubscribeToTopicTest.java
Labels: samples

#6709 chore: add E2E tests for Cloud Run
  run/jobs/README.md
  run/jobs/pom.xml
  run/jobs/src/main/java/com/example/JobsExample.java
  run/jobs/src/test/java/com/example/JobsIntegrationTests.java
  run/jobs/src/test/java/com/example/resources/e2e_test_cleanup.yaml
  run/jobs/src/test/java/com/example/resources/e2e_test_setup.yaml
  run/jobs/src/test/java/com/example/resources/retry.sh
Labels: samples

#6700 samples: added dialogflow webhook snippet
  dialogflow/basic-webhook/pom.xml
  dialogflow/basic-webhook/src/main/java/com/example/dialogflow/cx/BasicWebhook.java
  dialogflow/basic-webhook/src/test/java/com/example/dialogflow/cx/BasicWebhookIT.java
Labels: needs work, samples

#6703 feat: add cloud spanner change streams samples
  spanner/changestreams/README.md
  spanner/changestreams/pom.xml
  spanner/changestreams/src/main/java/com/example/spanner/changestreams/ChangeStreamRecordMapper.java
  spanner/changestreams/src/main/java/com/example/spanner/changestreams/ChangeStreamSample.java
  spanner/changestreams/src/main/java/com/example/spanner/changestreams/model/ChangeStreamRecord.java
  spanner/changestreams/src/main/java/com/example/spanner/changestreams/model/ChildPartition.java
  spanner/changestreams/src/main/java/com/example/spanner/changestreams/model/ChildPartitionsRecord.java
  spanner/changestreams/src/main/java/com/example/spanner/changestreams/model/ColumnType.java
  spanner/changestreams/src/main/java/com/example/spanner/changestreams/model/DataChangeRecord.java
  spanner/changestreams/src/main/java/com/example/spanner/changestreams/model/HeartbeatRecord.java
  spanner/changestreams/src/main/java/com/example/spanner/changestreams/model/Mod.java
  spanner/changestreams/src/main/java/com/example/spanner/changestreams/model/ModType.java
  spanner/changestreams/src/main/java/com/example/spanner/changestreams/model/TypeCode.java
  spanner/changestreams/src/main/java/com/example/spanner/changestreams/model/ValueCaptureType.java
  spanner/changestreams/src/main/java/com/example/spanner/changestreams/model/package-info.java
  spanner/changestreams/src/test/java/com/example/spanner/changestreams/ChangeStreamSampleIT.java
Labels: samples
