Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2022-10, with the labels that each got.

#7324 Update Cloud SQL sample App Engine xml and README
  cloud-sql/mysql/servlet/README.md
  cloud-sql/mysql/servlet/src/main/webapp/WEB-INF/appengine-web.xml
  cloud-sql/postgres/servlet/README.md
  cloud-sql/postgres/servlet/src/main/webapp/WEB-INF/appengine-web.xml
  cloud-sql/sqlserver/servlet/README.md
  cloud-sql/sqlserver/servlet/src/main/webapp/WEB-INF/appengine-web.xml
Labels: samples

#7326 Add S3 compatible transfer sample
  storage-transfer/pom.xml
  storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/TransferFromS3CompatibleSource.java
  storage-transfer/src/test/java/com/google/cloud/storage/storagetransfer/samples/test/ITStoragetransferSamplesTest.java
Labels: samples, owlbot:run

#7328 fix(samples): Fix Video Stitcher region tag prefix
  media/stitcher/src/main/java/com/example/stitcher/CreateCdnKey.java
  media/stitcher/src/main/java/com/example/stitcher/CreateLiveSession.java
  media/stitcher/src/main/java/com/example/stitcher/CreateSlate.java
  media/stitcher/src/main/java/com/example/stitcher/CreateVodSession.java
  media/stitcher/src/main/java/com/example/stitcher/DeleteCdnKey.java
  media/stitcher/src/main/java/com/example/stitcher/DeleteSlate.java
  media/stitcher/src/main/java/com/example/stitcher/GetCdnKey.java
  media/stitcher/src/main/java/com/example/stitcher/GetLiveAdTagDetail.java
  media/stitcher/src/main/java/com/example/stitcher/GetLiveSession.java
  media/stitcher/src/main/java/com/example/stitcher/GetSlate.java
  media/stitcher/src/main/java/com/example/stitcher/GetVodAdTagDetail.java
  media/stitcher/src/main/java/com/example/stitcher/GetVodSession.java
  media/stitcher/src/main/java/com/example/stitcher/GetVodStitchDetail.java
  media/stitcher/src/main/java/com/example/stitcher/ListCdnKeys.java
  media/stitcher/src/main/java/com/example/stitcher/ListLiveAdTagDetails.java
  media/stitcher/src/main/java/com/example/stitcher/ListSlates.java
  media/stitcher/src/main/java/com/example/stitcher/ListVodAdTagDetails.java
  media/stitcher/src/main/java/com/example/stitcher/ListVodStitchDetails.java
  media/stitcher/src/main/java/com/example/stitcher/UpdateCdnKey.java
  media/stitcher/src/main/java/com/example/stitcher/UpdateSlate.java
Labels: samples

#7333 fix(samples): Fix VertexAI IDs for CBT fraud-detection use case
  bigtable/use-cases/fraudDetection/terraform/scripts/vertexai_build.sh
  bigtable/use-cases/fraudDetection/terraform/scripts/vertexai_destroy.sh
Labels: samples

#7337 chore: Remove unused code coverage badge
  README.md
  codecov.yml
Labels: samples

#7339 test: Temporarily ignore flaky Spanner test
  spanner/changestreams/src/test/java/com/example/spanner/changestreams/ChangeStreamSampleIT.java
Labels: samples

#7341 test: add retries for flaky GAE test
  unittests/src/test/java/com/google/appengine/samples/DeferredTaskTest.java
Labels: samples

#7343 fix(opencensus): add core dependency
  opencensus/pom.xml
Labels: samples

#7344 chore(deps): cleanup trace dependencies
  trace/pom.xml
Labels: samples

#7342 test: Address IOT flaky tests
  iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java
Labels: samples

#7347 chore: Update README.md with nightly build status
  README.md
Labels: samples

#7187 test: add got to assertion message
  spanner/changestreams/src/test/java/com/example/spanner/changestreams/ChangeStreamSampleIT.java
Labels: samples

#7346 docs(compute-samples): improving snapshot samples
  compute/cloud-client/src/main/java/compute/disks/DeleteSnapshotsByFilter.java
  compute/cloud-client/src/main/java/compute/disks/GetSnapshot.java
  compute/cloud-client/src/test/java/compute/InstanceTemplatesIT.java
  compute/cloud-client/src/test/java/compute/disks/SnapshotsIT.java
Labels: api: compute, samples

#7349 test: handle expected exception when running IoT GUI test
  iot/api-client/codelab/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java
Labels: api: cloudiot, samples

#7334 fix(storagetransfer):use AWS creds from environment variable directly in sample
  storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/TransferFromAws.java
  storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/apiary/TransferFromAwsApiary.java
  storage-transfer/src/test/java/com/google/cloud/storage/storagetransfer/samples/test/ITStoragetransferSamplesTest.java
Labels: api: storagetransfer, samples

#7350 fix: add gae region tag
  appengine-java8/datastore/src/test/java/com/example/appengine/EntitiesTest.java
Labels: samples

#7353 test: address "functions in use" build failures
  .kokoro/tests/build_cloud_functions.sh
Labels: samples

#7354 test: handle expected exception in GUI test
  iot/api-client/codelab/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java
Labels: api: cloudiot, samples

#7352 chore: update GAE Oauth2 sample
  appengine-java11/oauth2/pom.xml
  appengine-java11/oauth2/src/main/appengine/app.yaml
  appengine-java11/oauth2/src/main/java/com/example/appengine/Utils.java
Labels: api: appengine, samples

#7362 deps: update com.google.apis:google-api-services-kgsearch to v1-rev20200809-2.0.0
  functions/slack/pom.xml
Labels: samples

#7360 fix(deps): update dependency add new line in pom file for CBT fraud-detection
  bigtable/use-cases/fraudDetection/pom.xml
Labels: samples

#7357 add 2nd gen GCF OCR sample
  functions/v2/ocr/ocr-process-image/pom.xml
  functions/v2/ocr/ocr-process-image/src/main/java/functions/OcrProcessImage.java
  functions/v2/ocr/ocr-process-image/src/main/java/functions/OcrTranslateApiMessage.java
  functions/v2/ocr/ocr-process-image/src/main/java/functions/eventpojos/CustomerEncryption.java
  functions/v2/ocr/ocr-process-image/src/main/java/functions/eventpojos/StorageObjectData.java
  functions/v2/ocr/ocr-process-image/src/test/java/functions/OcrProcessImageTest.java
  functions/v2/ocr/ocr-save-result/pom.xml
  functions/v2/ocr/ocr-save-result/src/main/java/functions/OcrSaveResult.java
  functions/v2/ocr/ocr-save-result/src/main/java/functions/OcrTranslateApiMessage.java
  functions/v2/ocr/ocr-save-result/src/main/java/functions/eventpojos/Message.java
  functions/v2/ocr/ocr-save-result/src/main/java/functions/eventpojos/MessagePublishedData.java
  functions/v2/ocr/ocr-save-result/src/test/java/functions/OcrSaveResultTest.java
  functions/v2/ocr/ocr-translate-text/pom.xml
  functions/v2/ocr/ocr-translate-text/src/main/java/functions/OcrTranslateApiMessage.java
  functions/v2/ocr/ocr-translate-text/src/main/java/functions/OcrTranslateText.java
  functions/v2/ocr/ocr-translate-text/src/main/java/functions/eventpojos/Message.java
  functions/v2/ocr/ocr-translate-text/src/main/java/functions/eventpojos/MessagePublishedData.java
  functions/v2/ocr/ocr-translate-text/src/test/java/functions/OcrTranslateTextTest.java
Labels: samples

#7367 docs: Bigtable fraud example update readme and convert scan to get
  bigtable/use-cases/fraudDetection/README.md
  bigtable/use-cases/fraudDetection/src/main/java/bigtable/fraud/beam/FraudDetection.java
Labels: samples
