Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2022-06, with the labels that each got.

#7176 feat: add Video Stitcher VOD session code samples and tests
  media/stitcher/src/main/java/com/example/stitcher/CreateVodSession.java
  media/stitcher/src/main/java/com/example/stitcher/GetVodAdTagDetail.java
  media/stitcher/src/main/java/com/example/stitcher/GetVodSession.java
  media/stitcher/src/main/java/com/example/stitcher/GetVodStitchDetail.java
  media/stitcher/src/main/java/com/example/stitcher/ListVodAdTagDetails.java
  media/stitcher/src/main/java/com/example/stitcher/ListVodStitchDetails.java
  media/stitcher/src/test/java/com/example/stitcher/CreateVodSessionTest.java
  media/stitcher/src/test/java/com/example/stitcher/GetVodAdTagDetailTest.java
  media/stitcher/src/test/java/com/example/stitcher/GetVodSessionTest.java
  media/stitcher/src/test/java/com/example/stitcher/GetVodStitchDetailTest.java
  media/stitcher/src/test/java/com/example/stitcher/ListVodAdTagDetailsTest.java
  media/stitcher/src/test/java/com/example/stitcher/ListVodStitchDetailsTest.java
Labels: samples

#7180 feat: add Video Stitcher live session code samples and tests
  media/stitcher/src/main/java/com/example/stitcher/CreateLiveSession.java
  media/stitcher/src/main/java/com/example/stitcher/GetLiveAdTagDetail.java
  media/stitcher/src/main/java/com/example/stitcher/GetLiveSession.java
  media/stitcher/src/main/java/com/example/stitcher/ListLiveAdTagDetails.java
  media/stitcher/src/test/java/com/example/stitcher/CreateLiveSessionTest.java
  media/stitcher/src/test/java/com/example/stitcher/GetLiveAdTagDetailTest.java
  media/stitcher/src/test/java/com/example/stitcher/GetLiveSessionTest.java
  media/stitcher/src/test/java/com/example/stitcher/ListLiveAdTagDetailsTest.java
  media/stitcher/src/test/java/com/example/stitcher/TestUtils.java
Labels: samples

#7185 pubsub(fix): avoid default port in spring app
  pubsub/spring/src/main/resources/application.properties
Labels: samples

#7175 bigtable: migrate HelloWorld sample from cloud-bigtable-examples
  bigtable/hbase/snippets/src/main/java/com/example/bigtable/HelloWorld.java
  bigtable/hbase/snippets/src/test/java/com/example/bigtable/HelloWorldTest.java
Labels: api: bigtable, samples

#7168 bigtable: migrate BigtableConnect sample from cloud-bigtable-examples
  bigtable/hbase/snippets/src/main/java/com/example/bigtable/BigtableConnect.java
  bigtable/hbase/snippets/src/main/resources/hbase-site.xml
  bigtable/hbase/snippets/src/test/java/com/example/bigtable/BigtableConnectTest.java
Labels: api: bigtable, samples

#7188 chore: update GSON dependency
  appengine-java11/gaeinfo/pom.xml
  appengine-java8/firebase-tictactoe/pom.xml
  appengine-java8/gaeinfo/pom.xml
  appengine-java8/metadata/pom.xml
  bigtable/scheduled-backups/pom.xml
  bigtable/scheduled-backups/src/test/java/com/example/cloud/bigtable/scheduledbackups/CreateBackupTestIT.java
  compute/signed-metadata/pom.xml
  container-registry/vulnerability-notification-function/pom.xml
  endpoints/getting-started/pom.xml
  endpoints/multiple-versions/pom.xml
  flexible/gaeinfo/pom.xml
  functions/concepts/retry-pubsub/pom.xml
  functions/concepts/retry-timeout/pom.xml
  functions/firebase/auth/pom.xml
  functions/firebase/remote-config/pom.xml
  functions/firebase/rtdb/pom.xml
  functions/helloworld/hello-gcs/pom.xml
  functions/helloworld/hello-http-gradle/build.gradle
  functions/helloworld/hello-http/pom.xml
  functions/helloworld/hello-pubsub/pom.xml
  functions/http/parse-content-type/pom.xml
  functions/http/parse-xml/pom.xml
  functions/logging/stackdriver-logging/pom.xml
  functions/slack/pom.xml
  functions/v2/hello-gcs/pom.xml
  functions/v2/label-compute-instance/pom.xml
  functions/v2/log-cloudevent/pom.xml
  functions/v2/pubsub/pom.xml
  monitoring/cloud-client/pom.xml
  monitoring/v3/pom.xml
  monitoring/v3/src/main/java/com/example/UptimeSample.java
  monitoring/v3/src/test/java/com/example/UptimeIT.java
  run/image-processing/pom.xml
Labels: samples

#7186 fix: fix tests using wrong Pub/Sub func name
  .kokoro/tests/build_cloud_functions.sh
  functions/helloworld/kotlin-hello-pubsub/src/main/kotlin/functions/KotlinHelloBackground.kt
  functions/helloworld/kotlin-hello-pubsub/src/test/java/functions/KotlinHelloPubSubTest.java
Labels: samples

#7190 (docs) Bigtable test cleanup and additional workload generator test
  bigtable/beam/workload-generator/README.md
  bigtable/beam/workload-generator/pom.xml
  bigtable/beam/workload-generator/src/main/java/bigtable/WorkloadGenerator.java
  bigtable/beam/workload-generator/src/test/java/bigtable/WorkloadGeneratorTest.java
  bigtable/cassandra-migration-codelab/pom.xml
  bigtable/cassandra-migration-codelab/src/test/java/CassandraMigrationCodelabTest.java
  bigtable/hbase/snippets/src/test/java/com/example/bigtable/ConfigureConnectionPoolTest.java
  bigtable/hbase/snippets/src/test/java/com/example/bigtable/WritesTest.java
  bigtable/memorystore/src/test/java/MemcachedTest.java
Labels: samples

#7192 feat: add sample for readAll for PG
  dataflow/spanner-io/src/main/java/com/example/dataflow/SpannerGroupWrite.java
  dataflow/spanner-io/src/main/java/com/example/dataflow/SpannerReadAll.java
  dataflow/spanner-io/src/main/java/com/example/dataflow/SpannerWrite.java
  dataflow/spanner-io/src/test/java/com/example/dataflow/SpannerGroupWriteIT.java
  dataflow/spanner-io/src/test/java/com/example/dataflow/SpannerReadIT.java
  dataflow/spanner-io/src/test/java/com/example/dataflow/SpannerWriteIT.java
Labels: samples

#7195 pubsublite: rewrite test and bump versions
  pubsublite/streaming-analytics/pom.xml
  pubsublite/streaming-analytics/src/test/java/PubsubliteToGcsIT.java
Labels: samples, api: pubsublite

#7181 docs: align channel config with best practices
  media/livestream/src/main/java/com/example/livestream/CreateChannel.java
  media/livestream/src/main/java/com/example/livestream/CreateChannelWithBackupInput.java
Labels: samples

#7199 chore(functions): clarify equality of endpoint and audience
  run/authentication/src/main/java/com/example/cloudrun/Authentication.java
Labels: api: cloudfunctions, samples
