Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2022-12, with the labels that each got.

#7468 chore: migrated left out samples
  dialogflow/snippets/src/main/java/com/example/dialogflow/ConversationManagement.java
  dialogflow/snippets/src/main/java/com/example/dialogflow/ConversationProfileManagement.java
  dialogflow/snippets/src/main/java/com/example/dialogflow/ParticipantManagement.java
  dialogflow/snippets/src/test/java/com/example/dialogflow/CreateConversationProfileTest.java
  dialogflow/snippets/src/test/java/com/example/dialogflow/CreateConversationTest.java
  dialogflow/snippets/src/test/java/com/example/dialogflow/CreateParticipantTest.java
Labels: samples

#7470 add main method to quickstart sample
  storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/QuickstartSample.java
Labels: api: storagetransfer, samples

#7441 Add Java docs samples for KMS key import.
  kms/pom.xml
  kms/src/main/java/kms/CheckStateImportJob.java
  kms/src/main/java/kms/CheckStateImportedKey.java
  kms/src/main/java/kms/CreateImportJob.java
  kms/src/main/java/kms/CreateKeyForImport.java
  kms/src/main/java/kms/ImportManuallyWrappedKey.java
  kms/src/test/java/kms/SnippetsIT.java
Labels: api: cloudkms, samples

#7473 chore: remove reference to googleapis
  asset/pom.xml
  batch/snippets/pom.xml
  mediatranslation/README.md
  mediatranslation/pom.xml
  recaptcha_enterprise/pom.xml
  security-command-center/snippets/pom.xml
  talent/snippets/pom.xml
  tasks/snippets/pom.xml
  vision/beta/README.md
  vision/cloud-client/README.md
  vision/product-search/README.md
  workflows/cloud-client/README.md
Labels: samples

#7485 feat: add iam authn example for mysql
  cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java
  cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/ConnectorIamAuthnConnectionPoolFactory.java
Labels: samples

#7486 samples: create long-lived resources for article suggestion feature
  dialogflow/snippets/src/test/java/com/example/dialogflow/CreateDocumentForArticleSuggestionTest.java
Labels: samples

#7484 Update readme: run/filesystem
  run/filesystem/README.md
Labels: samples

#7489 samples: remove code for creating long-lived resources
  dialogflow/snippets/src/test/java/com/example/dialogflow/CreateDocumentForArticleSuggestionTest.java
Labels: automerge, samples

#7491 test: increased timeout and added retries to flaky tests
  asset/src/test/java/com/example/asset/QuickStartIT.java
  automl/src/test/java/beta/automl/TablesCreateModelTest.java
  automl/src/test/java/beta/automl/TablesPredictTest.java
  automl/src/test/java/com/example/automl/LanguageTextClassificationCreateModelTest.java
Labels: samples

#7497 samples: add sample code for updating answer record
  dialogflow/snippets/src/main/java/com/example/dialogflow/AnswerRecordManagement.java
  dialogflow/snippets/src/main/java/com/example/dialogflow/ParticipantManagement.java
  dialogflow/snippets/src/test/java/com/example/dialogflow/UpdateAnswerRecordTest.java
Labels: samples

#7498 test: add MultipleAttemptsRule to failing Compute tests
  compute/cloud-client/src/test/java/compute/FirewallIT.java
  compute/cloud-client/src/test/java/compute/SnippetsIT.java
Labels: api: compute, samples

#7506 fix: remove maven-wrapper.jar file
  appengine-java8/springboot-helloworld/.mvn/wrapper/maven-wrapper.jar
Labels: samples

#7505 fix: Update .gitignore so that .jar file isn't included
  appengine-java8/springboot-helloworld/.gitignore
Labels: samples

#7512 test: add aiplatform env vars to test runner
  .kokoro/tests/run_tests.sh
Labels: samples

#7517 test: fix flaky asset tests
  asset/src/main/java/com/example/asset/ExportAssetsBigqueryExample.java
  asset/src/main/java/com/example/asset/ExportAssetsExample.java
  asset/src/test/java/com/example/asset/QuickStartIT.java
Labels: samples

#7520 test: handle flaky timeout in GAE task test
  unittests/src/test/java/com/google/appengine/samples/DeferredTaskTest.java
Labels: samples
