Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2022-05, with the labels that each got.

#7084 Update README.md
  bigtable/beam/bulk-data-generator/README.md
Labels: automerge, samples

#7054 feat: Update Cloud SQL MySQL samples to include more connection methods
  cloud-sql/mysql/servlet/.env.yaml
  cloud-sql/mysql/servlet/README.md
  cloud-sql/mysql/servlet/pom.xml
  cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java
  cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/ConnectionPoolFactory.java
  cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/ConnectorConnectionPoolFactory.java
  cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/IndexServlet.java
  cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/TcpConnectionPoolFactory.java
  cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/TemplateData.java
  cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/Utils.java
  cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/functions/Main.java
  cloud-sql/mysql/servlet/src/test/java/com/TestIndexServletMysql.java
Labels: samples

#7085 chore: add Kokoro build configs for JDK 17
  .kokoro/java17/common.cfg
  .kokoro/java17/continuous.cfg
  .kokoro/java17/periodic.cfg
  .kokoro/java17/presubmit.cfg
  .kokoro/tests/run_test_java.sh
Labels: samples

#7097 chore: require Java 17 CI check
  .github/sync-repo-settings.yaml
  .kokoro/tests/run_tests.sh
Labels: samples

#7080 feat: Update Postgres samples to include more connection methods
  cloud-sql/postgres/servlet/.env.yaml
  cloud-sql/postgres/servlet/README.md
  cloud-sql/postgres/servlet/pom.xml
  cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java
  cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/ConnectionPoolFactory.java
  cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/ConnectorConnectionPoolFactory.java
  cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/IndexServlet.java
  cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/TcpConnectionPoolFactory.java
  cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/TemplateData.java
  cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/Utils.java
  cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/functions/Main.java
  cloud-sql/postgres/servlet/src/test/java/com/TestIndexServletPostgres.java
Labels: samples

#7117 chore: add maven-war-plugin to fix java17 periodic failures
  appengine-java11-bundled-services/datastore/pom.xml
  appengine-java11/guestbook-cloud-firestore/pom.xml
  appengine-java11/helloworld-servlet/pom.xml
  appengine-java11/oauth2/pom.xml
  appengine-java8/analytics/pom.xml
  appengine-java8/appidentity/pom.xml
  appengine-java8/datastore-indexes-exploding/pom.xml
  appengine-java8/datastore-indexes-perfect/pom.xml
  appengine-java8/datastore-indexes/pom.xml
  appengine-java8/datastore-schedule-export/pom.xml
  appengine-java8/datastore/pom.xml
  appengine-java8/endpoints-v2-migration/pom.xml
  appengine-java8/firebase-event-proxy/pom.xml
  appengine-java8/firebase-tictactoe/pom.xml
  appengine-java8/guestbook-cloud-datastore/pom.xml
  appengine-java8/helloworld/pom.xml
  appengine-java8/iap/pom.xml
  appengine-java8/mail/pom.xml
  appengine-java8/mailgun/pom.xml
  appengine-java8/mailjet/pom.xml
  appengine-java8/multitenancy/pom.xml
  appengine-java8/pubsub/pom.xml
  appengine-java8/remote-server/pom.xml
  appengine-java8/sendgrid/pom.xml
  appengine-java8/spanner/pom.xml
  appengine-java8/static-files/pom.xml
  appengine-java8/tasks/quickstart/pom.xml
  appengine-java8/tasks/snippets/pom.xml
  appengine-java8/twilio/pom.xml
  appengine-java8/urlfetch/pom.xml
  appengine-java8/users/pom.xml
  endpoints/multiple-versions/pom.xml
  flexible/analytics/pom.xml
  flexible/async-rest/pom.xml
  flexible/cloudsql/pom.xml
  flexible/cloudstorage/pom.xml
  flexible/cron/pom.xml
  flexible/datastore/pom.xml
  flexible/disk/pom.xml
  flexible/errorreporting/pom.xml
  flexible/extending-runtime/pom.xml
  flexible/helloworld/pom.xml
  flexible/memcache/pom.xml
  flexible/pubsub/pom.xml
  flexible/static-files/pom.xml
  flexible/twilio/pom.xml
  flexible/websocket-jetty/pom.xml
  flexible/websocket-jsr356/pom.xml
  memorystore/redis/pom.xml
  session-handling/pom.xml
Labels: samples

#7118 fix: java.lang.reflect.InaccessibleObjectException in functions.StackdriverLogging sample
  functions/logging/stackdriver-logging/pom.xml
Labels: samples

#7098 feat: update SQL Server samples to include more connection methods
  cloud-sql/mysql/servlet/README.md
  cloud-sql/mysql/servlet/pom.xml
  cloud-sql/postgres/servlet/README.md
  cloud-sql/sqlserver/servlet/.env.yaml
  cloud-sql/sqlserver/servlet/README.md
  cloud-sql/sqlserver/servlet/pom.xml
  cloud-sql/sqlserver/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java
  cloud-sql/sqlserver/servlet/src/main/java/com/example/cloudsql/ConnectionPoolFactory.java
  cloud-sql/sqlserver/servlet/src/main/java/com/example/cloudsql/ConnectorConnectionPoolFactory.java
  cloud-sql/sqlserver/servlet/src/main/java/com/example/cloudsql/IndexServlet.java
  cloud-sql/sqlserver/servlet/src/main/java/com/example/cloudsql/TcpConnectionPoolFactory.java
  cloud-sql/sqlserver/servlet/src/main/java/com/example/cloudsql/TemplateData.java
  cloud-sql/sqlserver/servlet/src/main/java/com/example/cloudsql/Utils.java
  cloud-sql/sqlserver/servlet/src/main/java/com/example/cloudsql/functions/Main.java
  cloud-sql/sqlserver/servlet/src/test/java/com/TestIndexServletSqlServer.java
Labels: samples

#7137 docs: add Google Cloud Samples browser link to readme template
  README.md
Labels: samples

#7135 docs(bundled services): Include instructions to add bundled services JAR
  appengine-java11-bundled-services/README.md
Labels: samples

#7071 docs(compute-samples): added parallel testing support
  compute/cloud-client/pom.xml
  compute/cloud-client/src/main/java/compute/CreateEncryptedInstance.java
  compute/cloud-client/src/main/java/compute/CreateFirewallRule.java
  compute/cloud-client/src/main/java/compute/CreateInstance.java
  compute/cloud-client/src/main/java/compute/CreateInstanceFromTemplate.java
  compute/cloud-client/src/main/java/compute/CreateInstanceFromTemplateWithOverrides.java
  compute/cloud-client/src/main/java/compute/CreateInstanceTemplate.java
  compute/cloud-client/src/main/java/compute/CreateInstancesAdvanced.java
  compute/cloud-client/src/main/java/compute/CreateTemplateFromInstance.java
  compute/cloud-client/src/main/java/compute/CreateTemplateWithSubnet.java
  compute/cloud-client/src/main/java/compute/DeleteFirewallRule.java
  compute/cloud-client/src/main/java/compute/DeleteInstance.java
  compute/cloud-client/src/main/java/compute/DeleteInstanceTemplate.java
  compute/cloud-client/src/main/java/compute/PatchFirewallRule.java
  compute/cloud-client/src/main/java/compute/ResetInstance.java
  compute/cloud-client/src/main/java/compute/SetUsageExportBucket.java
  compute/cloud-client/src/main/java/compute/StartEncryptedInstance.java
  compute/cloud-client/src/main/java/compute/StartInstance.java
  compute/cloud-client/src/main/java/compute/StopInstance.java
  compute/cloud-client/src/main/java/compute/customhostname/CreateInstanceWithCustomHostname.java
  compute/cloud-client/src/main/java/compute/deleteprotection/CreateInstanceDeleteProtection.java
  compute/cloud-client/src/main/java/compute/deleteprotection/SetDeleteProtection.java
  compute/cloud-client/src/main/java/compute/preemptible/CreatePreemptibleInstance.java
  compute/cloud-client/src/test/java/compute/FirewallIT.java
  compute/cloud-client/src/test/java/compute/InstanceOperationsIT.java
  compute/cloud-client/src/test/java/compute/InstanceTemplatesIT.java
  compute/cloud-client/src/test/java/compute/InstancesAdvancedIT.java
  compute/cloud-client/src/test/java/compute/SnippetsIT.java
  compute/cloud-client/src/test/java/compute/Util.java
  compute/cloud-client/src/test/java/compute/customhostname/CustomHostnameInstanceIT.java
  compute/cloud-client/src/test/java/compute/deleteprotection/DeleteProtectionIT.java
  compute/cloud-client/src/test/java/compute/preemptible/PreemptibleIT.java
Labels: samples

#7142 chore: remove J17 required check
  .github/sync-repo-settings.yaml
Labels: samples

#7121 feat(functions/v2): Add imagemagick tutorial code
  functions/v2/imagemagick/pom.xml
  functions/v2/imagemagick/src/main/java/functions/ImageMagick.java
  functions/v2/imagemagick/src/main/java/functions/eventpojos/GcsEvent.java
  functions/v2/imagemagick/src/test/java/functions/ImageMagickTest.java
  functions/v2/imagemagick/zombie.jpg
Labels: api: cloudfunctions, samples

#7143 chore(functions/v2): revert change to cloudfunctions_ prefix
  functions/v2/imagemagick/src/main/java/functions/ImageMagick.java
  functions/v2/imagemagick/src/main/java/functions/eventpojos/GcsEvent.java
Labels: api: cloudfunctions, samples

#7141 docs(compute-samples): added windows samples and tests
  compute/cloud-client/src/main/java/compute/windows/osimage/CreateWindowsOsImage.java
  compute/cloud-client/src/main/java/compute/windows/windowsinstances/CreateFirewallRuleForWindowsActivationHost.java
  compute/cloud-client/src/main/java/compute/windows/windowsinstances/CreateRouteToWindowsActivationHost.java
  compute/cloud-client/src/main/java/compute/windows/windowsinstances/CreateWindowsServerInstanceExternalIp.java
  compute/cloud-client/src/main/java/compute/windows/windowsinstances/CreateWindowsServerInstanceInternalIp.java
  compute/cloud-client/src/main/java/compute/windows/windowsinstances/GetInstanceSerialPort.java
  compute/cloud-client/src/test/java/compute/windows/osimage/WindowsOsImageIT.java
  compute/cloud-client/src/test/java/compute/windows/windowsinstances/CreatingManagingWindowsInstancesIT.java
Labels: samples

#7144 fix: java 17 test errors in functions.EnvVarsTest
  functions/concepts/env-vars/pom.xml
Labels: samples

#7119 fix: java 17 tests
  .kokoro/tests/run_test_java.sh
  run/system-package/pom.xml
Labels: samples

#7156 fix(run): Update kokoro config
  .kokoro/tests/run_test_java.sh
  run/filesystem/pom.xml
  run/hello-broken/pom.xml
Labels: api: run, samples

#7154 chore: update gradle function
  functions/helloworld/hello-http-gradle/build.gradle
Labels: samples

#7159 feat:add Live Stream samples
  media/livestream/pom.xml
  media/livestream/src/main/java/com/example/livestream/CreateInput.java
  media/livestream/src/main/java/com/example/livestream/DeleteInput.java
  media/livestream/src/main/java/com/example/livestream/GetInput.java
  media/livestream/src/main/java/com/example/livestream/ListInputs.java
  media/livestream/src/main/java/com/example/livestream/UpdateInput.java
  media/livestream/src/test/java/com/example/livestream/CreateInputTest.java
  media/livestream/src/test/java/com/example/livestream/DeleteInputTest.java
  media/livestream/src/test/java/com/example/livestream/GetInputTest.java
  media/livestream/src/test/java/com/example/livestream/ListInputsTest.java
  media/livestream/src/test/java/com/example/livestream/TestUtils.java
  media/livestream/src/test/java/com/example/livestream/UpdateInputTest.java
Labels: samples

#7163 feat: add channel event resource code samples and tests
  media/livestream/src/main/java/com/example/livestream/CreateChannelEvent.java
  media/livestream/src/main/java/com/example/livestream/DeleteChannelEvent.java
  media/livestream/src/main/java/com/example/livestream/GetChannelEvent.java
  media/livestream/src/main/java/com/example/livestream/ListChannelEvents.java
  media/livestream/src/test/java/com/example/livestream/CreateChannelEventTest.java
  media/livestream/src/test/java/com/example/livestream/DeleteChannelEventTest.java
  media/livestream/src/test/java/com/example/livestream/GetChannelEventTest.java
  media/livestream/src/test/java/com/example/livestream/ListChannelEventsTest.java
  media/livestream/src/test/java/com/example/livestream/TestUtils.java
Labels: samples

#7164 feat: add Video Stitcher slate code samples and tests
  media/stitcher/pom.xml
  media/stitcher/src/main/java/com/example/stitcher/CreateSlate.java
  media/stitcher/src/main/java/com/example/stitcher/DeleteSlate.java
  media/stitcher/src/main/java/com/example/stitcher/GetSlate.java
  media/stitcher/src/main/java/com/example/stitcher/ListSlates.java
  media/stitcher/src/main/java/com/example/stitcher/UpdateSlate.java
  media/stitcher/src/test/java/com/example/stitcher/CreateSlateTest.java
  media/stitcher/src/test/java/com/example/stitcher/DeleteSlateTest.java
  media/stitcher/src/test/java/com/example/stitcher/GetSlateTest.java
  media/stitcher/src/test/java/com/example/stitcher/ListSlatesTest.java
  media/stitcher/src/test/java/com/example/stitcher/UpdateSlateTest.java
Labels: samples

#7172 chore(functions/v2): Add region tag
  functions/v2/label-compute-instance/src/main/java/functions/AutoLabelInstance.java
Labels: api: cloudfunctions, samples

#7173 feat: add Video Stitcher CDN key code samples and tests
  media/stitcher/src/main/java/com/example/stitcher/CreateCdnKey.java
  media/stitcher/src/main/java/com/example/stitcher/DeleteCdnKey.java
  media/stitcher/src/main/java/com/example/stitcher/GetCdnKey.java
  media/stitcher/src/main/java/com/example/stitcher/ListCdnKeys.java
  media/stitcher/src/main/java/com/example/stitcher/UpdateCdnKey.java
  media/stitcher/src/test/java/com/example/stitcher/CreateCdnKeyTest.java
  media/stitcher/src/test/java/com/example/stitcher/DeleteCdnKeyTest.java
  media/stitcher/src/test/java/com/example/stitcher/GetCdnKeyTest.java
  media/stitcher/src/test/java/com/example/stitcher/ListCdnKeysTest.java
  media/stitcher/src/test/java/com/example/stitcher/UpdateCdnKeyTest.java
Labels: samples
