Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2022-03, with the labels that each got.

#6861 chore: update job tests with retries
  run/jobs/src/test/java/com/example/JobsIntegrationTests.java
Labels: samples

#6863 fix(serverless): clean up ID token example
  run/authentication/src/main/java/com/example/cloudrun/Authentication.java
  run/authentication/src/test/java/com/example/cloudrun/AuthenticationTest.java
Labels: samples

#6865 test: remove flaky unnecessary testCreateFirewallRule
  compute/cloud-client/src/test/java/compute/SnippetsIT.java
Labels: automerge, samples

#6867 Fix and add logging to com.example.spanner.changestreams.ChangeStreamSampleIT: testChangeStreamSample
  spanner/changestreams/src/main/java/com/example/spanner/changestreams/ChangeStreamSample.java
  spanner/changestreams/src/test/java/com/example/spanner/changestreams/ChangeStreamSampleIT.java
Labels: automerge, samples

#6880 Use latest 2.4 Spark version 2.4.8
  bigtable/spark/build.sbt
Labels: automerge, samples

#6846 chore(secret-manager): add checksum-usage to snippets
  secretmanager/pom.xml
  secretmanager/src/main/java/secretmanager/AccessSecretVersion.java
  secretmanager/src/main/java/secretmanager/AddSecretVersion.java
Labels: api: secretmanager, samples, owlbot:run

#6879 healthcare API: do not use client library for FHIR search requests
  healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceSearchGet.java
  healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceSearchPost.java
  healthcare/v1/src/test/java/snippets/healthcare/FhirResourceTests.java
Labels: api: healthcare, samples

#6918 Use Cloud Client library for Troubleshooter
  iam/api-client/pom.xml
Labels: samples
