Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2022-01, with the labels that each got.

#6177 samples: update gfe_latency sample
  spanner/opencensus/pom.xml
  spanner/opencensus/src/main/java/com/example/spanner/opencensus/CaptureGfeMetric.java
Labels: cla: yes, samples

#6607 Make script copy and pasteable
  run/filesystem/gcsfuse_run.sh
  run/filesystem/run.sh
Labels: samples

#6606 Add import statement to make sample clearer
  run/pubsub/src/main/java/com/example/cloudrun/PubSubController.java
Labels: samples

#6612 docs: Update README.md
  bigtable/beam/workload-generator/README.md
Labels: samples

#6609 fix(compute-samples): fixed flaky firewall rule deletion
  compute/cloud-client/src/test/java/compute/SnippetsIT.java
Labels: samples

#6668 chore(functions/slack): fix flaky API call
  functions/slack/src/test/java/functions/SlackSlashCommandTest.java
Labels: api: cloudfunctions, samples

#6667 bug(compute): Fixing a small issue with sample region tags
  compute/cloud-client/src/main/java/compute/CreateInstancesAdvanced.java
Labels: type: bug, api: compute, samples

#6664 chore: migrate to secretmanager
  .kokoro/java11/common.cfg
  .kokoro/java8/common.cfg
  .kokoro/tests/run_tests.sh
Labels: samples

#6677 chore: fix typo
  compute/cloud-client/src/main/java/compute/StopInstance.java
Labels: samples

#6678 docs(compute-samples): init add samples for custom hostname
  compute/cloud-client/pom.xml
  compute/cloud-client/src/main/java/compute/customhostname/CreateInstanceWithCustomHostname.java
  compute/cloud-client/src/main/java/compute/customhostname/GetInstanceHostname.java
  compute/cloud-client/src/test/java/compute/customhostname/CustomHostnameInstanceIT.java
Labels: samples

#6671 feat(functions): add missing XML parsing sample
  functions/http/parse-xml/pom.xml
  functions/http/parse-xml/src/main/java/functions/ParseXml.java
  functions/http/parse-xml/src/test/java/functions/ParseXmlTest.java
Labels: api: cloudfunctions, samples

#6672 chore(functions): fix dep. on allow-unauthenticated
  functions/helloworld/hello-http/src/test/java/functions/ExampleSystemIT.java
Labels: api: cloudfunctions, samples

#6683 docs(compute-samples): init add create templates from instance and su…
  compute/cloud-client/src/main/java/compute/CreateTemplateFromInstance.java
  compute/cloud-client/src/main/java/compute/CreateTemplateWithSubnet.java
  compute/cloud-client/src/main/java/compute/ListAllInstances.java
  compute/cloud-client/src/main/java/compute/ListInstanceTemplates.java
  compute/cloud-client/src/test/java/compute/InstanceTemplatesIT.java
  compute/cloud-client/src/test/java/compute/Util.java
Labels: samples

#6665 feat(transcoder): add samples and tests for adding captions to videos
  media/transcoder/src/main/java/com/example/transcoder/CreateJobWithEmbeddedCaptions.java
  media/transcoder/src/main/java/com/example/transcoder/CreateJobWithStandaloneCaptions.java
  media/transcoder/src/test/java/com/example/transcoder/CreateJobWithEmbeddedCaptionsTest.java
  media/transcoder/src/test/java/com/example/transcoder/CreateJobWithStandaloneCaptionsTest.java
  media/transcoder/src/test/java/com/example/transcoder/testdata/caption.srt
Labels: samples, api: transcoder

#6679 chore(deps): update protobuf
  kms/pom.xml
Labels: samples

#6691 chore(deps): update protobuf
  appengine-java8/tasks/snippets/pom.xml
  endpoints/bookstore-grpc/api/build.gradle
  endpoints/getting-started-grpc/api/build.gradle
  secretmanager/pom.xml
  spanner/opencensus/pom.xml
Labels: samples

#6686 Adding a Java11 App Engine Standard compat (bundled services) sample.
  appengine-java11-bundled-services/datastore/README.md
  appengine-java11-bundled-services/datastore/pom.xml
  appengine-java11-bundled-services/datastore/src/main/java/com/example/appengine/AbstractGuestbook.java
  appengine-java11-bundled-services/datastore/src/main/java/com/example/appengine/AbstractGuestbookServlet.java
  appengine-java11-bundled-services/datastore/src/main/java/com/example/appengine/Greeting.java
  appengine-java11-bundled-services/datastore/src/main/java/com/example/appengine/Guestbook.java
  appengine-java11-bundled-services/datastore/src/main/java/com/example/appengine/GuestbookServlet.java
  appengine-java11-bundled-services/datastore/src/main/java/com/example/appengine/GuestbookStrong.java
  appengine-java11-bundled-services/datastore/src/main/java/com/example/appengine/GuestbookStrongServlet.java
  appengine-java11-bundled-services/datastore/src/main/java/com/example/appengine/ListPeopleServlet.java
  appengine-java11-bundled-services/datastore/src/main/java/com/example/appengine/ProjectionServlet.java
  appengine-java11-bundled-services/datastore/src/main/java/com/example/appengine/StartupServlet.java
  appengine-java11-bundled-services/datastore/src/main/java/com/example/appengine/StatsServlet.java
  appengine-java11-bundled-services/datastore/src/main/java/com/example/time/Clock.java
  appengine-java11-bundled-services/datastore/src/main/java/com/example/time/SystemClock.java
  appengine-java11-bundled-services/datastore/src/main/java/com/example/time/testing/FakeClock.java
  appengine-java11-bundled-services/datastore/src/main/webapp/WEB-INF/appengine-web.xml
  appengine-java11-bundled-services/datastore/src/main/webapp/WEB-INF/datastore-indexes.xml
  appengine-java11-bundled-services/datastore/src/main/webapp/WEB-INF/web.xml
  appengine-java11-bundled-services/datastore/src/main/webapp/guestbook.jsp
  appengine-java11-bundled-services/datastore/src/test/java/com/example/appengine/EntitiesTest.java
  appengine-java11-bundled-services/datastore/src/test/java/com/example/appengine/GuestbookStrongTest.java
  appengine-java11-bundled-services/datastore/src/test/java/com/example/appengine/GuestbookTest.java
  appengine-java11-bundled-services/datastore/src/test/java/com/example/appengine/IndexesTest.java
  appengine-java11-bundled-services/datastore/src/test/java/com/example/appengine/ListPeopleServletTest.java
  appengine-java11-bundled-services/datastore/src/test/java/com/example/appengine/MetadataEntityGroupTest.java
  appengine-java11-bundled-services/datastore/src/test/java/com/example/appengine/MetadataKindsTest.java
  appengine-java11-bundled-services/datastore/src/test/java/com/example/appengine/MetadataNamespacesTest.java
  appengine-java11-bundled-services/datastore/src/test/java/com/example/appengine/MetadataPropertiesTest.java
  appengine-java11-bundled-services/datastore/src/test/java/com/example/appengine/ProjectionServletTest.java
  appengine-java11-bundled-services/datastore/src/test/java/com/example/appengine/ProjectionTest.java
  appengine-java11-bundled-services/datastore/src/test/java/com/example/appengine/QueriesTest.java
  appengine-java11-bundled-services/datastore/src/test/java/com/example/appengine/ReadPolicyTest.java
  appengine-java11-bundled-services/datastore/src/test/java/com/example/appengine/StartupServletTest.java
  appengine-java11-bundled-services/datastore/src/test/java/com/example/appengine/TransactionsTest.java
Labels: automerge, samples

#6692 fix(pubsublite): remove processing time trigger
  pubsublite/streaming-analytics/pom.xml
  pubsublite/streaming-analytics/src/main/java/examples/PubsubliteToGcs.java
Labels: samples, api: pubsublite

#6693 test: fix job v3 autoCompleteSampleTest
  jobs/v3/src/test/java/SampleTests.java
Labels: samples

#6684 chore(functions): fix failing E2E tests
  .kokoro/tests/build_cloud_functions.sh
  .kokoro/tests/run_test_java.sh
  .kokoro/tests/teardown_cloud_functions.sh
  functions/helloworld/hello-gcs/src/test/java/functions/ExampleSystemIT.java
  functions/helloworld/hello-http/src/test/java/functions/ExampleSystemIT.java
  functions/helloworld/hello-pubsub/src/test/java/functions/ExampleSystemIT.java
Labels: api: cloudfunctions, samples

#6694 chore: fix double-main typo in sample code
  SAMPLE_FORMAT.md
Labels: samples

#6697 docs(iam-samples): extract json_key_file from privatedata
  iam/api-client/src/main/java/iam/snippets/CreateServiceAccountKey.java
  iam/api-client/src/test/java/iam/snippets/ServiceAccountTests.java
Labels: samples

#6695 Add top level README for GAE Java11 bundled services samples, based on Java8 samples.
  appengine-java11-bundled-services/README.md
Labels: samples
