Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2023-03, with the labels that each got.

#7716 fix: add MultipleAttemptsRule for Batch template creation
  batch/snippets/src/test/java/BatchTemplateIT.java
Labels: samples, api: batch

#7719 chore: update CODEOWNERS for recaptcha demosite
  .github/CODEOWNERS
Labels: samples

#7718 fix: gce machine type name for auto-deletion
  compute/cloud-client/src/test/java/compute/custommachinetype/CustomMachineTypeIT.java
Labels: api: compute, samples

#7725 chore: Adding self-service DLP team to labels and blunderbuss
  .github/auto-label.yaml
  .github/blunderbuss.yml
Labels: api: dlp, samples

#7717 Add sample app engine flex projects for java 11 and 17
  flexible/java-11/springboot-helloworld/README.md
  flexible/java-11/springboot-helloworld/pom.xml
  flexible/java-11/springboot-helloworld/src/main/appengine/app.yaml
  flexible/java-11/springboot-helloworld/src/main/java/com/example/appengine/springboot/SpringbootApplication.java
  flexible/java-11/springboot-helloworld/src/main/resources/application.properties
  flexible/java-11/springboot-helloworld/src/test/java/com/example/appengine/springboot/SpringbootApplicationTest.java
  flexible/java-17/micronaut-helloworld/README.md
  flexible/java-17/micronaut-helloworld/micronaut-cli.yml
  flexible/java-17/micronaut-helloworld/pom.xml
  flexible/java-17/micronaut-helloworld/src/main/appengine/app.yaml
  flexible/java-17/micronaut-helloworld/src/main/java/com/example/appengine/Application.java
  flexible/java-17/micronaut-helloworld/src/main/java/com/example/appengine/HelloController.java
  flexible/java-17/micronaut-helloworld/src/main/resources/application.yml
  flexible/java-17/micronaut-helloworld/src/main/resources/logback.xml
  flexible/java-17/micronaut-helloworld/src/test/java/com/example/appengine/HelloControllerTest.java
Labels: api: appengine, samples

#7732 fix: Add missing product region tags for Cloud CDN snippets
  cdn/signed-urls/src/main/java/com/google/cdn/SignedUrls.java
Labels: samples

#7735 chore: install chrome and driver for recaptcha tests
  .kokoro/tests/run_tests.sh
Labels: samples

#7740 chore: add datacatalog to self-service program
  .github/CODEOWNERS
  .github/auto-label.yaml
  .github/blunderbuss.yml
Labels: samples

#7722 feat: add recaptcha demosite v1
  .kokoro/tests/run_tests.sh
  recaptcha_enterprise/demosite/Dockerfile
  recaptcha_enterprise/demosite/README.md
  recaptcha_enterprise/demosite/docker-compose.yaml
  recaptcha_enterprise/demosite/pom.xml
  recaptcha_enterprise/demosite/src/main/java/app/MainController.java
  recaptcha_enterprise/demosite/src/main/java/app/SpringbootMain.java
  recaptcha_enterprise/demosite/src/main/java/recaptcha/CreateAssessment.java
  recaptcha_enterprise/demosite/src/main/resources/static/browserconfig.xml
  recaptcha_enterprise/demosite/src/main/resources/static/images/bot-color-unoptimized.svg
  recaptcha_enterprise/demosite/src/main/resources/static/images/castle-alternate-unoptimized.svg
  recaptcha_enterprise/demosite/src/main/resources/static/images/human-color-unoptimized.svg
  recaptcha_enterprise/demosite/src/main/resources/static/images/icons/favicon-120px.png
  recaptcha_enterprise/demosite/src/main/resources/static/images/icons/favicon-128px.png
  recaptcha_enterprise/demosite/src/main/resources/static/images/icons/favicon-144px.png
  recaptcha_enterprise/demosite/src/main/resources/static/images/icons/favicon-150px.png
  recaptcha_enterprise/demosite/src/main/resources/static/images/icons/favicon-152px.png
  recaptcha_enterprise/demosite/src/main/resources/static/images/icons/favicon-16px.png
  recaptcha_enterprise/demosite/src/main/resources/static/images/icons/favicon-180px.png
  recaptcha_enterprise/demosite/src/main/resources/static/images/icons/favicon-192px.png
  recaptcha_enterprise/demosite/src/main/resources/static/images/icons/favicon-196px.png
  recaptcha_enterprise/demosite/src/main/resources/static/images/icons/favicon-310px.png
  recaptcha_enterprise/demosite/src/main/resources/static/images/icons/favicon-32px.png
  recaptcha_enterprise/demosite/src/main/resources/static/images/icons/favicon-512px.png
  recaptcha_enterprise/demosite/src/main/resources/static/images/icons/favicon-64px.png
  recaptcha_enterprise/demosite/src/main/resources/static/images/icons/favicon-70px.png
  recaptcha_enterprise/demosite/src/main/resources/static/images/icons/favicon-96px.png
  recaptcha_enterprise/demosite/src/main/resources/static/images/icons/favicon.ico
  recaptcha_enterprise/demosite/src/main/resources/static/images/icons/favicon.svg
  recaptcha_enterprise/demosite/src/main/resources/static/images/item-hydrant-unoptimized.svg
  recaptcha_enterprise/demosite/src/main/resources/static/images/item-stoplight-unoptimized.svg
  recaptcha_enterprise/demosite/src/main/resources/static/images/land-unoptimized.svg
  recaptcha_enterprise/demosite/src/main/resources/static/manifest.webmanifest
  recaptcha_enterprise/demosite/src/main/resources/static/scripts/component.js
  recaptcha_enterprise/demosite/src/main/resources/static/scripts/global.js
  recaptcha_enterprise/demosite/src/main/resources/static/styles/global.css
  recaptcha_enterprise/demosite/src/main/resources/templates/comment.html
  recaptcha_enterprise/demosite/src/main/resources/templates/game.html
  recaptcha_enterprise/demosite/src/main/resources/templates/home.html
  recaptcha_enterprise/demosite/src/main/resources/templates/login.html
  recaptcha_enterprise/demosite/src/main/resources/templates/signup.html
  recaptcha_enterprise/demosite/src/main/resources/templates/store.html
  recaptcha_enterprise/demosite/src/test/java/ScoreKeyIT.java
  recaptcha_enterprise/demosite/src/test/java/Util.java
  recaptcha_enterprise/pom.xml
Labels: api: recaptchaenterprise, samples

#7751 chore: cleanup un-wanted region tags
  cdn/signed-urls/src/main/java/com/google/cdn/SignedUrls.java
Labels: samples

#7654 fix(healthcare-api): clean up de-identified dataset after tests
  healthcare/v1/src/test/java/snippets/healthcare/DatasetTests.java
Labels: samples, api: healhcare

#7747 test: add retries to dlp tests
  dlp/snippets/src/test/java/dlp/snippets/TestBase.java
Labels: api: dlp, samples

#7745 test: add retries to jobs tests
  jobs/v3/src/test/java/SampleTests.java
  jobs/v4/src/test/java/CommuteSearchJobsTest.java
  jobs/v4/src/test/java/CustomRankingSearchJobsTest.java
  jobs/v4/src/test/java/HistogramSearchJobsTest.java
  jobs/v4/src/test/java/JobSearchAutoCompleteJobTitleTest.java
  jobs/v4/src/test/java/JobSearchCreateCompanyTest.java
  jobs/v4/src/test/java/JobSearchCreateJobTest.java
  jobs/v4/src/test/java/JobSearchCreateJobWithCustomAttrTest.java
  jobs/v4/src/test/java/JobSearchCreateTenantTest.java
  jobs/v4/src/test/java/JobSearchDeleteCompanyTest.java
  jobs/v4/src/test/java/JobSearchDeleteJobTest.java
  jobs/v4/src/test/java/JobSearchDeleteTenantTest.java
  jobs/v4/src/test/java/JobSearchGetCompanyTest.java
  jobs/v4/src/test/java/JobSearchGetJobTest.java
  jobs/v4/src/test/java/JobSearchGetTenantTest.java
  jobs/v4/src/test/java/JobSearchListCompaniesTest.java
  jobs/v4/src/test/java/JobSearchListJobsTest.java
  jobs/v4/src/test/java/JobSearchListTenantsTest.java
Labels: api: jobs, samples

#7746 test: add retries to container-registry tests
  container-registry/container-analysis/src/test/java/com/example/containeranalysis/SamplesTest.java
  container-registry/vulnerability-notification-function/src/test/java/com/example/containeranalysis/VulnerabilityFunctionTest.java
Labels: api: containeranalysis, samples

#7783 docs: add a comment for using optimizer_version with PG
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/SetQueryOptionsExample.java
Labels: api: spanner, samples

#7789 chore: Update CODEOWNERS
  .github/CODEOWNERS
Labels: samples

#7792 chore(functions/v2/firebase/firestore): Create new firestore tirgger gen2 compatible sample
  functions/v2/firebase/firestore/pom.xml
  functions/v2/firebase/firestore/src/main/java/functions/FirebaseFirestore.java
  functions/v2/firebase/firestore/src/test/java/functions/FirebaseFirestoreTest.java
Labels: api: cloudfunctions, samples

#7780 docs(demosite-recaptcha): update control flow from client
  recaptcha_enterprise/demosite/src/main/java/app/MainController.java
  recaptcha_enterprise/demosite/src/main/java/recaptcha/CreateAssessment.java
  recaptcha_enterprise/demosite/src/main/resources/config.properties
  recaptcha_enterprise/demosite/src/main/resources/static/scripts/component.js
  recaptcha_enterprise/demosite/src/main/resources/static/scripts/global.js
  recaptcha_enterprise/demosite/src/main/resources/templates/comment.html
  recaptcha_enterprise/demosite/src/main/resources/templates/home.html
  recaptcha_enterprise/demosite/src/main/resources/templates/login.html
  recaptcha_enterprise/demosite/src/main/resources/templates/signup.html
  recaptcha_enterprise/demosite/src/main/resources/templates/store.html
Labels: api: recaptchaenterprise, samples

#7813 fix: Batch bucket issue fix
  batch/snippets/src/test/java/BatchBucketIT.java
Labels: samples, api: batch

#7823 fix(functions/v2/firebase/firestore): Remove 'Any' protobuf usage from code sample
  functions/v2/firebase/firestore/src/main/java/functions/FirebaseFirestore.java
  functions/v2/firebase/firestore/src/test/java/functions/FirebaseFirestoreTest.java
Labels: api: cloudfunctions, samples
