Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2023-01, with the labels that each got.

#7536 fix function names in pom
  functions/concepts/env-vars/pom.xml
  functions/concepts/execution-count/pom.xml
  functions/concepts/lazy-fields/pom.xml
Labels: samples

#7540 test: update aiplatform FeatureStore timeout + add retries
  aiplatform/src/test/java/aiplatform/FeatureValuesSamplesTest.java
  aiplatform/src/test/java/aiplatform/FeaturestoreSamplesTest.java
Labels: samples

#7529 STS Azure sample
  .kokoro/tests/run_tests.sh
  storage-transfer/pom.xml
  storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/QuickstartSample.java
  storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/TransferFromAzure.java
  storage-transfer/src/test/java/com/google/cloud/storage/storagetransfer/samples/test/ITStoragetransferSamplesTest.java
Labels: samples

#7558 chore: Update ownership of Retail samples
  .github/CODEOWNERS
Labels: samples

#7554 test: add retries to livestream tests
  media/livestream/src/test/java/com/example/livestream/CreateChannelEventTest.java
  media/livestream/src/test/java/com/example/livestream/CreateChannelTest.java
  media/livestream/src/test/java/com/example/livestream/CreateChannelWithBackupInputTest.java
  media/livestream/src/test/java/com/example/livestream/CreateInputTest.java
  media/livestream/src/test/java/com/example/livestream/DeleteChannelEventTest.java
  media/livestream/src/test/java/com/example/livestream/DeleteChannelTest.java
  media/livestream/src/test/java/com/example/livestream/DeleteInputTest.java
  media/livestream/src/test/java/com/example/livestream/GetChannelEventTest.java
  media/livestream/src/test/java/com/example/livestream/GetChannelTest.java
  media/livestream/src/test/java/com/example/livestream/GetInputTest.java
  media/livestream/src/test/java/com/example/livestream/ListChannelEventsTest.java
  media/livestream/src/test/java/com/example/livestream/ListChannelsTest.java
  media/livestream/src/test/java/com/example/livestream/ListInputsTest.java
  media/livestream/src/test/java/com/example/livestream/StartChannelTest.java
  media/livestream/src/test/java/com/example/livestream/StopChannelTest.java
  media/livestream/src/test/java/com/example/livestream/UpdateChannelTest.java
  media/livestream/src/test/java/com/example/livestream/UpdateInputTest.java
Labels: samples

#7553 test: added uuid to bq dataset name for concurrency
  security-command-center/snippets/src/test/java/BigQueryExportIT.java
Labels: samples

#7566 Add multiple attempts to Spanner ChangeStreams
  spanner/changestreams/pom.xml
  spanner/changestreams/src/test/java/com/example/spanner/changestreams/ChangeStreamSampleIT.java
Labels: samples

#7568 test: add multiple attempts to aiplatform pipeline tests
  aiplatform/src/test/java/aiplatform/CreateTrainingPipelineCustomJobSampleTest.java
  aiplatform/src/test/java/aiplatform/CreateTrainingPipelineCustomTrainingManagedDatasetSampleTest.java
  aiplatform/src/test/java/aiplatform/CreateTrainingPipelineImageClassificationSampleTest.java
  aiplatform/src/test/java/aiplatform/CreateTrainingPipelineImageObjectDetectionSampleTest.java
  aiplatform/src/test/java/aiplatform/CreateTrainingPipelineTabularClassificationSampleTest.java
  aiplatform/src/test/java/aiplatform/CreateTrainingPipelineTabularRegressionSampleTest.java
  aiplatform/src/test/java/aiplatform/CreateTrainingPipelineTextClassificationSampleTest.java
  aiplatform/src/test/java/aiplatform/CreateTrainingPipelineTextEntityExtractionSampleTest.java
  aiplatform/src/test/java/aiplatform/CreateTrainingPipelineTextSentimentAnalysisSampleTest.java
  aiplatform/src/test/java/aiplatform/CreateTrainingPipelineVideoActionRecognitionSampleTest.java
  aiplatform/src/test/java/aiplatform/CreateTrainingPipelineVideoClassificationSampleTest.java
  aiplatform/src/test/java/aiplatform/CreateTrainingPipelineVideoObjectTrackingSampleTest.java
Labels: samples

#7567 Fix Cloud Run service cleanup for Filesystems
  run/filesystem/src/test/java/com/example/filesystem/ApplicationTests.java
Labels: samples

#7569 chore: increase timeout for flaky test
  asset/src/test/java/com/example/asset/QuickStartIT.java
Labels: samples

#7584 ci: add service mappings for auto-label bot
  .github/auto-label.yaml
Labels: samples

#7570 feat(speech): Adds speech V2 samples
  speech/src/main/java/com/example/speech/CreateRecognizerV2.java
  speech/src/main/java/com/example/speech/QuickstartSampleV2.java
  speech/src/main/java/com/example/speech/TranscribeFileV2.java
  speech/src/test/java/com/example/speech/CreateRecognizerV2IT.java
  speech/src/test/java/com/example/speech/QuickstartSampleV2IT.java
  speech/src/test/java/com/example/speech/TranscribeFileV2IT.java
Labels: api: speech, samples

#7581 feat(speech): adds adaptation samples for V2
  speech/src/main/java/com/example/speech/AdaptationCustomClassReferenceV2.java
  speech/src/main/java/com/example/speech/AdaptationInlineCustomClassV2.java
  speech/src/main/java/com/example/speech/AdaptationInlinePhraseSetV2.java
  speech/src/main/java/com/example/speech/AdaptationPhraseSetReferenceV2.java
  speech/src/test/java/com/example/speech/AdaptationCustomClassReferenceV2IT.java
  speech/src/test/java/com/example/speech/AdaptationInlineCustomClassV2IT.java
  speech/src/test/java/com/example/speech/AdaptationInlinePhraseSetV2IT.java
  speech/src/test/java/com/example/speech/AdaptationPhraseSetReferenceV2IT.java
Labels: api: speech, samples

#7585 chore: update region tags on session-handling sample
  session-handling/src/main/java/com/example/gettingstarted/actions/HelloWorldServlet.java
  session-handling/src/main/java/com/example/gettingstarted/util/FirestoreSessionFilter.java
Labels: api: run, samples, snippet-bot:no-prefix-req

#7593 docs(samples): Added Endpoint to Document AI Samples
  document-ai/src/main/java/documentai/v1/BatchProcessDocument.java
  document-ai/src/main/java/documentai/v1/ProcessDocument.java
  document-ai/src/main/java/documentai/v1/QuickStart.java
  document-ai/src/main/java/documentai/v1beta3/ProcessFormDocument.java
  document-ai/src/main/java/documentai/v1beta3/ProcessOcrDocument.java
  document-ai/src/main/java/documentai/v1beta3/ProcessQualityDocument.java
  document-ai/src/main/java/documentai/v1beta3/ProcessSpecializedDocument.java
  document-ai/src/main/java/documentai/v1beta3/ProcessSplitterDocument.java
Labels: samples, api: documentai

#7632 Minor fix of comment text in SpannerReadApiWithIndex
  dataflow/spanner-io/src/main/java/com/example/dataflow/SpannerReadApiWithIndex.java
Labels: samples

#7635 fix: migrate GAE samples to thymeleaf 3.1
  appengine-java11/gaeinfo/pom.xml
  appengine-java11/gaeinfo/src/main/java/com/example/appengine/standard/GaeInfoServlet.java
  appengine-java8/gaeinfo/pom.xml
  appengine-java8/gaeinfo/src/main/java/com/example/appengine/standard/GaeInfoServlet.java
  appengine-java8/metadata/pom.xml
  appengine-java8/metadata/src/main/java/com/example/appengine/standard/MetadataServlet.java
  flexible/gaeinfo/pom.xml
  flexible/gaeinfo/src/main/java/com/example/appengine/flex_compat/GaeInfoServlet.java
Labels: api: appengine, samples

#7603 Revert "Add multiple attempts to Spanner ChangeStreams"
  spanner/changestreams/pom.xml
  spanner/changestreams/src/test/java/com/example/spanner/changestreams/ChangeStreamSampleIT.java
Labels: api: spanner, samples

#7639 chore: update compute API version for GCF sample
  functions/v2/label-compute-instance/pom.xml
  functions/v2/label-compute-instance/src/main/java/functions/AutoLabelInstance.java
Labels: api: cloudfunctions, samples

#7644 test: add retries to monitoring tests
  monitoring/v3/src/test/java/com/example/monitoring/AlertIT.java
  monitoring/v3/src/test/java/com/example/monitoring/CreateAlertPolicyIT.java
  monitoring/v3/src/test/java/com/example/monitoring/CreateMetricDescriptorIT.java
  monitoring/v3/src/test/java/com/example/monitoring/DeleteAlertPolicyIT.java
  monitoring/v3/src/test/java/com/example/monitoring/DeleteMetricDescriptorIT.java
  monitoring/v3/src/test/java/com/example/monitoring/DeleteNotificationChannelIT.java
  monitoring/v3/src/test/java/com/example/monitoring/EnableDisableAlertPolicyIT.java
  monitoring/v3/src/test/java/com/example/monitoring/GetAlertPolicyIT.java
  monitoring/v3/src/test/java/com/example/monitoring/GetMonitoredResourceIT.java
  monitoring/v3/src/test/java/com/example/monitoring/ListAlertPolicyIT.java
  monitoring/v3/src/test/java/com/example/monitoring/ListMetricDescriptorIT.java
  monitoring/v3/src/test/java/com/example/monitoring/ListMonitoredResourcesIT.java
  monitoring/v3/src/test/java/com/example/monitoring/QuickstartSampleIT.java
  monitoring/v3/src/test/java/com/example/monitoring/TimeSeriesIT.java
  monitoring/v3/src/test/java/com/example/monitoring/UpdateAlertPolicyIT.java
  monitoring/v3/src/test/java/com/example/monitoring/UptimeIT.java
Labels: api: monitoring, samples
