Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2023-12, with the labels that each got.

#8929 bigtable (docs): add multiple attempts for change stream test
  bigtable/beam/change-streams/src/test/java/ChangeStreamsHelloWorldTest.java
Labels: api: bigtable, samples

#8897 docs(samples): Add Dataflow "Getting started" flex template
  dataflow/flex-templates/getting_started/README.md
  dataflow/flex-templates/getting_started/metadata.json
  dataflow/flex-templates/getting_started/pom.xml
  dataflow/flex-templates/getting_started/src/main/java/com/example/dataflow/FlexTemplateGettingStarted.java
  dataflow/flex-templates/getting_started/src/test/java/com/example/dataflow/FlexTemplateGettingStartedIT.java
Labels: api: dataflow, samples

#8844 fix: update references to deprecated `hashed_account_id`
  recaptcha_enterprise/snippets/src/main/java/recaptcha/account_defender/AccountDefenderAssessment.java
  recaptcha_enterprise/snippets/src/main/java/recaptcha/account_defender/AnnotateAccountDefenderAssessment.java
  recaptcha_enterprise/snippets/src/test/java/app/SnippetsIT.java
Labels: api: recaptchaenterprise, samples

#8931 Vertex AI Java SDK samples using the Gemini large language model
  .kokoro/tests/run_test_java.sh
  vertexai/snippets/pom.xml
  vertexai/snippets/src/main/java/vertexai/gemini/ChatDiscussion.java
  vertexai/snippets/src/main/java/vertexai/gemini/MultiTurnMultimodal.java
  vertexai/snippets/src/main/java/vertexai/gemini/MultimodalMultiImage.java
  vertexai/snippets/src/main/java/vertexai/gemini/MultimodalQuery.java
  vertexai/snippets/src/main/java/vertexai/gemini/MultimodalVideoInput.java
  vertexai/snippets/src/main/java/vertexai/gemini/QuestionAnswer.java
  vertexai/snippets/src/main/java/vertexai/gemini/Quickstart.java
  vertexai/snippets/src/main/java/vertexai/gemini/SingleTurnMultimodal.java
  vertexai/snippets/src/main/java/vertexai/gemini/StreamingQuestionAnswer.java
  vertexai/snippets/src/main/java/vertexai/gemini/WithSafetySettings.java
  vertexai/snippets/src/test/java/vertexai/gemini/SnippetsIT.java
Labels: samples

#8934 chore(vertexai): update bom to remove depdency version
  vertexai/snippets/pom.xml
Labels: samples

#8938 chore(proc): prevent dependency upgrades for java8 code samples
  .github/renovate.json5
  README.md
Labels: samples

#8865 OpenTelemetry Spring Boot example
  .github/CODEOWNERS
  opentelemetry/spring-boot-instrumentation/.dockerignore
  opentelemetry/spring-boot-instrumentation/.gitignore
  opentelemetry/spring-boot-instrumentation/.mvn/wrapper/maven-wrapper.properties
  opentelemetry/spring-boot-instrumentation/Dockerfile
  opentelemetry/spring-boot-instrumentation/README.md
  opentelemetry/spring-boot-instrumentation/docker-compose.adc.yaml
  opentelemetry/spring-boot-instrumentation/docker-compose.yaml
  opentelemetry/spring-boot-instrumentation/mvnw
  opentelemetry/spring-boot-instrumentation/mvnw.cmd
  opentelemetry/spring-boot-instrumentation/otel-collector-config.yaml
  opentelemetry/spring-boot-instrumentation/pom.xml
  opentelemetry/spring-boot-instrumentation/src/main/java/com/example/demo/DemoApplication.java
  opentelemetry/spring-boot-instrumentation/src/main/java/com/example/demo/MultiController.java
  opentelemetry/spring-boot-instrumentation/src/main/java/com/example/demo/SingleController.java
  opentelemetry/spring-boot-instrumentation/src/main/resources/logback.xml
  opentelemetry/spring-boot-instrumentation/src/test/java/com/example/demo/DemoApplicationTests.java
  opentelemetry/spring-boot-instrumentation/src/test/java/com/example/demo/DockerComposeTestsIT.java
  opentelemetry/spring-boot-instrumentation/src/test/resources/logback-test.xml
Labels: samples

#8941 Use image first in prompts
  vertexai/snippets/src/main/java/vertexai/gemini/SingleTurnMultimodal.java
Labels: samples

#8942 chore(proc): update repo's settings
  .github/header-checker-lint.yml
  .github/sync-repo-settings.yaml
Labels: samples

#8949 Use gemini-pro instead of gemini-pro-vision in chat
  vertexai/snippets/src/main/java/vertexai/gemini/ChatDiscussion.java
  vertexai/snippets/src/test/java/vertexai/gemini/SnippetsIT.java
Labels: samples

#8955 chore(proc): enable running java8 tests periodically
  .kokoro/java8/continuous.cfg
  .kokoro/java8/presubmit.cfg
Labels: samples

#8957 chore(proc): Update repo's settings
  .github/sync-repo-settings.yaml
  README.md
Labels: samples

#8960 chore(proc): make header check required
  .github/sync-repo-settings.yaml
Labels: type: process, samples
