Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2024-08, with the labels that each got.

#9430 fix: generativeaionvertexai_stream_text_basic
  vertexai/snippets/src/main/java/vertexai/gemini/StreamingQuestionAnswer.java
  vertexai/snippets/src/test/java/vertexai/gemini/SnippetsIT.java
Labels: kokoro:run, samples

#9422 feat(aiplatform): add initial Imagen code sample and test
  aiplatform/src/main/java/aiplatform/imagen/GenerateImageSample.java
  aiplatform/src/test/java/aiplatform/imagen/GenerateImageSampleTest.java
Labels: samples, api: aiplatform

#9427 Add controlled generation support with response mime type and JSON schema
  vertexai/snippets/pom.xml
  vertexai/snippets/src/main/java/vertexai/gemini/ControlledGenerationMimeType.java
  vertexai/snippets/src/main/java/vertexai/gemini/ControlledGenerationSchema.java
  vertexai/snippets/src/main/java/vertexai/gemini/ControlledGenerationSchema2.java
  vertexai/snippets/src/main/java/vertexai/gemini/ControlledGenerationSchema3.java
  vertexai/snippets/src/main/java/vertexai/gemini/ControlledGenerationSchema4.java
  vertexai/snippets/src/main/java/vertexai/gemini/ControlledGenerationSchema6.java
  vertexai/snippets/src/main/java/vertexai/gemini/GroundingWithPublicData.java
  vertexai/snippets/src/test/java/vertexai/gemini/SnippetsIT.java
Labels: samples

#9437 fix(jobs): updating region_tag with product prefix
  jobs/v3/src/main/java/com/google/samples/CustomAttributeSample.java
Labels: api: jobs, samples

#9426 fix: generativeaionvertexai_gemini_get_started
  vertexai/snippets/src/main/java/vertexai/gemini/Quickstart.java
  vertexai/snippets/src/test/java/vertexai/gemini/SnippetsIT.java
Labels: kokoro:run, samples

#9367 feat(routeoptimization): New code samples
  .github/CODEOWNERS
  .github/blunderbuss.yml
  routeoptimization/snippets/pom.xml
  routeoptimization/snippets/src/main/java/com/example/OptimizeTours.java
  routeoptimization/snippets/src/test/java/com/example/OptimizeToursTest.java
Labels: samples

#9425 chore: added secret manager team in codeowners
  .github/CODEOWNERS
Labels: samples

#9431 Add regional endpoints code samples
  dlp/snippets/src/main/java/dlp/snippets/InspectStringRep.java
  dlp/snippets/src/test/java/dlp/snippets/InspectTests.java
Labels: samples

#9420 Remove execute/assessment from homepage load
  recaptcha_enterprise/demosite/src/main/java/app/MainController.java
  recaptcha_enterprise/demosite/src/main/resources/config.properties
  recaptcha_enterprise/demosite/src/main/resources/static/scripts/demo-9b37f5d6.js
  recaptcha_enterprise/demosite/src/main/resources/templates/comment.html
  recaptcha_enterprise/demosite/src/main/resources/templates/home.html
  recaptcha_enterprise/demosite/src/main/resources/templates/login.html
  recaptcha_enterprise/demosite/src/main/resources/templates/signup.html
  recaptcha_enterprise/demosite/src/main/resources/templates/store.html
Labels: api: recaptchaenterprise, samples, asset: flagship

#9441 docs(samples): Update Dataflow Iceberg samples for Beam 2.58.0
  dataflow/snippets/pom.xml
  dataflow/snippets/src/main/java/com/example/dataflow/ApacheIcebergRead.java
  dataflow/snippets/src/main/java/com/example/dataflow/ApacheIcebergWrite.java
Labels: api: dataflow, samples

#9429 fix: generativeaionvertexai_gemini_safety_settings
  vertexai/snippets/src/main/java/vertexai/gemini/WithSafetySettings.java
Labels: kokoro:run, samples

#9407 feat(vertexai): Add a new sample for automatic function calling
  vertexai/snippets/src/main/java/vertexai/gemini/AutomaticFunctionCalling.java
  vertexai/snippets/src/main/java/vertexai/gemini/GroundingWithPublicData.java
  vertexai/snippets/src/test/java/vertexai/gemini/SnippetsIT.java
Labels: samples

#9424 docs(samples): Add Kafka to Dataflow snippet
  dataflow/snippets/pom.xml
  dataflow/snippets/src/main/java/com/example/dataflow/KafkaRead.java
  dataflow/snippets/src/test/java/com/example/dataflow/KafkaReadIT.java
Labels: api: dataflow, samples

#9428 fix: Elastic Text-Embedding demo.
  aiplatform/src/main/java/aiplatform/PredictTextEmbeddingsSamplePreview.java
  aiplatform/src/test/java/aiplatform/PredictTextEmbeddingsSampleTest.java
Labels: samples

#9462 chore: add GoogleCloudPlatform/text-embedding to CODEOWNERS
  .github/CODEOWNERS
Labels: samples

#9436 feat(gemini sdk): add generativeaionvertexai complex function calling
  vertexai/snippets/src/main/java/vertexai/gemini/ComplexFunctionCalling.java
  vertexai/snippets/src/test/java/vertexai/gemini/SnippetsIT.java
Labels: kokoro:run, samples, api: vertex-ai

#9480 fix(compute): bug fixes HyperdisksIT test
  compute/cloud-client/src/test/java/compute/disks/HyperdisksIT.java
Labels: kokoro:run, api: compute, samples

#9502 docs(generativeai): clear unused region tags for code samples
  vertexai/snippets/src/main/java/vertexai/gemini/ChatDiscussion.java
  vertexai/snippets/src/main/java/vertexai/gemini/FunctionCalling.java
  vertexai/snippets/src/main/java/vertexai/gemini/GetTokenCount.java
  vertexai/snippets/src/main/java/vertexai/gemini/MultimodalMultiImage.java
  vertexai/snippets/src/main/java/vertexai/gemini/MultimodalQuery.java
  vertexai/snippets/src/main/java/vertexai/gemini/MultimodalVideoInput.java
  vertexai/snippets/src/main/java/vertexai/gemini/Quickstart.java
  vertexai/snippets/src/main/java/vertexai/gemini/SingleTurnMultimodal.java
  vertexai/snippets/src/main/java/vertexai/gemini/WithSafetySettings.java
Labels: samples

#9500 refactor(recaptcha): update CreateAssessment sample
  recaptcha_enterprise/snippets/src/main/java/recaptcha/CreateAssessment.java
Labels: api: recaptchaenterprise, samples

#9479 feat(compute): add compute_reservation_delete
  compute/cloud-client/src/main/java/compute/reservation/DeleteReservation.java
  compute/cloud-client/src/test/java/compute/SnippetsIT.java
  compute/cloud-client/src/test/java/compute/disks/HyperdisksIT.java
  compute/cloud-client/src/test/java/compute/reservation/ReservationIT.java
Labels: kokoro:run, api: compute, samples
