Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2024-01, with the labels that each got.

#8866 docs(samples): Add Dataflow snippet for Pub/Sub write
  dataflow/snippets/pom.xml
  dataflow/snippets/src/main/java/com/example/dataflow/PubSubWriteWithAttributes.java
  dataflow/snippets/src/test/java/com/example/dataflow/PubSubWriteIT.java
Labels: api: dataflow, samples

#8959 chore(proc): Add support for Java 21 tests
  .kokoro/java11/periodic.cfg
  .kokoro/java17/continuous.cfg
  .kokoro/java21/common.cfg
  .kokoro/java21/periodic.cfg
  .kokoro/tests/run_test_java.sh
Labels: samples

#8932 feat: update samples with LROs to not use a try block
  media/stitcher/src/main/java/com/example/stitcher/CreateCdnKey.java
  media/stitcher/src/main/java/com/example/stitcher/CreateCdnKeyAkamai.java
  media/stitcher/src/main/java/com/example/stitcher/CreateLiveConfig.java
  media/stitcher/src/main/java/com/example/stitcher/CreateLiveSession.java
  media/stitcher/src/main/java/com/example/stitcher/CreateSlate.java
  media/stitcher/src/main/java/com/example/stitcher/CreateVodSession.java
  media/stitcher/src/main/java/com/example/stitcher/DeleteCdnKey.java
  media/stitcher/src/main/java/com/example/stitcher/DeleteLiveConfig.java
  media/stitcher/src/main/java/com/example/stitcher/DeleteSlate.java
  media/stitcher/src/main/java/com/example/stitcher/GetCdnKey.java
  media/stitcher/src/main/java/com/example/stitcher/GetLiveAdTagDetail.java
  media/stitcher/src/main/java/com/example/stitcher/GetLiveConfig.java
  media/stitcher/src/main/java/com/example/stitcher/GetLiveSession.java
  media/stitcher/src/main/java/com/example/stitcher/GetSlate.java
  media/stitcher/src/main/java/com/example/stitcher/GetVodAdTagDetail.java
  media/stitcher/src/main/java/com/example/stitcher/GetVodSession.java
  media/stitcher/src/main/java/com/example/stitcher/GetVodStitchDetail.java
  media/stitcher/src/main/java/com/example/stitcher/ListCdnKeys.java
  media/stitcher/src/main/java/com/example/stitcher/ListLiveAdTagDetails.java
  media/stitcher/src/main/java/com/example/stitcher/ListLiveConfigs.java
  media/stitcher/src/main/java/com/example/stitcher/ListSlates.java
  media/stitcher/src/main/java/com/example/stitcher/ListVodAdTagDetails.java
  media/stitcher/src/main/java/com/example/stitcher/ListVodStitchDetails.java
  media/stitcher/src/main/java/com/example/stitcher/UpdateCdnKey.java
  media/stitcher/src/main/java/com/example/stitcher/UpdateCdnKeyAkamai.java
  media/stitcher/src/main/java/com/example/stitcher/UpdateSlate.java
Labels: samples, api: videostitcher

#8967 Set default priority of flaky bot issues to P2
  .github/flakybot.yaml
Labels: samples

#8973 fix(opentelemetry): update method names of sprring controllers to match the javadoc
  opentelemetry/spring-boot-instrumentation/src/main/java/com/example/demo/MultiController.java
  opentelemetry/spring-boot-instrumentation/src/main/java/com/example/demo/SingleController.java
Labels: samples

#8937 feat: samples for partitioned queries on Spanner with PostgreSQL
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/PgAutoPartitionModeExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/PgDataBoostExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/PgPartitionQueryExample.java
  spanner/jdbc/src/main/java/com/example/spanner/jdbc/PgRunPartitionedQueryExample.java
  spanner/jdbc/src/test/java/com/example/spanner/jdbc/BaseJdbcPgExamplesIT.java
  spanner/jdbc/src/test/java/com/example/spanner/jdbc/PgPartitionedQueryIT.java
Labels: api: spanner, samples

#8974 fix: update references to deprecated hashed_account_id
  recaptcha_enterprise/snippets/src/main/java/recaptcha/account_defender/SearchRelatedAccountGroupMemberships.java
  recaptcha_enterprise/snippets/src/test/java/app/SnippetsIT.java
Labels: api: recaptchaenterprise, samples

#8940 feat(testing): convert CI to use Makefile for testing
  .kokoro/tests/run_test_java.sh
Labels: samples

#9225 chore: exclude flakybot to run on Java8 tests
  .kokoro/tests/run_test_java.sh
Labels: samples

#9226 fix(Makefile): use string value checks instead of ifndef
  Makefile
Labels: samples

#9228 chore: restore periodic configs in Java 11 and 17
  .kokoro/java11/periodic.cfg
  .kokoro/java17/periodic.cfg
Labels: samples

#9227 chore: update workflow badges
  README.md
Labels: samples

#9229 chore: update workflow badge
  README.md
Labels: samples

#9230 chore: fix typo in README link
  README.md
Labels: samples

#8986 fix: use model id instead of model name in undeployModelAsync
  aiplatform/src/main/java/aiplatform/UndeployModelSample.java
Labels: samples, api: aiplatform
