Repository GoogleCloudPlatform/java-docs-samples, pull requests merged in 2025-09, with the labels that each got.

#10163 Fixing Iceberg documentation code comments
  dataflow/snippets/src/main/java/com/example/dataflow/ApacheIcebergCdcRead.java
  dataflow/snippets/src/main/java/com/example/dataflow/ApacheIcebergRestCatalogStreamingWrite.java
Labels: api: dataflow, samples

#10166 chore: upgrade images to java21
  appengine-java21/ee8/images/README.md
  appengine-java21/ee8/images/pom.xml
  appengine-java21/ee8/images/src/main/java/com/example/appengine/images/ImagesServlet.java
  appengine-java21/ee8/images/src/main/webapp/WEB-INF/appengine-web.xml
  appengine-java21/ee8/images/src/main/webapp/WEB-INF/image.jpg
  appengine-java21/ee8/images/src/main/webapp/WEB-INF/web.xml
  appengine-java8/images/src/main/webapp/WEB-INF/web.xml
Labels: api: appengine, samples

#10147 feat(genai): add tools samples
  genai/snippets/resources/640px-Monty_open_door.svg.png
  genai/snippets/src/main/java/genai/tools/ToolsCodeExecWithText.java
  genai/snippets/src/main/java/genai/tools/ToolsCodeExecWithTextLocalImage.java
  genai/snippets/src/main/java/genai/tools/ToolsGoogleSearchWithText.java
  genai/snippets/src/test/java/genai/tools/ToolsIT.java
Labels: samples

#10165 chore(deps): update GenAI SDK to v1.15.0
  genai/snippets/pom.xml
Labels: samples

#10169 feat(genai): add image generation samples using Flash MM
  genai/snippets/resources/example-image-eiffel-tower.png
  genai/snippets/resources/output/bw-example-image.png
  genai/snippets/resources/output/example-breakfast-meal.png
  genai/snippets/resources/output/example-image-eiffel-tower.png
  genai/snippets/src/main/java/genai/imagegeneration/ImageGenMmFlashEditImageWithTextAndImage.java
  genai/snippets/src/main/java/genai/imagegeneration/ImageGenMmFlashLocaleAwareWithText.java
  genai/snippets/src/main/java/genai/imagegeneration/ImageGenMmFlashMultipleImagesWithText.java
  genai/snippets/src/main/java/genai/imagegeneration/ImageGenMmFlashTextAndImageWithText.java
  genai/snippets/src/main/java/genai/imagegeneration/ImageGenMmFlashWithText.java
  genai/snippets/src/test/java/genai/imagegeneration/ImageGenerationMmFlashIT.java
Labels: samples

#10150 feat(genai): add Vertex AI Search tool sample
  genai/snippets/pom.xml
  genai/snippets/src/main/java/genai/tools/ToolsVaisWithText.java
  genai/snippets/src/test/java/genai/tools/ToolsIT.java
Labels: samples
